### ISSUE TITLE
[Banana Cake Pop] Workspaces

### ISSUE THREAD

**Issue by rstaib** [ChilliCream/graphql-platform#1349]

**Comment by fredericbirke** [comment]
The ChilliCream products should have a recognizable way of organizing data. In the SchemaRegistry there is organization on a per Project basis, this should also come to BCP.

A project could be the set of:
 - Name
 - Environments
 - AuthenticationFlows (See #40 )
 - Schemas, Per Schema:
   - AuthenticationFlows (can be inherited from project, if there exist some in the project)
   - Name
   - ServerURL
   - Collections, per collection:
     - Name
     - Documents, Per Document:
       - Name
       - ParameterizationObjects, including the last Chosen one
       - Chosen AuthenticationFlow for Document

**Comment by tobias-tengler** [comment]
Already being worked on and tracked in a different repository.

**Comment by vsdepontes** [comment]
> Already being worked on and tracked in a different repository.

Where?

**Comment by rstaib** [comment]
@vsdepontes It'

**Comment by rstaib** [comment]
@vsdepontes first thing we will release next is organizations. Each one will have a workspace assigned. We're releasing the first insider version today or tomorrow. If you would be interested in having an early look at it, let me know.
