### ISSUE TITLE
Automatic naming of uppercase acronyms

### ISSUE THREAD

**Issue by CoskunSunali** [ChilliCream/graphql-platform#1863]
The automatic naming for acronyms seems to be in an unexpected format, in my opinion.

Consider the following POCO:

```cs
public class Car
{
    public string EAN { get; set; }
}
```

The schema generated for this POCO is as below.

```graphql
type Car {
    eAN: String!
}
```

I don't know how the automatic naming works for fields but just `eAN` looks weird :) The best naming would probably be `ean`.

I will go ahead and use the `GraphQLName` attribute to fix the issue on my behalf but thought opening an issue for further discussion might be a good idea.

**Comment by PascalSenn** [comment]
Hi @CoskunSunali  
You can override this behaviour in two ways :) 
You can change it globally:
https://hotchocolate.io/docs/conventions#__docusaurus
Or just for a property with descriptor attributes :)

**Comment by CoskunSunali** [comment]
Hi @PascalSenn 

Thank you for the suggestions :) I am actually aware of them but still, thanks again.

The reason I created the issue was that maybe you might want to solve the issue on your end for other consumers of your library :)

Please feel free to close the issue if it is not a concern for you.

Thanks again!

**Comment by michaelstaib** [comment]
@CoskunSunali you are right we could easily test if it is acronym.

`IO` => `io`
`IOFile` => `ioFile`

and so on ....

**Comment by michaelstaib** [comment]
@CoskunSunali do you want to do a PR?
