### ISSUE TITLE
Help me Discover Types with Missing Descriptions

### ISSUE THREAD

**Issue by RehanSaeed** [ChilliCream/graphql-platform#2183]
**Is your feature request related to a problem? Please describe.**

I'd like to know when I have missed setting a description on any of my fields or types.

**Describe the solution you'd like**

It would be nice if I could see a warning when this happened. Some devs may not like this, so perhaps it could be configurable.

**Comment by michaelstaib** [comment]
With version 11 you can add type system validators that produce errors or warnings on such issues. I will add this item to the backlog and link the examples ones we are done with it.

**Comment by PascalSenn** [comment]
Hi @RehanSaeed 

In V11 you can do this by creating a TypeIntercetpor and validate all the types in OnTypeCompleted
```csharp
 public class CustomerTypeInterceptor
        :  TypeInterceptor
    { 

        public override void OnAfterCompleteType(
            ITypeCompletionContext completionContext,
            DefinitionBase? definition,
            IDictionary<string, object?> contextData)
        {
            // completionContext.Type <-- contains the type
            // you can store the types with no description in a list on the instance of this interceptor
        } 

        public virtual void OnAfterCompleteTypes()
        {
            // Throw a schema exception here with all the type without description
        }

    }
```

To register a type interceptor you can use
```csharp
services.AddGraphQLServer()
   ... 
   .TryAddTypeInterceptor<CustomerTypeInterceptor>();
```
