### ISSUE TITLE
AnyType IDictionary serialize like JSON

### ISSUE THREAD

**Issue by steveoh** [ChilliCream/graphql-platform#3617]
**Describe the bug**

`IDictionary<string, object>` serialization as `AnyType` is weird. 

**To Reproduce**

With the following query and output type

```cs
public class Query
{
    public Thing Query() => new Thing { Junk = new Dictionary<string, object> {{ "name", "yo" }}};
}

public class Thing {
  [GraphQLType(typeof(AnyType))] public IDictionary<string, object> Junk { get; set; }
}
```

An error is thrown `EXEC_INVALID_LEAF_VALUE` when querying.

If I change the dictionary type to `IDictionary<string, string>` then the serialization is weird

```gql
{
  "junk": [
    {
       "key": "name",
       "value": "yo"
    }
  ]
}
```

If I create a constructor to take the `dictionary<string, object>` and iterate over its values calling `ToString` then I get the expected result and that is weird.

```cs
foreach(var key in Junk.Keys) {
   Junk[key] = Junk[key].ToString();
}
```

But, I get the expected result

```gql
{
  "junk": {
    "name": "yo"
   }
}
```

**Expected behavior**

I expect `IDictionary<string, object>` to serialize like json

**Desktop (please complete the following information):**

 - OS: macos
 - Version: 10.15.7

**Comment by louisoftokyo** [comment]
I'm also seeing this issue.

OS: macos
Version: 11.3.0

**Comment by scottcollins** [comment]
I am as well.

Windows 10
Visual studio 2019
Version 11.3.0

```
partial record CountryDto
{
    [GraphQLType(typeof(AnyType))]
    public IDictionary<string, string> Provinces { get; init; } = null!;
}
```

Results in the following

```
{
  "data": {
    "country": {
      "name": "United States",
      "abbreviation": "us",
      "provinces": [
        {
          "key": "AL",
          "value": "Alabama"
        },
        {
          "key": "AK",
          "value": "Alaska"
        },
```

**Comment by RubcovMindbox** [comment]
Also faced this issue

**Comment by glen-84** [comment]
I added this test:

```c#
        [Fact]
        public async Task Output_Return_Dictionary()
        {
            // arrange
            ISchema schema = SchemaBuilder.New()
                .AddQueryType(d => d
                    .Name("Query")
                    .Field("foo")
                    .Type<AnyType>()
                    .Resolve(_ => new Dictionary<string, object> {
                        { "number", 123 },
                        { "dateTime", DateTime.UtcNow } }))
                .Create();

            IRequestExecutor executor = schema.MakeExecutable();

            // act
            IExecutionResult result = await executor.ExecuteAsync("{ foo }");

            // assert
            result.ToJson().MatchSnapshot();
        }
```

But the snapshot looks correct ...

```json
{
  "data": {
    "foo": {
      "number": 123,
      "dateTime": "2022-06-17T19:39:30.495Z"
    }
  }
}
```

So I'm not sure what's going on in my case (and the case of the OP and others).

I'm using this in my Error type.

I need to look into it more.

**Comment by Soundman32** [comment]
I'm also getting this issue.   It works for some kinds of dictionary, but not others.   The dictionary being serialised is declared as `Dictionary<string,object>`, but the data that works only contains string keys and values, whereas the dictionary that fails, contains non-string values (simple CLR objects, like int).

**Comment by ygo74** [comment]
Hello,

Do you think you will work on this subject ?
I have to return yaml content files from my api (I parse the files and load them into Dictionary<string, object>) and need to have the capacity.

Maybe I found a workaround. Don't expose a Dictionary but a IReadOnlyDictionary as the AnyType ParseValue will do :

```csharp
 if (value is IReadOnlyDictionary<string, object> dict)
            {
                var fields = new List<ObjectFieldNode>();
                foreach (var field in dict)
                {
                    fields.Add(new ObjectFieldNode(
                        field.Key,
                        ParseValue(field.Value, set)));
                }
                return new ObjectValueNode(fields);
            }
```

By changing my Dictionary type to IReadOnlyDictionary, I had the expected result

__Before :__
```json
{
"capacities":[{"key":"SubnetProvider","value":true}]
}
```
__After :__
```json
{
"capacities":{"SubnetProvider":true}
}
```

thank you

**Comment by ernestfolch** [comment]
I have same error and the workaround exposing the Dictionary as IReadOnlyDictionary it doesn't work in my case.

**Comment by corinaivanov** [comment]
The same thing happens to me, even after changing to IReadOnlyDictionary.

**Comment by glen-84** [comment]
Trying to debug this a bit, and for whatever reason, the runtime type is a `KeyValuePair` – that seems odd, shouldn't it be a dictionary?

![image](https://user-images.githubusercontent.com/261509/218080137-5f75abfc-2736-4e87-bc85-f0012304c73f.png)

**Comment by Soundman32** [comment]
A dictionary is basically `ICollection<KeyValuePair<K,V>>`.

**Comment by glen-84** [comment]
> A dictionary is basically `ICollection<KeyValuePair<K,V>>`.

Right, but `KeyValuePair` is the element type, not the type itself.

**Comment by michaelstaib** [comment]
Use our new JsonType. Video coming out soon ...

**Comment by glen-84** [comment]
@michaelstaib

> Use our new JsonType. Video coming out soon ...

If I do ...

```cs
    [GraphQLType<JsonType>]
    public required Dictionary<string, string> Fields { get; init; }
```

I get:

> JSON cannot serialize the given value.

I don't think that the JSON type solves the original issue of serializing dictionaries _specifically_, not just any dynamic data.

Maybe there needs to be another built-in scalar, since the current default (key/value pair objects) probably makes sense?

**Comment by michaelstaib** [comment]
I have reopened this to investigate the issue @glen-84 still has with the Any and JSON.

**Comment by glen-84** [comment]
I tested the issue in the OP, and I cannot reproduce it in HC 13.0.2.

Michael has said that only `<string, object>` is supported, not `<string, string>`.

@RubcovMindbox @ernestfolch @corinaivanov

Which type and generic arguments are you using?

**Comment by Spaier** [comment]
I encountered this issue.

Returning type
```csharp
public record MyObjectState
{
    public string Id {get; set; }
    
    [GraphQLType(typeof(AnyType))]
    public IDictionary<string, object?>? Fields { get; set; }
}

```

GraphQL
```
  myObject(
    id: "cool-guid") {
    id
    fields
  }
```

MongoDB Database content
```
{
  "_id": "d8defe10-3d17-1111-822d-f151301594d9",
  "fields": {
    "name": "MyName",
    "someOptionalValue": null,
    "someStringValue": "32",
    "dateOfBirth": {
      "$date": "2023-04-05T00:00:00.000Z"
    },
    "gender": "female",
    "nestedObject": {},
    "nestedArray": [
      {
        "name": "item1",
        "isOk": true,
        "rules": [
          {
            "node": "abra kadabra"
          }
        ],
        "dataFields": [
          "dateOfBirth",
          "name"
        ]
      },
      {
        "name": "item2",
        "isOk": true,
        "rules": [
          {
            "description": "hehe < 5"
          }
        ],
        "dataFields": [
          "dateOfBirth",
          "someStringValue"
        ]
      }
    ],
    "someCode": {
      "$numberLong": "0"
    }
  },
}
```

**Comment by Spaier** [comment]
For me it was `JToken` and `ExpandoObject` issue. 

I had to convert JToken to Dictionary recursively instead of just using `.ToObject<Dictionarty<string, object?>>`

**Comment by Spaier** [comment]
![image](https://user-images.githubusercontent.com/18536847/230352213-fef4dcc9-030f-414f-9b21-bba1b70dcaee.png)

**Comment by Spaier** [comment]
@michaelstaib 
Does it make sense to change IReadOnlyDictionary to IDictionary in ObjectToDictionaryConverter?

```
    private void VisitObject(
        object obj,
        Action<object> setValue,
        ISet<object> processed)
    {
        if (processed.Add(obj))
        {
            var dict = new Dictionary<string, object>();
            setValue(dict);

            if (obj is IReadOnlyDictionary<string, object> d)
            {
                foreach (KeyValuePair<string, object> item in d)
                {
                    Action<object> setField = v => dict[item.Key] = v;
                    VisitValue(item.Value, setField, processed);
                }
            }
            else
            {
                foreach (PropertyInfo property in GetProperties(obj))
                {
                    string name = property.GetGraphQLName();
                    object value = property.GetValue(obj);
                    Action<object> setField = v => dict[name] = v;
                    VisitValue(value, setField, processed);
                }
            }
        }
    }
```

**Comment by michaelstaib** [comment]
I have moved this to 13.4 to refine the Any type further.

**Comment by LorenzoMarchisio05** [comment]
shouldn't this work also with dictionary<string, string>? or any value type different from object? i'm facing this issues where if i store data as IDictionary<string, string> i get the list of keyvaluepair serialization, instead if i store them as IDictionary<string, object> i get the correct serialization like json, shouldn't this work in both case?

**Comment by realnickivanov** [comment]
That's a bummer, because the hstore type in Postgres is mapped to Dictionary<string, string>.
