### ISSUE TITLE
Strawberry Shake empty directories obj/berry in unexpected locations

### ISSUE THREAD

**Issue by nightroman** [ChilliCream/graphql-platform#3653]
# Strawberry Shake empty directories obj/berry in unexpected locations

ref: [Slack](https://hotchocolategraphql.slack.com/archives/CMUJ40EHJ/p1619871373447700)

Directories `obj/berry`, often empty, are usually created in parent directories of directories with Strawberry Shake.

Several our projects with Strawberry Shake exhibit this pattern.

I can also see empty `obj/berry` in very unexpected locations:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\obj\berry
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\ServiceHub\Hosts\ServiceHub.Host.CLR.AnyCPU\obj\berry
```

**Expected behavior**

If directories `berry` are needed, they should be created in more expected locations, e.g. in `bin` or `obj` relative to project directories.

**Additional context**

- Windows 10
- Strawberry Shake 11.2.2

**Comment by agr** [comment]
Not sure if related, but in my case I see the following build errors.

When built with `dotnet build`:
> Access to the path 'C:\Program Files\dotnet\sdk\7.0.200-preview.22605.5\Roslyn\bincore\obj\berry' is denied.

When built with `msbuild`:
> Access to the path 'obj\\berry' is denied.

It seems that `obj\berry` gets appended to some unexpected path (current directory?) at some point.

**Comment by agr** [comment]
The value `obj\\berry` seems to be coming from the `StrawberryShake_State` variable which in turn based on the value of `BaseIntermediateOutputPath` which seems to default to just `obj\` and come from `Microsoft.Common.CurrentVersion.targets` that comes standard with MSBuild.

**Comment by nightroman** [comment]
@michaelstaib @tobias-tengler 
I cannot reopen the issue because it is closed by the stale bot and I did not have a chance to revisit at the time.
Could you please reopen? Or should I or somebody else create duplicate issues?

**Comment by agr** [comment]
I worked around my issue by setting
```
    <BaseIntermediateOutputPath>$(MSBuildProjectExtensionsPath)</BaseIntermediateOutputPath>
```
in my .csproj. But no clue where it is coming from. And it also happens on my dev machines. CI pipeline builds it fine.

**Comment by agr** [comment]
Hacked together a repro: https://github.com/agr/StrawberryShakeObjBerryRepro. Just a classlib project with some GraphQL files added.

Thinking more about it, I'm pretty sure it works on our CI machines just because .NET SDK there is installed to a location where user under which the build runs has permissions to write to, so it just creates missing `obj\berry` directory (I guess that's what is observed in OP), on my dev machines, .NET SDK is installed under Program files (with VS), where user under which I work don't have write permissions, so it fails.

Adding
```
    <StrawberryShake_State>$(MSBuildProjectExtensionsPath)berry</StrawberryShake_State>
```
to .csproj under `PropertyGroup` makes it build.

**Comment by agr** [comment]
I would take a swing of fixing it (assuming that `StrawberryShake_State` setup above is OK), but I can't even find any reference to that variable in the repository. Where does the `StrawberryShake.CodeGeneration.CSharp.Analyzers.targets` file that is present in the StrawberryShake.CodeGeneration.CSharp.Analyzers package come from?

**Comment by nightroman** [comment]
I've just searched my whole PC and found dozens of `obj\berry`, some in very unexpected locations that have nothing to do with StrawberryShake development or even "development" at all.

The latter case is probably due to my habit of running build related commands from arbitrary file system locations, e.g. using helper PowerShell scripts and console. Perhaps `obj\berry` location may also depend on the current directory when builds are invoked.

**Comment by michaelstaib** [comment]
We are done this week with the server and then we will tackle the Strawberry Shake issues.

**Comment by michaelstaib** [comment]
In any case @nightroman are you using 11? Try out the new 13 builds ... I have a youtube guide on how to get started with these. They are much more stable then the source generator based solution.

**Comment by nightroman** [comment]
@michaelstaib I am using the latest 12.15.2

https://www.nuget.org/packages/StrawberryShake.CodeGeneration.CSharp.Analyzers/12.15.2

I do not see v13 of this package.

**Comment by michaelstaib** [comment]
The new version is still preview and you will need to remove all package of the old version first. Depending on where you are using this we have now:

- StrawberryShake.Server -> Backend to Backend / Tests and so on
- StrawberryShake.Blazor
- StrawberryShake.Maui

Essentially choose you flow.

I have done a couple videos to get started with the new version:
https://www.youtube.com/playlist?list=PLrstfnkvFxvo_eP4s816F_EtT8rb97Lg3

**Comment by TyrenDe** [comment]
I tried to update and got it mostly working, but realized my docker images are .NET7, but the 13-preview seems to require .NET6.

**Comment by nightroman** [comment]
@michaelstaib In a test project I replaced

```
    <PackageReference Include="StrawberryShake.CodeGeneration.CSharp.Analyzers" Version="12.15.2" />
    <PackageReference Include="StrawberryShake.Transport.Http" Version="12.15.2" />
```

with

```
    <PackageReference Include="StrawberryShake.Server" Version="13.0.0-preview.92" />
    <PackageReference Include="StrawberryShake.Transport.Http" Version="13.0.0-preview.92" />
```

Then build fails

```
EXEC : error GQL: Unable to resolve type reference `None: Name!`. ...
```

**Comment by michaelstaib** [comment]
This is now fixed with 13
