### ISSUE TITLE
Schemas Stitching: Delegate Directive doesn't support arrays in variables

### ISSUE THREAD

**Issue by Savvato** [ChilliCream/graphql-platform#3682]
**Describe the bug**

When the gateway service tries to resolve some reference by an array of Ids, it returns an error message like "X cannot parse the given value of type `HotChocolate.Language.StringValueNode`." where X may be Uuid, Int, or just String.
My assumption is there is something wrong with how the GraphQL variables are serialized in such cases.

The essential idea is the following: one entity contains references to the other one. The entities are stored in the different services. GraphQL Gateway is supposed to resolve these references.
It turns out that there are some deserialization issues during loading referenced entities from the other schema by a set of Ids. The type doesn't matter, it may be GUID, int, string.

**To Reproduce**
1. Create service A that contains some type A
2. Create service B, where type B  has one-to-many references to A
3. Create GraphQL Gateway service, add stitching file, extend type B with delegation resolver to type A
4. Run all services
5. Run a GraphQL query that requests full type B entities with resolved references to type A
6. Get the error `Uuid cannot parse the given value of type `HotChocolate.Language.StringValueNode`.`

Also, I created a repository that contains the example: https://github.com/Savvato/HC_StitchingIssue

**Expected behavior**
The Gateway Service is supposed to successfully resolve one-to-many references by arrays of Uuid/Int/String.

**Desktop (please complete the following information):**
 - OS: windows 10
 - .Net 5. HotChocolate.AspNetCore 11.2.2

**Comment by jamiewinder** [comment]
I've just encountered this issue in 12.9.0 and the latest preview.

**Comment by EricStG** [comment]
Same issue with both 12.16 and 13 preview 94.
With an int array parameter, we get:
```
Int cannot parse the given value of type `HotChocolate.Language.IntValueNode`.
```
It works when we hardcode the array parameter in the type extension though, but that's not super practical obviously.

Here's the stiching
```
extend type SomeType {
    items: [Item!]! @delegate(schema: "item", path:"items(itemIds: $fields:itemIds)")
}
```

**Comment by EricStG** [comment]
Still happens in 13.0.5
Setup a minimal repro here: https://github.com/EricStG/hc-stitching-array-repro

**Comment by michaelstaib** [comment]
HotChocolate.Stitching is now in legacy mode and is replaced by HotChocolate.Fusion. I am closing this issue as we essentially froze the fusion code.

You can join the preview of Hot Chocolate Fusion now on Slack
