### ISSUE TITLE
Allow only persisted queries to be executed

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/graphql-platform#3943]
**Is your feature request related to a problem? Please describe.**
While writing documentation for persisted queries (#3616) it came up that there is currently no good way of allowing only persisted queries to be executed.

**Describe the solution you'd like**
There should be a new option in the server configuration users can set to refuse any "dynamic" queries and only execute requests which contain a query `id`:

```csharp
app.UseEndpoints(endpoints =>
{
    endpoints.MapGraphQL().WithOptions(new GraphQLServerOptions
    {
        AllowOnlyPersistedRequests = true
    });
});
```

`AllowOnlyPersistedRequests` is of course just an idea and nothing final.

**Comment by tobias-tengler** [comment]
This is something that would "harden" the GraphQL server against specifically crafted, malicious queries, so I'm marking it as not stale and a security topic.

**Comment by glen-84** [comment]
Could this option be changed dynamically, for example if it was based on the ClaimsPrincipal? Or would you just implement that more manually, with middleware or something?
