### ISSUE TITLE
Strip leading "I" from interface name

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/graphql-platform#4154]
### Is your feature request related to a problem?

When writing interfaces in C# i follow the naming convention of placing an `I` in front of the name, so an interface for a message becomes `IMessage`. When using this interface as a GraphQL interface type, I don't want to have the leading `I`, as this is not a common naming convention. Therefore I often find myself renaming interface types to strip of  the leading "I":
```csharp
[InterfaceType("Message")]
public interface IMessage
{
}
```

### The solution you'd like

Hot Chocolate should introduce a new naming Convention that strips of the leading "I", if the type is an interface type and if the second character is also capital (optional).
Maybe there will be some false positives with people not naming their C# interfaces per convention, but those shouldn't be the norm and they can still opt to explicitly naming the interface type.

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
This could be a option ... There are interfaces without the leading `I` that is why I did not add something until now. But we can provide an output on the the schema options.

**Comment by rickardp** [comment]
We currently add our own type interceptor to do exactly this.
