### ISSUE TITLE
No fields defined on Query when using [ExtendObjectType] along with global Explicit Binding behavior

### ISSUE THREAD

**Issue by leealso** [ChilliCream/graphql-platform#4320]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When using [ExtendObjectType] in v12
`[ExtendObjectType("Query")]
    public class MyExtension
    {
        [GraphQLName("Hello)]
        public string> Hello()
        {
            return "Hello";
        }
    }`

and global Explicit Binding behavior
`services.AddGraphQLServer()
  .AddQueryType(d => d.Name("Query"))
  .AddTypeExtension<MyExtension>()
  .ModifyOptions(c => c.DefaultBindingBehavior = BindingBehavior.Explicit);`

no fields are defined/detected on the Query
`The object type `Query` has to at least define one field in order to be valid. (HotChocolate.Types.ObjectType)`

### Steps to reproduce

1. Enable global Explicit Binding behavior.
2. Create a query and an extension with a field.
3. Relate the extension to the query.
4. Run the project.

### Relevant log output

```shell
The object type `Query` has to at least define one field in order to be valid. (HotChocolate.Types.ObjectType)
```

### Product

Hot Chocolate

### Version

12.0.0

**Comment by MarkoH17** [comment]
Any update on this? It seems to also affect HC 13.0.0-preview.5

**Comment by glen-84** [comment]
@michaelstaib Could this issue please be reopened?

**Comment by michaelstaib** [comment]
We have implemented this for rc.1 but it broke existing user workflows like outlined in #5709.

What some code first users are doing is using the errors to ensure that for each type there is in fact an explicit type declared so that properties do not accidentally leak out.

I find that a very compelling workflow. However, we also want to enable this issue here.

**Comment by michaelstaib** [comment]
With RC.5 we have this now implemented.
