### ISSUE TITLE
RFC: Client Controlled Nullability

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/graphql-platform#4379]
This PR implements the Client Controlled Nullability RFC.

https://github.com/graphql/graphql-spec/pull/895

- [x] AST
- [ ] AST Tests
- [ ] AST Docs
- [x] Lexer
- [ ] Lexer Tests
- [ ] Lexer Docs
- [x] Parser
- [x] Parser Tests
- [ ] Parser Docs
- [x] SyntaxPrinter
- [ ] Visitor
- [x] Rewriter
- [x] Operation Compiler
- [x] Do we have changes in the execution or does a change in the operation compiler suffice?
- [ ] Benchmarks
  - [ ] Parser
  - [ ] OperationCompiler
  - [ ] QueryPlan
  - [ ] Execution
- [x] Validation Rules
- [ ] Naming is not quite right yet

**Comment by glen-84** [comment]
Closing, as Client Controlled Nullability is [being replaced](https://github.com/graphql/graphql-spec/pull/895#issuecomment-1863928348) with another solution.
