### ISSUE TITLE
ExtendObjectType allows multiple instances on a class but only respects the last one

### ISSUE THREAD

**Issue by oising** [ChilliCream/graphql-platform#4460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

```
[ExtendObjectType(typeof(A))]
[ExtendObjectType(typeof(B))]
[ExtendObjectType(typeof(C))]
public class FooExtensions { ... }
```

Expectation: I would expect the extensions to be applied to all types: A, B & C. 

Reality: The extensions are only applied to type C.

### Steps to reproduce

n/a -- see description. 

### Relevant log output

```shell
n/a
```

### Additional Context?

I know there are workarounds (use a common base class/interface) but in my case, this is not practical. 

### Product

Hot Chocolate

### Version

12.2

**Comment by oising** [comment]
Is this fixed, @michaelstaib  ? I can't remember.

**Comment by michaelstaib** [comment]
This was never intended to allow more than one. I fixed it now.

If you want to extend multiple classes at once use an interface or a base type as the generic. I made a video that goes into detail on this.
