### ISSUE TITLE
Improve Cursor Pagination with EFCore

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/graphql-platform#4525]
Track: https://github.com/dotnet/efcore/issues/26822, https://github.com/dotnet/efcore/issues/17065

**Comment by glen-84** [comment]
Is this considered blocked, or are the linked issues just nice-to-haves?

Keyset pagination can be implemented without row-value comparison. What is Skip/TakeLast needed for?

**Comment by michaelstaib** [comment]
Its not blocked, its on the backlog for 13. If you want to have a go at it you can do. Essentially we need to implement a specific paging provider for EF. @PascalSenn can talk you through it if you want to do a PR.

**Comment by michaelstaib** [comment]
This one was superseded by our new paging implementation that is now in 14
