### ISSUE TITLE
Schema first: V12 Removed functionality to achieve two-way binding of input type fields

### ISSUE THREAD

**Issue by jerrysdev** [ChilliCream/graphql-platform#4560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In V11 schema first, we were able to do the following to solve mismatch in input type field names between runtime type properties and GraphQL type fields:
`BindComplexType<RuntimeFooInput>(b => b.To("FooInput").Field(f => f.FooProp).Name("fooField"))`

In V12 schema first, no `BindRuntimeType` overload can achieve this, and we have not found another way to do it. Everything we've tried accomplishes resolver-style, i.e. one-way, bindings. Are we missing something?

We have sidestepped the issue temporarily by renaming the runtime type properties to match the corresponding GraphQL input type fields, but for our setup it comes with other issues that we would like to avoid in the future.

### Steps to reproduce

1. N/A

### Product

Hot Chocolate

### Version

12.3.2

**Comment by michaelstaib** [comment]
That is true... I have removed this functionality in favor of better automatic bindings. We will do another round of improvements soon for schema-first with another dot release. I will have a look at how we re-introduce this kind of bindings. Probably another overload on BindRuntimeType.

**Comment by jerrysdev** [comment]
Please don't close this issue sir stale
