### ISSUE TITLE
Documentation for generated mutation-specific Input types does not render default argument values

### ISSUE THREAD

**Issue by xavierdecoster** [ChilliCream/graphql-platform#4763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using default mutation naming conventions to generate the boiler-plate code for mutation-specific Payload and Input types, Banana Cake Pop is expected to also show relevant documentation for these types.

Documentation is being generated typically leveraging XML comments and signature information.
For Query fields, the default argument values are properly rendered.
For Mutation fields, this should also be the case.

When generating the mutation-specific Input types, the argument default values are omitted from this documentation.

### Steps to reproduce

1. Using default MutationNamingConventions, create a mutation accepting several arguments.
    For example:

    ```csharp
    public Task<Entity> CreateEntity(string id, bool flag = true) { }
    ```
2. Observe the generated `CreateEntityInput` type in GraphQL schema. The documentation in Banana Cake Pop UI is expected to show the default value for `flag = true`, but it is omitted.

### Product

Banana Cake Pop

### Version

12.6.0

**Comment by michaelstaib** [comment]
@artola this seems to be a bcp bug ... i just checked the server and its correct. It seems that default values for inputs are not displayed.

**Comment by michaelstaib** [comment]
Awesome!

**Comment by artola** [comment]
@xavierdecoster Thanks for the heads-up. We fixed the default values to correctly be shown in fields and arguments.
It will be soon released with BCP v4.
