### ISSUE TITLE
Allow BCP schema endpoint to automatically match browser URL

### ISSUE THREAD

**Issue by AlexKubiesa** [ChilliCream/graphql-platform#4765]
### Is your feature request related to a problem?

I am testing the same GraphQL API in multiple environments (local, dev, uat and prod) and each of these has a different URL. When I navigate to one of these URLs and sign in to my BCP workspace, my queries always run against the saved schema endpoint from last time, but I want them to run against the URL in my address bar instead.

### The solution you'd like

Ideally, the Schema Endpoint setting would be configured based on which GraphQL server I am accessing, not which document I have open.

If this is not possible, then an alternative solution would be to allow variables in the Schema Endpoint setting, and have a variable like `%bcpEndpoint%` so I can set the Schema Endpoint to equal the BCP Endpoint.

### Product

Banana Cake Pop

**Comment by michaelstaib** [comment]
We are working on a new feature that will make BCP environment aware.

**Comment by rstaib** [comment]
Wouldn't this issue be solved by hitting the schema reload button?

**Comment by AlexKubiesa** [comment]
@rstaib I feel like you've misunderstood the issue. I am talking about controlling the GraphQL Endpoint (called "Schema Endpoint" in the BCP UI) based on whether I navigated to the local/dev/uat/prod service URL.

Giving BCP an "environments" feature akin to Postman and Insomnia, as @michaelstaib mentioned, would be a step in the right direction as I could have the same set of documents between local/dev/uat/prod and by switching to a different environment make them all point to the service I'm currently testing or debugging.
