### ISSUE TITLE
Uppercase properties in mutation inputs throws InvalidOperationException 

### ISSUE THREAD

**Issue by brunowarmling** [ChilliCream/graphql-platform#4811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Given a mutation input like this;

```
public class CreateCNAEInput
{
	public CreateCNAEInput(CNAEMutationInput cnae)
	{
		this.CNAE = cnae;
	}
	
	[Required]
	public CNAEMutationInput CNAE { get; }
}
```

When the project is ran a `InvalidOperationException`  is thrown.

> System.InvalidOperationException: 'No compatible constructor found for input type type `Models.Mutations.Input.CreateCNAEInput`.
Either you have to provide a public constructor with settable properties or a public constructor that allows to pass in values for read-only properties.There was no way to set the following properties: cNAES.'

Changing the property `CNAE` to `Cnae` it's going to work.

### Steps to reproduce

1. Create a mutation.
2. Sets the mutation to receive a input.
3. Sets the mutation input to have a property in uppercase and receive a parameter on its constructor to set it.
4. Runs the project.

### Product

Hot Chocolate

### Version

12.6.0

**Comment by da1rren** [comment]
Repo'd with

```csharp
using System.ComponentModel.DataAnnotations;

var builder = WebApplication.CreateBuilder(args);

builder.Services
    .AddGraphQLServer()
    .AddQueryType<Query>()
    .AddMutationType<Mutation>();

var app = builder.Build();
app.MapGraphQL();
app.Run();

public class Book
{
    public string Title { get; set; }
}

public class Query
{
    public Book GetBook() =>
        new Book
        {
            Title = "C# in depth."
        };
}

public class Mutation
{
    public ADDBookResponse AddBook(CreateCnaeInput input)
    {
        return new ADDBookResponse(input.CNAE.Title);
    }
}


public class CreateCnaeInput
{
    public CreateCnaeInput(CNAEMutationInput cnae)
    {
        this.CNAE = cnae;
    }

    [Required]
    public CNAEMutationInput CNAE { get; }
}

public record CNAEMutationInput(string Title);

public record ADDBookResponse(string Title);
```

**Comment by michaelstaib** [comment]
This is now fixed with 13 rc 2

**Comment by michaelstaib** [comment]
For version 13 we slightly tweaked it. If the fields in the input are unique when the casing is removed we will use a relaxed algorithm that ignores the case. If however there are multiple versions of the same fieldname, like `baR` and `Bar` we will use the strict rules used in version 12.
