### ISSUE TITLE
EnrichError not getting called when producing HC0018

### ISSUE THREAD

**Issue by glucaci** [ChilliCream/graphql-platform#4821]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

`EnrichError` override not getting called when producing HC0018 error.

### Steps to reproduce

1. create custom `ActivityEnricher` and override `EnrichError(IError error, Activity activity)`.
2. register custom enricher
```csharp
.AddSingleton<ActivityEnricher, CustomActivityEnricher>();
```
4. produce HC0018 error
```csharp
.AddQueryType(d => d
    .Field("foo")
    .Type<NonNullType<StringType>>()
    .Resolve((_, _) => null))
```
5. `EnrichError` is not getting called nor the `EnrichHttpRequestError` (both overloads)

### Relevant log output

```shell
{"errors":[{"message":"Cannot return null for non-nullable field.","locations":[{"line":1,"column":2}],"path":["foo"],"extensions":{"code":"HC0018"}}]}
```

### Additional Context?

I'm getting the `HttpClient` response without getting into `EnrichError`.

In another use-case where I throw an Exception in the field resolver, the `EnrichError` is getting called.

### Product

Hot Chocolate

### Version

13.0.0-preview.9

**Comment by queil** [comment]
I've tried overriding all the methods on a custom enricher and none of them were called. It seems to be a broader issue.

**Comment by queil** [comment]
OK, so it looks like the issue is that the activity is null in [here](https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Diagnostics/src/Diagnostics/Listeners/ActivityExecutionDiagnosticListener.cs#L50). Following [this](https://github.com/dotnet/runtime/issues/45070#issuecomment-731770336) guidance I managed to get it working by adding the following code to my custom enricher constructor:

```c#
        ActivitySource.AddActivityListener(new ActivityListener
        {
             ShouldListenTo =  _ => true,
             SampleUsingParentId = (ref ActivityCreationOptions<string> activityOptions) 
                 => ActivitySamplingResult.AllData,
             Sample = (ref ActivityCreationOptions<ActivityContext> activityOptions) 
                 => ActivitySamplingResult.AllData
        });

```

**Comment by michaelstaib** [comment]
This one is fixed!

**Comment by glucaci** [comment]
@michaelstaib at least in my test this is not working. Just tested with `13.0.0-preview.103`
```csharp
new ServiceCollection()
    .AddSingleton<ActivityEnricher, GraphQLActivityEnricher>()
    .AddGraphQLServer()
    .AddQueryType(d => d
        .Field("foo")
        .Type<NonNullType<StringType>>()
        .Resolve((_, _) => null));
```
When the resolvers return `null` none of the `Enrich*Error` methods from the custom `GraphQLActivityEnricher` gets called.
