### ISSUE TITLE
Schema Disposal Issues when using Redis Federated Schemas & Subscriptions

### ISSUE THREAD

**Issue by matt-psaltis** [ChilliCream/graphql-platform#4863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

We've been seeing high memory pressure on API gateways when microservices are redeployed which invokes a schema publish and subsequent schema reload. This leads to the following identified issues.

1. The RedisExecutorOptionsProvider incorrectly disposes of the ServiceProvider prematurely. This leads to ObjectDisposedExceptions which are not logged in the RequestExecutorResolver.BeginRunEvictionEvents due to the use of the Task Factory.
2. The OperationExecutionMiddleware forms a closure over the Schema object preventing GC collection.

### Steps to reproduce

1. An integration test has been provided.

I would like some input on the 5 minute delay in the RequestExecutorResolver. My thoughts are we could use the Diagnostics system to more accurately track pipelines when they reach an empty state (in terms of active network requests) and complete the disposal process rather than the existing:

`await Task.Delay(TimeSpan.FromMinutes(5));`

### Product

Hot Chocolate

### Version

12.7.0

**Comment by Spaier** [comment]
Getting this error as well.

HC: 12.3.2

**Comment by michaelstaib** [comment]
HotChocolate.Stitching is now in legacy mode and is replaced by HotChocolate.Fusion. I am closing this issue as we essentially froze the fusion code.

You can join the preview of Hot Chocolate Fusion now on Slack
