### ISSUE TITLE
Activate Remove Unreachable Types by default

### ISSUE THREAD

**Issue by PascalSenn** [ChilliCream/graphql-platform#4900]
### Is your feature request related to a problem?

With the new customization feature of filtering there are a bunch of dead types in the schema. These have to be removed

### The solution you'd like

We decided to turn on remove unreachable types by default.

Even if the user opts out of the feature, the algorithm will still run and remove specially tagged types (like filtering types)

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
We did not do this.
