### ISSUE TITLE
Support optional projection for calculated properties

### ISSUE THREAD

**Issue by th-fulcrum** [ChilliCream/graphql-platform#4981]
### Is your feature request related to a problem?

Currently, if you have a projected property the only way to tell hot chocolate to project the required fields is to use `IsProjected(true)` which will always include the fields. This is unnecessary as a calculated field isn't necessarily always included. 

### The solution you'd like

I'd like there to be something like a `RequiredProjections` attribute which you could add to calculated fields. My imaginary syntax would look like: 

```
[RequiredProjections(Person.FirstName, Person.LastName)]
public string FullName => x.FirstName + x.LastName
```

Then, hot chocolate would be able to know, if FullName is included in the query, project FirstName and LastName.

### Product

Hot Chocolate

**Comment by glen-84** [comment]
Duplicate of #2575 (?).

**Comment by glen-84** [comment]
Closing as a duplicate of https://github.com/ChilliCream/graphql-platform/issues/2575.
