### ISSUE TITLE
Bug in the Equals method of SpreadReference causes slow execution times

### ISSUE THREAD

**Issue by yechiz** [ChilliCream/graphql-platform#5042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The equals methods were copied from another place so the object type is incorrect, causing it to always return false.
As a consequence, the OperationCompiler.ResolveFragmentSpread method always not finding the SpreadReference in the context.Spreads, and adding another vaule to this dictionary.

The fix is very simple, just fix the equals methods of SpreadReference to be:
```
        public bool Equals(SpreadReference other)
        {
            return Path.Equals(other.Path) && Spread.Equals(other.Spread);
        }

        public override bool Equals(object? obj)
        {
            return obj is SpreadReference other && Equals(other);
        }
```

instead of:
```
        public bool Equals(SelectionReference other)
        {
            return Path.Equals(other.Path) && Spread.Equals(other.Selection);
        }

        public override bool Equals(object? obj)
        {
            return obj is SelectionReference other && Equals(other);
        }
```

Notice there that in addition to the changes of the object type, there is the change of: Spread.Equals(other.**Spread**).

### Steps to reproduce

Use a query with fragments on a field that can be of some different sealed types. 
Debug the OperationCompiler.ResolveFragmentSpread method, and see it always adds to the context.Spreads dictionary. 
If there are a lot of types the **first** query execution will have a slow compilation time (for every different query).

### Product

Hot Chocolate

### Version

12.7.0

**Comment by michaelstaib** [comment]
This issue was fixed with 13.9.8 and 14.0.0
