### ISSUE TITLE
Use filtering result does not filter

### ISSUE THREAD

**Issue by VahidCh013** [ChilliCream/graphql-platform#5055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi,
I am using `UseFiltering` in my app.
In my development and staging environments I get the result with filtering, but it does not work in Production environment.

### Steps to reproduce

Here is my Query class:
```
public class ProductQueries
    {
        [Authorize]
        [UseDbContext(typeof(MyDbContext))]
        [UsePaging]
        [UseFiltering]
        [UseSorting]
        public IQueryable<Product> GetProducts([ScopedService] MyDbContext db)
        {
            var query = db.Products;
            return query.OrderBy(x => x.ModelCode);
        }
   }
```
This query will return products (stating with test) in my development and staging but will return **all products** in live.
```
query{
	products(where: { productName: { startsWith: "Test" } }) {
                                nodes {
                                                categoryName
                                                productName
			}
		}
}
```

### Additional Context?

I struggled with this issue before and raised my question [here](https://stackoverflow.com/questions/69391500/graphql-where-does-not-filter-in-staging).

I could fix the issue by adding new queries in class, like below and after deployment on production it will work.

```
public class ProductQueries
    {
        [Authorize]
        [UseDbContext(typeof(MyDbContext))]
        [UsePaging]
        [UseFiltering]
        [UseSorting]
        public IQueryable<Product> GetAnyProduct([ScopedService] MyDbContext db)
        {
            var query = db.Products);
            return query.OrderBy(x => x.ModelCode);
        }

        [Authorize]
        [UseDbContext(typeof(MyDbContext))]
        [UsePaging]
        [UseFiltering]
        [UseSorting]
        public IQueryable<Product> GetProducts([ScopedService] MyDbContext db)
        {
            var query = db.Products);
            return query.OrderBy(x => x.ModelCode);
        }
   }
```

### Product

Hot Chocolate

### Version

11.2.2

**Comment by glen-84** [comment]
@VahidCh013 Please add a link to a minimal reproduction of this issue.

**Comment by glen-84** [comment]
Closing, for lack of a minimal reproduction.
