### ISSUE TITLE
I'm not sure how you've built your dynamic schema, but when using `ITypeModule` you have the `TypesChanged` event that you can trigger to reload the schema.

### ISSUE THREAD

**Issue by lunindv** [ChilliCream/graphql-platform#5061]
I'm not sure how you've built your dynamic schema, but when using `ITypeModule` you have the `TypesChanged` event that you can trigger to reload the schema.

Currently there is no documentation on this, but you can read [this blog post entry](https://chillicream.com/blog/2021/09/27/hot-chocolate-12#dynamic-schemas) as a primer and look at [this example](https://github.com/ChilliCream/hotchocolate-examples/blob/master/misc/TypeModules/DynamicTypes/CustomTypeModule.cs).

_Originally posted by @tobias-tengler in https://github.com/ChilliCream/hotchocolate/discussions/4902#discussioncomment-2451067_

**Comment by lunindv** [comment]
This very actual problem for me to. I don't undestend how ITypeModule can help me. We tried use ITypeModule but it not resolve our task. On example i has classes:
1. Query - code for all my resolvers
2. Mutation - code for all my mutations
3. MyDbContext - EF db context
4. Models classes from DB
5. Input and Output classes for my mutations
All classes generates dynamicaly and compile as "in memory" assembly.
And the end i'm  call hotchocolate methods (AddQueryType and AddMutation) for my generated classes with reflection. This work fine.
I want after change structure my DB and regeneration my assemble simple reloading "Query" class and "Mutation" class in runtime. How i can do it?
Can you help me do it?

**Comment by Nivisan-Jeyananthan** [comment]
https://hotchocolategraphql.slack.com/archives/C01QQ4JKYUV/p1646768716848369

This slack thread might help.
