### ISSUE TITLE
Allow Distributed Domain Model Integration

### ISSUE THREAD

**Issue by darrenhull** [ChilliCream/graphql-platform#5094]
### Is your feature request related to a problem?

In our system we have a graphQL gateway in one Azure function, A rest API Gateway in a microservice and a backend implementation in another project which has multiple Azure functions.  The Gateways communicate using the AMPQ request response pattern over a messaging service such as Azure ServiceBus. 

### The solution you'd like

Is there anyway for us to get convert the filtering and sorting into a domain model that we can pass over our services. We are thinking we might have to write a handler such as the MongoDbListAnyOperationHandler.

This way we can use the GraphQL filtering and paging but also use our distributed system.

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
We have this on our list for 13. Essentially you will be able to serialize the filter into a dictionary structure. That can be used to send into your application layer or over the wire.

**Comment by darrenhull** [comment]
Well that is great, what specific point on 13 is this referring too? 13 has May 22 as the delivery is that still accurate? Unfortunately, we cannot really use this wonderful framework until that is in place.

**Comment by michaelstaib** [comment]
This is implemented ... you can inject IFilterContext in version 13 and on the IFilterContext call to ToDictionary() ... same goes for sorting ... just there you have to inject ISortingContext
