### ISSUE TITLE
AnyType throws "Parameter count mismatch" exception for JsonElements

### ISSUE THREAD

**Issue by onionhammer** [ChilliCream/graphql-platform#5099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

[JsonExtensionData] for System.Text.Json deserialized Dictionary<string, object>'s as JsonElements, so if you have deserialized an entity from, say Cosmos DB or some other persistence with System.Text.Json which has JsonExtensionData, and trying to output that same Dictionary to a GraphQL field, you will see the parameter count mistmatch error if the dictionary's values are of type JsonElement.

### Steps to reproduce

1. Create a dictionary of type Dictionary<string, object> and fill it it with items of type JsonElement
2. Create a graphQL field with an AnyType and return the dictionary from step 1

### Relevant log output
See #3073 and #2416

### Additional Context?

I think this will happen more and more as libraries switch away from Newtonsoft towards System.Text.Json, so this should be addressed by simply deserializing the JsonElement based on its ValueKind property into an object.

### Product

Hot Chocolate

### Version

12.9.0

**Comment by onionhammer** [comment]
Also, this is not an indictment of anyone (this project is great, and so far I'm 90% loving it) - I do NOT think that the pace of development can support such an aggressive stale bot; it's staling bugs before anyone even has a chance to triage.

**Comment by michaelstaib** [comment]
Regarding the stale bot you just need to comment that it is not stale so that the bot keeps it open for another 60 days. We have found that a lot of the issues are really already done or no longer relevant.

**Comment by michaelstaib** [comment]
I am moving this to the 13 backlog

**Comment by onionhammer** [comment]
@michaelstaib Re: the stalebot, as long as you guys are satisfied with the # of issues its closing vs the number your team is closing I think it's fine. I just wanted to raise the question.

**Comment by michaelstaib** [comment]
@onionhammer can you create a test for us in a PR showing the issue?

This is an example on how to create a repro:
https://github.com/ChilliCream/graphql-platform/blob/main/src/HotChocolate/Core/test/Types.Tests/Regressions/Issue_4811.cs
