### ISSUE TITLE
Support Relay ID deserialization with custom Ids

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/graphql-platform#5114]
### Is your feature request related to a problem?

I saw that #4884 was closed, but I wanted to bring this up as a feature request again.
Recently we've switched to https://github.com/andrewlock/StronglyTypedId to catch some common mistakes, like people passing wrong Ids into our business layer.

Using something like
```csharp
.AddTypeConverter<DeviceId, int>(x => x.Value)
.AddTypeConverter<int, DeviceId>(x => new DeviceId(x))
.BindRuntimeType<DeviceId, IntType>()
```
works great when we have an output like
```csharp
public class Device
{
    [ID]
    public DeviceId Id { get; set; }
}
```
but sadly it doesn't work for inputs like
```csharp
public Task<Device?> GetDeviceAsync(
    [ID(nameof(Device))] DeviceId deviceId,
    DeviceDataLoader dataLoader)
{
    return dataLoader.LoadAsync(deviceId);
}
```
and gives an error like:

> Unable to convert the value of the argument `deviceId` to `MyApp.DeviceId`. Check if the requested type is correct or register a custom type converter.

Maybe I'm also missing something in my configuration, I'm not sure.
But I feel like with the registered type converters, there should be enough information to be able to support this case.

At the moment we have to take the Id as an int and convert it ourselves in each input, which isn't ideal.

### The solution you'd like

The input shown above should just work out of the box, if type converters have been registered.

### Product

Hot Chocolate

**Comment by tobias-tengler** [comment]
The same thing applies also to node resolvers. The following does not work:
```csharp
[Node]
[ExtendObjectType(TypeConsts.Device)]
public class DeviceNode
{
    [NodeResolver]
    public Task<Device?> GetDeviceAsync(DeviceId id, DeviceDataLoader dataLoader)
    {
        return dataLoader.LoadAsync(convertedId);
    }
}
```
Currently we also need to pass the Id as int in the method and then convert it in there.

**Comment by michaelstaib** [comment]
I think its two places where we would need to handle this.

**Comment by mwasson74** [comment]
@tobias-tengler Will this handle "plural fetches" as well? I can't find the issue right now but I remember seeing that only primitive types worked for an ID on "plural fetches" queries like `GetMyEntitiesByIdAsync([ID(nameof(MyEntity))] ComplexIdType[] ids, ...`

**Comment by tobias-tengler** [comment]
I have patched this for the moment in the following way in our code base:

```csharp
public class TypedIdTypeInterceptor : TypeInterceptor
{
    public override void OnBeforeCompleteType(ITypeCompletionContext completionContext,
        DefinitionBase? definition, IDictionary<string, object?> contextData)
    {
        if (completionContext.IsIntrospectionType)
        {
            return;
        }

        if (definition is ObjectTypeDefinition objType)
        {
            foreach (var field in objType.Fields)
            {
                foreach (var argument in field.Arguments)
                {
                    // If we just add our formatter directly on the argument, the formatter is registered
                    // before the Relay ID formatter, which would cause incorrect results.
                    var descriptor = argument.ToDescriptor(completionContext.DescriptorContext);

                    if (argument.Parameter?.ParameterType == typeof(DeviceId))
                    {
                        descriptor.Extend().OnBeforeCompletion((c, d) =>
                        {
                            d.Formatters.Add(new DeviceIdInputValueFormatter());
                        });
                    }
                }
            }
        }
    }
}

public class DeviceIdInputValueFormatter : IInputValueFormatter
{
    public object? OnAfterDeserialize(object? runtimeValue)
    {
        if (runtimeValue is string str)
        {
            return new DeviceId(str);
        }

        return runtimeValue;
    }
}
```

Have to add an `IInputValueFormatter` for each of our typed Ids and register it from within the type interceptor, which is a bit annoying, but atleast not every resolver has to use a workaround...

**Comment by michaelstaib** [comment]
hoho ... @tobias-tengler type interceptors :) BTW ... I refactored the type interceptor and broke a bit the contract for version 13. I will add an upgrade guide to the docs.

**Comment by mwasson74** [comment]
> @tobias-tengler Will this handle "plural fetches" as well? I can't find the issue right now but I remember seeing that only primitive types worked for an ID on "plural fetches" queries like `GetMyEntitiesByIdAsync([ID(nameof(MyEntity))] ComplexIdType[] ids, ...`

I think I'm excited for your new changes. If it also fixes plural fetches, I _know_ I will be excited... 😬

**Comment by mwasson74** [comment]
@tobias-tengler @michaelstaib Is this in any release (preview or otherwise) that I can try out? My ID is the following:
```graphql
type EurodatKey {
  incId: Int!
  sqlId: Short!
}
```
My TypeCoverters work for singular fetches ById but plural fetches ById yells at me saying `The IDS 'blah blah' have an invalid format.`

**Comment by michaelstaib** [comment]
This is now supported

**Comment by tobias-tengler** [comment]
List of custom Ids still aren't working with the new serializer, but I'll check and open another issue, if it's the case.

**Comment by mwasson74** [comment]
@tobias-tengler can you please post back here or tag me in the new issue if one is created?

**Comment by tobias-tengler** [comment]
@mwasson74 I can confirm that it is working in v14! The special sauce is implementing and registering a `INodeIdValueSerializer` for your strongly typed Id. Here's an example of this in action: https://github.com/ChilliCream/graphql-platform/pull/7238/commits/380aac1bb6caf4a2c1dff3ebb0e5e51408078484
There's still an issue if you need the new serializer to handle both the old and new Id format. I hope to address this in: https://github.com/ChilliCream/graphql-platform/pull/7238

**Comment by michaelstaib** [comment]
We also will add source generator support for the ID `INodeIdValueSerializer` ... but this might not be in the initial release.
