### ISSUE TITLE
Building `ObjectType<C# interface goes here>` no longer seems to work

### ISSUE THREAD

**Issue by michaelmccord** [ChilliCream/graphql-platform#5129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Previously building an `ObjectType` where the object was based on/inferred from an interface would work if you overrode the `IsInstanceOfType` method.

For instance:

```csharp
    public class TweetReportType : ObjectType<ITweetReport>
    {
        

        public override bool IsAssignableFrom(INamedType type)
        {
            return base.IsAssignableFrom(type);
        }

        public override bool IsInstanceOfType(IResolverContext context, object resolverResult)
        {
            if (resolverResult as ITweetReport != null)
                return true;

            return false;
        }


        protected override void Configure(IObjectTypeDescriptor<ITweetReport> descriptor)
        {
            descriptor.Authorize("owner", ApplyPolicy.BeforeResolver);
            descriptor.Name("TweetReport");
            descriptor.Field("id")
                .Resolve(context =>
                {
                    ITweetReport grain = context.Parent<ITweetReport>();
                    return grain.GetPrimaryKeyString();
                }).Type<NonNullType<IdType>>();

            descriptor.ImplementsNode()
                .ResolveNodeWith<TweetReportResolver>(r => r.GetGrain(default, default))
                .ID("id");

            base.Configure(descriptor);
        }

    }
```

In the above example, assume `ITweetReport` is an interface. This functionality is necessary to provide interoperability with [MS Orleans](https://dotnet.github.io/orleans/). It seems to at least no longer work (or perhaps never did) when the object is being resolved from a type dynamically defined by a configurator from within the `ConfigureSchemaAsync` method.

For instance something like:

```csharp
builder.AddQueryType(descriptor=>{
descriptor.Field("TweetReports").Type(new ListType<TweetReportType >()).Resolve(ctx=>{....});
});
```

The only field the resulting schema would contain on `TweetReport` objects would be the `id` field. The other fields would not be inferred from `ITweetReport`.

However, this definitely used to work where the resolver was defined on a POCO such as (assuming the same previous definition for `TweetReportType`):

```csharp
public class Query
{
     public List<ITweetReport> GetTweetReports() { ... }
}
```

The object fields would correctly be inferred from the `ITweetReport` interface and would show up in the schema as an object and not an interface.

### Steps to reproduce

1. Produce a code-first schema as noted in the description.
2. Note that in the resultant schema output the defined object does not infer any fields from the interface

### Product

Hot Chocolate

### Version

12.9.0

**Comment by mmccord-processunity** [comment]
> Just to understand this correctly. You are missing fields in the schema?

Yes, it's not picking up the fields from the interface on which the object type is based.

**Comment by michaelmccord** [comment]
> Just to understand this correctly. You are missing fields in the schema?

Yes, it's not picking up the members from the interface on which the object type is based. Examining your code in `FieldDescriptorUtilities` and `DefaultTypeInspector`, this is probably due to this: 

https://stackoverflow.com/questions/2132791/reflecting-over-all-properties-of-an-interface-including-inherited-ones

The interface in question has no properties or methods, only ones it inherits from a generic interface which also inherits some methods from yet another interface (non-generic).

Sorry, I would have included that information in my original description above, but I only discovered that last night. My guess is...that's the culprit and why this isn't working in this particular case.

**Comment by michaelmccord** [comment]
Probably the answer there is if it's an interface, looping through the inherited interfaces (as suggested in the post) and using a recursive algorithm to go through the inheritance hierarchy looking for members.

**Comment by michaelstaib** [comment]
@PascalSenn could this be the change for the interface default impl thingy?

@michaelmccord can you provide a small project with your problem?

**Comment by glen-84** [comment]
Closing, for lack of a reproduction.
