### ISSUE TITLE
Slow schema generation

### ISSUE THREAD

**Issue by FreddyFox1** [ChilliCream/graphql-platform#5185]
### Is your feature request related to a problem?

Hi everyone!
We with my team, using your product Banana Cake Pop on .NET Core platform. Often when we debug our app, we collide with so slow load of schema in banana. How can we fix it? Cuz for any start in debug mode we can not load schema every time its takes so much time.

I tried Add services.AddGraphQLServer().Initialize Startup() but no effect, i get error "Schema Fetching Failed".

Best wishes.

### Product

Banana Cake Pop

**Comment by FreddyFox1** [comment]
Maybe i mistakenly, i saved graphql schema in file, then i load her from file and fetching schema complete for 1 sec. When i try execute any query in banana any way i need wait for 3 mins.

**Comment by alfosua** [comment]
> Maybe i mistakenly, i saved graphql schema in file, then i load her from file and fetching schema complete for 1 sec. When i try execute any query in banana any way i need wait for 3 mins.

Yes, it is happening to me too. Even with a really simple query type, the banana cake pop load time to get the schema takes too much.

**Comment by FreddyFox1** [comment]
😫

**Comment by FreddyFox1** [comment]
Any one can help me ? 😟

**Comment by FreddyFox1** [comment]
I have answer for this. 
When graphql starts, he parsing all XML comments in class where he hasn't a attribute [GraphQLDescription()], like 
`:/// <summary>
 ///......
/// </summary>` this so slow process. To resolve this problem, you need exhange all your summary for the  [GraphQLDescription()] attribute.
