### ISSUE TITLE
The example usage of NoOpStringBuilderPool in CustomNamingConventions in the documentation is misleading

### ISSUE THREAD

**Issue by ekinbarut** [ChilliCream/graphql-platform#5261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The [class](https://github.com/ChilliCream/hotchocolate/blob/ef0015b30aa459270508b7cc1b7d23c75237666f/src/HotChocolate/Core/src/Types/Types/Descriptors/Conventions/DescriptorContext.cs#L270) you've mentioned [here](https://github.com/ChilliCream/hotchocolate/blob/ef0015b30aa459270508b7cc1b7d23c75237666f/website/src/docs/hotchocolate/api-reference/migrate-from-11-to-12.md#custom-naming-conventions) and [here](https://github.com/ChilliCream/hotchocolate/blob/ef0015b30aa459270508b7cc1b7d23c75237666f/website/src/docs/hotchocolate/defining-a-schema/documentation.md#with-a-custom-naming-convention) in the documentation is a private class and not accessible when you're actually consuming the ```HotChocolate.Types.Descriptors``` namespace. 

### Steps to reproduce

1. Import HotChocolate v.12+
2. Use ```HotChocolate.Types.Descriptors``` namespace.
3. Call```new NoOpStringBuilderPool()``` 

### Product

Hot Chocolate

### Version

12.6.0

**Comment by michaelstaib** [comment]
There are actually two classes one is public ... I will remove the private one and then the docs should be alright.

**Comment by michaelstaib** [comment]
1. Remove `HotChocolate.Types.Descriptors.DescriptorContext.NoOpStringBuilderPool`
2. Seal `HotChocolate.Types.Descriptors.NoOpStringBuilderPool`
