### ISSUE TITLE
convert CursorPagingArguments to class

### ISSUE THREAD

**Issue by RichardGrant-93** [ChilliCream/graphql-platform#5267]
### Is your feature request related to a problem?

I love the UsePaging functionality that HotChocolate offers out of the box, what i don't like is the performance behind the implementation. All rows are fetched from the DB then filtered / sorted. This means more data is indexed in your DB than necessary.
HotChocolate offers some cool functionality with Entity framework tying in pagination solving my problem; however,
I am heavily invested into the Dapper ORM using stored procedure patterns.

To get the functionality i need am adding a custom CursorPagingArguments class to my resolver parameters which then passes the paging information to my DataAccessLayer.

### The solution you'd like

Would be nice if this readonly struc was a class instead. as structs cannot be used as resolver params.

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
This is implemented with the new paging abstractions
