### ISSUE TITLE
Allow to add response headers in IHttpResultSerializer

### ISSUE THREAD

**Issue by snifter** [ChilliCream/graphql-platform#5271]
### Is your feature request related to a problem?

In some cases i want to set custom http status and add header to response. IHttpResultSerializer allow to modify response status but unable to add header. At this time a workaround is to inject HttpContextAccessor to IHttpResultSerializer implementation and add header on HttpContext.Response. IMO it is a code smell because method GetStatusCode has side effect. 

### The solution you'd like

Add a method `IReadOnlyDictionary<string, StringValues> GetResponseHeaders(IExecutionResult result)` to `IHttpResultSerializer` and add its result to HttpContext.Response.Headers.
Another solution would be to allow to access HttpContext.Response in IHttpResultSerializer.

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
You can now override the method:

```csharp
    protected virtual void OnWriteResponseHeaders(
        IQueryResult responseStream,
        FormatInfo format,
        IHeaderDictionary headers)
    {
    }
```
