### ISSUE TITLE
Error using sorting with in-memory list

### ISSUE THREAD

**Issue by AlexKubiesa** [ChilliCream/graphql-platform#5304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have a resolver which returns a normal array and uses the sorting middleware. When a client runs a query without sorting, it works fine. When a client uses sorting, an error is thrown: `Unexpected Execution Error | The source 'IQueryable' doesn't implement 'IAsyncEnumerable<MyCustomType>'. Only sources that implement 'IAsyncEnumerable' can be used for Entity Framework asynchronous operations.`

This error appears to come from HC's `ToListMiddleware`:
```csharp
public async ValueTask InvokeAsync(IMiddlewareContext context)
    {
        await _next(context).ConfigureAwait(false);

        context.Result = context.Result switch
        {
            IQueryable<TEntity> queryable =>
                await queryable
                    .ToListAsync(context.RequestAborted)
                    .ConfigureAwait(false),
            _ => context.Result
        };
    }
```

This middleware assumes that all `IQueryable<T>` must implement `IAsyncEnumerable<T>`, which is not true in this case because my resolver is returning a normal array instead of an EF Core DbSet or expression. I need to return a normal array in this case because I am combining the data in our database with data from other services before returning it.

This problem was caused by us switching to registering the DB context in Startup.cs with `RegisterDbContext<ApplicationDbContext>(DbContextKind.Pooled)`, where we previously used `UseDbContext<ApplicationDbContext>` on individual field descriptors.

### Steps to reproduce

1. Make sure your project is using EF Core and HC sorting.
2. Create a resolver which returns an array.
3. Add the sorting middleware.
4. Run a query that uses sorting.

### Product

Hot Chocolate

### Version

12.12.1

**Comment by AlexKubiesa** [comment]
I think the issue is in `ObjectFieldDescriptor.OnCreateDefinition`:
```csharp
protected override void OnCreateDefinition(ObjectFieldDefinition definition)
    {
        MemberInfo? member = definition.ResolverMember ?? definition.Member;

        if (!Definition.AttributesAreApplied && member is not null)
        {
            Context.TypeInspector.ApplyAttributes(Context, this, member);
            Definition.AttributesAreApplied = true;
        }

        base.OnCreateDefinition(definition);

        CompleteArguments(definition);
    }
```

The sorting middleware is applied in the `Context.TypeInspector.ApplyAttributes(Context, this, member);` line, while the UseDbContext with its ToListMiddleware is applied in the `CompleteArguments(definition);` line. If these two middlewares could be applied in the reverse order, this would solve the issue. (But for resolvers that return DbSets or IQueryables that order would presumably be bad because sorting queries would not be propagated to the database).

**Comment by michaelstaib** [comment]
Why do you have the USeDbContext or ToListMiddleware when you are returning a in-memory array? what is the use case?

**Comment by AlexKubiesa** [comment]
I'm using the DB context to get data from our database. However, our entities have additional data that needs to be fetched from other services. So, I call `ToListAsync()` manually on the IQueryable of database objects, populate the extra data, and return the resulting array.

Here is a simplified and obfuscated version of our resolver code:

```csharp
[ExtendObjectType("Query")]
    public class FruitQueries
    {
        [UseSorting]
        public async Task<IEnumerable<OurCompany.API.Fruit>> GetFruits(
            ApplicationDbContext context,
            CancellationToken cancellationToken)
        {
            List<OurCompany.Data.Fruit> dbFruits = await context.Fruits.ToListAsync(cancellationToken);

            ExternalCompany.FruitService fruitService = new();
            // Some data is stored externally in so needs to be merged with our data.
            IEnumerable<Task<OurCompany.API.Fruit>> creationTasks = dbFruits.Select(x => OurCompany.API.Fruit.CreateAsync(x, fruitService, cancellationToken));
            OurCompany.API.Fruit[] fruits = await Task.WhenAll(creationTasks);

            return fruits;
        }
    }
```

Here is a version of the `Fruit.CreateAsync` method:

```csharp
public static async Task<OurCompany.API.Fruit> CreateAsync(
            OurCompany.Data.Fruit dbFruit,
            ExternalCompany.FruitService fruitService,
            CancellationToken cancellationToken)
        {
            string externalFruitId = dbFruit.ExternalId;

            if (string.IsNullOrWhiteSpace(externalFruitId))
                throw new ArgumentOutOfRangeException(nameof(dbFruit));

            ExternalCompany.Fruit externalFruit = await fruitService.GetAsync(
                externalFruitId,
                cancellationToken: cancellationToken);

            return new OurCompany.API.Fruit(dbFruit, externalFruit);
        }
```

**Comment by AlexKubiesa** [comment]
activity

**Comment by michaelstaib** [comment]
I think we should add a check for in-memory collection in the ToList middleware. We have a similar thing actually in sorting. I will put this on the 13 backlog.

**Comment by PascalSenn** [comment]
hi @AlexKubiesa 

I try to reproduce the issue in https://github.com/ChilliCream/graphql-platform/pull/5747 but had no luck. Can you give it a go?

**Comment by michaelstaib** [comment]
We are closing this as we cannot repro it. If you still have this issue create a new issue and attach to it a repro.
