### ISSUE TITLE
Synchronized DbContext is not synchronized in data loaders

### ISSUE THREAD

**Issue by Deathrage** [ChilliCream/graphql-platform#5328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Have a data loader tha uses DbContext:
```csharp
public class EntityByIdDataLoader<TEntity>: BatchDataLoaderWithDbContext<int, TEntity>
    where TEntity : class, IEntity
{
    public EntityByIdDataLoader(CommonDbContext dbContext, IBatchScheduler batchScheduler, DataLoaderOptions? options = null) 
        : base(dbContext, batchScheduler, options)
    {
    }

    protected override async Task<IReadOnlyDictionary<int, TEntity>> LoadBatchAsync(IReadOnlyList<int> keys,
        CommonDbContext dbContext, CancellationToken cancellationToken)
        => await dbContext.Set<TEntity>().Where(e => keys.Contains(e.Id)).ToDictionaryAsync(k => k.Id, k => k, cancellationToken);
}
```

Have a resolver that uses two of these loaders:
```csharp
    [GraphQLType(typeof(UserNoteRelatedEntityUnionType))]
    public async Task<object?> GetRelatedEntityAsync([Parent] UserNote parent,
        [DataLoader] EntityByIdDataLoader<Instrument> instrumentLoader,
        [DataLoader] EntityByIdDataLoader<Instruction> instructionLoader,
        [Service] IMapper mapper,
        CancellationToken token)
        => parent.RelatedEntityType switch
        {
            UserNoteRelatedEntityType.Instrument => await instrumentLoader.LoadAsync(parent.RelatedEntityId!.Value, token),
            UserNoteRelatedEntityType.Instruction => 
                mapper.Map<ViewInstruction>(await instructionLoader.LoadAsync(parent.RelatedEntityId!.Value, token)),
            _ => null,
        };
```

Occasionaly get:
```
A second operation was started on this context instance before a previous operation completed. This is usually caused by different threads concurrently using the same instance of DbContext. For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.
```
on path 
```
[
  "userNotes",
  "nodes",
  2,
  "relatedEntity"
]
```

### Steps to reproduce

1. See above

### Additional Context?

DbContext is registered as synchronized:
```
services.AddGraphQLServer().RegisterDbContext<CommonDbContext>(DbContextKind.Synchronized);
```

I thought I could enforce synchronization by adding DbContext explicitly as a parameter of the resover. However, this leads to endlessly running query.

### Product

Hot Chocolate

### Version

12.9.0

**Comment by Deathrage** [comment]
Changing resolver to this might work as a quick but performance costly fix:
```
    [GraphQLType(typeof(UserNoteRelatedEntityUnionType))]
    public async Task<object?> GetRelatedEntityAsync([Parent] UserNote parent,
        //TODO: https://github.com/ChilliCream/hotchocolate/issues/5328
        //[DataLoader] EntityByIdDataLoader<Instrument> instrumentLoader,
        //[DataLoader] LongEntityByIdDataLoader<Instruction> instructionLoader,
        CommonDbContext dbContext,
        [Service] IMapper mapper,
        CancellationToken token)
        => parent.RelatedEntityType switch
        {
            UserNoteRelatedEntityType.Instrument => await dbContext.Set<Instrument>().SingleAsync(i => i.Id == parent.RelatedEntityId),
            UserNoteRelatedEntityType.Instruction => 
                mapper.Map<ViewInstruction>(await dbContext.Set<Instruction>().SingleAsync(i => i.Id == parent.RelatedEntityId)),
            _ => null,
        };
```

**Comment by tobias-tengler** [comment]
Synchronization only works on a resolver level. We could probably introduce a way to also run DataLoaders sequentially. You are probably better of just creating and disposing a new dbcontext instance in the dataloader method. In essence this https://chillicream.com/docs/hotchocolate/integrations/entity-framework#dataloaders but instead of the factory you create a new service scope and resolve the dbcontext from there. then dispose the scope and return the items.

**Comment by Deathrage** [comment]
Okay, but documentation heavily implies otherwise. In "Working with a pooled DbContext" docu states "You also need to access your DbContext differently. In the following chapters we will take a look at some of the changes you have to make." In conjunction that the next chapter being "DataLoaders" it heavily implies that DbContext should work even with data loaders and the next chapter "DataLoaders" describe how they should be changed in case of pooled DbContext. It should be clearly stated that this is not the case.

However, this does not explain why this makes it endless:
```csharp
[GraphQLType(typeof(UserNoteRelatedEntityUnionType))]
public async Task<object?> GetRelatedEntityAsync([Parent] UserNote parent,
    [DataLoader] EntityByIdDataLoader<Instrument> instrumentLoader,
    [DataLoader] EntityByIdDataLoader<Instruction> instructionLoader,
    [Service] IMapper mapper,
    CancellationToken token)
{
    await _semaphor.Wait();

    object? result = parent.RelatedEntityType switch
    {
        UserNoteRelatedEntityType.Instrument => await instrumentLoader.LoadAsync(parent.RelatedEntityId!.Value, token),
        UserNoteRelatedEntityType.Instruction => 
            mapper.Map<ViewInstruction>(await instructionLoader.LoadAsync(parent.RelatedEntityId!.Value, token)),
        _ => null,
    };

    _semaphor.Release();

    return result;
}

[GraphQLType(typeof(UserNoteRelatedEntityUnionType))]
public async Task<object?> GetRelatedEntityAsync([Parent] UserNote parent,
    [DataLoader] EntityByIdDataLoader<Instrument> instrumentLoader,
    [DataLoader] EntityByIdDataLoader<Instruction> instructionLoader,
    CommonDbContext _,
    [Service] IMapper mapper,
    CancellationToken token)
    => parent.RelatedEntityType switch
        {
            UserNoteRelatedEntityType.Instrument => await instrumentLoader.LoadAsync(parent.RelatedEntityId!.Value, token),
            UserNoteRelatedEntityType.Instruction => 
                mapper.Map<ViewInstruction>(await instructionLoader.LoadAsync(parent.RelatedEntityId!.Value, token)),
            _ => null,
        };
```

I suppose both deadlock as under the hood second case is just the first case (implicitly). But why do they deadlock?

**Comment by michaelstaib** [comment]
Can you point to the chapter?

The short version is .... if you synchronize do not use DataLoader. While there is some sync logic we do (executing the DataLoader one after the other) it in the best case will make your API super slow. 

If you do EF Core and you want a fast API use one of the following:
- Pooling
- Resolver Scoping

if you go for the latter one make sure to scope the context for DataLoader.

**Comment by michaelstaib** [comment]
we do not use a semaphore ... we have an execution plan that marks certain nodes as serial and makes sure that they are executed one after the other.

**Comment by michaelstaib** [comment]
OK ... I see the issue you have. So, you marked the DbContext serial but we do not have an knowledge that the DataLoader need synchronous execution. Mark the resolvers as serial.

```csharp
[Serial]
[GraphQLType(typeof(UserNoteRelatedEntityUnionType))]
public async Task<object?> GetRelatedEntityAsync([Parent] UserNote parent,
    [DataLoader] EntityByIdDataLoader<Instrument> instrumentLoader,
    [DataLoader] EntityByIdDataLoader<Instruction> instructionLoader,
    CommonDbContext _,
    [Service] IMapper mapper,
    CancellationToken token)
    => parent.RelatedEntityType switch
        {
            UserNoteRelatedEntityType.Instrument => await instrumentLoader.LoadAsync(parent.RelatedEntityId!.Value, token),
            UserNoteRelatedEntityType.Instruction => 
                mapper.Map<ViewInstruction>(await instructionLoader.LoadAsync(parent.RelatedEntityId!.Value, token)),
            _ => null,
        };
```

**Comment by michaelstaib** [comment]
bit it should not deadlock... can you create a small repro for us?

**Comment by michaelstaib** [comment]
Why aren't you using pooled? instead of synchronized?

**Comment by Deathrage** [comment]
@michaelstaib The issue in doc I see in https://chillicream.com/docs/hotchocolate/integrations/entity-framework/#working-with-a-pooled-dbcontext the last paragraph implies that if u are using pooled, change data loaders this way, otherwise use let them access DbContext directly. The phrase "a look at some of the changes you have to make" in conjuction with chapter "DataLoaders" implies that you already have a data loader that uses DbContext (directly) and that you have to change it this way to work with pooled DbContext.

**Comment by Deathrage** [comment]
I do not want to use factory as there is a single DbContext that tracks everythin in the current operation and auto-saves it at the end. Auto-save happens after GQL (in ASP NET Core middleware) and thus if any other DbContext materialized the entities it would materialize them as unchaged based on fetched data instead of reusing tracked instances.

**Comment by devgavrilov** [comment]
I faced the same problem yesterday. After several experiments I've managed to reproduce it on a simple case.

Code:
```
public class DataQuery
{
	[GraphQLName("multiple-data")]
	[GraphQLNonNullType]
	public async Task<DataQuery[]> GetMultipleDataAsync()
	{
		return new[]
		{
			new DataQuery(),
			new DataQuery(),
		};
	}
	
	[GraphQLName("data")]
	[GraphQLNonNullType]
	public async Task<int> GetDataAsync(
		IResolverContext resolverContext,
		[Service(ServiceKind.Synchronized)] IServiceScopeFactory serviceScopeFactory)
	{
		return await resolverContext
			.BatchDataLoader<int, int>(fetch: async (ints, _) => ints.ToDictionary(i => i, i => i))
			.LoadAsync(Random.Shared.Next());
	}
}
```
Query:
```
query {
  multiple_data {
    data
  }
}
```

Important things to reproduce the deadlock:
- Resolver must have at least one Synchronized service (or implicitly disabled parallel execution in parameter expression builder / e.t.c.).
- Resolver with DataLoader must be called at least twice.
- DataLoader must be loaded with unique CacheKeys (if we replace `Random.Shared.Next()` with static number, it will work).

Deadlock happens because we call `await ....LoadAsync(...)`. We _stuck_ here until end of the query.
Here is hypothetical situation (in the case above with two data rows):
- DataLoader waits for the 2nd "data" resolver's call completion.
- The 1st "data" resolver's call waits for DataLoader's LoadAsync because of await.
- The 2nd "data" resolver's call waits the 1st "data" resolver's call completion because of Synchronized service.

**Comment by michaelstaib** [comment]
Thank you for providing a repro ... I will have a look at it tomorrow.

**Comment by Shtannikov** [comment]
> Thank you for providing a repro ... I will have a look at it tomorrow.

@michaelstaib do you have any updates?

**Comment by nzbart** [comment]
I'm not using Entity Framework, but would like to leverage SQL Server's snapshot isolation transaction to ensure that all the data loaded from the database is internally consistent. Executing multiple queries concurrently may speed up single request latency and look good on performance benchmarks, but concurrent execution makes it impossible to share the same snapshot isolation transaction throughout a single GraphQL query, potentially causing inconsistent results. Due to this issue, is it currently impossible to do what I want, which is to service all requests with the same connection and transaction? I also thought that I could serialise access to my connection/unit of work using `Serial`, but are data loaders not serialisable at all?

**Comment by michaelstaib** [comment]
@nzbart we have a transaction abstraction that wraps around the whole request ... you can implement this.

**Comment by michaelstaib** [comment]
While we do not synchronize them we now scope them ... so this issue is fixed.
