### ISSUE TITLE
Streamline the developer workflow on the schema reference tab

### ISSUE THREAD

**Issue by Strandedpirate** [ChilliCream/graphql-platform#5332]
### Is your feature request related to a problem?

Any developer looking at the schema reference is going to want inevitably use one or more queries, mutations, objects, etc.. listed there. Rather than eyeballing the information and then having to go back to another tab and re-write, from memory (ugh), the query, mutation, object, whatever, provide a way to streamline this process as much as possible.

### Copy to clipboard

1. Add a button next to each schema object that, when clicked, would copy queries, mutations, objects, etc.. definitions to the clipboard in a format that is advantageous to pasting somewhere else and require minimal effort to modify for the exact desired context.

### New document from queries, mutations, objects, etc..

1. Add a button next to each schema object that, when clicked, would automatically create a new document and paste the query, mutation, object, etc.. which would require minimal effort to modify for a developer's desired context.

### Copy to existing document for queries, mutations, objects, etc..

1. Add a button next to each schema object that, when clicked, would automatically copy queries, mutations, objects, etc.. definitions to a user selectable list of existing documents, in a format that requires minimal effort to modify for the exact desired context.

### Product

Banana Cake Pop

**Comment by Strandedpirate** [comment]
Here is a quick mockup of the workflow. The first icon is the `Copy to clipboard` button. It would show the same sub-menu shown in the mockup that would give options for copying the schema type/object as some form of valid graphql syntax, and the options would be contextual based on the type of schema type/object that is being copied. e.g. for a query have X options, for a mutation have Y options, and so on.

The second button is for the `Copy to document` button. The submenu would give context sensitive options for copying to a new or existing document as some form of valid graphql syntax.  e.g. for a query have X options, for a mutation have Y options, and so on. For the `To existing document as` option, there would need to be some sort of pop-up after the sub-menu option is selected, to allow the user to choose the existing document to copy to.

![schema-reference-button-mockup](https://user-images.githubusercontent.com/1452996/186041118-10a92d54-6fcd-4659-a8c8-4ab31da25904.png)


### Named Query Operation Syntax
```
query HeroNameAndFriends {
  hero {
    name
    friends {
      name
    }
  }
}
```

### Shorthand Query Operation Syntax
```
{
  hero {
    name
    friends {
      name
    }
  }
}
```

### Parameterized Query Operation Syntax
```
query HeroNameAndFriends($episode: Episode) {
  hero(episode: $episode) {
    name
    friends {
      name
    }
  }
}
```

### Fragment Query Operation Syntax
Unknown - maybe too complex?

### Other schema type syntax
Other types of schema types would have their own options shown in the submenu and pre-defined syntax that would be copied.

`Final thought`: 
If this is implemented the feature should adopt the "whole enchilada" approach. e.g. the entire schema of the object should be apart of the copy operation. A developer can more easily remove the unwanted bits, than having to add missing ones.

**Comment by michaelstaib** [comment]
This issue is solved with the new operation builder.
