### ISSUE TITLE
Redis Channels do not get closed when multiple subscriptions are active

### ISSUE THREAD

**Issue by SWojtyla** [ChilliCream/graphql-platform#5336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm having an issue with redis channels not getting closed when using multiple subscriptions. So I have a subscription defined and multiple clients are subscribing on it. Once the subscriptions get closed the channels remain in redis forever(I have to restart the graphql to close them) . Is there something I forgot to configure or any idea what the issue might be ?

### Steps to reproduce

1. Create a subscription using redis
[SubscribeAndResolve]
        public async ValueTask<ISourceStream<IList<Models.Notification>>> LoadTestIncomingNotificationsAsync(
            [Topic] string uniqueId
            , [Service] ITopicEventReceiver receiver
            , [Service] IHttpContextAccessor httpContextAccessor
            )
        {           

            var sourceStream = await receiver.SubscribeAsync<string, IList<Models.Notification>>(uniqueId);
            return sourceStream;
        }
2. Subscribe multiple times to the subscription with multiple ids and close them.
3. The channels do not get disposed in redis 

### Product

Hot Chocolate

### Version

12.12.1

**Comment by fr4nky80** [comment]
Can this issue be causing a memory leak in the process?

I think this is causing the memory to grow gradually in production environments. I don't know if this is related to this topic.

**Comment by michaelstaib** [comment]
Can you recheck with 13.2 .... this should be solved.

**Comment by SWojtyla** [comment]
Thx! Will check ASAP. But first I'll have to migrate from 12 to 13 then.
Will keep you posted.

**Comment by michaelstaib** [comment]
Closing this issue as we fixed the general issue with unsubscribing from topics. @SWojtyla comment if you still find an issue while testing.
