### ISSUE TITLE
BatchingExecutor skips execution middlewares

### ISSUE THREAD

**Issue by Deathrage** [ChilliCream/graphql-platform#5373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Have a server with one middleware.

```cshapr
services
   .AddGraphQLServer()
   .UseRequest(next => ctx => {
      return next(ctx); // BREAKPOINT here
   })
```

Send a batched query, does not break.
Send single query, does break.

### Steps to reproduce

1. Above

### Product

Hot Chocolate

### Version

12.9.0

**Comment by Deathrage** [comment]
This issue causes #5223

**Comment by Deathrage** [comment]
This issue causes #2987

**Comment by Deathrage** [comment]
Analysis:

In [RequestExecutor.cs](https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Core/src/Execution/RequestExecutor.cs) on line 78 the `_requestDelegate` containing middlewares is called.

In [BatchExecutor.Enumerable.cs](https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Core/src/Execution/Batching/BatchExecutor.Enumerable.cs) the `_requestDelegate` is not called.

**Comment by Deathrage** [comment]
Okay, my mistake. Middlewares would be called but execution fails on #5223 execption before middlewares get called (by recursively calling `IRequestExecutor`).  Middlewares should be called BEFORE line 74 in [BatchExecutor.Enumerable.cs](https://github.com/ChilliCream/hotchocolate/blob/main/src/HotChocolate/Core/src/Execution/Batching/BatchExecutor.Enumerable.cs) as otherwise `request.Query` won't be populated.

**Comment by michaelstaib** [comment]
We have reworked the batching executer.
