### ISSUE TITLE
Specified fields order does not preserved for methods

### ISSUE THREAD

**Issue by bohdan-kolomiiets** [ChilliCream/graphql-platform#5387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In annotation-based approach (at least tested with this), object methods are rendered always above properties, even though these methods specified below properties in c# code. And I haven't found a way to influence that (maybe with some attrbite at least).

I was expecting that class memebers order is preserved when they are transformed into object fields and rendered in graphql syntax.

I think that by specifing fields in certain order, engineer put some sense in it, making focus or putting attention on some fields more and on others less. 
Otherwise, for example in my real case, object schema results to have `id`, `name` fields somewhere in the middle which are logically expeted to be somewhere at the beginning because these fields may visually help to distinct objects by humans. 

### Steps to reproduce

<b>Code</b>

```
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddGraphQLServer().AddQueryType<Query>();

var app = builder.Build();
app.MapGraphQL();
app.Run();

public class Query
{
    public SomeEntity GetEntity() => new SomeEntity();
}

public class SomeEntity
{
    [GraphQLType(typeof(IdType))]
    public string Id { get; set; }
    public string Ccc { get; set; }
    public string Bbb { get; set; }
    public string Aaa { get; set; }
    public string Z() => "123";
    public string A() => "123";
}
```

<b>Actual object schema</b>

```
... 

type SomeEntity {
  z: String!
  a: String!
  id: ID
  ccc: String!
  bbb: String!
  aaa: String!
}

...
```

<b>Expected object schema</b>

```
...

type SomeEntity {
  id: ID
  ccc: String!
  bbb: String!
  aaa: String!
  z: String!
  a: String!
}

...
```

PS: Applying `GraphQLName` attribute does influence generated fields order.

### Product

Hot Chocolate

### Version

12.13.2

**Comment by tobias-tengler** [comment]
We can't order them the way you wrote them, since the underlying reflection API does not guarantee an order: https://docs.microsoft.com/en-us/dotnet/api/system.type.getmethods?view=net-6.0
We can order alphabetically, via `ModifyOptions(options => { options.SortFieldsByName = true; })` (since this is just a sort on all the methods we got), but we can't guarantee a field order without an attribute or another indicator of order (like the fluent API).
We could introduce something like an Order attribute though, but I'm not sure...

**Comment by bohdan-kolomiiets** [comment]
Yes, I think some sort of `Order` attribute could be a solution.

**Comment by michaelstaib** [comment]
We have alphabetic order ... the rest we cannot guarantee. I find working with order attributes not really a solution and would end up in chaos. If you want order ... just opt into alphabetic order.
