### ISSUE TITLE
Adding JSON Scalar

### ISSUE THREAD

**Issue by antyrama** [ChilliCream/graphql-platform#5459]
### Is your feature request related to a problem?

Because of lack a handling JSON scalar type StrawberryShake fails to 'deserialize' whole response when JSON type have been used there. 

### The solution you'd like

I was thinking about few solutions when it comes to parse JSON scalar:
* keep it as `JsonElement` but then we tightening it up particular serialization solution, in that case to `System.Text.Json` - bad idea
* convert it to `ExpandoObject`
* convert it just to string, then you can do with it whatever you want - best idea (IMHO)

### Product

Strawberry Shake

**Comment by glen-84** [comment]
@antyrama This sounds more like a bug than an enhancement. Can you add a reproduction?

**Comment by glen-84** [comment]
Closing, for lack of a minimal reproduction.
