### ISSUE TITLE
Offer: add automated spell-check & markdown linting to docs via GitHub Actions

### ISSUE THREAD

**Issue by SeanKilleen** [ChilliCream/graphql-platform#5460]
### Is your feature request related to a problem?

It is related to an ask in the docs that mentions folks can help by spotting typos etc.

### The solution you'd like

I've used this technique for a few repos, including the NUnit dcos, the Marten docs, and my blog. 

Essentially:

* Use GitHub actions for spellcheck & linting the docs.
* In the same PR that introduces the action, remediate the spelling & linting issues that occur. 

Then at the end, you're left with material improvements + the ability to spot issues later.

Let me know if you're up for this, and I'd be happy to adapt what I've already done to benefit your docs too.

### Product

Hot Chocolate

## Progress

* [x] Spell check: #5461
* [x] Enable Markdown linting with all rules disabled #6842
* [ ] Turn on rules and remediate in small batches
  * [ ] MD001
  * [x] MD009 #6843
  * [x] MD012 #6843
  * [ ] MD013
  * [x] MD018 #6843
  * [x] MD022 #6843
  * [ ] MD024
  * [ ] MD025
  * [ ] MD026
  * [ ] MD028
  * [ ] MD029
  * [x] MD031 #6843
  * [x] MD032 #6843
  * [ ] MD033 
  * [x] MD034 #6843
  * [ ] MD036
  * [ ] MD037
  * [ ] MD040
  * [ ] MD041
  * [ ] MD045
  * [ ] MD053
- [ ] Only run Markdown lint when changes are detected. (Last step)

**Comment by tobias-tengler** [comment]
Sounds great! Please feel free to go for it :)

**Comment by michaelstaib** [comment]
Can this be closed?

**Comment by SeanKilleen** [comment]
@michaelstaib that depends. Spell-checking is the only thing that's been done. Was going to consider adding markdown-lint and then fixing all the markdown issues as well, or at least writing it up so that somebody could. If you're less interested in that, that's ok; feel free to close it. 👍

**Comment by michaelstaib** [comment]
Its good ... feel free to go ahead :) was just keeping track if it was completed with your PR. Your contributions are welcome and we appreciate the work you have already done!

**Comment by glen-84** [comment]
@SeanKilleen Are you likely to proceed with this, or shall we close it? 🙂

**Comment by SeanKilleen** [comment]
@glen-84 thanks for the ping! I'll see if I can get into it soon.

**Comment by SeanKilleen** [comment]
@glen-84 I just kicked off #6842 and updated the remaining work here. Feel free to approve that CI job so that it'll run and we can check it.
