### ISSUE TITLE
Bearer Token Authentication not working in Azure Function Isolated Process

### ISSUE THREAD

**Issue by Tech4ConsultingDev** [ChilliCream/graphql-platform#5511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Unable to get HotChocolate authorization working when running as an Isolated Process Azure Function, query always receives a "The current user is not authorized to access this resource." response.

In the example shown here I have registered an API via Azure AD and have confirmed that authentication works correctly using HotChocolate 12.15.0 running as a standard .NET 6 Web API.  

### Steps to reproduce

1. Using the Azure Function Isolated template 'graphql-azf-ip' in 13.0.0-preview.70, add authorization and jwt configuration to program.cs:

```
using Microsoft.Extensions.Hosting;
using Microsoft.AspNetCore.Authentication.JwtBearer;

var host = new HostBuilder()
    .ConfigureFunctionsWorkerDefaults()
    .AddGraphQLFunction(b =>
    {
        b.AddAuthorization();
        b.AddQueryType<Query>();
    })
    .ConfigureServices( s =>
    {
        s.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer(options =>
            {
                var AzureADTenantId = "EXAMPLE";
                var AzureADClientId = "EXAMPLE";
                options.Authority = $"https://login.microsoftonline.com/{AzureADTenantId}/";
                options.Audience = $"api://{AzureADClientId}";
            });
    }
    )
    .Build();

host.Run();
```

2. Decorate Person Query with [Authorize] attribute:

```
using HotChocolate.AspNetCore.Authorization;

namespace AzureFunctions;

public class Query
{
    [Authorize]
    public Person GetPerson() => new Person("Luke Skywalker");
}

public class Person
{
    public Person(string name)
    {
        Name = name;
    }

    public string Name { get; }
}
```

3. In Banana Cake Pop, configure Bearer Authorization with valid token and run following query:

```
{
  person {
    name
  }
}
```

### Relevant log output

```shell
Result:

{
  "errors": [
    {
      "message": "The current user is not authorized to access this resource.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "person"
      ],
      "extensions": {
        "code": "AUTH_NOT_AUTHENTICATED"
      }
    }
  ]
}
```

### Product

Hot Chocolate

### Version

13.0.0-preview.70

**Comment by jhueppauff** [comment]
Did you solve your problem? 
Having some documentation around Azure Functions and how to implement authentication would be great.

**Comment by michaelstaib** [comment]
We think that running in AzureFuction is not a good idea as it has to many limitations. A better alternative here are Azure Container Apps which allows you to run full Hot Chocolate but still have the same scaling and pricing benefits as with AzureFunctions.

**Comment by jhueppauff** [comment]
Sad to hear. Especially with isolated I think many of the previous limitations do not apply anymore as they were used with the in-process model.
 
While container apps provide similar scalability and have pricing benefits in comparison with App Service they are still more expensive than a Function.
Also additionally you would need to maintain more infrastructure (like container updates, some additional networking options, etc) which results in more operational workload.

**Comment by michaelstaib** [comment]
> Sad to hear. Especially with isolated I think many of the previous limitations do not apply anymore as they were used with the in-process model.

There are now more limitations as the isolated functions proxy the result through which lead to streams capabilities of GraphQL not working.

This also leads to issues with BCP... 

But there are so much more issues like a custom service container that does not behave like the standard service container and many, many so many more things.

Also from the operational side its a nightmare.

In my experience the lambdas from AWS are more streamlined and do not impose these limitations. The moment Microsoft releases functions I hoped they would go more towards the AWS model. But to be honest ... Container Apps are right there from how it should work. The abstraction of a container is the better one, especially when dealing with streams and long running connections.

**Comment by michaelstaib** [comment]
Also this issue ... why does it not just work? Its standard ASP.NET core functionality on which HotChocolate builds.

**Comment by PanacheSoftwareDev** [comment]
I've spent quite a lot of time building microservices using Azure Functions and found them to be a really good option for a lot of scenarios.

But having recently begun building a hotchocolate project using container apps and Aspire to orchestrate fusion and my subgraphs I'm finding the more functionally rich environment and detailed configuration and logging tools to have really improved the development and deployment process.

If Azure functions had been included in Aspire it's possible I would have gone down that route, but while it's a shame that feature parity for hotchocolate on isolated functions likely won't be possible, I definitely understand why the team made that decision.

**Comment by michaelstaib** [comment]
This is the point, why did they not just take standard ASP.NET core and just added in binding functionality and you would have an awesome experience. Also Aspire is a major factor, it combines so nicely with container apps its a much better experience.

**Comment by michaelstaib** [comment]
> I've spent quite a lot of time building microservices using Azure Functions and found them to be a really good option for a lot of scenarios.

There are scenarios where they are a good fit ... like async message processing. But I find them really sub par for everything that has to do with web APIs.
