### ISSUE TITLE
Authorize does not work with NodeResolver

### ISSUE THREAD

**Issue by samisq** [ChilliCream/graphql-platform#5527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

It seems the authorization logic doesn't run on node resolvers, even though it runs correctly on field resolvers.
I expected the authorization logic to be consistently applied on both  node and field resolvers. 

### Steps to reproduce

Create a simple GraphQL server with the following code:

Query.cs
```
public class Book
{
    public int Id { get; set; }
    public string Title { get; set; }
}

public class Query
{
    [NodeResolver] // <-- Mark as a node resolver 
    [HotChocolate.AspNetCore.Authorization.Authorize] // <-- require authorization
    public Book GetBook(int id) => new() {Id = 1, Title = "C# in depth."};
}
```

Program.cs
```
var builder = WebApplication.CreateBuilder(args);
builder.Services
    .AddAuthorization()
    .AddGraphQLServer()
    .AddAuthorization()
    .AddQueryType<Query>()
    .AddGlobalObjectIdentification();
var app = builder.Build();
app.MapGraphQL();
app.Run();
```

In Banana Cake Pop, run the following queries:

```
query GetBook{
  book(id: "Qm9vawppMQ==") {
    id
    title
  }
}
```
Result: As expected, the query above will be blocked with `AUTH_NOT_AUTHENTICATED` error.

```
query GetBookNode{
  node(id: "Qm9vawppMQ==") {
    id
  }
}
```
Result: This query will execute and return data. I would have expected the same authorize attribute to be applied to the node resolver, and the request to be blocked.

### Product

Hot Chocolate

### Version

13.0.0-preview.75

**Comment by michaelstaib** [comment]
This is now fixed.
