### ISSUE TITLE
HeaderPropagation fails with InitializeOnStartup

### ISSUE THREAD

**Issue by walexnelson** [ChilliCream/graphql-platform#5547]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm stitching remote schemas together and need to propagate headers, like `Authorization` to the upstream services. After adding HeaderPropagation the project failed to start in debug, throwing an InvalidOperationException with the message:

```
"The HeaderPropagationValues.Headers property has not been initialized. Register the header propagation middleware by adding 'app.UseHeaderPropagation()' in the 'Configure(...)' method. Header propagation can only be used within the context of an HTTP request."
```

I'm pretty sure I've narrowed it down to if `.InitializeOnStartup()` is used or not. We're considering transition our existing schema stitching solution to Hotchocolate and have a few pretty large schemas sitting behind this gateway. We'd love to take advantage of the more performant startup with `InitializeOnStartup` if possible.

Here's a very basic repro:

```cs
// Program.cs

var builder = WebApplication.CreateBuilder(args);

builder.Services
    .AddHttpClient("example", options => options.BaseAddress = new Uri("http://localhost:3002/graphql"))
    .AddHeaderPropagation();

builder.Services
    .AddGraphQLServer()
    // the project fails to start in debug mode with this option set. Comment this
    // out and things start up and headers are propagated without issue
    .InitializeOnStartup()
    .AddRemoteSchema("example");

builder.Services.AddHeaderPropagation(options =>
{
    options.Headers.Add("X-TraceId");
    options.Headers.Add("Authorization");
});

var app = builder.Build();

app.MapGraphQL();
app.UseHeaderPropagation();

app.Run();
```

Here are a few links to similar issues from Slack and StackOverflow. I couldn't find anything that had been created here though.

- [Slack Aug 16](https://hotchocolategraphql.slack.com/archives/CN3EZ03U1/p1660677839805749)
- [StackOverflow](https://stackoverflow.com/questions/70301368/useheaderpropagation-not-recognized-during-debug-run)
- [Slack Oct 6th](https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1665065487977969?thread_ts=1665057762.442769&cid=CD9TNKT8T)

### Steps to reproduce

Versions:
- HotChocolate.AspNetCore 12.15.2
- HotChocolate.Stitching 12.15.2
- Microsoft.AspNetCore.HeaderPropagation 7.0.0

1. follow the guides to create a [basic graphql server](https://chillicream.com/docs/hotchocolate/v12/get-started) with [schema stitching](https://chillicream.com/docs/hotchocolate/v12/distributed-schema/schema-stitching).
2. add HeaderPropagation
3. add [InitializeOnStartup](https://chillicream.com/docs/hotchocolate/v12/performance#startup-performance)

### Relevant log output

```shell
"The HeaderPropagationValues.Headers property has not been initialized. Register the header propagation middleware by adding 'app.UseHeaderPropagation()' in the 'Configure(...)' method. Header propagation can only be used within the context of an HTTP request."
```
```


### Additional Context?

_No response_

### Product

Hot Chocolate

### Version

12.15.2

**Comment by michaelstaib** [comment]
Thank you for your analysis. I will have a look at this... The InitializeOnStartup has not been reworked for a long time... I think we could actually make it better now :)

**Comment by glen-84** [comment]
Stitching is deprecated in favour of `HotChocolate.Fusion`. We are no longer offering any fixes or updates for stitching. With version 14 we have removed the code and packages for stitching.
