### ISSUE TITLE
MapGraphQL with dynamic schema name.

### ISSUE THREAD

**Issue by JelleHissink** [ChilliCream/graphql-platform#5548]
### Is your feature request related to a problem?

I have a multi-tenant application, where each tenant is able to define attributes. I'd like to be able to define a schema per tenant. However I don't know the tenants up front and the Middleware caches output and reuses Schema's based on the SchemaName.

```app.MapGraphQL()``` currently only accepts a string, sets it in the ```httpContext.Items``` but all middleware seems to use the constant provided to the middleware.

### The solution you'd like

I'd like to be able to dynamically provide a schema name to the middleware. 

If we would be able to pass a labmda to determine the schema name based on the ```HttpContext``` all schema caching and optimizations would work. eg:
```app.MapGraphQL(httpContext => GetSchemaName(httpContext))```

When the model of a tenant is changed it is easy to regenerate the schema using ```IRequestExecutorResolver```.

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
While it sounds easy this is an epic with many things to consider to get it implemented that it performs well. We will consider something in this area for the version 14 cycle.

**Comment by michaelstaib** [comment]
We have no plans to implement this for now.
