### ISSUE TITLE
When requesting a compressed response, SBS code fails

### ISSUE THREAD

**Issue by GeneralSan** [ChilliCream/graphql-platform#5557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When requesting a compressed response from the graphql server with SBS, the execution fails.

### Steps to reproduce

1. In the startup configuration, we add a SBS client, and add the accept encoding as follows:

`
services
  .AddOurGraphQlClient()
  .ConfigureHttpClient((_, client) =>
    {
      // ...
      client.DefaultRequestHeaders.AcceptEncoding.ParseAdd("gzip,br");
    }
`

2. Execute a request

### Relevant log output

```shell
at StrawberryShake.Response`1..ctor(TBody body, Exception exception)
   at StrawberryShake.Transport.Http.HttpConnection.<ExecuteAsync>d__3.MoveNext()
   at StrawberryShake.Transport.Http.HttpConnection.<ExecuteAsync>d__3.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at StrawberryShake.OperationExecutor`2.<ExecuteAsync>d__5.MoveNext()
   at StrawberryShake.OperationExecutor`2.<ExecuteAsync>d__5.MoveNext()
```

### Additional Context?

Adding the line 
client.DefaultRequestHeaders.AcceptEncoding.ParseAdd("gzip,br");
to the configuration causes the exception.  Removing it makes it work again.

### Product

Strawberry Shake

### Version

12.15.2

**Comment by glen-84** [comment]
You need to configure automatic decompression:

```cs
.ConfigureHttpClient(
    httpClient =>
    {
        httpClient.BaseAddress = new Uri("https://workshop.chillicream.com/graphql");
        httpClient.DefaultRequestHeaders.AcceptEncoding.ParseAdd("gzip,br");
    },
    httpClientBuilder =>
    {
        httpClientBuilder.ConfigurePrimaryHttpMessageHandler(
            () => new HttpClientHandler()
            {
                AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Brotli
            });
    });
```
