### ISSUE TITLE
Share authorization settings across tabs

### ISSUE THREAD

**Issue by dcorb** [ChilliCream/graphql-platform#5560]
### Is your feature request related to a problem?

Our authorization setup invalidates our Bearer token quickly, and it's tiring to update it in EVERY tab I have opened in Banana Pop.

### The solution you'd like

It would be nice to have a shared configuration, like Apollo Studio (that can be overridden in each tab, if needed)

![image](https://user-images.githubusercontent.com/881333/203662418-d6166ec7-435f-4bc4-a7b1-73723e76e837.png)

### Product

Banana Cake Pop

**Comment by michaelstaib** [comment]
This is coming and we are already testing it internally.

**Comment by dcorb** [comment]
Great!, I downloaded the "Insider" app, so I'm happy to test it when ready

**Comment by rstaib** [comment]
This is solved with APIs and Environments.
