### ISSUE TITLE
Execute SingleOrDefault query on database

### ISSUE THREAD

**Issue by xmasctf** [ChilliCream/graphql-platform#5566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hi, 

I'm trying to optimize my _SingleOrDefault()_ query to the database, but can not get desired result.

I created that GraphQL query, which is giving me correct result, besides that _Projection_ is working well too, so only columns provided are also returned. What bother me is when I look at the generated SQL query, it looks like all the items that satisfy _.Where()_ condition are loaded into memory, and then _SingleOrDefault()_ is executed.

My C# code:

```csharp
[UseDbContext(typeof(AccountDbContext))]
[UseSingleOrDefault]
[UseProjection]
public IQueryable<AccountType> GetById(
    int id,
    [ScopedService] AccountDbContext context)
{
    return context.Accounts
        .Where(x => x.Id == id)
        .Select(x => new AccountType
        {
            Id = x.Id,
            Name = x.Name,
            Country = x.Country,
            Email = x.Email
        });
}
```

Generated SQL:
```sql
SELECT [a].[Id], [a].[Name], [a].[Country], [a].[Email]
      FROM [Accounts] AS [a]
      WHERE [a].[Id] = @__id_0
```

If I try with another code, then _SingleOrDefault()_ is performed on database, but the thing is that _Projection_ stops working. I am aware that _Projections_ are working only on _IQueryable_, and that is the reason why it returns all of the columns from DB.

Antoher C# example:
```csharp
[UseDbContext(typeof(AccountDbContext))]
[UseProjection]
public AccountType GetById(
    int id,
    [ScopedService] AccountDbContext context)
{
    var x = context.Accounts
       .SingleOrDefault(x => x.Id == id);

    return new AccountType
    {
        Id = x.Id,
        Name = x.Name,
        Country = x.Country,
        Email = x.Email
    };
}
```

And generated SQL statement:
```sql
SELECT TOP(2) [a].[Id], [a].[Country], [a].[CreatedAt], [a].[Email], [a].[LastChangedAt], [a].[Name]
      FROM [Accounts] AS [a]
      WHERE [a].[Id] = @__id_0
```

As you can see this is whole different query performed on database level, but in this case _Projection_ stops working. If I instead of searching by _int id_ use _[UseFiltering]_ attribute the things are still working the same way as in 1st case.

Is there something I am missing out, am I interpreting SQL statements in a wrong way, or is the query I am trying to achieve impossible using HotChocolate?

Thank you for help.

Am I missing something, o

### Steps to reproduce

I provided all the source code in descrpiton of bug.

### Product

Hot Chocolate

### Version

12

**Comment by michaelstaib** [comment]
The code you provided looks good ... not sure whats wrong. Can you create a little repro and attach it to the issue?

**Comment by xmasctf** [comment]
> The code you provided looks good ... not sure whats wrong. Can you create a little repro and attach it to the issue?

@michaelstaib [here ](https://github.com/xmasctf/GraphQLPoC)I prepared small repro for you, this time using SQL Lite instead of Azure SQL. Migrations and DB seeding should be executed on startup.

These are all possible queries to execute on BananaCakePop.

```graphql
query getAll {
  all {
    id
    name
  }
}

query getById {
  byId(id: 1) {
    id
    name
  }
}

query getByIdX {
  byIdX(id: 1) {
    id
    name
  }
}
```

If you check _getById_ query, you can see, that the generated SQL statement is:
``` sql
SELECT "a"."Id", "a"."Name"
      FROM "Accounts" AS "a"
      WHERE "a"."Id" = @__id_0
```

And if you check _getByIdX_, you will see that the generated SQL looks like:
```sql
 SELECT "a"."Id", "a"."Country", "a"."CreatedAt", "a"."Email", "a"."LastChangedAt", "a"."Name"
      FROM "Accounts" AS "a"
      WHERE "a"."Id" = @__id_0
      LIMIT 2
```

As I said in previous post, for me it looks like 1st query loads all the items that satisfy condition to memory, and then performs _SingleOrDefault_ on data that are already in memory. In 2nd case, there is different query, where _SingleOrDefault_ is performed on DB layer, but projection isn't working.

I may be wrong, or maybe I don't understand how each of those SQL statements wrong, so that's why I am asking for help.
