### ISSUE TITLE
`UseProjection` does not work with field expressions

### ISSUE THREAD

**Issue by aristotelos** [ChilliCream/graphql-platform#5584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When using `UseProjection` together with field expressions, there does not seem to be any way to return those fields. The fields mapped to field expressions will always return `null`.

This means that we can't use projection together with field expressions, it seems. The effect is that the GraphQL schema needs to very closely resemble the entity model if we want to bind to EF Core with projections. This makes our GraphQL schema to tightly coupled - we want to be able to evolve the entity model without having to change the GraphQL schema.

### Steps to reproduce

Example code:

```
public class ListItemType : ObjectType<ListItem>
    { 
        protected override void Configure(IObjectTypeDescriptor<ListItem> descriptor)
        {
            descriptor.Name("listItem");
            descriptor.BindFieldsExplicitly();
            descriptor.Field(t => t.Priority == null ? null : t.Priority.SortIndex)
                .Type<IntType>()
                .Name("prioritySortIndex");
        }
   }
```

This does not work when `UseProjection` is used on a list of those `ListItemType` objects:

```
public class MyQueryType : ObjectType<MyQuery>
    {
        protected override void Configure(IObjectTypeDescriptor<MyQuery> descriptor)
        {
            descriptor.Field(f => f.GetListItems(default))
               .Type<ListType<NonNullType<ListItemType>>>()
               .UseProjection();
        }
    }
```

Even though we use Include in Entity Framework:

```
public IQueryable<ListItem> GetAllListItems()
        {
            return _context.Set<ListItem>()
                .Include(y => y.Priority);
        }
```

In this case, `prioritySortIndex` always returns `null`. Is there any way to return the `prioritySortIndex` without using a nested type?

### Additional Context?

See also [this thread on Slack](https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1663159516241989).

### Product

Hot Chocolate

### Version

13.0.0-preview.56

**Comment by michaelstaib** [comment]
This is a known limitation. We at the moment do are not planing to implement this.
