### ISSUE TITLE
Don't set all fields in InputObject if those not in Request

### ISSUE THREAD

**Issue by nesherhh** [ChilliCream/graphql-platform#5608]
### Is your feature request related to a problem?

HC sets all fields in InputObject even those not in request #5523.
We have around 100 input objects with about 10-15 fields. All of them inherit from a single object that tracks if property was set during deserialization. We are migrating from graphql-dotnet to HotChocolate and would like to reuse our current logic. Also those input objects are in Application layer and HotChocolate is referenced only in Infrastructure layer.

### The solution you'd like

Make it configurable how HC handles fields not in Request.
1. Current behavior. Set all fields even if those not in Request. Use Optional to distinguish between NULL and unspecified.
2. Set only specified fields (those in Request).

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
There is lots complexity to this issue as we take into account if we for instance have input objects that are immutable and only have a constructors. There are also mixed cases where objects have some things in the constructor and some set through properties. At the moment I think this will not take priority as I have not a good Idea on enabling this without degrading aspects of this for other users.

**Comment by michaelstaib** [comment]
We have decided to not implement this.
