### ISSUE TITLE
Support System.ComponentModel.DataAnnotations for validation

### ISSUE THREAD

**Issue by nordfjord** [ChilliCream/graphql-platform#5626]
### Is your feature request related to a problem?

If I create a type like so

```fsharp
type LoginInput =
  { [<Required>]
    username: string
    [<Required; MinLength(2, ErrorMessage = "Password must contain two characters")>]
    password: string}
```

HotChocolate correctly picks up that the strings are not null, but it does not validate.

### The solution you'd like

I would like HotChocolate to automatically validate classes annotated with validation annotations.

At the moment I'm running this code in all mutations.

```fsharp
Validator.ValidateObject(input, new ValidationContext(input), true)
```

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
We support it partially ... Required for instance is supported and will translate into NonNull.

If we want to do something like this we need to have it as an explicit opt-in. Since there are community packages that provide support for other validation solutions like FluentValidation for instance.

**Comment by michaelstaib** [comment]
Ideally we would use a type interceptor and inspect things at startup and only add a middleware where arguments or objects are annotated.

**Comment by michaelstaib** [comment]
Closing this one as we not gonna invest into this ... there are a ton of community projects out there for exactly this thing.
