### ISSUE TITLE
Latest Entity Framework Core Tools database first scaffolded DB Contexts breaks collection projections

### ISSUE THREAD

**Issue by talynone** [ChilliCream/graphql-platform#5640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When I scaffolded a db context/models from a database using the latest version EF Core Tools (7.0.1)  collections projections stopped working, (returned null). 

### Steps to reproduce

I upgraded to the latest (7.0.1) EF Core Tools using the following command:
`dotnet tool update --global dotnet-ef`

I then scaffolded a context with models from the database using a command similar to:
`dotnet ef dbcontext scaffold "Data Source=localsqldb;Initial Catalog=TestDB;Encrypt=False;Persist Security Info=True;user id=myuserid;password=mypassword" Microsoft.EntityFrameworkCore.SqlServer `

The main difference is in an earlier version of Entity Framework Core scaffolded collections in models are represented as an ICollection property with a get/set, like this:
`public virtual ICollection<Pipeline> Pipelines { get; set; }`

The new version of Entity Framework Core scaffolds collections as an ICollection property with only a getter:
`public virtual ICollection<Pipeline> Pipelines { get; } = new List<Pipeline>();`

As a work around changing the property so it has a setter fixes the issue:
`public virtual ICollection<Pipeline> Pipelines { get; set;} = new List<Pipeline>();`

### Product

Hot Chocolate

### Version

12.15.2

**Comment by glen-84** [comment]
@talynone I believe that the [scaffolding change](https://github.com/dotnet/efcore/issues/30286) was reverted in EF Core 7.0.5. Can we close this issue?
