### ISSUE TITLE
EF Core TPC abstract classes unable to query implementations

### ISSUE THREAD

**Issue by PHILLIPS71** [ChilliCream/graphql-platform#5643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've been attempting to get the [table-per-concrete-type](https://devblogs.microsoft.com/dotnet/announcing-ef7-preview5/) feature that was introduced in EF Core 7.0 to work with unions in Hot Chocolate and have no luck. Is this something that is supported via HotChocolate out of the box or do I need to supply additional configuration to get this to work with abstract classes?

I've got a basic schema that has a abstract type of FileSystemNode and then 2 descendants (FileSystemDirectory & FileSystemFile), I want to be able to query FileSystemNode and use unions to extract the additional information in the descendants, although none of the union types are available, only those members within FileSystemNode. I've watched the video posted to YouTube [How to use GraphQL input unions with Hot Chocolate?](https://www.youtube.com/watch?v=tztXm15grU0&ab_channel=ChilliCream) and the setup is pretty much the same with the exception I'm using an abstract class as required by TPC instead of an interface.

### Steps to reproduce

Here is my current setup as it stands as I assumed that the decedents would be picked up automatically without a additional configuration, if I am missing something please let me know :slightly_smiling_face:!

Note: using projection in this query causes the now closed issue outlined here to occur https://github.com/ChilliCream/hotchocolate/issues/1658 unsure if this should be reopped or if I'm doing something incorrect?

```C#
[ExtendObjectType(OperationTypeNames.Query)]
public class FindManyFileSystemNodes
{
    [UsePaging]
    // [UseProjection] https://github.com/ChilliCream/hotchocolate/issues/1658 
    [UseFiltering]
    [UseSorting]
    public IQueryable<FileSystemNode> FileSystemNodes([ScopedService] ApplicationDbContext database)
    {
        return database.FileSystemNodes;
    }
}

public abstract class FileSystemNode : ITimestampableEntity
{
    ...
}

public class FileSystemFile : FileSystemNode
{
    ...
}

public class FileSystemDirectory : FileSystemNode
{
    ...
}
```

### Product

Hot Chocolate

### Version

13.0.0-preview.90

**Comment by PascalSenn** [comment]
Do you mark the type as a union or interface ?

**Comment by PHILLIPS71** [comment]
I've attempted to mark the FileSystemNode entity as a UnionType but this creates the following error `The name 'FileSystemNode' was already registered by another type.`. I'm also using `HotChocolate.Types.Analyzers` unsure if that's registering something it shouldn't, but it looks fine at a glance.

I've had no issue in the past when using interface types, and in Michael's video explaining HotChocolate's union types interfaces are used there too. I'm lead to believe it's due to an abstract class used instead but this is required for EF's TPC feature.

I've marked the union type as below as well as the descendants as follows, the query itself remains the same as referenced in the original issue description.
```C#
public class FileSystemNodeType : UnionType<FileSystemNode>
{
    protected override void Configure(IUnionTypeDescriptor descriptor)
    {
        descriptor.Type<FileSystemFileType>();
        descriptor.Type<FileSystemDirectoryType>();
    }
}

public class FileSystemDirectoryType : ObjectType<FileSystemDirectory>
{
    protected override void Configure(IObjectTypeDescriptor<FileSystemDirectory> descriptor)
    {
        descriptor
            .Field(p => p.Nodes)
            .UsePaging()
            .UseFiltering()
            .UseSorting();
    }
}

public class FileSystemFileType : ObjectType<FileSystemFile>
{
    protected override void Configure(IObjectTypeDescriptor<FileSystemFile> descriptor)
    {
    }
}
```

**Comment by PHILLIPS71** [comment]
@PascalSenn pinning the type yields the following exception;

```
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. For more details look at the `Errors` property.

1. Unable to infer the element type from the current resolver. This often happens if the resolver is not an iterable type like IEnumerable, IQueryable, IList etc. Ensure that you either explicitly specify the element type or that the return type of your resolver is an iterable type.
 (HotChocolate.Types.ObjectTypeExtension<Giantnodes.Service.Dashboard.Api.Resolvers.Explorer.FindManyFileSystemNodes>)

   at HotChocolate.Configuration.TypeInitializer.DiscoverTypes()
   at HotChocolate.Configuration.TypeInitializer.Initialize()
   at HotChocolate.SchemaBuilder.Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
   at HotChocolate.SchemaBuilder.Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
   at HotChocolate.SchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.SchemaBuilder.HotChocolate.ISchemaBuilder.Create(IDescriptorContext context)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaAsync(String schemaName, RequestExecutorSetup options, RequestExecutorOptions executorOptions, IServiceProvider serviceProvider, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.CreateSchemaServicesAsync(String schemaName, RequestExecutorSetup options, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
   at HotChocolate.Execution.RequestExecutorProxy.GetRequestExecutorAsync(CancellationToken cancellationToken)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context)
   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.EndpointRouteBuilderExtensions.<>c__DisplayClass20_0.<<UseCancellation>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Watch.BrowserRefresh.BrowserRefreshMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by PascalSenn** [comment]
@PHILLIPS71  ok, can you provide a simple repro of the bug?

**Comment by PHILLIPS71** [comment]
@PascalSenn I've created a repo here https://github.com/PHILLIPS71/hc-5643, let me know if there is any other information required 🙂

**Comment by PHILLIPS71** [comment]
@PascalSenn is there any plans to resolve the issue in any upcoming release? Or are you able to point me in the right direction on where to start looking if I were to attempt to resolve the issue myself, or at least provide more details in this issue?

**Comment by JordanGistLens** [comment]
I've done some more digging and it looks as though in v13.4.0 it's partially working, if you pin the GraphQL type it's able to resolve the query and return some data, however, if you don't pin the type in the query you will get a `HotChocolate.SchemaException`.

```cs
[GraphQLType<ListType<FileSystemNodeType>>]
[UsePaging]
[UseProjection]
[UseFiltering]
[UseSorting]
public IQueryable<FileSystemNode> FileSystemEntries([Service] ApplicationDbContext database)
{
    return database.FileSystemNodes;
}
```

It's also worth noting that while the above does work if you pin the type, it does not handle [owned entity types](https://learn.microsoft.com/en-us/ef/core/modeling/owned-entities) and always produces a null value for those objects, it looks as though its not selecting those values when constructing the sql query.

It doesn't work if the union type is part of a nested collection, for example if I had a library that has a collection of FileSystemNode objects, the collection that is returned is always an empty array. I've attempted to pin the type on the nested collection but it's produces the same result, it also looks as though the nodes are not being selected via the sql query.

```cs
public class LibraryObjectType : ObjectType<Library>
{
    protected override void Configure(IObjectTypeDescriptor<Library> descriptor)
    {
        descriptor
            .Field(p => p.Nodes)
            .Type<ListType<FileSystemNode>>()
            .UseProjection()
            .UseFiltering()
            .UseSorting();
    }
}
```

**Comment by PHILLIPS71** [comment]
I've done some more digging and it looks as though in v13.4.0 it's partially working, if you pin the GraphQL type it's able to resolve the query and return some data, however, if you don't pin the type in the query you will get a `HotChocolate.SchemaException`.

```cs
[GraphQLType<ListType<FileSystemNodeType>>]
[UsePaging]
[UseProjection]
[UseFiltering]
[UseSorting]
public IQueryable<FileSystemNode> FileSystemEntries([Service] ApplicationDbContext database)
{
    return database.FileSystemNodes;
}
```

It's also worth noting that while the above does work if you pin the type, it does not handle [owned entity types](https://learn.microsoft.com/en-us/ef/core/modeling/owned-entities) and always produces a null value for those objects, it looks as though its not selecting those values when constructing the sql query.

It doesn't work if the union type is part of a nested collection, for example if I had a library that has a collection of FileSystemNode objects, the collection that is returned is always an empty array. I've attempted to pin the type on the nested collection but it's produces the same result, it also looks as though the nodes are not being selected via the sql query.

```cs
public class LibraryObjectType : ObjectType<Library>
{
    protected override void Configure(IObjectTypeDescriptor<Library> descriptor)
    {
        descriptor
            .Field(p => p.Nodes)
            .Type<ListType<FileSystemNode>>()
            .UseProjection()
            .UseFiltering()
            .UseSorting();
    }
}
```

**Comment by PHILLIPS71** [comment]
closing as it's an issue with ef core and owned types using TPC see https://github.com/ChilliCream/graphql-platform/issues/6423
