### ISSUE TITLE
Apollo Field Level Tracing (FTV1) Support

### ISSUE THREAD

**Issue by craigbehnke** [ChilliCream/graphql-platform#5658]
### Is your feature request related to a problem?

Not a bug, but it is a gap in functionality that is irksome.

### The solution you'd like

Right now, while it is possible to create a subgraph for use with Apollo Federation, [federated tracing](https://www.apollographql.com/docs/graphos/metrics/field-usage/#reporting-field-usage) is not supported.

Adding this support would allow for more insight into how we are using our different graphs, as well as identify performance issues. This is also the only Federation v1 feature that Hot Chocolate does not support [according to Apollo](https://www.apollographql.com/docs/federation/building-supergraphs/supported-subgraphs#c--net).

(I saw that this feature was referenced [in this issue](https://github.com/ChilliCream/hotchocolate/issues/4622#issuecomment-1016288051), but I was unable to find it mentioned in any open issues or in the roadmap.)

### Product

Hot Chocolate

**Comment by michaelstaib** [comment]
Hot Chocolate supports standard OTel and we will not support custom tracing formats. If you are using Honecomb, Elastic, BananaCakePop you will get field level tracing for free with rich GraphQL insides.

Have a look at this introduction:
https://youtu.be/KfBV3GQ3760
