### ISSUE TITLE
Pagination parameters

### ISSUE THREAD

**Issue by thammermann** [ChilliCream/graphql-platform#5659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Passing first and last parameter within a query throws "Unexpected Execution Error" exception, when last parameter is less than first parameter. 
The query works if the last parameter is equal or greater than first parameter or if I remove the projection objects 
![image](https://user-images.githubusercontent.com/7557712/210533001-d790569f-c01b-46ae-83ed-1e856f4108cc.png)

A similar issue occurs for offset pagingation. Passing paramters skip and take only works if I remove the object projections. Only using takes works fine even if I include the object projections.

![image](https://user-images.githubusercontent.com/7557712/210533391-3773ada8-0acd-4da0-a820-de98c10d1187.png)

### Steps to reproduce

[UseOffsetPaging]
        [UseProjection]
        [UseFiltering]
        public IQueryable<Product> GetProductsPaging([ScopedService] ApplicationDbContext context)
        {
            try
            {
                var returnValue = context.Product.AsQueryable();
                return returnValue;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message + ex.StackTrace);
                return Enumerable.Empty<Product>().AsQueryable();
            }
        }
        

### Relevant log output

```shell
"errors": [
    {
      "message": "Unexpected Execution Error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "productsPaging"
      ]
    }
  ],
  "data": {
    "productsPaging": null
  }
}
```

### Product

Hot Chocolate

### Version

12.12.1

**Comment by thammermann** [comment]
Mabye the translated sql query gives a bit more clarity. Iam **not** an sql expert but calling tolist()  on the projection might cause the problem? 

  'DbSet<Product>()
.Where(_s0 => _s0.Visible == __p_0)
.Select(_s1 => new Product{
    ProductId = _s1.ProductId,
    ProductName = _s1.ProductName,
    BrandName = _s1.BrandName,
    ProductNamePrefix = _s1.ProductNamePrefix,
    ManufacturingCountry = _s1.ManufacturingCountry,
    StandardPrice = _s1.StandardPrice,
    CategoryName = _s1.CategoryName,
    CategoryId = _s1.CategoryId,
    SupplierId = _s1.SupplierId,
    ProductVariantPictures = _s1.ProductVariantPictures
        .Select(p1 => new ProductVariantPicture{
            PictureGuid = p1.PictureGuid,
            PictureType = p1.PictureType
        }
        )
        .ToList()
}
)
.Skip(__p_1)
.Take(__p_2)'



As soon as a remove the projection on "ProductVariantPictures" skip / take works fine:

SELECT[p].[ProductId], [p].[ProductName], [p].[BrandName], [p].[ProductNamePrefix], [p].[ManufacturingCountry], [p].[StandardPrice], [p].[CategoryName], [p].[CategoryId], [p].[SupplierId]
FROM[Product] AS[p]
WHERE[p].[Visible] = @__p_0
ORDER BY(SELECT 1)
OFFSET @__p_1 ROWS FETCH NEXT @__p_2 ROWS ONLY

**Comment by willnationsdev** [comment]
The v12 documentation seems to mention that you shouldn't use `first` and `last` together as you did in your first example. People are supposed to use `first` and `after` OR `last` and `before` where `after`/`before` indicate the starting point (like `skip`) and `first`/`last` indicate the range beyond that point to collect and return (like `take`). Though none of that explains why the offset paging example would likewise produce an error, so this tidbit from the docs might have no bearing on the cause of your issue.

Note: Idk about HC's internals; just happened to check this issue out on a whim while browsing.
