### ISSUE TITLE
Ambiguity errors on every build

### ISSUE THREAD

**Issue by aidensgithub** [ChilliCream/graphql-platform#5670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Every `dotnet build` regenerates the schema.graphql and merges the existing generated code, those causing the ambiguity errors throughout the project.
Changing the document parameter to specify the folder containing query files, breaks the generation -> no signs of generation, or errors.

 

### Steps to reproduce

1. `dotnet build` -> Generated folder along with client is created. Client is functional
2. Change some of your code
3. `dotnet build` -> Creates ambiguity errors, Roslyn goes crazy throughout the project. Codes inside client is duplicated.
4. remove the "Generated" folder -> All ambiguity errors are gone, generated client is functional, probably retrieving from assembly.
5. `dotnet build` -> Creates ambiguity errors, Roslyn goes crazy throughout the project. Codes inside client is duplicated.
6. Changing the "documents" parameter in .grapqlrc.json to specify Queries folder
7. `dotnet build` -> Client is broken. Client and its methods are unrecognized. No code is generated.

### Product

Strawberry Shake

### Version

12.16

**Comment by judebowman** [comment]
I am curious @aidensgithub if you are using Rider or VS with ReSharper?  I work on a team where I am one of four developers, and I am the only one who uses ReSharper.  I was seeing the same behavior you describe, and to fix it, I changed the .graphqlrc.json config file to set emitGeneratedCode to false.  However, for my co-workers who do not have ReSharper, they would see errors in VS and see red squiggly lines when the generated types were being used in code, however technically the solution would build successfully.

I am trying to figure out a way to avoid both set of issues regardless of using ReSharper or not. 

Have you tried setting the emitGeneratedCode to false?  I am curious if that fixes the issue for you.

See this link for others experiencing what I assume is the same issue - https://youtrack.jetbrains.com/issue/RIDER-66262

**Comment by aidensgithub** [comment]
I am using Rider @judebowman, and having the exact same described behavior. I have also tried to set  emitGeneratedCode to false. It indeed solves the syntax error highlights for a while, however after the debug launch, Rider stops recognizing the generated client's methods, right after I open the file containing the usage of these methods. Quite disappointing. 
It indeed could be the same as #4823

**Comment by judebowman** [comment]
I am hopeful that version 13 fixes this and a couple other issues I am experiencing.

**Comment by michaelstaib** [comment]
Its already fixed in 13

**Comment by michaelstaib** [comment]
closing this issue since its fixed
