### ISSUE TITLE
Changed case for ScalarValue

### ISSUE THREAD

**Issue by NikitaPozharskyi** [ChilliCream/graphql-platform#5679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

In the previous versions variableType could be written like this. 
![image](https://user-images.githubusercontent.com/42443861/212145960-20e3543d-817c-4103-9d16-b6e724751ade.png)

Now it should be like this
![image](https://user-images.githubusercontent.com/42443861/212145866-f1cf3e09-9b99-4b30-af7d-150743f68444.png)

This causes a lot of issues with API's which were working with GraphQl directly and it is a real problem because we have a vendor team who owns this API's and it is breaking backward compatiblitity. 
Is there any possible solution to make it doesn't case sensitive? 

 

### Steps to reproduce

1.Just a question

### Relevant log output

![image](https://user-images.githubusercontent.com/42443861/212147559-24ce13e3-a2e2-4822-bb2b-c29618a83282.png)
![image](https://user-images.githubusercontent.com/42443861/212147630-2c12173a-6f3d-4052-9ce4-6858d82cdb16.png)

### Version

12.16.0

**Comment by michaelstaib** [comment]
You can alias the type ... 
 
`AddType(new UuidType("MyName"))`
