### ISSUE TITLE
Allow for multiple [ExtendObjectType] on a extension class

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/graphql-platform#5688]
### Product

Hot Chocolate

### Is your feature request related to a problem?

When specifying multiple `ExtendObjectType` attributes on a class, only the type of the last `ExtendObjectType` is being extended.

### The solution you'd like

We have two object types that are backed by the same class and we would like to add the same extensions to both of them.

**Comment by michaelstaib** [comment]
What is your use-case?

I think its more a bug that you can specify multiple.

**Comment by tobias-tengler** [comment]
We have an entity with a discriminator. The discriminator is used in combination with `IsOfType` to represent the entity as a specific object type. We want to transform the set of shared properties of the entity using type extensions. Therefore we would like to specify that the extension applies to these n object types. It would work since the parent would always be of the same type.
Currently I've build an extension method on the `IOhjectTypeDescriptor<Entity>` that registers a common set of fields and is called by each of the object types.

I'm just thinking that we should also try whether `[ExtendObjectType(typeof(Entity))]` would work for this. I'm sure we did and there was some problem, but I'll have to re-check after the weekend.

**Comment by KreativJos** [comment]
Can't this be solved by creating an `ObjectTypeExtension` on an interface, like this:

```Csharp
[ExtendObjectType(typeof(IEntity))]
public class IEntityTypeExtension
{
    [GraphQLName("_id")]
    [GraphQLType(typeof(NonNullType<IdType>))]
    public string GetId([Parent] IEntity parent) => parent.Id;
}
```

All classes implementing this interface will have this field exposed in the same way in the schema.

**Comment by tobias-tengler** [comment]
@KreativJos Sure, but then I would have to introduce a marker interface in my entity project just for this. Sometimes this might not be possible or desirable.
