### ISSUE TITLE
To able to write own serialize and deserialize for relay id.

### ISSUE THREAD

**Issue by 0xHexE** [ChilliCream/graphql-platform#5693]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Can we add a custom serialize and deserialize function for the ID in the relay? This feature can be useful if you want to make the ID in the URL more user-friendly and SEO-friendly. For example, instead of having a URL like /organization/T3JnYW5pemF0aW9uCmRhbmd1bGFy, you can have a URL like /organization/angular. To do this, you would need to create a custom function that can take the ID and convert it to a more readable format and another function that can take the readable format and convert it back to the original ID. This way, you can use the custom functions in your front-end code to handle the ID encoding and decoding.

### The solution you'd like

A class we can pass will encode and decode relay id.

**Comment by michaelstaib** [comment]
This is already implemented:

```csharp
services
    .AddGraphQLServer()
    .AddIdSerializer<YourIdSerializer>()
    ....
```
