### ISSUE TITLE
Error in generated code "Argument 3: cannot convert from 'StrawberryShake.IOperationStore' to 'System.Func<StrawberryShake.IResultPatcher<System.Text.Json.JsonDocument>>'"

### ISSUE THREAD

**Issue by darren-clark** [ChilliCream/graphql-platform#5698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

Updating from 12.15.2 to 13.0.0-preview.103 resulted in this compiler error(in addition to the one reported in #5668)

This compile error is being reported against all the DI registrations of
`IOperationExecutor<IXXXResult>`

If I set noStore: true, then I get:
There is no argument given that corresponds to the required parameter 'resultPatcher' of 'StorelessOperationExecutor...

### Steps to reproduce

1.  Update StrawberryShake.Transport.Http and StrawberryShake.Transport.WebSockets from version 12 to version 13
2. Compile

### Additional Context?

I did not update the StrawberryShake.CodeGeneration.CSharp.Analyzers project, as NuGet wasn't showing a preview version for that. 

### Version

13.0.0-preview.103

**Comment by bromix** [comment]
Same for me as well :(

**Comment by PascalSenn** [comment]
@bromix & @darren-clark  There is no more analyzer package. You need to use one of the meta packages for Blazor, Maui or server. you can check it here:
https://chillicream.com/blog/2023/02/08/new-in-hot-chocolate-13#strawberry-shake

**Comment by sgabler** [comment]
Here are the changes I did to make it work. Not sure if all of them are necessary, but I'll post them anyway:

```diff
--- a/Client.csproj
+++ b/Client.csproj
@@ -15,34 +15,7 @@
   </PropertyGroup>
 
   <ItemGroup>
-    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0" />
-    <PackageReference Include="Microsoft.Extensions.Http" Version="6.0.0" />
-    <PackageReference Include="StrawberryShake.CodeGeneration.CSharp.Analyzers" Version="12.15.2" />
-    <PackageReference Include="StrawberryShake.Transport.Http" Version="12.15.2" />
-  </ItemGroup>
-
-  <ItemGroup>
-    <GraphQL Remove="Generated\**" />
-    <GraphQL Update="Queries\*.graphql">
-      <Generator>MSBuild:Compile</Generator>
-    </GraphQL>
-  </ItemGroup>
-
-  <ItemGroup>
-    <GraphQLConfig Remove="Generated\**" />
-  </ItemGroup>
-
-  <!-- This condition is currently needed because Rider and VS behave differently here. Apparently fixed in v13 of StrawberryShake, but that is currently in Preview -->
-  <ItemGroup Condition="'$(BuildingInsideVisualStudio)' != 'true'">
-    <Compile Remove="Generated\**" />
-  </ItemGroup>
-
-  <ItemGroup>
-    <EmbeddedResource Remove="Generated\**" />
-  </ItemGroup>
-
-  <ItemGroup>
-    <None Remove="Generated\**" />
+    <PackageReference Include="StrawberryShake.Server" Version="13.0.2" />
   </ItemGroup>
 
   <ItemGroup>
```


```diff
--- a/.config/dotnet-tools.json
+++ b/.config/dotnet-tools.json
@@ -3,10 +3,10 @@
   "isRoot": true,
   "tools": {
     "strawberryshake.tools": {
-      "version": "12.15.2",
+      "version": "13.0.2",
       "commands": [
         "dotnet-graphql"
       ]
     }
   }
```

```diff
--- a/.graphqlrc.json
+++ b/.graphqlrc.json
@@ -4,17 +4,7 @@
   "extensions": {
     "strawberryShake": {
       "name": "OurClient",
-      "namespace": "Namespace.Of.OurClient",
       "url": "https://our-api-url.com",
-      "dependencyInjection": true,
-      "strictSchemaValidation": true,
-      "hashAlgorithm": "md5",
-      "useSingleFile": true,
-      "requestStrategy": "Default",
-      "outputDirectoryName": "Generated",
-      "noStore": false,
-      "emitGeneratedCode": true,
-      "razorComponents": false,
       "records": {
         "inputs": false,
         "entities": false
```

One thing I noticed: now the code is not autogenerated automatically anymore. I have to build the project first. But that's not so bad.

I also removed all the explicit config in .graphqlrc.json, because if you create a new project with the instructions that @PascalSenn posted, then those values are not there.

@PascalSenn would you say that it makes sense like this?

**Comment by PascalSenn** [comment]
@sgabler  all in all this makes sense. The changes to graphqlrc.json are not necessary though we provide more presets with the meta packages. e.g. we often saw people having a cache in the backend where they do not want it.

>I have to build the project first. 
This is indeed the case as we migrated away from source gens to plain old msbuild. the reason for this is that this approach now also works with other source generators in combination (e.g. blazor). (and generating the sources is now rocksolid)
