### ISSUE TITLE
Having entity methods that accept DbContext as a parameter throws a SchemaException.

### ISSUE THREAD

**Issue by willnationsdev** [ChilliCream/graphql-platform#5705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I have an entity from EF Core that I return in an IQueryable. If I have a helper method on the class that accepts as an argument a `DbContext` to facilitate writing queries involving the entity, then Hot Chocolate throws a `SchemaException` and tells me that the  schema is unavailable in BananaCakePop.

If I inspect the contents of the exception, they differ depending on the method. Methods that are generic tell me that it is "Unable to create instance of type". Methods that are not generic say it is "Unable to infer or resolve a schema type for type reference" and then details the type name, mentioning `IDbContextTransaction`, `IModel`, and `DbContextId`, as if it were trying to analyze the model of the `DbContext` class itself. However, this is merely a random method on the entity and not some property. I do not appear to be able to tell Hot Chocolate that I do not want it to try parsing these methods as being part of the model. It does so regardless, even if you declare that fields must be bound explicitly.

Interestingly, while the "schema is unavailable" UI in BananaCakePop happens regardless, the SchemaException itself is only reported if I have custom middleware that I've added to the ASP.NET Core pipeline prior to the `UseRouting()` middleware. The exception is then triggered on the middleware's `await next()` line of code. If you add multiple middleware before `UseRouting()`, the exception will be re-triggered once for each one.

### Steps to reproduce

1. Add a method to an EF core entity that accepts as an argument a `DbContext`. Then return an `IQueryable<T>` of that entity's type from a GraphQL endpoint.
2. Add a custom middleware before the `UseRouting()` middleware of your ASP.NET Core application. (I experienced it with .NET 6)

### Relevant log output

```shell
Exception thrown: 'HotChocolate.SchemaException' in System.Private.CoreLib.dll
```

### Additional Context?

Here is an obfuscated, best-attempt-duplication of the code I have.

```
public class EntityA
{
    // Produces SchemaException with error "Unable to infer or resolve a schema type..." etc. as detailed above.
    public IQueryable<EntityB> QueryB(DbContext db)
        => db.Set<EntityA>().Where(x => x.Id == Id)
            .Join(db.Set<EntityB>(), x => new { x.Id }, x2 => new { Id = x2.EntityAId }, (x, x2) => x2);
    
    // Produces SchemaException with error "Unable to create instance of type ``".
    public IQueryable<TRelated> QueryRelated<TRelated>(DbContext db)
        where TRelated : class, IRelatedToA
        => db.Set<EntityA>().Wgere(x => x.Id == Id)
            .Join(db.Set<TRelated>(), x => new { x.Id }, x2 => new { Id = x2.EntityAId }, (x, x2) => x2);
    
    // Actually works, but frustratingly abandons type-safety for the caller.
    public IQueryable<EntityB> QueryB(other db)
        => ((DbContext)db).Set<EntityA>().Where(x => x.Id == Id)
            .Join(((DbContext)db).Set<EntityB>(), x => new { x.Id }, x2 => new { Id = x2.EntityAId }, (x, x2) => x2);
}
```

### Version

12.16.0

**Comment by michaelstaib** [comment]
There are a couple of solutions for this with version 13. You can use `RegisterDbContext` as a common service with the schema and than this will be not an issue. Another way is to use a fluent type to declare the DBContext as a service. With V14 we will automatically detect services.
