### ISSUE TITLE
Getting "Specified method is not supported." on executing a querycall

### ISSUE THREAD

**Issue by DanteSparda** [ChilliCream/graphql-platform#5715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

Hey all,
Has anyone seen "Specified method is not supported." error?
The request works perfectly in Postman and the browser UI (graphql sandbox).
Using StrawberryShake I get the error above and only for this query.
```
query GetCategories {
  categories {
    data {
      id
      name
    }
  }
}

```
This query for instance works:
```
query GetBrands {
  brands {
    data {
      name
    }
  }
}

```

Fiddler says the result is 200 and it does return the value.
![image](https://user-images.githubusercontent.com/7839549/214577234-ed7d2e58-5ff4-4892-8c11-305d492a1ee2.png)

Inside of the StrawberryShake.OperationResult.Errors>Extensions I can see the value of the response.
![image](https://user-images.githubusercontent.com/7839549/214577202-e20f1578-f013-45ec-b95d-3c78b1d2e3e7.png)

excuse the white flashing :D

### Steps to reproduce

1. Create console application
Follow the strawberry setup guide in the site or use this tutorial (https://www.youtube.com/watch?v=6oJlibTwn_4&ab_channel=SingletonSean)
 
   a. The url I'm using is for a dev env that I shouldn't share on the internet, but I can provide it to a developer that wants to test 
       it 1:1

2. Paste this code 
 ```
           var serviceCollection = new ServiceCollection();

            serviceCollection
                .AddDemoServicesClient()
                .ConfigureHttpClient(client => client.BaseAddress = new Uri("url I can provide to individuals only"));

            IServiceProvider services = serviceCollection.BuildServiceProvider();

            var client = services.GetRequiredService<IDemoServicesClient>();
            var categories = await client.GetCategories.ExecuteAsync();
```

3. Run it.

The GetCategories is the query from the bug

```
query GetCategories {
  categories {
    data {
      id
      name
    }
  }
}

```

### Version

12.16.0

**Comment by DanteSparda** [comment]
From what I gathered so far - looks like the __typename wasn't set for the Categories. I don't have access to the GraphQL server, so I'll contact the team and see if setting the typename will resolve this.
Will keep this updated

**Comment by ibramn** [comment]
I have exactly the same issue, how did you resolve this issue ?

**Comment by glen-84** [comment]
@DanteSparda Do you have an update? Did setting the `__typename` resolve the issue?

**Comment by nollidnosnhoj** [comment]
I recently came across this error while using StrawberryShake. I had to debug the issue and found out that the exception was thrown when the generated StrawberryShake client was trying to deserialize the response into the generated C# type, but failed. It failed because the type from the response did not match the type from the generated C# type. So I had to update my schema.graphql and regenerate the C# code, and it works now. 

Do not know if this solves the issue, since this exception could be thrown anywhere, but best way to solve this is to use a debugger (whether in Visual Studio or Jetbrains Rider), and run the code locally.

Cheers.

**Comment by glen-84** [comment]
Closing, as no response has been received from the author.

**Comment by Temppus** [comment]
I encountered same issue when evaluating Shake client generation. Problem is that our backend platform upgraded HotChocolate which changed navigation properties type names of our EF core models.

This generated code is falling back to `NotSupportedException` branch

``` 
       private global::SFClientNS.State.WatchlistMemberCollectionSegmentData? Deserialize_IGetMembersWithWatchlists_WatchlistMembers(global::StrawberryShake.IEntityStoreUpdateSession session, global::System.Text.Json.JsonElement? obj, global::System.Collections.Generic.ISet<global::StrawberryShake.EntityId> entityIds)
        {
            if (!obj.HasValue)
            {
                return null;
            }

            if (obj.Value.ValueKind == global::System.Text.Json.JsonValueKind.Null)
            {
                return null;
            }

            var typename = obj.Value.GetProperty("__typename").GetString();
            if (typename?.Equals("WatchlistMemberCollectionSegment", global::System.StringComparison.Ordinal) ?? false)
            {
                return new global::SFClientNS.State.WatchlistMemberCollectionSegmentData(typename, items: Update_IGetMembersWithWatchlists_WatchlistMembers_ItemsEntityArray(session, global::StrawberryShake.Json.JsonElementExtensions.GetPropertyOrNull(obj, "items"), entityIds));
            }

            throw new global::System.NotSupportedException();
        }```

is GQL type name change considered as breaking change ? Using GraphQLNet seems to have no problem with mapping response  when name of type has changed.
