### ISSUE TITLE
graphql-workshop-neo4j serialization issue on Code First

### ISSUE THREAD

**Issue by bnayae** [ChilliCream/graphql-platform#5719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

# [graphql-workshop-neo4j](https://github.com/ChilliCream/graphql-workshop-neo4j) serialization issue on Code First

Unless I'm naming my properties as a camel-case in the first place, results return as nulls.

![image](https://user-images.githubusercontent.com/3382669/214807229-bab2dd8a-cf1f-4776-9640-8745c7ae1cc1.png)

Even when I tried to use `[JsonPropertyName("title")]`, it didn't help.

```cs
    public class Movie
    {
        [JsonPropertyName("title")]
        public string Title { get; set; }

        [Neo4JRelationship("ACTED_IN", RelationshipDirection.Incoming)]
        public List<Actor> Actors { get; set; }
    }
 ```

The only thing which work for me is using a camel case (which is against our convention).

```cs
    public class Movie
    {
        public string title { get; set; }

        [Neo4JRelationship("ACTED_IN", RelationshipDirection.Incoming)]
        public List<Actor> Actors { get; set; }
    }
 ```
 
 I expect the library being able to use Pascal Case properties and honor `[JsonPropertyName("title")]`.

### Steps to reproduce

1. Just run the code first sample of the workshop
https://github.com/ChilliCream/graphql-workshop-neo4j

You can change the project setting to 

```
    <PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<LangVersion>11.0</LangVersion>
		<Nullable>disable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

    <ItemGroup>
      <PackageReference Include="HotChocolate.AspNetCore" Version="12.16.0" />
      <PackageReference Include="HotChocolate.Data.Neo4J" Version="12.16.0" />
    </ItemGroup>
```

Yet, it doesn't work on the original either.

### Version

12.16.0

**Comment by glen-84** [comment]
Closing, as Neo4j support has been [removed](https://github.com/ChilliCream/graphql-platform/pull/6655) in v14.
