### ISSUE TITLE
Case insensitive filtering doesnt work

### ISSUE THREAD

**Issue by wellWINeo** [ChilliCream/graphql-platform#5720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

In [documentation](https://chillicream.com/docs/hotchocolate/v12/api-reference/extending-filtering#extending-iqueryable) and in this [demo repo](https://github.com/PascalSenn/Filtering.Demo) provided way to implement case insensitive operators for filtering. But it doesn't work. I created own example demo [here](https://github.com/wellWINeo/ODataGraphQL_Demo/tree/main/GraphQLDemo).

### Steps to reproduce

1. Launch for example my demo
2. Database contains book with title "Мастер и Маргарита"
3. Run this query 
```graphql
query GetBookByTitle ($title: String!) {
    books (where: {
        title: { contains: $title }
    }) {
        title,
    }
} 
```
4. With title="мастер" it returns empty array
5. With title="Мастер" i've got desired book

### Version

12.15.2

**Comment by dzmitrykarnitski-na** [comment]
I am not a contributor to HotChocolate, but was curious about this issue as recently was implementing the same feature on my project using the example you mentioned and all was fine.

In your case seems like you are sending a query for the `contains` operation, however, the case-insensitive search is set up only for the `equals` operation.
https://github.com/PascalSenn/Filtering.Demo/blob/19aaf301196699296586eee8f964ad210a9c742e/QueryableStringInvariantEqualsHandler.cs#L19
``` c#        
protected override int Operation => DefaultFilterOperations.Equals;
```
See this configuration: 
https://github.com/PascalSenn/Filtering.Demo/blob/19aaf301196699296586eee8f964ad210a9c742e/CustomFilteringConvention.cs#L12
``` c#
descriptor.Operation(DefaultFilterOperations.Equals).Name("equals");
```

**Comment by wellWINeo** [comment]
I configured case insensitive for "contains" operation in my demo. I'll check later with "equals" operator.

**Comment by dzmitrykarnitski-na** [comment]
oh, I looked at the expression in the handler and it is an `Equal` expression, so it messed up thoughts in my head and I assumed that repos are the same, sorry for that stupid mistake.
https://github.com/wellWINeo/ODataGraphQL_Demo/blob/5d836922cc5b085555725acfe83091ce2a5ae9bc/GraphQLDemo/Handlers/QueryableStringInvariantContainsHandler.cs#L29
tbh, I am not sure how it can return the desired book, taking into account that the expression created is the `Equal` expression, but I think it should be `Contains` method call expression instead. Also, on our product we are adding null check expression, so our code looks like this (I cannot copy the code, but I 'replayed' as much as I can):

``` c#
    ctor
    {
        CanBeNull = false;
    }

    public override Expression HandleOperation(
        QueryableFilterContext context,
        IFilterOperationField field,
        IValueNode value,
        object? parsedValue)
    {
        var propertyAccessExpression = context.GetInstance();

       var parsedValueAsString = (string)parsedValue!;

        return Expression.AndAlso(
            BuildNotEqualsToNullExpression(propertyAccessExpression),
            BuildContainsMethodCallExpression(propertyAccessExpression, parsedValueAsString));
    }

    protected Expression BuildContainsMethodCallExpression(Expression propertyAccessExpression, string parsedValue)
    {
        var propertyValueConvertedToLowercase = Expression.Call(propertyAccessExpression, ToLowerMethodInfo);

        return Expression.Call(
            propertyValueConvertedToLowercase,
            ContainsMethodInfo,
            Expression.Constant(parsedValue.ToLowerInvariant(), typeof(string)));
    }

    private Expression BuildNotEqualsToNullExpression(Expression propertyAccessExpression) =>
        Expression.NotEqual(propertyAccessExpression, Expression.Constant(null, typeof(string)));
```

Hope it helps, and sorry for being blind :)

**Comment by wellWINeo** [comment]
Sorry for so huge gap between messages. Yeah, i didn't notice this thins with expression) I tried to reproduce ur sample code and it didn't work. After some time of tinkering i found that sqlite incorrectly works with cyrillic 😞, i checked it with latin and everything works as expected) I updated my repository for those who face same problem in the future

**Comment by michaelstaib** [comment]
Thanks for the feedback.
