### ISSUE TITLE
When using HotChocolate v12 along with EntityFrameworkCore, .UseOffsetPaging breaks the graphql schema

### ISSUE THREAD

**Issue by MrJackWilson** [ChilliCream/graphql-platform#5721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Using .UseOffsetPaging breaks my graphql schema. If I remove the call to .UseOffsetPaging it works just fine. I would expect that the schema is valid and it has the appropriate paging arguments applied in the schema.

### Steps to reproduce

The issue can be seen in the solution I've attached below:

[UseOffsetPagingBug.zip](https://github.com/ChilliCream/graphql-platform/files/10508813/UseOffsetPagingBug.zip)

### Version

12.6.0

**Comment by glen-84** [comment]
You need to specify the element type:

```cs
UseOffsetPaging<ObjectType<Author>>()
```

@michaelstaib Is there any way for this to be inferred, or is it a technical limitation?
