### ISSUE TITLE
Hotchocolate Enum Lowercase character schema unavailable problem

### ISSUE THREAD

**Issue by tunahan-guler** [ChilliCream/graphql-platform#5729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I am describing an enum that has 1 property like Question.
Then i started project and schema is not loaded.
Then i changed Property name to QUESTION and it started successfully.
Problem was Question's i letter.
Hotchocolate generating enum name with UPPERCASE.

### Steps to reproduce

1. Create enum that has lowercase i letter.
2. Start project.
3. Schema is unavailable.

### Version

12.0.0

**Comment by michaelstaib** [comment]
Can you please attach a small repro... like a small project that shows the issue?

**Comment by Torellonik** [comment]
We had similar problems with enum conventions.

We resolved by creating a class that inherits from `DefaultNamingConventions` like following one:

```c#
public class EnumNamingConvention : DefaultNamingConventions
{
    public override NameString GetEnumValueName(object value)
    {
        if (value == null)
        {
            throw new ArgumentNullException(nameof(value));
        }
        return value.ToString() ?? string.Empty;
    }
}
```

Then you have to register it in your `Startup`:

`services.AddConvention<INamingConventions>(new EnumNamingConvention())`

In this way we can use also lower case in enum classes and even in GraphQL queries.

**Comment by vbornand** [comment]
Hello @tunahan-guler,

I tried to reproduce your issue but without success.

I created a small project with an enum. Te name of the enum "Cont**i**nent" contains an "i", and there is "Afr**i**ca" as enum value.

You can find it in the repo https://github.com/vbornand/enumlowerissue

You can fork and try to add the code to reproduce your issue.

**Comment by michaelstaib** [comment]
Closing this issue as it has no repro
