### ISSUE TITLE
Breaking change in AnyType deserialization on Input types

### ISSUE THREAD

**Issue by Andrej-Peplinski** [ChilliCream/graphql-platform#5730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

We started to use hotchocolate in version 11 where it was possible to deserialize arbitrary input object (scalar and complex). When using complex input object, we used to get a deserialized dotnet representation being a `IReadOnlyDictionary<string, object>` (as it's also stated in the [documentation](https://chillicream.com/docs/hotchocolate/v13/defining-a-schema/scalars#any-type)).
However, this functionality has been broken in version 12 where the deserialized version if of type `System.Object`. As a consequence, all information send to the frontend is lost - which prevents us from from updating the HotChocolate packages. Furthermore, I have tried version 13.0.0.-rc.1 where the complete deserialization fails with an InvalidCastException.

### Steps to reproduce

1. Please clone the [repro-project](https://github.com/Andrej-Peplinski/HotChocolateInputTypeAnyDeserialization).
2. The solution contains 2 (almost) identical projects using the same graphql schema - but using either HotChocolate version 11 or 12.
3. In both projects set a breakpoint in the `ParameterValuePair.Value.set` property found in _Program.cs_.
4. Start debugging either of the 2 project and copy the queries (from the _Sample Queries.txt_) into the Banana Cake Pop.
5. Excute the _simpleObjectAsDictionary_ mutation, and, once the breakpoint is hit, observe the `value`.

- ![image](https://user-images.githubusercontent.com/44775468/215545213-33c3e93e-8837-4773-b2a6-904d46d9664a.png)
- ![image](https://user-images.githubusercontent.com/44775468/215545765-f603c204-24b6-4df0-a3fb-4760edbd19ee.png)

### Additional Context?

Another way of "just" viewing the deserialisation defect is running the two project and inspecting the responses. In version 11 one show see this:
![image](https://user-images.githubusercontent.com/44775468/215766420-ea26b28c-c68e-41df-b0ac-180461905625.png)

And in version 12 this:
![image](https://user-images.githubusercontent.com/44775468/215766478-7db2a1ea-ef26-41d3-8819-c40f7ae82259.png)

### Version

11.3.7, 12.6, 13.0.0-rc.1

**Comment by michaelstaib** [comment]
The repro does not exist
https://github.com/Andrej-Peplinski/HotChocolateInputTypeAnyDeserialization

**Comment by michaelstaib** [comment]
Wait ... i try to create a tests from the infos you provided.

**Comment by Andrej-Peplinski** [comment]
I have now attached the solution here in case there are problems clone my repository from Github: [HotChocolateInputTypeAnyDeserialization - Kopie.zip](https://github.com/ChilliCream/graphql-platform/files/10546551/HotChocolateInputTypeAnyDeserialization.-.Kopie.zip)
