### ISSUE TITLE
HotChocolate example link is broken

### ISSUE THREAD

**Issue by Andrej-Peplinski** [ChilliCream/graphql-platform#5731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

![image](https://user-images.githubusercontent.com/44775468/215561249-159903ff-d3fb-437d-bd2a-1a035219e85f.png)

### Steps to reproduce

1. View screenshot

### Version

12.0

**Comment by glen-84** [comment]
This was fixed in #5793.
