### ISSUE TITLE
Directive on query element is not resolving arguments

### ISSUE THREAD

**Issue by Tasteful** [ChilliCream/graphql-platform#5755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I created a directive `@urlContext(url: String!)` for the `Query` element. Added a middleware and was set that for the `.Use` on the directive definition. When the middleware is executed the directive is found below the `context.Directive` but when executing `context.Directive.GetArgument<string>("url")` I always getting `null` out.

If instead adding the directive on the field/field definition the middleware and get arguments methods are working as expected.

Workaround that I found is to use this to find the directive argument value
```cs
var directive = context.Operation.Definition.Directives.FirstOrDefault(x => x.Name.Value == context.Directive.Name);
var argument = directive?.Arguments.FirstOrDefault(x => x.Name.Value == "url");
var urlString = argument?.Value.Value as string;

if ((argument?.Value.Kind != HotChocolate.Language.SyntaxKind.Variable
    || context.Variables.TryGetVariable(urlString, out urlString))
    && !string.IsNullOrEmpty(urlString)
    && Uri.TryCreate(urlString, UriKind.RelativeOrAbsolute, out var url))
{

}
```

### Steps to reproduce

Schema
```gql
directive @UrlContext(
  """
  The url for the contextual information.
  """
  url: String = "not-set"
) on QUERY | MUTATION | FIELD | OBJECT | FIELD_DEFINITION

type Query {
  content: String!
}
```

Query
```gql
query @UrlContext(url: "https://github.com")  {
  content
}
```

Directive definition
```cs
public class UrlContext
{
    public string Url { get; set; }
}

public class UrlContextType : DirectiveType<UrlContext>
{
    protected override void Configure(IDirectiveTypeDescriptor<UrlContext> descriptor)
    {
        descriptor.Argument(x => x.Url)
            //.Type<NonNullType<StringType>>()
            .Description("The url for the contextual information.")
            .DefaultValue("not-set");

        descriptor.Location(DirectiveLocation.Query | DirectiveLocation.Mutation | DirectiveLocation.Field | DirectiveLocation.FieldDefinition | DirectiveLocation.Object);

        descriptor.Use<UrlContextMiddleware>();
    }
}
```

Directive middleware
```cs
public class UrlContextMiddleware
{
    private readonly FieldDelegate _next;

    public UrlContextMiddleware(
        FieldDelegate next)
    {
        _next = next;
    }

    // this method must be called InvokeAsync or Invoke
    public async ValueTask InvokeAsync(IDirectiveContext context)
    {
        // Code up here is executed before the following middleware
        // and the actual field resolver
        var url = context.Directive.GetArgument<string>("url"); // this always return null when directive is on query

        // This invokes the next middleware
        // or if we are at the last middleware the field resolver
        await _next(context);

        // Code down here is executed after all later middleware
        // and the actual field resolver has finished executing
    }
}
```

### Version

13.0.0-preview.85

**Comment by michaelstaib** [comment]
That is not how the API works.

The middleware is only invoked for FieldDefinition and Field directives. Also, the middleware context has nothing todo with the directive itself. In order to get the directive values you need to resolver the directive object.

**Comment by Tasteful** [comment]
Can you point my in the correct direction? The https://chillicream.com/docs/hotchocolate/v12/defining-a-schema/directives does not include how to use the directive and their argument, only how to define them and specifying the middleware, and hard to navigate in the test-cases if there is any example.

**Comment by Tasteful** [comment]
Also if I change to use the use-delegate directly to simplify, the middleware is executed even if the directive is on the query-element itslef

For the query
![image](https://user-images.githubusercontent.com/357589/216376755-15806db3-a825-4c17-9ec0-597d912fc772.png)
I got a break point hit as
![image](https://user-images.githubusercontent.com/357589/216376692-f5edff4b-6b3f-4fc8-938f-f43676fdb815.png)

And however I try to fetch the value it's null.
![image](https://user-images.githubusercontent.com/357589/216377246-e441d990-c55f-407d-88b3-26d8ef08630b.png)

If I instead move the directive down to the field, 
![image](https://user-images.githubusercontent.com/357589/216378738-cfd4c603-066f-491a-8f05-7130e238cfe3.png)

it's working intended and the values are fetched by the inbuilt functions
![image](https://user-images.githubusercontent.com/357589/216378641-79b4d899-993f-47bd-86b9-b35fc730bb08.png)

So if this middleware not should be executed for query-directives, it's a bug that it will be executed. If it should be executed for the query directives either there is a bug that for resolving of the directive argument or lack of documentation about how we should access the directive argument.

**Comment by michaelstaib** [comment]
That breakpoint is from the field... but we changed it with 13 to be more predictable ... so you will no longer get that.

**Comment by michaelstaib** [comment]
Use the newest HC 13 build and it will no longer hit the breakpoint.

**Comment by michaelstaib** [comment]
What are you trying to do with the directives? can you explain a bit your use-case then I will be better able to help you. Are you on slack btw... slack.chillicream.com?

**Comment by Tasteful** [comment]
I see, I was using a previous prerelease but after upgraded to the RC.4 it was behave as you describe. I'm not on slack and was not able to join either, the link has expired...

Our current model looks like this (simplified)
```gql
Query {
    contextual (url: String!): ContextualContext {
        content: IContent,
        search (query: QueryInput!): SearchResult!
    }
}

type SeachResult {
    products: ProductSearchResult!,
    pages: PageSearchResult!
}

type ProductSearchResult {
    totalCount: Number!,
    items: [ProductContent!]!
}

type PageSearchResult {
    totalCount: Number!,
    items: [PageContent!]!
}

type QueryInput {
    tags: [String!]
}


type PageContent {
    childPages: [PageContent!]!
}

type ProductContent {
    name: String,
    price: Number!
}

union IContent = PageContent | ProductContent
```
where all of the information that will be returned is contextual to the url that we should fetch the information from, url is resolved in the system and from that we are getting the culture/currency that should be used for the language element in the types (like name/price field in the ProductContent). We also need to be able to add the contextual information to the mutations, they will as-well be dependent on that one.

We feel that this structure is not the best and having this `contextual` node that everything is below and was looking into the `@directive` usage and to get rid of the `contextual` item to get a flat structure instead of this deep structure. 

More like this setup, and then use the information from the directive inside the different nodes (content/search etc) and only need to resolve the needed contextual information (language, currency etc) once.
```gql
Query @urlContext(url: String!) {
    content: IContent,
    search (query: QueryInput!): SearchResult!
}
```

I don't like the need to pass in the contextual information in all elements that we need to resolve either because all the replicate of code that not feels straight forward and that we need to execute the same resolver multiple times.
```gql
Query  {
    content(url: String!): IContent,
    search (url: String!, query: QueryInput!): SearchResult!
}
```

I know that we can pass the information as http-headers and I want to avoid that as-well because looking to use GQL Federation for extensibility and I think it will be harder (if at all possible) to get that information down to the sub-graphs if needed.

**Comment by michaelstaib** [comment]
I have fixed the link ... if you want to try again.

**Comment by michaelstaib** [comment]
> I know that we can pass the information as http-headers and I want to avoid that as-well because looking to use GQL Federation for extensibility and I think it will be harder (if at all possible) to get that information down to the sub-graphs if needed.

Header propagation is an well-known concept with federated graphs.

**Comment by michaelstaib** [comment]
So you can access the directives on each field ... we do not coerce them by default because it has a performance impact. You could do that in the query compilation phase but there are variables that could be passed into the arguments ... these would prevent you from doing it there.

**Comment by Tasteful** [comment]
> I have fixed the link ... if you want to try again.

Thanks, now it was working.

> > I know that we can pass the information as http-headers and I want to avoid that as-well because looking to use GQL Federation for extensibility and I think it will be harder (if at all possible) to get that information down to the sub-graphs if needed.
> 
> Header propagation is an well-known concept with federated graphs.

Do you, from the above information, think that it's better to send this contextual information as http-header information?

> So you can access the directives on each field ... we do not coerce them by default because it has a performance impact. You could do that in the query compilation phase but there are variables that could be passed into the arguments ... these would prevent you from doing it there.

_the query compilation phase_ is that the same as implementing an `IHttpRequestInterceptor` or how do I inject my own code inside that?
