### ISSUE TITLE
HotChocolate Server silent fails and does not respect ConfigureKestrel options

### ISSUE THREAD

**Issue by PandaBlackAndWhitr** [ChilliCream/graphql-platform#5758]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When you use `ConfigureKestrel` to configure the underlying webhost, HotChocolate does not configure according to it

### Steps to reproduce

Configure your Kestrel webhost somewhere and run with GraphQL:
```
var builder = WebApplication.CreateBuilder(args);

builder.WebHost.ConfigureKestrel(options =>
  {
    options.Listen(IPAddress.Any, 8080, listenOptions =>
    {
      listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
    });
  });

// Abbreviated
builder.Services.AddGraphQLServer()...

var app = builder.Build();

app.MapGraphQL();
app.Run();
```
Standard stuff; I configured Kestrel to follow the [gRPC guide.](https://learn.microsoft.com/en-us/aspnet/core/grpc/aspnetcore?view=aspnetcore-7.0&tabs=visual-studio#tls)

When you run, Kestrel should announce it's using a separate endpoint (shown in log output), and HotChocolate will not use it. No error messages will come up regarding HotChocolate.

### Relevant log output

```shell
Microsoft.AspNetCore.Server.Kestrel: Warning: Overriding address(es) 'http://localhost:5129, https://localhost:7186'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Overriding address(es) 'http://localhost:5129, https://localhost:7186'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://0.0.0.0:5001
Microsoft.Hosting.Lifetime: Information: Now listening on: http://0.0.0.0:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
```

### Version

12.16.0

**Comment by michaelstaib** [comment]
We do nothing special here ... internally we are just an ASP.NET middleware.

**Comment by michaelstaib** [comment]
OK, tested it now and it works all fine.

**Comment by michaelstaib** [comment]
```csharp
builder.WebHost.ConfigureKestrel(options =>
  {
      options.ListenAnyIP(8080, listenOptions =>
      {
          listenOptions.Protocols = HttpProtocols.Http1AndHttp2;
      });
  });
```
