### ISSUE TITLE
BananaCakePop UI works only from localhost

### ISSUE THREAD

**Issue by Temppus** [ChilliCream/graphql-platform#5784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Banana Cake Pop

### Describe the bug

We are using standard Graphql integration with 

`
        app.UseEndpoints(endpoints =>
        {
            endpoints.MapGraphQL();
        });
`

When accessing BananaCakePop from browser and browser URL is `http://localhost:8097/graphql/` everything works as expected.
But when I access UI  by machine hostname `http://machine-name:8097/graphql/` I get this error on client side

![image](https://user-images.githubusercontent.com/827991/216980920-5114248e-aef9-478a-97af-247fabe23ed3.png)

Do you have any ideas what can be done to pin down issue ?
Thanks.

### Steps to reproduce

1. Access BananaCakePop UI by hostname

### Relevant log output

```shell
{
  "name": "TypeError",
  "message": "Cannot read properties of undefined (reading 'addEventListener')",
  "stack": "TypeError: Cannot read properties of undefined (reading 'addEventListener')\n    at http://machine-name:8097/graphql/static/js/191.88fc520b.chunk.js:1:464182\n    at ru (http://machine-name:8097/graphql/static/js/917.89c7cf0e.js:2:116682)\n    at _s (http://machine-name:8097/graphql/static/js/917.89c7cf0e.js:2:136909)\n    at http://machine-name:8097/graphql/static/js/917.89c7cf0e.js:2:133499\n    at _ (http://machine-name:8097/graphql/static/js/917.89c7cf0e.js:2:162554)\n    at MessagePort.R (http://machine-name:8097/graphql/static/js/917.89c7cf0e.js:2:163088)"
}
```

### Version

12.16.0

**Comment by tobias-tengler** [comment]
Is there a proxy involved in the setup where you access BCP over the Hostname?

**Comment by artola** [comment]
@Temppus You are using `http` and in the BCP version that you are running, we have a call that only works in secure context.
It was fixed around a month ago, you will find the find in BCP v3.0.4

**Comment by artola** [comment]
@Temppus You can now upgrade to [12.16.2](https://www.nuget.org/packages/HotChocolate/12.16.2) that contains the fix for BCP.
Please let us know if it works with that to close this issue.

**Comment by Temppus** [comment]
Thanks ! I have upgraded to latest RC candidate and it seems like it works correctly.

**Comment by Temppus** [comment]
> @Temppus You can now upgrade to [12.16.2](https://www.nuget.org/packages/HotChocolate/12.16.2) that contains the fix for BCP. Please let us know if it works with that to close this issue.

I also works with [12.16.2](https://www.nuget.org/packages/HotChocolate/12.16.2). Thanks.
