### ISSUE TITLE
Unable to use different authentication schemes for different queries

### ISSUE THREAD

**Issue by oysandvik94** [ChilliCream/graphql-platform#5792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When using different authentication policies, for example Cookie and JWT, I am unable to use one of these on different queries. For example, I would like one query to be authenticated by cookies, and one by JWT. I can achieve this behaviour in different controllers for MVC.

The policies are still getting applied, so if my different policies for my different queries have different requirements, they will be applied in an OR pattern, however it seems like the Authentication Scheme does not.

### Steps to reproduce

Reproduction below with instructions in readme:
https://github.com/oysandvik94/hotchocolate-multiauth-repro

### Additional Context?

I dont know if it's relevant, but I noticed that the Asp.Net Core Authroize attribute contains a "schemes" property, while the Hot Chocolate does not. 

### Version

12.6.0, 13.0.0.RC

**Comment by michaelstaib** [comment]
This works ...

you need to implement a HttpRequestInterceptor.

```csharp
    internal class CustomHttpRequestInterceptor : DefaultHttpRequestInterceptor
    {
        public override async ValueTask OnCreateAsync(
            HttpContext context,
            IRequestExecutor requestExecutor,
            IQueryRequestBuilder requestBuilder,
            CancellationToken cancellationToken)
        {
            await context.AuthenticateAsync("YOUR_SCHEME");
            await base.OnCreateAsync(context, requestExecutor, requestBuilder, cancellationToken);
        }
    }
```

**Comment by shahabfar** [comment]
For me, the custom policy works only in the global authorization of Hotchocolate.
app.MapGraphQL().RequireAuthorization("CustomPolicy");

**Comment by Pieeer1** [comment]
> This works ...
> 
> you need to implement a HttpRequestInterceptor.
> 
> ```cs
>     internal class CustomHttpRequestInterceptor : DefaultHttpRequestInterceptor
>     {
>         public override async ValueTask OnCreateAsync(
>             HttpContext context,
>             IRequestExecutor requestExecutor,
>             IQueryRequestBuilder requestBuilder,
>             CancellationToken cancellationToken)
>         {
>             await context.AuthenticateAsync("YOUR_SCHEME");
>             await base.OnCreateAsync(context, requestExecutor, requestBuilder, cancellationToken);
>         }
>     }
> ```

Would be curious to see if there is a full working sample for this. I am unable to get this to function correctly, seems like even if it makes the correct AuthenticateAsync request here, it makes ANOTHER request after, which uses the default and fails.

**Comment by uncle-mo** [comment]
> This works ...
> 
> you need to implement a HttpRequestInterceptor.
> 
> ```cs
>     internal class CustomHttpRequestInterceptor : DefaultHttpRequestInterceptor
>     {
>         public override async ValueTask OnCreateAsync(
>             HttpContext context,
>             IRequestExecutor requestExecutor,
>             IQueryRequestBuilder requestBuilder,
>             CancellationToken cancellationToken)
>         {
>             await context.AuthenticateAsync("YOUR_SCHEME");
>             await base.OnCreateAsync(context, requestExecutor, requestBuilder, cancellationToken);
>         }
>     }
> ```

I'm also unable to get this working. Any more information or a more comprehensive sample would be very much appreciated.

I'm trying to have some queries & mutations support both JWT Bearer and Basic Authentication but no query/mutation needs to nor should it support both schemes simultaneously. 

Any help would be appreciated.

**Comment by Pieeer1** [comment]
> > This works ...
> > you need to implement a HttpRequestInterceptor.
> > ```cs
> >     internal class CustomHttpRequestInterceptor : DefaultHttpRequestInterceptor
> >     {
> >         public override async ValueTask OnCreateAsync(
> >             HttpContext context,
> >             IRequestExecutor requestExecutor,
> >             IQueryRequestBuilder requestBuilder,
> >             CancellationToken cancellationToken)
> >         {
> >             await context.AuthenticateAsync("YOUR_SCHEME");
> >             await base.OnCreateAsync(context, requestExecutor, requestBuilder, cancellationToken);
> >         }
> >     }
> > ```
> 
> I'm also unable to get this working. Any more information or a more comprehensive sample would be very much appreciated.
> 
> I'm trying to have some queries & mutations support both JWT Bearer and Basic Authentication but no query/mutation needs to nor should it support both schemes simultaneously.
> 
> Any help would be appreciated.

I was able to get this working somewhat. It is not ideal and is definitely a workaround, but you can check to see if it authenticated successfully on one and then try the other if it fails. Code below:

```CSharp
public class AuthenticationInterceptor : DefaultHttpRequestInterceptor
{
    public override async ValueTask OnCreateAsync(HttpContext context, IRequestExecutor requestExecutor, IQueryRequestBuilder requestBuilder, CancellationToken cancellationToken)
    {

        var result = await context.AuthenticateAsync("NON-DEFAULT-SCHEME");
        if (!result.Succeeded)
        {
            result = await context.AuthenticateAsync(); // find a better way to do this. currently the claims only get populated if we successfully authenticate, so we need to do it twice. this takes the default scheme
        }
        //not an else here because we reassign the value of result. Just looks confusing
        if (result.Succeeded)
        {
            context.User = result.Principal;
        }
        await base.OnCreateAsync(context, requestExecutor, requestBuilder, cancellationToken);
    }
}
```

**Comment by uncle-mo** [comment]
Thank you @Pieeer1 This worked for me.

**Comment by erikkipp** [comment]
No fix for this just a workaround?  My implementation is the following,

    public override async ValueTask OnCreateAsync(HttpContext context,
        IRequestExecutor requestExecutor, IQueryRequestBuilder requestBuilder,
        CancellationToken cancellationToken)
    {
        var authorizationHeader = context.Request.Headers[HeaderNames.Authorization];
        if (!string.IsNullOrEmpty(authorizationHeader))
        {
            var result = await context.AuthenticateAsync(GeneralConstants.BearerScheme);
            
            if (result.Succeeded)
            {
                context.User = result.Principal;
            }
        }
        await base.OnCreateAsync(context, requestExecutor, requestBuilder,
            cancellationToken);
    }

**Comment by Hareshraman** [comment]
Hi @michaelstaib , We have multiple authentication schemes , let's say 4-5 are registered in the startup,and depending on the claims it consists we determine if the JWT tokens are valid .In REST, we are able to use Attributes in the controllers, and ensure the controller is allowed access if any of the authentication schemes pass.
In the example below
```
public class SomeController {
[Attribute1] //authentication attribute 1
[Attribute2] //authentication attribute 2
public async Task<IActionResult> DoSomething(){
//Return actionResult
  }
}
```
If any of the attribute authenticateAsync passes or if authenticateResult is successful then we say the methods in the controller will have access. 
Are interceptors the only way to authenticate ? multiple schemes as of today ? 
What about authorization ? if i were to use my own custom schemes ? 
This would help us identify better ways,
