### ISSUE TITLE
Specify OAuth flow configuration for BCP

### ISSUE THREAD

**Issue by Temppus** [ChilliCream/graphql-platform#5795]
### Product

Banana Cake Pop

### Is your feature request related to a problem?

Correct me if I am wrong but currently there is no way to specify OAuth configuration that should BCP use in UI. Only thing that is possible to set are headers

```
        endpoints.MapGraphQL().WithOptions(new GraphQLServerOptions()
        {
            Tool =
            {
                HttpHeaders = new HeaderDictionary()
                {
                    {"aaa", "bbb"}
                }
            }
        });
```
In swagger there is possibility to specify those OAuth URLs so user do not need to know them and can use oauth flow. Is it possible or planned to add this URLs to configuration same as headers probably ?

![image](https://user-images.githubusercontent.com/827991/217239913-2d73700e-f14b-433d-8f96-71b3e4d73743.png)

### The solution you'd like

New Authorization property at same levels as `Tool` for Authorization where backend could specify OAuth flow URLs that BCP would respect if used.

**Comment by Hanskrogh** [comment]
Would be really nice to have this feature!. You even have to set all configuration each time you open a new document...

**Comment by PascalSenn** [comment]
@Hanskrogh  In the newest version of BCP you can now create APIs that share the connection information. Check out https://eat.bananacakepop.com :)
