### ISSUE TITLE
Change schema source used by BCP

### ISSUE THREAD

**Issue by Temppus** [ChilliCream/graphql-platform#5806]
### Product

Banana Cake Pop

### Is your feature request related to a problem?

Is there possibility for BCP to use ?sdl GET endpoint for schema fetching instead of getting schema by introspection ?
I am asking because when authorization is enabled I would like to have schema available even when user is not authorized yet. Currently we have authorization on Query itself and thus schema can not be fetched before auth.

It seems like we could workaround it by defining authorization for each query root node explicitly and then schema can be fetched, but it would ne nicer if we could specify this GET endpoint which is not guarded by authorization without modifying our code.

### The solution you'd like

Have a way to specify schema endpoint to use by BCP ideally somewhere in GraphQLToolOptions.

**Comment by michaelstaib** [comment]
We are working on this.

**Comment by artola** [comment]
@michaelstaib Tracked in BCP backlog.
