### ISSUE TITLE
Parallel execution of mutations

### ISSUE THREAD

**Issue by mjr27** [ChilliCream/graphql-platform#5807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Mutations in v13 are executed in paralled, whil GraphQL specification clearly states: https://graphql.org/learn/queries/#multiple-fields-in-mutations

 > While query fields are executed in parallel, mutation fields run in series, one after the other.

### Steps to reproduce

Here is a minimal  reproducible example.

GraphQL:
```gql
mutation {
  a: do
  b: do
}
```

Code:
```csharp
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddGraphQLServer()
    .AddQueryType<Queries>()
    .AddMutationType<Mutations>();
var app = builder.Build();

app.MapGraphQL();
app.Run();

public class Mutations
{
    private readonly ILogger<Mutations> _logger;

    public Mutations(ILogger<Mutations> logger)
    {
        _logger = logger;
    }

    public async Task<bool> Do()
    {
        _logger.LogWarning("BEGIN");
        await Task.Delay(100);
        _logger.LogError("/END");
        return true;
    }
}

public class Queries
{
    private readonly ILogger<Queries> _logger;

    public Queries(ILogger<Queries> logger)
    {
        _logger = logger;
    }

    public async Task<bool> Get()
    {
        _logger.LogWarning("Q");
        await Task.Delay(100);
        _logger.LogError("/Q");
        return true;
    }
}
```

### Relevant log output

```shell
Expected output:
BEGIN
/END
BEGIN
/END

Actual output:

BEGIN
BEGIN
/END
/END
```

### Version

13.0.0

**Comment by tobias-tengler** [comment]
What is the query you sent to your request?

Is it:

```graphql
mutation {
  a: do
  b: do
}
```

**Comment by mjr27** [comment]
Yes, exactly that, my bad

**Comment by tobias-tengler** [comment]
@michaelstaib this seems like a major breaking change. Can you verify this also?

**Comment by michaelstaib** [comment]
This would be a major bug in the execution engine.

**Comment by michaelstaib** [comment]
I can confirm the issue. Still looking for the cause and why our test did not catch it.
