### ISSUE TITLE
Where is IHttpResultSerializer

### ISSUE THREAD

**Issue by marekbomber** [ChilliCream/graphql-platform#5812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I can't find the interface the `IHttpResultSerializer `and extension  I`ServiceCollection AddHttpResultSerializer` in version 13.
What happened to them or what were they replaced with? `DefaultHttpResponseFormatter` ?
There is no information about this in the documentation.

### Steps to reproduce

1

### Version

13.0.0

**Comment by tobias-tengler** [comment]
You are correct about the DefaultHttpResponseFormatter. I'm trying to add some documentation over the weekend.

**Comment by tobias-tengler** [comment]
The migration guide is now here: https://github.com/ChilliCream/graphql-platform/blob/a2a82c63027ce20623da1bbf01d286ade7278df1/website/src/docs/hotchocolate/v13/migrating/migrate-from-12-to-13.md#ihttpresultserializer

I'll also document the formatter over the coming days.
