### ISSUE TITLE
setting socket keepalive interval

### ISSUE THREAD

**Issue by randyridge** [ChilliCream/graphql-platform#5822]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

The default websocket keepalive interval has changed in hc13 from 5 seconds to some value that's larger (offhand I don't recall what it is), to override the new default interval I attempted:

`
app.UseWebSockets(new WebSocketOptions {
  KeepAliveInterval = TimeSpan.FromSeconds(5),
});
`

This seems to have no effect.

Michael pointed me to:

`
endpoints.MapGraphQL().WithOptions(new GraphQLServerOptions {
  Sockets = {
    KeepAliveInterval = TimeSpan.FromSeconds(5)
});
`

Which does appear to work, however, he thinks the first should work as well, so at his request I'm opening this bug.

-- edit
it occurs to me, in case it matters, that the order of app.UseWebSockets() comes before endpoints.MapGraphQL() in our application.

### Steps to reproduce

I verified using an existing browser client's devtools and watching the keepalive messages against my local dev server with both configurations listed above.

### Version

13.0.2

**Comment by michaelstaib** [comment]
This one is done 13.0.4
