### ISSUE TITLE
"The Strawberry Shake code generation requires .NET SDK 6 or .NET SDK 7 to work" error when using preview version of .NET

### ISSUE THREAD

**Issue by Mephistofeles** [ChilliCream/graphql-platform#5823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

There is a bug in StrawberryShake.Server.targets resulting in incorrect error "The Strawberry Shake code generation requires .NET SDK 6 or .NET SDK 7 to work." when using preview version of .NET, for example dotnet version returning:
7.0.200-preview.22628.1
It can't be parsed by Version.TryParse and DotNetMajor does not return correct major version.

### Steps to reproduce

1. Install preview version of .NET 6 or 7
2. Try to build project using StrawberryShake.Server
3. Build results in error : The Strawberry Shake code generation requires .NET SDK 6 or .NET SDK 7 to work.

### Version

13.0.2

**Comment by sunghwan2789** [comment]
For reference, 13.0.0-rc4 works even if I use the preview version of .NET SDK.

**Comment by michaelstaib** [comment]
RC4 was pinned to SDK 6. If you had non installed it would not work.

I will put this on the next patch build. 

Thanks for reporting this.

**Comment by sunghwan2789** [comment]
I think this can be handled with https://learn.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2022#msbuild-version-comparison-functions

**Comment by glen-84** [comment]
Closing. This was likely fixed by #6012.
