### ISSUE TITLE
Intermitted InvalidCastException in HotChocolate pipeline during error reporting

### ISSUE THREAD

**Issue by Andrej-Peplinski** [ChilliCream/graphql-platform#5825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

During testing we find that HotChocolate (v.13.0.0 and v.13.0.2) throw an InvalidCastException when reporting errors (see screenshot). Unfortunately the error does not occur repeatably but only once in a while. I have therefore attached a [dump file](https://drive.google.com/drive/folders/1S4i3wYIXAdX9Lk7jPobK4jL1ErLiTWrU?usp=sharing) for further analysis. Please ping me if you need further information.

![image](https://user-images.githubusercontent.com/44775468/218142106-35a7382d-b7c9-4417-9270-36c15ddae1d4.png)

### Steps to reproduce

1. Suggest to do dump analysis
2. 

### Version

13.0.2

**Comment by Andrej-Peplinski** [comment]
BTW, I forgot to mention that the [dump file](https://drive.google.com/drive/folders/1S4i3wYIXAdX9Lk7jPobK4jL1ErLiTWrU?usp=sharing) was taken on a Windows machine using the VS save dump command. If for some reason you cannot analyze it on your Mac then please let me know and I can try to provide other information.

**Comment by michaelstaib** [comment]
This issue is bugging me :) Thanks for your help with the informations you provided.

**Comment by prodrammer** [comment]
@michaelstaib It appears to be the same error mentioned in #5400.

**Comment by RobinVangampelaere** [comment]
Any updates on this? We are finding the same results. Using package version 13.0.5.

An extra piece of information is that we are using the 'OnError'-method from the IErrorFilter-filter. This method executes two times. Once with the correct IError and immediately after that a second time with the error: 'Exception: Unable to cast object of type 'RootPathSegment' to type 'HotChocolate.IndexerPathSegment'.'

Any updates on this would be appreciated.

**Comment by sergiu-enache** [comment]
I can confirm seeing the same logs once in a while in production for mutations, using package version 13.0.5.

**Comment by Andrej-Peplinski** [comment]
The same problem has also been mentioned on the slack channel by Peter Simon: https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1683547149505519

**Comment by RobinVangampelaere** [comment]
Do you happen to have any updates on this? This bug is preventing us from upgrading to v13.

**Comment by bcherniakh** [comment]
Facing the same issue in production.

**Comment by onionhammer** [comment]
Happening here as well

**Comment by onionhammer** [comment]
I'm getting this a lot now, is there any workaround for this? A pattern I can avoid?

**Comment by SivkovSavely** [comment]
we upgraded to the version 13 (from 12) and started getting the same exception

is there any workaround?

**Comment by michaelstaib** [comment]
This is fixed on my internal branch ... I have moved it to the next dot release 13.5.

**Comment by michaelstaib** [comment]
Needs a bit more testing though :)

**Comment by onionhammer** [comment]
Any update on this one?

**Comment by michaelstaib** [comment]
This is fixed

**Comment by michaelstaib** [comment]
in 13.5.0-preview.21
