### ISSUE TITLE
Directive types for validations attributes do not work anymore

### ISSUE THREAD

**Issue by erwan-joly** [ChilliCream/graphql-platform#5828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Hello there, since I updated to HotChocolate 13 I'm getting this error at startup. 
I'm aware there are changes around directives. 

What I'm trying to achieve here is to get directives for my validation attributes so my frontend can generate yup(frontend validation) for those. 

Not sure if that's the best way to achieve such a thing but I'm relying on the method I explained there: https://medium.com/@erwanjoly_55953/hotchocolate-graphql-validation-with-validationattribute-yup-373e830dd547

only difference is that I had to replace 
```
var typeref = completionContext.TypeInspector.GetTypeRef(attribute.GetType());
field.Directives.Add(new DirectiveDefinition(attribute, typeref));
```
by
```
field.AddDirective(attribute, completionContext.TypeInspector);
```
I'm pretty sure it's irrelevant as I get the same error without the interceptor.

Now I upgraded to 13.0.2 I'm getting an error. Is there anyway way to solve this ?

### Steps to reproduce

Declare a directive type from EmailAddressAttribute
```
    public class EmailAddressDirective : DirectiveType<EmailAddressAttribute>
    {
        protected override void Configure(IDirectiveTypeDescriptor<EmailAddressAttribute> descriptor)
        {
            descriptor.Name("emailAddress");
            descriptor.Location(DirectiveLocation.InputFieldDefinition | DirectiveLocation.ArgumentDefinition | DirectiveLocation.FieldDefinition);
            descriptor.Ignore(dt => dt.RequiresValidationContext);
            descriptor.Ignore(dt => dt.ErrorMessageResourceName);
            descriptor.Ignore(dt => dt.CustomDataType);
        }
    };
```

### Relevant log output

```shell
System.InvalidOperationException : No compatible constructor found for input type type `System.ComponentModel.DataAnnotations.EmailAddressAttribute`.
    Either you have to provide a public constructor with settable properties or a public constructor that allows to pass in values for read-only properties. There was no way to set the following properties: dataType.
```

### Version

13.0.2

**Comment by michaelstaib** [comment]
Can you post the class `EmailAddressAttribute`

**Comment by 0Lucifer0** [comment]
Sure, It is a Microsoft class : https://github.com/microsoft/referencesource/blob/master/System.ComponentModel.DataAnnotations/DataAnnotations/EmailAddressAttribute.cs

**Comment by erwan-joly** [comment]
Sure, It is a Microsoft class : https://github.com/microsoft/referencesource/blob/master/System.ComponentModel.DataAnnotations/DataAnnotations/EmailAddressAttribute.cs

**Comment by erwan-joly** [comment]
@michaelstaib could this be the same as https://github.com/ChilliCream/graphql-platform/pull/5844 ?

**Comment by michaelstaib** [comment]
So, this will no longer work, as we aligned the way we format and parse the runtime value with input objects.

How does your directive work? do you have a middleware?

**Comment by michaelstaib** [comment]
Skimmed through your blog. So, understand now what you are doing.

**Comment by erwan-joly** [comment]
Any good way to expose validation attribute as directives ?

**Comment by atykhyy** [comment]
> @michaelstaib could this be the same as #5844 ?

No, that's a simple targeted fix only for structs. In your case, since your directive targets only definitions, it does not need a constructor - HC won't have occasion to create instances of `EmailAddressAttribute` from queries. Presumably you will be adding instances of `EmailAddressAttribute` to types as directives to decorate the SDL schema. Try this:
```
public class EmailAddressDirective : ...
{
    protected override DirectiveTypeDefinition CreateDefinition (ITypeDiscoveryContext context)
    {
        var definition = base.CreateDefinition (context) ;
        definition.CreateInstance = _ => throw new NotImplementedException () ;
        return definition ;
    }
}
```
I don't know enough to say if it would be a good idea to make this the default, i.e. to stub out a directive's `CreateInstance` when it has only `XyzDefinition` schema locations.

**Comment by michaelstaib** [comment]
I would not do that, this could have implications when the directive instance is created.

@erwan-joly can you create a small demo project so i can play with your setup?

**Comment by erwan-joly** [comment]
> I would not do that, this could have implications when the directive instance is created.
> 
> @erwan-joly can you create a small demo project so i can play with your setup?

Should have a demo project ready in the next day or so

**Comment by erwan-joly** [comment]
@michaelstaib here a small demo project https://github.com/erwan-joly/HC13BugRepro it only generate the schema to show the error (doesn't actually run a graphqlServer but should be easy to add if required)

**Comment by michaelstaib** [comment]
It really amazes me in all our interactions how deep you have drilled into Hot Chocolate @atykhyy! Especially since most of this is not documented :D

**Comment by michaelstaib** [comment]
Can this be closed?

**Comment by erwan-joly** [comment]
Thanks @atykhyy seems to works fine :)
