### ISSUE TITLE
Nuget packages missing for StrawberryShake.CodeGeneration.CSharp and StrawberryShake.CodeGeneration for any v13 release

### ISSUE THREAD

**Issue by cornonthecobb** [ChilliCream/graphql-platform#5831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

Was gettting a lot of bugs from the Generated Strawberry Shake client using the version 13 process. Turns out cause the nuget packages havent been updated it was using the v12 code generation nuget package. This results in the generated code using all the old namespaces as v13 changed them. I manually compiled the source code and extracted the dlls and was able to get it to work properly. Is there an ETA when the version 13 packages could be uploaded?

### Steps to reproduce

1. Follow the exact instructions for v13 strawberry shake getting started.

### Version

13.0.2

**Comment by PascalSenn** [comment]
Hi @cornonthecobb 

The migration guide for this is still missing, but we added a bunch of new meta packages that avoid common mistakes that are often done. 

Have a look at this:
https://chillicream.com/blog/2023/02/08/new-in-hot-chocolate-13#strawberry-shake

**Comment by cornonthecobb** [comment]
Thank you. Guess the documentation hasnt caught up yet. Saved me a lot of headache answering so quickly.

**Comment by DominicMaas** [comment]
@PascalSenn Hey, what do you guys recommend for app types not supported in these meta packages (in my case, a WinUI3/WinAppSDK application). Just `StrawberryShake.Server`? What's this talk of a "client store"? I assume for caching?

**Comment by michaelstaib** [comment]
Depends on the application type ...

Probably the maui setup should work well for you.

**Comment by michaelstaib** [comment]
> What's this talk of a "client store"? I assume for caching?

The client store allows client components to subscribe to data.... meaning if you change data anywhere all subscribed components are updated.
