### ISSUE TITLE
Explicit IdType of non-nullable argument creates not-required value in schema

### ISSUE THREAD

**Issue by DanielRose** [ChilliCream/graphql-platform#5836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

After upgrading to Hot Chocolate v13, I noticed that my arguments of type ID were marked as not required in the schema. I am using the annotation-based variant, in a nullable-enabled project.

After a bit of testing, the problem is the `[GraphQLType(typeof(IdType))]` annotation. Even though the arguments are non-nullable, the generated schema marks them as optional, and gives a null value (or an empty Guid) at runtime if the argument is missing. Only if I add the `[GraphQLNonNullType]` annotation is the schema correct.

### Steps to reproduce

Create a query type with the following queries:

```cs
#nullable enable
[QueryType]
public class Query
{
	public string GetGuid(Guid id) => "Ok";
	public string GetString(string id) => "Ok";

	public string GetGuidId([GraphQLType(typeof(IdType))] Guid id) => "Ok";
	public string GetStringId([GraphQLType(typeof(IdType))] string id) => "Ok";

	public string GetGuidIdNonNull([GraphQLNonNullType] [GraphQLType(typeof(IdType))] Guid id) => "Ok";
	public string GetStringIdNonNull([GraphQLNonNullType] [GraphQLType(typeof(IdType))] string id) => "Ok";
}
```

This results in a schema of

```
type Query {
  guid(id: UUID!): String!
  string(id: String!): String!
  guidId(id: ID): String!
  stringId(id: ID): String!
  guidIdNonNull(id: ID!): String!
  stringIdNonNull(id: ID!): String!
}
```

As you can see, the argument "id" is not required in `guidId(id: ID)` and `stringId(id: ID)`. _Correct would be to have the id argument as required._

When running a query against this, and setting a breakpoint at the resolvers, the value of id is `Guid.Empty` for `GetGuidId` and `null` for `GetStringId`. _Both values are very broken. A null string value for a non-nullable string argument can easily cause NullReferenceExceptions, while a Guid.Empty can cause various strange problems, depending on the implementation._

### Version

13.0.2

**Comment by tobias-tengler** [comment]
That's actually the correct behavior. As soon as you specify a  GraphQLType explicitly, it's up to you to specify the _correct_ type (and nullability). In your case you can either use `[GraphQLType<NonNullType<IdType>>]` or the `[ID]` attribute, which should respect the nullability of the underlying .NET type.

**Comment by DanielRose** [comment]
@tobias-tengler I checked again, and I was sure it was different in v12. But you are right, it was the same there.

The documentation is a bit lacking there, however. There is no link between [explicit types](https://chillicream.com/docs/hotchocolate/v13/defining-a-schema/object-types#explicit-types) and [explicit nullability](https://chillicream.com/docs/hotchocolate/v13/defining-a-schema/non-null/#explicit-nullability). Note that this is not only needed for an explicit ID-type, but also for custom scalars (including the built-in ones from `HotChocolate.Types.*`).
