### ISSUE TITLE
CollectionSegmentType<T> and CollectionSegmentCountType<T> missing in 13.x?

### ISSUE THREAD

**Issue by EvilVir** [ChilliCream/graphql-platform#5839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I'm trying to move our current codebase to Hot Chocolate 13.x line and I just can't find output types for CollectionSegments.

We have custom pagination logic and in 12.x we created our resolvers in a following way:

```
[GraphQlType(typeof(CollectionSegementCountType<MyEntityType>))]
public Task<CollectionSegment<MyEntity>> GetPagedEntity()
{
}
```

It worked perfectly - our resolver returned domain models which then were automapped by Hot Chocolate to API DTOs behind the scenes. Currently it looks like I need to remake CollectionSegmentCountType<T> on my own to achieve same behavior? Or these types are somewhere there but moved to other library/namespace (I searched for them but no luck).

### Steps to reproduce

1. Create Hot Chocolate 13.x project
2. Try to find `CollectionSegmentType<T>` and/or `CollectionSegmentCountType<T>` output type class.

### Version

13.0.2

**Comment by EvilVir** [comment]
@tobias-tengler `UserOffsetPaging` looks promising (althrough I didn't found generic version and had to use `UseOffsetPaging(typeof())` approach) but documentation it creates isn't exactly as I need it to be:

```
		[UseOffsetPaging(typeof(NonNullType<FormDefinitionType>))]
		public Task<CollectionSegment<FormDefinition>> GetFormDefinitions([Service] IFormDefinitionsRepository formDefinitionsRepository, FormDefinitionFilterInput[]? filterBy, FormDefinitionSortInput[]? sortBy, LimitInput? limitBy)
			=> formDefinitionsRepository.GetPage(filterBy, sortBy, limitBy).ToCollectionSegment();
```

Results in:

```
FormDefinitions(skip: Int take: Int filterBy: [FormDefinitionFilterInput!] sortBy: [FormDefinitionSortInput!] limitBy: LimitInput): FormDefinitionsCollectionSegment
```

(Note the missing bang at the end, indicating that there always will be some kind of output).

This is common issue I found in Hot Chocolate and I get it it's because it's almost impossible to get proper nullability info via .NET's reflection, that's why I opted for explicitly using [GraphQLType] annotations across the board, to ensure that docs and constraints on the API level are exactly as I need them. And that brings us back to why I need `CollectionSegmentType<T>` available :)

For now I wrote my own replacement and I'm good to go, but consider bringing it back for these few edge cases :)

**Comment by tobias-tengler** [comment]
If you just want to make the field type non-null, instead of replicating the internals, you could just create an attribute that does what you want:

```csharp
[AttributeUsage(AttributeTargets.Method | AttributeTargets.Property)]
public class ExampleAttribute : ObjectFieldDescriptorAttribute
{
    protected override void OnConfigure(IDescriptorContext context,
        IObjectFieldDescriptor descriptor, MemberInfo member)
    {
        descriptor.Extend()
            .OnBeforeCreate((context, definition) =>
            {
                if (definition.Type is SyntaxTypeReference typeReference)
                {
                    definition.Type = typeReference.With(
                        new NonNullTypeNode((INullableTypeNode)typeReference.Type),
                        typeReference.Context,
                        typeReference.Scope,
                        typeReference.Factory);
                }
            });
    }
}
```

You could even automate this using a type interceptor.

I would be really careful with non-null though. The CollectionSegments and Connections being nullable is a good thing. Non-null is bad for evolvability and null-propagation can also be really bad, depending on what you're doing. You don't want to erase the entire user data, just because the friends connection on that user couldn't be resolved for example (in most cases). You are better of just handling the errors / nulls in your client. Client's like Relay.js provide better ways of dealing with missing data and the resulting UI states, using something like `@required` for example.

**Comment by EvilVir** [comment]
Sorry, but I don't agree. I can't see any imaginable scenario where CollectionSegment can be null. CollectionSegment is, as name says, chunk of some collection. If that collection is empty then that chunk is of zero length but is still there (and carries that information of source being empty in `TotalCount`, `HasPrevious` and `HasNext` fields). If that collection can be non-existent, then I would consider nullable CollectionSegment OR maybe throw an exception/return an error about this fact, but intention of pagination is that consumer wants to fetch part of collection AND info about it. Info about it always exists, even if collection doesn't.

As for connection - we're not using them (opted for offset pagination) but even with them I still thing CollectionSegment carries more informations than just list of edges, and therefore should always be there.

But, that's just my take probably biased by the requirements and facts about system I work currently on :)

Thanks for that example attribute tho, helped solve me other problem :)

**Comment by tobias-tengler** [comment]
If you return an empty collection in the case of an error, you are lying to your client. There was an error, but your client doesn't know about the error and a user would assume there are no items. Surfacing the error and marking the connection null is, in my opinion, the only correct way to deal with the scenario. But as you said your requirements might dictate something else.

**Comment by EvilVir** [comment]
If there was an error then yes, an error shall be returned. Or in that case there I would use nullable CollectionSegment. But if collection is *always* there then I opt for non-nullable CollectionSegment with non-nullable items. For example:

`CollectionSegment[MyEntity]` doesn't make any sense, because it says to the consumer that following is possible:

```
{
    "items": [
        { /** Some item */ },
        null,
        { /** Some other item */ },
    ]
}
```

That null doesn't make any sense there IMHO because it's impossible to know which edge or item it relates to. So in any `CollectionSegment<T>` T is either there or not, there's no "it's there but not really" state that `null` value could represent. I might me item of some another type in which then relation to user is null but still item will be there or not.

And as for `CollectionSegment` being nullable, it makes possible situation where consumer asks for chunk A to B and gets null. Not very useful, no error (eg: "collection you try to reach doesn't exist") nor info like "collection you try to reach is empty".

Im curious tho about that example you mentioned with deleting too much with non-nullable segment/edge. Can you post some example, please? It might be something I just didn't yet encountered so would be nice to know what to pitfalls there are waiting for me :)

**Comment by tobias-tengler** [comment]
The keyword you're looking for is error propagation. Let's imagine a schema like

```graphql
type Query {
  user: User
}

type User {
  id: ID
  name: String
  friends: FriendsCollectionSegment!
}
```

Notice how `friends` is non-null. If we send a request like

```graphql
{
  user {
    name
    friends {
      # ...
    }
  }
}
```

and `friends` throws an error. Now the field needs to be nulled out. But it's non-null, so the error needs to bubble up to the nearest nullable field, in this case `user`. So you would end up with a response like:

```json
{
  "data": {
    "user": null
  }
}
```

The bubbling of the `friends` error has erased the user data such as `name` by throwing an error and being non-null. If you think of a client application this is really bad. The user profile with the name could've been displayed and only the friends section could've highlighted an error. Now there is no data to go off - for no reason.
It gets even better if we imagine user is also non-null. Now the null would have to bubble up to the `data` field, erasing all data you requested in the process - yikes.

That's why I'm saying be really careful and use non-null sparingly.

**Comment by EvilVir** [comment]
Hm, ok this is a valid problem that originates from language limitation. I think in that case clean option would be to still define field as non-nullable but in case of error actually set it to null value (eg. stop propagation/response erasure). I can see you roll your eyes now lol :D But hear me out: in case of any error the "errors" array is present in the response and each such error has path property.

Client could easily and automagically do a sanity check with that and at the same time we don't loose any documentation/contract details - under normal operation, that field will never be null. Extraordinary situation like error can be also gracefully supported.

Still, thanks for the example, that's something important to keep in mind.
