### ISSUE TITLE
[CS7069] Reference to type 'IRequestExecutorBuilder' claims it is defined in 'HotChocolate.Execution', but it could not be found

### ISSUE THREAD

**Issue by raghavareddykv** [ChilliCream/graphql-platform#5841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Unable to build project after upgrading the HotChocolate to 13.0.2. Getting an error 
**Reference to type 'IRequestExecutorBuilder' claims it is defined in 'HotChocolate.Execution', but it could not be found**

Checked everything in the project, and looked into the DLLs. IRequestExecutorBuilder is located in HotChocolate.Execution.Configuration in HotChocolate.Execution.Abstractions package.

### Version

13.0.2

**Comment by tobias-tengler** [comment]
You probably didn't upgrade all of the HotChocolate.* packages in your project to the same version. That's when these kind of errors appear.
Going to close this, but feel free to re-open if that's not the case :)
