### ISSUE TITLE
Source generator for DataLoader does not handle nullable TValue for classes

### ISSUE THREAD

**Issue by DanielRose** [ChilliCream/graphql-platform#5842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

This is based on the information of ticket #2911. According to https://github.com/graphql/dataloader, it is valid to return null values for IDs which could not be loaded.

The Hot Chocolate DataLoaderBase always returns the `TValue` directly for `LoadAsync`. The suggestion from the ticket is to define a type of TValue which includes the null value, if a DataLoader would possibly return that value (https://github.com/ChilliCream/graphql-platform/issues/2911#issuecomment-764440918).

However, when using the source generator, it ignores a nullable TValue (but only for classes). Instead, it creates a DataLoader with the (non-null) inner type of the TValue. Note that if I duplicate the generated code, I get a CS8603 build error, but apparently this is ignored for generated code.

### Steps to reproduce

1. Add the Hot Chocolate source generator
2. Create a DataLoader function returning a nullable class, for example:

```cs
[DataLoader]
internal static async Task<string?> GetNullableString(string id) => null;
```

3. The generated DataLoader has a non-nullable TValue:

```cs
public sealed class NullableStringDataLoader : global::GreenDonut.CacheDataLoader<string, string>, INullableStringDataLoader
{
    private readonly global::System.IServiceProvider _services;

    public NullableStringDataLoader(
        global::System.IServiceProvider services,
        global::GreenDonut.DataLoaderOptions? options = null)
        : base(options)
    {
        _services = services ??
            throw new global::System.ArgumentNullException(nameof(services));
    }

    protected override async global::System.Threading.Tasks.Task<string> LoadSingleAsync(
        string key,
        System.Threading.CancellationToken ct)
    {
        return await Foo.GetNullableString(key).ConfigureAwait(false);
    }
}
```

4. As comparison, create a DataLoader function returning a nullable struct, for example:

```cs
[DataLoader]
internal static async Task<int?> GetNullableInt(string id) => null;
```

5. The generated DataLoader has the correct TValue:

```cs
public sealed class NullableIntDataLoader : global::GreenDonut.CacheDataLoader<string, int?>, INullableIntDataLoader
{
    private readonly global::System.IServiceProvider _services;

    public NullableIntDataLoader(
        global::System.IServiceProvider services,
        global::GreenDonut.DataLoaderOptions? options = null)
        : base(options)
    {
        _services = services ??
            throw new global::System.ArgumentNullException(nameof(services));
    }

    protected override async global::System.Threading.Tasks.Task<int?> LoadSingleAsync(
        string key,
        System.Threading.CancellationToken ct)
    {
        return await Foo.GetNullableInt(key).ConfigureAwait(false);
    }
}
```

### Version

13.0.2

**Comment by michaelstaib** [comment]
The issue why this is happening is because the there is no nullable string. Its just an annotation, whereas the nullable int is an actual type `Nullable<int>`.

We will have a look at it.

**Comment by DanielRose** [comment]
In my actual code, obviously I am not using string, but actual GraphQL object types, such as `User?`

**Comment by anadale** [comment]
I would like to support this request, since I have to introduce extension method just to throw in nullability and it looks really weird. I'm sure it'll be much better to have it out of the box, since DL generation is really a great feature.
