### ISSUE TITLE
🐛 Conflicting dotnet new templates

### ISSUE THREAD

**Issue by danielmackay** [ChilliCream/graphql-platform#5846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

HotChocolate provides 2 sets of templates that can be used with `dotnet new`.  If these are both installed they conflict with each other

### Steps to reproduce

Run the following commands:

1. `dotnet new install HotChocolate.Templates`
2. `dotnet new install HotChocolate.Templates.Server`
2. dotnet new graphql

You will see the following error: 
![image](https://user-images.githubusercontent.com/2636640/219192317-c4af7e0f-bdf3-40c7-8708-141a8785e02b.png)

Either the template should have unique template names, or one of these template packages should be deprecated.

### Version

13.0.0

**Comment by michaelstaib** [comment]
```
dotnet new install HotChocolate.Templates.Server
```

is the legacy templates ... we are keeping them around for people who have installed them but they are no longer updated.

Use the newer package if you can.

```
dotnet new install HotChocolate.Templates
```

**Comment by michaelstaib** [comment]
@PascalSenn @tobias-tengler should we deprecate the old one?
