### ISSUE TITLE
Cursor type should not be fixed to a String.

### ISSUE THREAD

**Issue by jkporter** [ChilliCream/graphql-platform#5847]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Per the spec the "cursor type" is a type that serializes as a String may be a String, a Non-Null wrapper around a String, a custom scalar that serializes as a String, or a Non-Null wrapper around a custom scalar that serializes as a String.

### The solution you'd like

Allow relay pagination arguments (after, before) and edge cursor field to be of any type that serializes to a string. Where done by tooling convert "cursor type" to String representation and set the PageInfo's startCursor and endCursor fields which are exclusively of type String.

**Comment by michaelstaib** [comment]
Can you provide you use case for this?

**Comment by jkporter** [comment]
Beyond the academic spec compliance in some scenarios I use GraphQL not just for over Web but for server-to-server and as an IPC method between applications or services. In my work data and cursors specifically can be large and are best represented by a binary representation. In those situations, I like to use an alternate serialization such as CBOR that supports binary without a need to encode that data as a string (base64) unnecessarily increasing size and overhead.

**Comment by michaelstaib** [comment]
OK ... you talk about the runtime format. But that can be anything. Can you post some code?

**Comment by michaelstaib** [comment]
The IEdge represent the serialization format ... so what your internal implementation is, is not our concern. Do whatever cursor style you want. If you provide some code we might be able to guide you where you are stuck. The spec is honored by HC in that regard.
