### ISSUE TITLE
DefaultHttpResultSerializer not available in 13

### ISSUE THREAD

**Issue by SniC** [ChilliCream/graphql-platform#5849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

After upgrading from version 12 to 13, the DefaultHttpResultSerializer class seems to be gone as well as the startup registration method to register a custom HttpResultSerializer. Documentation doesn't seem to be updated to reflect this change as well.

See: https://chillicream.com/docs/hotchocolate/v13/api-reference/aspnetcore/#serialization

Is there a different method in version 13 to write a custom serializer? The serializer we wrote in version 12 was used to change the response http status code based on authorization errors.

### Steps to reproduce

No real way to replicate it except trying to implement a custom HttpResultSerializer is now wrongly documented.

### Version

13.0.2

**Comment by tobias-tengler** [comment]
It's not yet live on the website, but you can check out the updated migration guide here: https://github.com/ChilliCream/graphql-platform/blob/9746a5a785589fbdb12e5081d3c2caaa01d0472b/website/src/docs/hotchocolate/v13/migrating/migrate-from-12-to-13.md#ihttpresultserializer

Hope that helps :)
