### ISSUE TITLE
StrawberryShake.CodeGeneration.CSharp.Analyzers in version 13

### ISSUE THREAD

**Issue by jorrit** [ChilliCream/graphql-platform#5855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

It seems `StrawberryShake.CodeGeneration.CSharp.Analyzers` is not available for StrawberryShake version 13. Is this intended? If so, how should I setup source generation in version 13?

### Steps to reproduce

1. Update a StrawBerry Shake app with `StrawberryShake.CodeGeneration.CSharp.Analyzers` 12.17.0 to v13.

### Version

13.0.2

**Comment by michaelstaib** [comment]
Is gone ... to migrate remove ALL packages from Strawberry Shake and add one of the following:

- StrawberryShake.Server
- StrawberryShake.Blazor
- StrawberryShake.Maui

**Comment by tobias-tengler** [comment]
I think I'm going to add a migration guide to Strawberry Shake as well... 😅
