### ISSUE TITLE
Issues with stream and defer in v 13

### ISSUE THREAD

**Issue by amirHosseinKhademii** [ChilliCream/graphql-platform#5856]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I have migrated to v13 and i am using react relay for the client and sending this request :

`{"query":"query TodosQuery(\n  $before: String\n  $after: String\n  $first: Int\n  $last: Int\n) {\n  ...TodosFragment\n}\n\nfragment TodosFragment on Query {\n  todos(before: $before, after: $after, first: $first, last: $last) {\n    ... @defer(label: \"TodosFragment$defer$List__todos$pageInfo\") {\n      pageInfo {\n        hasNextPage\n        endCursor\n        hasPreviousPage\n        startCursor\n      }\n    }\n    edges @stream(label: \"TodosFragment$stream$List__todos\", initial_count: 2) {\n      node {\n        title\n        body\n        id\n        isCompleted\n        __typename\n      }\n      cursor\n    }\n  }\n}\n","variables":{"before":null,"after":null,"first":2,"last":null}}`

but the server response is like this :

`{"errors":[{"message":"The specified operation kind is not allowed."}]}`

on the playground im not getting this error btw.

    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="HotChocolate.AspNetCore" Version="13.0.2" />
    <PackageReference Include="HotChocolate.AspNetCore.Authorization" Version="13.0.2" />
    <PackageReference Include="HotChocolate.Subscriptions.Redis" Version="13.0.2" />
    <PackageReference Include="HotChocolate.Data.MongoDb" Version="13.0.2" />
    <PackageReference Include="MongoDB.Driver" Version="2.19.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.10" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.24.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.24.0" />

### Steps to reproduce

1. 

### Version

13

**Comment by michaelstaib** [comment]
defer is by default disabled. you need to optin

**Comment by michaelstaib** [comment]
https://chillicream.com/docs/hotchocolate/v13/migrating/migrate-from-12-to-13

**Comment by amirHosseinKhademii** [comment]
I have that option enabled but still i am getting that error
```
 .AddGraphQLServer().ModifyOptions(o =>
                 {
                     o.EnableDefer = true;
                     o.EnableStream = true;
                 })
```

with that said it works on playground but not on relay

**Comment by tobias-tengler** [comment]
You are probably specifying an incompatible `Accept` header in your GraphQL request. 

If the Accept header isn't specified the browser sends `Accept: */*`, which just works in this case. If you send a different Accept header, you also need to include `multipart/mixed;charset=utf-8` for multipart responses to work in v13.

**Comment by michaelstaib** [comment]
@tobias-tengler this would be fine since would pick `multipart/mixed;charset=utf-8`.

**Comment by michaelstaib** [comment]
But on the other-hand, if you specify an explicit accept like `application/json` then we would honor it and say that we cannot fulfill your request.

**Comment by michaelstaib** [comment]
If you specify an accept other than `Accept: */*` you need to specify all the formats that you want to receive.

`Accept: application/json` and `Accept: multipart/mixed;charset=utf-8` for instance.

**Comment by amirHosseinKhademii** [comment]
Still having issue with relay:
Uncaught SyntaxError: JSON.parse: unexpected non-digit at line 2 column 2 of the JSON data[QueryResource.js:196:6](http://localhost:5173/node_modules/react-relay/lib/relay-hooks/QueryResource.js)

**Comment by tobias-tengler** [comment]
The issue is likely in your fetch function, since that's where you parse the JSON. Could you share your fetch function your Relay Environment is using?

**Comment by amirHosseinKhademii** [comment]
Yes. this is my relay enviroment:

```
const operations = (operation: RequestParameters, variables: Variables) => {
  return fetch("/graphql", {
    method: "POST",
    headers: {
      "content-type": "application/json; charset=utf-8 multipart/mixed",
      Authorization: token,
    },
    body: JSON.stringify({
      query: operation.text,
      variables,
    }),
  }).then(async (response) => {
    return response.json();
  });
};

const store = new Store(new RecordSource());

const network = Network.create(operations);


export const environment = new Environment({
  network,
  store,
});
```

**Comment by tobias-tengler** [comment]
Well this isn't fit at all to handle streamed responses... You can't do `.json()` on a multipart response. The following example should show you how to handle streamed responses: https://github.com/ChilliCream/workshops/blob/e421e4ecbce3ad4b0f958f04d36ba7297baa40c1/crypto/frontend/playground/2-screener/client/index.js#L107

Hope that helps :)

**Comment by amirHosseinKhademii** [comment]
Thanks now its working
