### ISSUE TITLE
13.0.2 Type Registration issue that works on 12.15.x

### ISSUE THREAD

**Issue by jkears** [ChilliCream/graphql-platform#5858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I migrated from 12.15.x to 13.0.2 and aside from changes to Authorization I am getting this startup  'Unable to Resolve Type Exception', however the type is registered and the same code has been running for years.  What gives??

![image](https://user-images.githubusercontent.com/1290937/219434782-6814fed7-e4cf-4613-9200-86cb52f2df11.png)

### Steps to reproduce

1. 

### Version

13.0.2

**Comment by jkears** [comment]
We would really love to move to 13 but this is a show stopper.   Any help to understand how to resolve would be greatly appreciated.  

Cheers
John

**Comment by PascalSenn** [comment]
Do you have static methods on your models?
Can you share  `ApplicationPage`?
![image](https://user-images.githubusercontent.com/14233220/219596569-a7a9f96a-a8f3-4285-8dc8-97e040f5e254.png)

**Comment by jkears** [comment]
@PascalSenn this is the model.  There are no statics defined, plus all other types being registered are defined in a similar manner.   

![image](https://user-images.githubusercontent.com/1290937/219676538-75400d8b-ae84-423e-ad1d-3032f6e9ce5f.png)

The above model has these types, code-generated, none of the related types contain static types.

![image](https://user-images.githubusercontent.com/1290937/219676902-adab1732-0281-4c1f-8a96-69d31ccf1a9a.png)

![image](https://user-images.githubusercontent.com/1290937/219677151-04bdba8d-73cd-4b25-bfc2-657c23a22d45.png)

**Comment by PascalSenn** [comment]
I dont think the problem is the Page type. I rather think that Page is used as an input somewhere and that this is now inferred and has not been inferred in v12  

Has ApplicationPage some property of type Page? 
Is ApplicationPage somewhere deliberatly used as an input or is this new?

<img width="937" alt="image" src="https://user-images.githubusercontent.com/14233220/219680545-329d563a-c20f-4689-bdbc-e0ec9eb8faf3.png">

**Comment by jkears** [comment]
@PascalSenn , thank you for your prompt support... 

Yes, 'Application' has a collection of 'ApplicationPage'  which contains a nullable 'Page' ...

![image](https://user-images.githubusercontent.com/1290937/219687036-5ea5d04a-0c74-4a52-b9b1-8616c9567c84.png)


![image](https://user-images.githubusercontent.com/1290937/219686860-51e64b8d-d122-49de-9859-598020c214bd.png)

**Comment by jkears** [comment]
I think you may be correct, as it appears we never-ever, defined ApplicationPage in our type references.  I believe there is now a much simpler way to define types in HC server registrations, is that so?

![image](https://user-images.githubusercontent.com/1290937/219687901-fb223a9f-4df6-4170-9e86-22f82ed4c7a4.png)

**Comment by jkears** [comment]
@PascalSenn we are making some head-way, thank you!  

We updated our code generator to include child types within an Aggregate-root  (such as entity, value objects) and are now adding these types to HC server at point of registration.

There are no longer any exception, at start-up, however when we attempt to query our service within BCP, it is not returning any schema. Is introspection disabled by default in HC 13.x?  Why can't we pick-up this schema?

![image](https://user-images.githubusercontent.com/1290937/219700992-0ec76e71-8b35-48ed-a1ba-37d7c0e2de45.png)

Here is the new configuration setup for HC GraphQL Server...

```
// Configure HotChocolate GraphQL Server
builder.Services.AddGraphQLServer().AddAuthorization()
.AddType<ErrorResponse>().AddType<AggregateEvent>()
.AddType<EditServicesWorkspaceSM.Workspace>().AddType<EditServicesWorkspaceSM.WorkspaceApplication>()
.AddType<EditServicesWorkspaceSM.WorkspaceDataSource>().AddType<EditServicesWorkspaceSM.WorkspaceQueryDefinition>()
.AddType<EditServicesWorkspaceSM.WorkspaceTheme>().AddType<EditServicesDataSourceSM.DataSource>()
.AddType<EditServicesApplicationSM.Application>().AddType<EditServicesApplicationSM.ApplicationPage>()
.AddType<EditServicesQueryDefinitionSM.QueryDefinition>().AddType<EditServicesAuthenticationDefinitionSM.AuthenticationDefinition>()
.AddType<EditServicesThemeDefinitionSM.ThemeDefinition>().AddType<EditServicesTemplateDefinitionSM.TemplateDefinition>()
.AddType<EditServicesPageSM.Page>().AddType<EditServicesComponentActionSM.ComponentAction>()
.AddType<EditServicesFlowSM.Flow>().AddType<EditServicesFlowSM.ParameterBindingGroup>()
.AddType<EditServicesFlowSM.ParameterBinding>().AddType<EditServicesViewComponentSM.ViewComponent>()
.AddType<EditServicesViewContainerSM.ViewContainer>().AddType<EditServicesViewEventSM.ViewEvent>()
.AddType<EditServicesViewEventSM.EventFlow>().AddType<EditServicesComponentFieldSM.ComponentField>()
.AddType<EditServicesComponentFieldSM.ClientValidator>().AddType<EditServicesRendererToolSM.RendererTool>()
.AddType<EditServicesValidatorSM.Validator>()
.AddQueryType()
.AddTypeExtension<WorkspaceGraphQLQuery>().AddTypeExtension<DataSourceGraphQLQuery>()
.AddTypeExtension<ApplicationGraphQLQuery>().AddTypeExtension<QueryDefinitionGraphQLQuery>()
.AddTypeExtension<AuthenticationDefinitionGraphQLQuery>().AddTypeExtension<ThemeDefinitionGraphQLQuery>()
.AddTypeExtension<TemplateDefinitionGraphQLQuery>().AddTypeExtension<PageGraphQLQuery>()
.AddTypeExtension<ComponentActionGraphQLQuery>().AddTypeExtension<FlowGraphQLQuery>()
.AddTypeExtension<ViewComponentGraphQLQuery>().AddTypeExtension<ViewContainerGraphQLQuery>()
.AddTypeExtension<ViewEventGraphQLQuery>().AddTypeExtension<ComponentFieldGraphQLQuery>()
.AddTypeExtension<RendererToolGraphQLQuery>().AddTypeExtension<ValidatorGraphQLQuery>()
.AddMutationType()
.AddTypeExtension<WorkspaceGraphQLMutation>().AddTypeExtension<DataSourceGraphQLMutation>()
.AddTypeExtension<ApplicationGraphQLMutation>().AddTypeExtension<QueryDefinitionGraphQLMutation>()
.AddTypeExtension<AuthenticationDefinitionGraphQLMutation>().AddTypeExtension<ThemeDefinitionGraphQLMutation>()
.AddTypeExtension<TemplateDefinitionGraphQLMutation>().AddTypeExtension<PageGraphQLMutation>()
.AddTypeExtension<ComponentActionGraphQLMutation>().AddTypeExtension<FlowGraphQLMutation>()
.AddTypeExtension<ViewComponentGraphQLMutation>().AddTypeExtension<ViewContainerGraphQLMutation>()
.AddTypeExtension<ViewEventGraphQLMutation>().AddTypeExtension<ComponentFieldGraphQLMutation>()
.AddTypeExtension<RendererToolGraphQLMutation>().AddTypeExtension<ValidatorGraphQLMutation>() 
.AddProjections()  
.AddFiltering()   
.AddSorting().RegisterDbContext<AppDbContext>(kind: DbContextKind.Pooled).PublishSchemaDefinition(c =>
{
    c.SetName("nextwareuibuildereditservices"); // The name of the schema. This name should be unique
    c.PublishToRedis("gatewayservice", sp => sp.GetRequiredService<ConnectionMultiplexer>());
}).AddInMemorySubscriptions();
```

**Comment by jkears** [comment]
It appears that BCP is throwing this exception...


![image](https://user-images.githubusercontent.com/1290937/219709278-cd2094de-b832-42fd-8ec0-dc257c54836f.png)

**Comment by jkears** [comment]
@PascalSenn , thank you as always you are very helpful!  I will endeavor to resolve the BCP issue and if still struggling will open a new issue, otherwise I think this issue has now come to a successful resolution, thanks again!

**Comment by jkears** [comment]
@PascalSenn 

This is the exception I get when querying --typename ...

![image](https://user-images.githubusercontent.com/1290937/219712853-43d99245-930e-4634-9412-2f0334b870e6.png)

**Comment by pratapkumarch** [comment]
> @PascalSenn we are making some head-way, thank you!
> 
> We updated our code generator to include child types within each Aggregate-root (such as entity, value objects) and are now adding these types to HC server at point of registration.
> 
> There are no longer any exceptions, at start-up, however when we attempt to query our service within BCP, it is not returning any schema. Is introspection disabled by default in HC 13.x? Why can't we pick-up this schema?
> 
> ![image](https://user-images.githubusercontent.com/1290937/219700992-0ec76e71-8b35-48ed-a1ba-37d7c0e2de45.png)
> 
> Here is the new configuration setup for HC GraphQL Server...
> 
> ```
> // Configure HotChocolate GraphQL Server
> builder.Services.AddGraphQLServer().AddAuthorization()
> .AddType<ErrorResponse>().AddType<AggregateEvent>()
> .AddType<EditServicesWorkspaceSM.Workspace>().AddType<EditServicesWorkspaceSM.WorkspaceApplication>()
> .AddType<EditServicesWorkspaceSM.WorkspaceDataSource>().AddType<EditServicesWorkspaceSM.WorkspaceQueryDefinition>()
> .AddType<EditServicesWorkspaceSM.WorkspaceTheme>().AddType<EditServicesDataSourceSM.DataSource>()
> .AddType<EditServicesApplicationSM.Application>().AddType<EditServicesApplicationSM.ApplicationPage>()
> .AddType<EditServicesQueryDefinitionSM.QueryDefinition>().AddType<EditServicesAuthenticationDefinitionSM.AuthenticationDefinition>()
> .AddType<EditServicesThemeDefinitionSM.ThemeDefinition>().AddType<EditServicesTemplateDefinitionSM.TemplateDefinition>()
> .AddType<EditServicesPageSM.Page>().AddType<EditServicesComponentActionSM.ComponentAction>()
> .AddType<EditServicesFlowSM.Flow>().AddType<EditServicesFlowSM.ParameterBindingGroup>()
> .AddType<EditServicesFlowSM.ParameterBinding>().AddType<EditServicesViewComponentSM.ViewComponent>()
> .AddType<EditServicesViewContainerSM.ViewContainer>().AddType<EditServicesViewEventSM.ViewEvent>()
> .AddType<EditServicesViewEventSM.EventFlow>().AddType<EditServicesComponentFieldSM.ComponentField>()
> .AddType<EditServicesComponentFieldSM.ClientValidator>().AddType<EditServicesRendererToolSM.RendererTool>()
> .AddType<EditServicesValidatorSM.Validator>()
> .AddQueryType()
> .AddTypeExtension<WorkspaceGraphQLQuery>().AddTypeExtension<DataSourceGraphQLQuery>()
> .AddTypeExtension<ApplicationGraphQLQuery>().AddTypeExtension<QueryDefinitionGraphQLQuery>()
> .AddTypeExtension<AuthenticationDefinitionGraphQLQuery>().AddTypeExtension<ThemeDefinitionGraphQLQuery>()
> .AddTypeExtension<TemplateDefinitionGraphQLQuery>().AddTypeExtension<PageGraphQLQuery>()
> .AddTypeExtension<ComponentActionGraphQLQuery>().AddTypeExtension<FlowGraphQLQuery>()
> .AddTypeExtension<ViewComponentGraphQLQuery>().AddTypeExtension<ViewContainerGraphQLQuery>()
> .AddTypeExtension<ViewEventGraphQLQuery>().AddTypeExtension<ComponentFieldGraphQLQuery>()
> .AddTypeExtension<RendererToolGraphQLQuery>().AddTypeExtension<ValidatorGraphQLQuery>()
> .AddMutationType()
> .AddTypeExtension<WorkspaceGraphQLMutation>().AddTypeExtension<DataSourceGraphQLMutation>()
> .AddTypeExtension<ApplicationGraphQLMutation>().AddTypeExtension<QueryDefinitionGraphQLMutation>()
> .AddTypeExtension<AuthenticationDefinitionGraphQLMutation>().AddTypeExtension<ThemeDefinitionGraphQLMutation>()
> .AddTypeExtension<TemplateDefinitionGraphQLMutation>().AddTypeExtension<PageGraphQLMutation>()
> .AddTypeExtension<ComponentActionGraphQLMutation>().AddTypeExtension<FlowGraphQLMutation>()
> .AddTypeExtension<ViewComponentGraphQLMutation>().AddTypeExtension<ViewContainerGraphQLMutation>()
> .AddTypeExtension<ViewEventGraphQLMutation>().AddTypeExtension<ComponentFieldGraphQLMutation>()
> .AddTypeExtension<RendererToolGraphQLMutation>().AddTypeExtension<ValidatorGraphQLMutation>() 
> .AddProjections()  
> .AddFiltering()   
> .AddSorting().RegisterDbContext<AppDbContext>(kind: DbContextKind.Pooled).PublishSchemaDefinition(c =>
> {
>     c.SetName("nextwareuibuildereditservices"); // The name of the schema. This name should be unique
>     c.PublishToRedis("gatewayservice", sp => sp.GetRequiredService<ConnectionMultiplexer>());
> }).AddInMemorySubscriptions();
> ```

@jkears , I am getting almost the same error when I upgrade 12.x.x to 13.0.2 and It works perfectly with the former version and the error came when I upgraded to 13.0.2. Could you please let me know how did you fix this error. Thank you!

Below is the error, I am getting and I registered that type "Defaultable<Double>" in startup but not "MultiSpaceDetailsDto" and "MultiSpaceDetailsDto" is just a dto class with some properties in it.

 **Unable to resolve type reference `Defaultable<Double!> (Input)`. (HotChocolate.Types.InputObjectType<Web.API.DesignHub.DTO.MultiSpaceDetailsDto>)\r\n\r\n**

**Comment by jkears** [comment]
@pratapkumarch If the error is the same it was because I was only registering top-level types (in my case Aggregates).  The error was a bit miss-leading in my case as it was saying that it couldn't find Page in ApplicationPage, but it was that ApplicationPage types weren't registered.    Can you pls share your DTO models.

**Comment by pratapkumarch** [comment]
> @pratapkumarch If the error is the same it was because I was only registering top-level types (in my case Aggregates). The error was a bit miss-leading in my case as it was saying that it couldn't find Page in ApplicationPage, but it was that ApplicationPage types weren't registered. Can you pls share your DTO models.

@jkears, Please find the  below DTO model

  ```
public class MultiSpaceDetailsDto
   {      
        public Defaultable<double> Height { get; set; }
        public Optional<double?> NumberOfPeopleOverride { get; set; }
   }
```

And I have registered the `Defaultable<Double>` like as below

 ```
 var hotChocolateServices = services
                .AddGraphQLServer()
                    .AddAuthorization()                   
                    .AddType<Defaultable<double>>()
```
And the error is misleading, and I am not sure why I am getting this error after upgrading to HC v13.0.2.
