### ISSUE TITLE
StrawberryShake 13: Unable to resolve type reference "Name!"

### ISSUE THREAD

**Issue by nightroman** [ChilliCream/graphql-platform#5860]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

StrawberryShake v13 fails on a HotChocolate GQL service schema with the error: Unable to resolve type reference "Name!"

Please find attached a project created with the following commands recommended here:
<https://chillicream.com/blog/2023/02/08/new-in-hot-chocolate-13#strawberry-shake>

Source code: [SSv13.zip](https://github.com/ChilliCream/graphql-platform/files/10762830/SSv13.zip)

```
dotnet new tool-manifest
dotnet tool install StrawberryShake.Tools

dotnet new classlib
dotnet add package StrawberryShake.Blazor

dotnet graphql init https://api.nexar.com/graphql -n NexarClient
```

After adding the simple query `Resources\Workspaces.graphql` the build fails with this error

```
EXEC : error GQL: Unable to resolve type reference `Name!`.
```

See also:

- Slack thread <https://hotchocolategraphql.slack.com/archives/CMUJ40EHJ/p1676188022540909>

### Version

13.0.2

**Comment by michaelstaib** [comment]
No, since this has a workaround.

**Comment by michaelstaib** [comment]
The workaround is removing the type.

**Comment by nightroman** [comment]
I am not aware of the workaround. The one suggested by @PascalSenn does not help, same error. We are blocked.

**Comment by nightroman** [comment]
> The workaround is removing the type.

I was not aware up to now. Let me try.

But how casual users of our service may know about this workaround? They follow HC recommended steps of using StarwberryShake, they get v13 this way. It does not build. Some users just stop trying and adopting not working software. And look for another client. It's a possible scenario.

**Comment by michaelstaib** [comment]
You removed the `Name` type and it says:

```
EXEC : error GQL: Unable to resolve type reference `Name!`.
```

The workaround I offered would be to download the schema manually and remove the `Name` type and directives that use it.

**Comment by michaelstaib** [comment]
The name type because of schema stitching.

**Comment by nightroman** [comment]
Updating the schema will require these workaround steps, too, presumably.

**Comment by jhueppauff** [comment]
If I remove all directives which are referencing `Name!` I am hit with different errors such as:
EXEC(1,1): error GQL: All operations must be named.

Is there anything more I need to do?

**Comment by nightroman** [comment]
I cannot repro the original issue with later versions, so I close it.

**Comment by andy-bout** [comment]
I am getting this error using 13.4.0 (I am new to StrawberryShake and trying to understand it to determine if this is the technology we want to use in our development process).  I have searched but can't find solutions for this problem.
