### ISSUE TITLE
StrawberryShake.Tools 13 does not update the schema.

### ISSUE THREAD

**Issue by nightroman** [ChilliCream/graphql-platform#5863]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

StrawberryShake.Tools 13 does not update the schema.

Please find attached a project created with the following commands recommended here:
https://chillicream.com/blog/2023/02/08/new-in-hot-chocolate-13#strawberry-shake

Source code: [SSv13.zip](https://github.com/ChilliCream/graphql-platform/files/10773457/SSv13.zip)

```
dotnet new tool-manifest
dotnet tool install StrawberryShake.Tools

dotnet new classlib
dotnet add package StrawberryShake.Blazor

dotnet graphql init https://api.nexar.com/graphql -n NexarClient
```

### Steps to reproduce

1. Manually edit `schema.graphql`, for example change a description or remove a field, type, etc.
2. Update the schema by `dotnet graphql update`

**Expected result**

The schema is updated, i.e. manual modifications above are gone.

**Actual result**

The schema is not updated/changed.

### Relevant log output

```
> dotnet graphql update
Download schema started.
Download schema completed in 1931 ms
```

### Version

13.0.2

**Comment by michaelstaib** [comment]
thanks for reporting

**Comment by F4r4m4rz** [comment]
Same issue here. Is there any estimated time to fix the issue?

**Comment by frabe1579** [comment]
Same issue here, manual schema update needed (copy/paste from Banana Cake Pop)

**Comment by mrange** [comment]
I can confirm this happens for me as well.

The workaround seems to be to use `dotnet graphql download` for now.
