### ISSUE TITLE
Cant perform filtering, sorting, etc.. on a Neo4jExecutable/.

### ISSUE THREAD

**Issue by KrankenWargen** [ChilliCream/graphql-platform#5868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

        [GraphQLName("building")]
        [UseFiltering]
        public  Neo4JExecutable<Building> GetBuildings([Service] IDriver driver)
        {
            
            var executable = new Neo4JExecutable<Building>(driver.AsyncSession(o => o.WithDatabase("neo4j")));

            return executable;
        }

in this case i won't have any of the filtering properties. and if I converted the executable to an IQueryable then i have to convert the whole db to a list in memory. which no one should do. how would one suppose to work with HC and Neo4j

### Steps to reproduce

1. connect to a neo4j db
2. try the filtering function

### Version

13.0.2

**Comment by MahmoudElgohary1992** [comment]
Here's a working Repo: https://github.com/MahmoudElgohary1992/playground
to reproduce:
 1) Create a local neo4j db
 2) Create Building,Floor,Room nodes with a name property
 3) Create relationship "HAS" from building to floor 
 4) Create relationship "CONTAIN" from floor to room
 5) enter db credentials 

PS: The workshop for neo4j repo @arif-hanif  created doesnt work in the slightest and mislead us alot in the beginning.

**Comment by glen-84** [comment]
Closing, as Neo4j support has been [removed](https://github.com/ChilliCream/graphql-platform/pull/6655) in v14.
