### ISSUE TITLE
Possible memory leak in HC 13

### ISSUE THREAD

**Issue by marcioscpinheiro** [ChilliCream/graphql-platform#5873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When we updated to version 13 we observed an increasing trend in memory allocation and profiling the memory with a simple query, we observed that the cause might be in the `OperationContextOwner` which is always increasing the number of allocated objects:

![image](https://user-images.githubusercontent.com/125901619/220161170-bab91a8c-4078-44ec-a98e-3c460e003901.png)

### Steps to reproduce

1. Create a new project from a template in version 13 
2. Simulate a reasonable and constant throughput
3. Profile the memory
4. The number of allocated objects and memory always increase

### Version

13.0.1

**Comment by PascalSenn** [comment]
@marcioscpinheiro  We have located the issue and are working on a patch

**Comment by michaelstaib** [comment]
This issue is now fixed with 13.0.3
