### ISSUE TITLE
ValidatePipelineOrder=false wont work

### ISSUE THREAD

**Issue by barnuri-cp** [ChilliCream/graphql-platform#5883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

when setting ValidatePipelineOrder=false, its probably not populate to MiddlewareValidationTypeInterceptor
because it keep throwing errors of invalid order

### Steps to reproduce

var graphqlBuilder = servicesCollection.AddGraphQLServer();
graphqlBuilder = graphqlBuilder.AddProjections();
graphqlBuilder = graphqlBuilder.AddFiltering();
graphqlBuilder = graphqlBuilder.AddSorting();
graphqlBuilder = graphqlBuilder.SetOptions(new() {ValidatePipelineOrder =false});
graphqlBuilder = graphqlBuilder.ModifyOptions(c => c.ValidatePipelineOrder = false);

[UseDbContext(typeof(User))]
[UseSorting]
[UsePaging]
[UseProjection]
[UseFiltering]
public IQueryable<User> GetUser([Service] Repo repository) => repository.Users;

### Version

13

**Comment by michaelstaib** [comment]
It also will not work... sorting cannot work after paging since paging is not outputing a list or queryable.

**Comment by michaelstaib** [comment]
How do you want to have one resolver for different types?

HC 13 allows you tow wrap attributes in attributes and introduce a new pipeline in there. The new pipeline can do the apply on the queryable.
