### ISSUE TITLE
Is it possible to use a directive to call a scalar SQL function?

### ISSUE THREAD

**Issue by pitboxx** [ChilliCream/graphql-platform#5890]
### Product

Hot Chocolate

### Is your feature request related to a problem?

We would like to use a directive to call a scalar SQL function with parameters.
![image](https://user-images.githubusercontent.com/52289967/221471277-617c876c-1211-424f-b02b-70fabf8c4dab.png)

What are the ways to use scalar SQL function in HotChocolate?

### The solution you'd like

We create our directive and middleware 
![image](https://user-images.githubusercontent.com/52289967/221483416-5c8b7e83-58ea-4757-b3d9-c3554bae58d7.png)
1. We cannot influence the formation of the database query, because the data has already been received during the execution of the middleware.
2. We can't add parameters to the AggSum scalar function as we would do it using IRequestExecutorBuilder.

What are the ways to use scalar SQL function in HotChocolate?

**Comment by michaelstaib** [comment]
We are not planing to add this. However what you are trying to do is possible. Just not the way you approach this.
