### ISSUE TITLE
Is it possible to use dynamic MongoDB data structure with dynamic hot chocolate schema definition with current codebase or nearest feature releases?

### ISSUE THREAD

**Issue by dimonchelli-dev** [ChilliCream/graphql-platform#5894]
### Product

Hot Chocolate

### Question

Is it possible to use dynamic MongoDB data structure with dynamic hot chocolate schema definition with current codebase or nearest feature releases?

### Input

1. MongoDB database with dynamic data structure
     - Any collection, that need to connect to GraphQL engine, may be added to database dynamically
     - Any field, that need to attach to existing GraphQL model, may be added to collection structure dynamically
        ```
        {
            # some core fields
            _id: '9ef436d1-dba7-4e55-8101-6e0477c73d49',
            CreatedAt: ISODate('2023-02-21T07:36:06.081Z'),
            
            # any other fields, that may be added to collection dynamically
            NewStringField: 'test value',
            NewIntField: 0'
         }
        ```

2.  Knowledge about database collections and each collection structure in JSON format (for example in file like in [DynamicTypes sample](https://github.com/ChilliCream/hotchocolate-examples/blob/master/misc/TypeModules/DynamicTypes/DynamicTypes.json))

    ```
    [
      {
        "graphQLName": "Person",
        "collectionName": "person_collection",
        "fields": [
          {"name": "stringField", "type": "string"},
          ...
      },
      ...
    ]
    ```

3. Need to use sorting and filtering by this dynamic fields

### Investigation

I'm a bit new to Hot Chocolate and not much familiar with the codebase, but after current docs investigation:
- [Docs - Dynamic Schemas](https://chillicream.com/blog/2021/09/27/hot-chocolate-12#dynamic-schemas)
- [Docs - MongoDB](https://chillicream.com/docs/hotchocolate/v12/integrations/mongodb)
- [Examples - MongoDB](https://github.com/ChilliCream/hotchocolate-examples/tree/master/misc/MongoDB/12.1)
- [Examples - TypeModules](https://github.com/ChilliCream/hotchocolate-examples/tree/master/misc/TypeModules)
- [Youtube - Adding dynamic types to your GraphQL schema with Hot Chocolate](https://www.youtube.com/watch?v=EjON8pU-CVs)
- [Youtube - How to deal with dynamic untyped data in GraphQL with Hot Chocolate 13?](https://www.youtube.com/watch?v=wODiVDT8ECI)

Still not clear for me:
- Seems it is not possible with current codebase. Is it true?
- Will be it possible with some releases at (nearest) future?
- Does this request seem ok or is it conceptually wrong (models need to be strongly-typed with small schema extension for display purposes)?

### The solution you'd like

1. Work with dynamic MongoDB data structure via `dynamic` objects or via [Dynamic Data MongoDB](https://mongodb.github.io/mongo-csharp-driver/2.0/examples/mixing_static_and_dynamic/) support.
2. Combine it with JSON dynamic schema definition to support MongoDB dynamic data.

**Comment by dimonchelli-dev** [comment]
@tobias-tengler @michaelstaib I would be grateful if you could guide me according to my request.

**Comment by dimonchelli-dev** [comment]
Resolved by dynamic type generation at runtime via `TypeBuilder`

**Comment by BenasB** [comment]
Hi, did you get around to this?

> Need to use sorting and filtering by this dynamic fields

If so, how did you manage to do it?
