### ISSUE TITLE
Latest .NET SDK fails to compile existing project

### ISSUE THREAD

**Issue by JulianBirch** [ChilliCream/graphql-platform#5903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

When using an existing .NET project with no `globals.json`, we can no longer compile the code using the latest .NET SDK. The error we are getting is: 

```
CSC : error SS0006: Access to the path 'C:\Program Files\dotnet\sdk\7.0.200\Roslyn\bincore\obj\berry' is denied. [C:\gi
t\BLAH.csproj]
```

Note `7.0.200`. I'm running `7.0.100` on my machine and it _doesn't_ happen.

Obviously, we'd expect the project compilation to be robust to changes in the SDK.

### Steps to reproduce

1. Take an existing .NET 6 SS project
2. Install the latest .NET SDK
3. Try to build

### Relevant log output

```shell
CSC : error SS0006: Access to the path 'C:\Program Files\dotnet\sdk\7.0.200\Roslyn\bincore\obj\berry' is denied. [C:\git\BLAH.csproj]
```

### Additional Context?

Given the seriousness of the problem, I'm loath to reproduce this on my machine. But it's already affected two members of my team.

### Version

12.18.0

**Comment by Jejuni** [comment]
We're facing the exact same issue.
We have SDK `7.0.201` and Code Generator `12.18.0` and get the same error 

```bash
CSC : error SS0006: Access to the path 'C:\Program Files\dotnet\sdk\7.0.201\Roslyn\bincore\obj\berry' is denied. [D:\Dev\path\proj.csproj]
```

**Comment by JulianBirch** [comment]
It's worth mentioning that people upgrading Visual Studio are likely to encounter this and according to our experimentation, `globals.json` doesn't affect the VS SDK. So basically it breaks the project in an unfixable way on those machines.

**Comment by michaelstaib** [comment]
Closing this issue as it does not happen with 13

**Comment by Jejuni** [comment]
There is no v13 for `StrawberryShake.CodeGeneration.CSharp.Analyzers` yet.
When will it be out?

**Comment by tobias-tengler** [comment]
The package has been removed in v13 in favor of MSBuild for a more stable building experience.

How you can upgrade is explained in our migration guide: https://chillicream.com/docs/strawberryshake/v13/migrating/migrate-from-12-to-13

If you encounter issues upgrading, let us know :)
