### ISSUE TITLE
Third binding method

### ISSUE THREAD

**Issue by EvilVir** [ChilliCream/graphql-platform#5905]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Currently we have two options of mapping domain model into output type: implicit or explicit. That makes us either expose all fields of domain model and then manually ignore ones we don't want or no fields and then manually add them in Configure method.

Example of implicit:

```
public class MyObjectType : ObjectType<MyDomainObject>
{
   protected override void Configure(IObjectTypeDescriptor<MyDomainObject> descriptor)
   {
      descriptor.Ignore(x => x.HiddenField);
   }
}
```

Example of explicit:

```
public class MyObjectType : ObjectType<MyDomainObject>
{
   protected override void Configure(IObjectTypeDescriptor<MyDomainObject> descriptor)
   {
      descriptor.Include(x => x.ExposedField);
   }
}
```

### The solution you'd like

I propose adding another option ("auto"?), it would work by doing implicit mapping of only properties and get* methods that are defined on the `ObjectType<T>` itself. Example:

```
public class MyObjectType : ObjectType<MyDomainObject>
{
   public int ExposedField { get; set; }

   public string GetDynamicField()
     => "Hello world!";
}
```

That would make things a bit simpler while enforcing separation of output DTOs and domain models. In project, I work currently on, we've implemented already this approach as separate class that inherits from `ObjectType<T>` but it would be nice to have this out-of-the-box.

**Comment by michaelstaib** [comment]
Why do you not use the annotation base approach?

```csharp
[ExtendObjectType<MyDomainObject>]
public class MyDomainObjectExtensions
{
   public int ExposedField { get; set; }

   public string GetDynamicField()
     => "Hello world!";
}
```

**Comment by EvilVir** [comment]
Oh, wasn't aware that `[ExtendObjectType]` works with something else than `IType` to be honest :)

But will that really achieve the goal? I mean in this case the GraphQL Output Type should have two fields: `ExposedField` and `DynamicField` they will be mapped from the domain automatically?

**Comment by michaelstaib** [comment]
It actually only works on things that are not type system related .... 

and yes ... you can ignore all things from MyDomainObject and define all resolvers explicitly.

**Comment by michaelstaib** [comment]
Closing this issue.

**Comment by EvilVir** [comment]
I was only using this attribute to split root Query/Mutation objects into separated classes, never thought about other use lol :D Thanks for the hint!

I'll check approach you propose above. My goal here is to cut down number of classes required to write to cleanly separate domain model from api model (hence the other proposition with input resolvers). Given that I have different input and output models sometimes, requirement to write DTOs and then `Input/ObjectType<T>` classes is just making things bloated quickly. Annotation aproach is fine but sometimes this little extra config, that `Input/ObjectType<T>` gives is needed.
