### ISSUE TITLE
Resolvers for input object

### ISSUE THREAD

**Issue by EvilVir** [ChilliCream/graphql-platform#5906]
### Product

Hot Chocolate

### Is your feature request related to a problem?

When defining `InputObjectType<T>` there is no possibility to override how the `T`'s field is composed.

### The solution you'd like

It would be nice to have same ability as with ouput types, to be able to alter how model's field is binded from the input. For example let's assume I have a domain model object with `FirstName` and `LastName` fields but in DTO I want to have `FullName`. Currently I need to write additional DTO class and then mapper method to domain model class. It would be nice to skip that like that:

```
public class MyInputType : InputObjectType<MyDomainType>
{
   protected override void Configure(IInputObjectTypeDescriptor<MyDomainType> descriptor)
   {
      descriptor.Field("fullName").Resolve<string>((value, target) =>
      {
         var splitted = value.Split(' ');
         target.FirstName = splitted[0];
         target.LastName = splitted[1];
      });
   }
}
```

**Comment by michaelstaib** [comment]
For GraphQL inputs are raw data. We also do not want to delve into the field of things like AutoMapper. I will close this issue as there are no plans to implement this. But you could implement such a thing on your own on top of HC ... the factories are accessible and you can override these or use type interceptors to introduce this.

**Comment by EvilVir** [comment]
Fair enough. I know a bit about interceptors, can you point me in right direction about factories please?
