### ISSUE TITLE
Occasionally inconsistent count of responses in batched queries

### ISSUE THREAD

**Issue by Deathrage** [ChilliCream/graphql-platform#5912]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

If request contains batched queries (array of queries) and execution of some queries fails, HC does not return same number of results. This happens randomly as sometimes HC returns equal number of responses (some failed) and sometimes it returns less responses (but even there can be multiple failed ones).

![image](https://user-images.githubusercontent.com/32812890/222709356-14573e39-75f3-466f-acea-56db73b817e7.png)

![image](https://user-images.githubusercontent.com/32812890/222709416-5c380862-d426-489c-88f7-e28e59de05ac.png)

This produces error in Apollo

![image](https://user-images.githubusercontent.com/32812890/222709501-2c680f09-8c82-4782-8346-f0a8c3822b40.png)

### Steps to reproduce

Do not know how to reproduce outside out project.

### Version

12.9.0

**Comment by michaelstaib** [comment]
Batches are now done in isolation. However we allow for fatal errors for certain reasons ... like rate limits reached.
