### ISSUE TITLE
Consider splitting each library/tool into its own dedicated repository for better discoverability

### ISSUE THREAD

**Issue by aradalvand** [ChilliCream/graphql-platform#5922]
To those of us who are already in the Hot Chocolate community, it's no mystery that Hot Chocolate is in fact the best all-around .NET GraphQL server framework out there, and is actually superior to the more well-known [graphql-dotnet](https://github.com/graphql-dotnet/graphql-dotnet) in most respects.

However, despite this, [graphql-dotnet](https://github.com/graphql-dotnet/graphql-dotnet) still has more GitHub stars (5.5K vs 4.3K) and NuGet installs than Hot Chocolate (16M vs 9.4M), and also consistently appears as the very first search result when you google phrases such as ".net graphql server" and so on.

Given all of this, I think it'd be fair to say that Hot Chocolate indeed suffers from a "discoverability" problem.
Hot Chocolate is hardly in the first top 10 search results when you google nearly any combination of the keywords "graphql" and ".net"; that's not trivial, and shouldn't just be hand-waved away; it's actually a pretty consequential problem, and is likely partly the reason why [graphql-dotnet](https://github.com/graphql-dotnet/graphql-dotnet) still seems to be getting more traction, despite being generally inferior to Hot Chocolate.

The repository recently was renamed from "ChilliCream/hotchocolate" to "ChilliCream/graphql-platform" which is understandable, given the fact that the repo wasn't sctually limited to HC but also contained the codebases for Strawberry Shake and Banana Cake Pop; it was essentially always a monorepo so the name change very much made sense from that perspective.
But this unfortunately exacerbated the discoverability problem; by making the name of the repo even more "generic", so to speak.

I would propose that each project is given its own separate repo under the "ChilliCream" organization, this would result in a much clearer structure:
- ChilliCream/HotChocolate
- ChilliCream/StrawberryShake
- ChilliCream/BananaCakePop

In a setup like this, the primary advantage would be that the README and the description of each repository could then be focused specifically on the respective tool that it contains, thereby enhancing its "discoverability" by orders of magnitude, basically.

Currently the README and the description of this repo are a bit too generic and unfocused; which I think is hurting the discoverability of the project(s).

This proposal might seem surface-level, or you might think it's not really worth the hassle, but I would argue it will genuinely result in better SEO, which will in turn help the project grow bigger; and hopefully eventually overtake [graphql-dotnet](https://github.com/graphql-dotnet/graphql-dotnet) and become the de-facto standard GraphQL server framework in the .NET world; which it very much deserves to be.

Let me know what you think.

**Comment by michaelstaib** [comment]
I think you are misreading the stats a bit.

We recently started optimizing SEO and are now number 3  for the search term "graphql .net". This is an ongoing investment and renaming the repo actually does not help.

<img width="853" alt="image" src="https://user-images.githubusercontent.com/9714350/223094185-4e60d992-dd14-43bc-a3c8-fe4796def983.png">

For us our dev workflow is more important. Working in a monorepo has made our workflow so much simpler and we will not go back to having multiple repros.

For the stats.... it takes time... we get 2 to 3 times more stars per day compared to graphql-dotnet and will overtake by the end of the year or mid next year... it takes time.

<img width="847" alt="image" src="https://user-images.githubusercontent.com/9714350/223095721-454bde35-d233-4988-bb09-8abd44b26583.png">
