### ISSUE TITLE
Enums are included in schema without being referenced when properties are ignored by ExtendObjectType

### ISSUE THREAD

**Issue by craigbehnke** [ChilliCream/graphql-platform#5926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I have tried to remove properties from a type within a subgraph, but while the property is hidden from the object type, the types backing those properties are still included.

I would expect that the enum, since it is not used anywhere, would not be included.

AccountTypeEnum is not used anywhere else.

### Steps to reproduce

1. Create an example base object:
```c#
public class Account
{
    public string Id {get;set;}
    public string Name {get;set;}
    public AccountTypeEnum AccountType {get;set;}
}

public enum AccountTypeEnum 
{
    CreditCard,
    Checking,
    Savings
}
```
2.  Extend the class to remove extra properties:
```c#
[ExtendObjectType(typeof(Account),IgnoreProperties = new[] {
    nameof(Account.AccountType),
    nameof(Account.Name)
})]
public class AccountReduction
{
}
```
3. Observe the erroneous results in the following schema (abridged):
```gql
type Account {
    id: String!
}

enum AccountTypeEnum {
    CREDIT_CARD
    CHECKING
    SAVINGS
}
```
4. Verify that AccountTypeEnum is not used anywhere else in the schema. (i.e. is orphaned)

### Additional Context?

As for why I am doing this: I am building multiple subgraphs within the same repo in order to reduce cold start times. To make things easier (haha) on myself, I am also using a common library with model definitions for interacting with the database across all subgraphs.

In order to not violate the single responsibility principle, I want to only return non-@key data from one subgraph.

However, updating/adding a member to an enum defined in multiple subgraphs results in a race condition within the Apollo GraphOS/Rover schema building system, which is how I found this issue originally.

### Version

13.0.4

**Comment by michaelstaib** [comment]
This one is fixed with the new `ObjectTypeAttribute` which replaces the `ExtendObjectTypeAttribute`
