### ISSUE TITLE
Stitching HyGraph graphs

### ISSUE THREAD

**Issue by AlwaysHC** [ChilliCream/graphql-platform#5929]
### Product

Hot Chocolate

### Is your feature request related to a problem?

I'm trying to stitch a graph from HyGraph but I get an error on the introspection_phase_2 phase because these 3 fields:
      onField
      onFragment
      onOperation
that are inserted on the query here:
https://github.com/ChilliCream/graphql-platform/blob/ea346082ef984769dc066ff4b6a41e3abb705ed5/src/HotChocolate/Utilities/src/Utilities.Introspection/IntrospectionQueryHelper.cs#L94

I suppose it happens because HyGraph doesn't return the __Directive fields in the introspection_phase_1 step:
https://github.com/ChilliCream/graphql-platform/blob/ea346082ef984769dc066ff4b6a41e3abb705ed5/src/HotChocolate/Utilities/src/Utilities.Introspection/SchemaFeatures.cs#L30

### The solution you'd like

Stitch HyGraph graphs

**Comment by michaelstaib** [comment]
HotChocolate.Stitching is now in legacy mode and is replaced by HotChocolate.Fusion. I am closing this issue as we essentially froze the fusion code.

You can join the preview of Hot Chocolate Fusion now on Slack
