### ISSUE TITLE
Automatic Datastore Mapping - Hasura or Postgraphile Style

### ISSUE THREAD

**Issue by raghavareddykv** [ChilliCream/graphql-platform#5931]
### Product

Hot Chocolate

### Is your feature request related to a problem?

@michaelstaib . Really loved HotChocolate. The Development on it was a breeze. I have an enhancement suggestion, can we look into integrating Hasura or Postgraphile like feature for automatic database mapping to generate schemas without writing much code like you mentioned in your enhancement suggestion before. Automatic Datastore mapping for faster development of types using the existing entities.

### The solution you'd like

It would be even more useful if the build workflow can generate the classes for every entity in the datastore as .cs files using type extensions and with some organizational schematic to locate the classes in appropriate name spaces, so adding additional features like validation and any other custom tasks can be added to the appropriate methods by the developers. This way it can handle both schema generation and the flexibility to add more logic in one go in a more predictable way. The developers will still have complete control over their overall codebase. This variant would eliminate the need for actions in Hasura or Postgraphile which needs setting up a different web service for handling custom jobs, and make the code stay in one place and manageable, since HC handles schema stitching very coherently it will just make it that much easier to separate the microservices. The whole approach can become datastore invariant as the build workflow generates the C# code that integrates into the Request executor. Let me know your thoughts on this, i would love to contribute to the project if you like it.

**Comment by michaelstaib** [comment]
There is something coming very soon... not from the ChilliCream team but it will use Hot Chocolate and will do exactly that. I am closing this issue as this will be available in the next couple of days.

Join us on slack for announcements
slack.chillicream.com
