### ISSUE TITLE
MapGraphQL issue >= 12.17.0 

### ISSUE THREAD

**Issue by jkears** [ChilliCream/graphql-platform#5951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

We have been setting the GraphQL path to root for over a year and it works well on12.8.2.  
This is done so that when we create Named HTTP Clients on down-stream services, that the Named HTTP connection can be utilized for both GraphQL and REST type integrations over each down-stream service within a Gateway.  

This is now broken in >= 12.17.0 (possibly before) but as mentioned, it works properly in 12.8.2 at least. 

This further prevents us from using Swagger and HC with root-level paths and is preventing us from migrating to 13.

### Steps to reproduce

1. Steps:

1.	Configure Swagger within in your program start-up using the default configuration
3.	Map GraphQL servers path to root.  i.e.  `app.MapGraphQL(path: "/");`
4.	Run your GraphQL server and try to run swagger.  i.e. `https://service/Swagger`

Expected Behavior:

                Swagger UI is rendered

Actual Behavior:
                
                BCP UI is rendered.

### Additional Context?

**Other Notes:**
                
If you accept the default `MapGraphQL();`  which resolves to path i.e. “`https:/service/GraphQL`”, this will return BCP rendered UI, and then when you run `https://service/Swagger` the Swagger UI is rendered.  Unfortunately this breaks a ton services that we have already created.   

### Version

>= 12.17.0

**Comment by jkears** [comment]
@michaelstaib call it a breaking change, but however you label this you never owned the path/subpaths previously i.e. 12.8.2 and this use to work really well for Dapr Client integration as we only required a single, shared named HTTP Connection(s).

**Comment by michaelstaib** [comment]
I will have a look at what has changed. I remember that we changed the routing to fix an issue with bcp. What you can do is move bcp on a specific route. Anyway will recheck what the change is.

**Comment by jkears** [comment]
It smells like it's here...

![image](https://user-images.githubusercontent.com/1290937/224381146-7a9e3107-23e8-4c48-8821-5abee84140bc.png)

**Comment by jkears** [comment]
If this is too much effort, one workaround we could take, is to create a separate set of named HTTP Clients, one for GraphQL and one for REST.  Since we are fully code-generated, it would just mean regeneration all of our services... so please don't change anything if it's a lot of effort. 

Please let me know if this needs to be close, and we will follow your recommendations to stay with default route.

Cheers

**Comment by jkears** [comment]
@michaelstaib ... plus this all relates to how we resolve our gateway end-points, thus if this is changing in Fusion, then it may not  be a problem in the future.

**Comment by jkears** [comment]
@michaelstaib ... So we managed to get this to work.... had to regenerate all of our services, but at least we are now finally running on 13.0.5,  bring on Fusion!

Cheers
