### ISSUE TITLE
Custom filtering middleware is not being applied unless the filtered field is a part of the result query

### ISSUE THREAD

**Issue by AntiTcb** [ChilliCream/graphql-platform#5952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

We're using a custom filter middleware to add on an expression to the result to filter out soft deleted entities in requests. What we're finding is that unless that field is included in the query, the middleware does not apply the filtering. When debugging, the code will go through and apply the `Where()` expression in both cases, but seems to only take affect in one.

```c#
// EF Entities
public interface ISoftDeletable { bool IsActive {get; set;} }
public class User : ISoftDeletable 
{
    public int Id {get;set;}
    public bool IsActive { get;set; }
}

// Middleware
[AttributeUsage(AttributeTargets.Method)]
public class UseInactiveFilteringAttribute<T> : ObjectFieldDescriptorAttribute
    where T : ISoftDeletable
{
    public UseInactiveFilteringAttribute([CallerLineNumber] int order = 0)
        => Order = order;

    protected override void OnConfigure(IDescriptorContext context, IObjectFieldDescriptor descriptor, MemberInfo member)
        => descriptor.UseInactiveFilteringMiddleware<T>();
}

public static class InactiveFilterObjectFieldDescriptorExtension
{
    public static IObjectFieldDescriptor UseInactiveFilteringMiddleware<T>(this IObjectFieldDescriptor descriptor)
        where T : ISoftDeletable
    {
        descriptor.Argument("includeInactive", x => x.Type<BooleanType>().DefaultValue(false));
        descriptor.Use(FilterInactiveEntityMiddleware<IQueryable<T>, T>());

        return descriptor;
    }

    private static FieldMiddleware FilterInactiveEntityMiddleware<TCollection, TEntity>()
        where TCollection : IEnumerable<TEntity>
        where TEntity : ISoftDeletable
    {
        return next => async context =>
        {
            await next(context);

            var includeInactiveArgument = context.Selection.Arguments.GetValueOrDefault("includeInactive")?.Value is bool argumentValue && argumentValue;
            var hasIsActiveWhereClause = context.Selection.Arguments.GetValueOrDefault("where")?.ValueLiteral?.ToString().Contains("isActive") ?? false;

            var filterInactive = !(includeInactiveArgument || hasIsActiveWhereClause);

            Expression<Func<TEntity, bool>> filterExpression = _ => _.IsActive == true;

            context.Result = context.Result switch
            {
                TCollection entityCollection when filterInactive => entityCollection.Where(filterExpression.Compile()),
                _ => context.Result
            };
        };
    }
}

// GQL
[UsePaging, UseInactiveFiltering<User>, UseProjection, UseFiltering, UseSorting]
    public IQueryable<User> GetUsers(MyDbContext db)
        => db.Users.AsNoTracking();     
```

```gql
query ActiveMiddlewareTesting {
  shouldOnlyGetActive_erronouslyGetsBoth: users {
    nodes {
      id
    }
  }
  shouldOnlyGetActive_worksAsExpected: users {
    nodes {
      id
      isActive
    }
  }
  shouldOnlyGetActive_worksAsExpected2: users (includeInactive: false) {
    nodes {
      id
    }
  }
  shouldGetBoth_worksAsExpected: users (includeInactive: true) {
    nodes {
      id
    }
  }
  shouldOnlyGetActive_worksAsExpected3: users (where: { isActive: { eq: true }}) {
    nodes {
      id
    }
  }
  shouldOnlyGetInactive_worksAsExpected: users (where: { isActive: { eq: false }}) {
    nodes {
      id
    }
  }
}
```
The first erroneous query is not getting the filter applied, despite the code succesfully running through the `TCollection` part of the switch expression that reassigns `context.Result`. 

### Steps to reproduce

1. Create a project with HotChocolate, EFCore, and apply all above code.
2. Seed with a mix of active and inactive users.
3. Run the GQL query and see that unless otherwise specified by the expressions the middleware looks for, or, the `isActive` field is included in the result set, inactive users will be included.

### Additional Context?

Additionally, if there's a means of having this middleware apply its expression to the generated EF expression before the query is executed against the database, I'd love some assistance in accomplishing that. 
I attempted with reordering the custom middleware to come after the `UseFilteringAttribute`, but could not find a way to add my own filtering afterwards before the return trip in the pipeline when `await next(context)` is called. Ideally, we'd like this soft deletion filtering to be represented in the generated SQL code.

### Version

13.0.5

**Comment by PascalSenn** [comment]
This is because the the other of the middlewares is wrong. This is the reason why the UseFiltering middleware has to be "after" the projection middleware

**Comment by AntiTcb** [comment]
> This is because the the other of the middlewares is wrong. This is the reason why the UseFiltering middleware has to be "after" the projection middleware

What would be the correct order for this then? I've observed that if `UseInactiveFiltering` comes after `UseProjection` then said projection no longer happens. 

Modifying like so:
```csharp
public interface ISoftDeletable { bool IsActive {get; set;} }
public class User : ISoftDeletable 
{
    public int Id {get;set;}
    public int ProfileId { get;set;}
    public bool IsActive { get;set; }
    
    public virtual Profile Profile {get;set;}
}
public class Profile
{
    public int Id {get;set;}
    public int ProfileId {get;set;}
    public string FullName {get;set;}
}

// GQL
[UsePaging, UseProjection, UseInactiveFiltering<User>, UseFiltering, UseSorting]
    public IQueryable<User> GetUsers(CmsDbContext db)
        => db.Users.AsNoTracking();
```
```gql
query ActiveMiddlewareTesting {
  shouldOnlyGetActive_errorsAsPersonIsNullOnEntity: users {
    nodes {
      id,
      profile {
        fullName
      }
    }
  }
}
```
Response (truncated for brevity to just the error message):
```json
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field."
    }]
}
```
Also occurs with these orders:
`[UsePaging, UseProjection, UseInactiveFiltering<User>, UseFiltering, UseSorting]`
`[UsePaging, UseProjection, UseFiltering, UseInactiveFiltering<User>, UseSorting]`
`[UsePaging, UseProjection, UseFiltering, UseSorting, UseInactiveFiltering<User>]`

**Comment by michaelstaib** [comment]
You cannot write these attributes in a line

C# actually does not have an order for attributes.... 

We used a compiler trick that infers the line number as order... all attributes starting with `Use` cannot be inlined

```
UsePaging,
UseProjection
UseInactiveFiltering<User>
UseFiltering
UseSorting
```

also the interactive attribute must implement the constructor like we do for filtering and stuff.

**Comment by michaelstaib** [comment]
public UseInactiveFilteringAttribute([CallerLineNumber] int order = 0)

thats correct ... and that is also the reason for this not working in a single line.
