### ISSUE TITLE
Cosmos IQueryable throws "LINQ query please set allowSynchronousQueryExecution true or use GetItemQueryIterator to execute asynchronously"

### ISSUE THREAD

**Issue by onionhammer** [ChilliCream/graphql-platform#5958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When returning a Cosmos Linq Queryable, HotChocolate throws because it appears to be attempting to access the IQueryable synchronously (rather than async)

```C#
[UseFiltering]
public IQueryable<MyModel> GetPartner() =>
    MyContainer.GetItemLinqQueryable<MyModel>();
```

### Steps to reproduce

1. Connect your program to a cosmos database
2. Return a queryable ala MyContainer.GetItemLinqQueryable<MyModel>()
3. Exception happens when accessing that node

### Relevant log output

```shell
GraphQL service exception for 'POST /graphql/UnknownOperation - 662a00b5500da5b6c5c6a01ee7142acd': To execute LINQ query please set allowSynchronousQueryExecution true or use GetItemQueryIterator to execute asynchronously
      System.NotSupportedException: To execute LINQ query please set allowSynchronousQueryExecution true or use GetItemQueryIterator to execute asynchronously
         at Microsoft.Azure.Cosmos.Linq.CosmosLinqQuery`1.GetEnumerator()+MoveNext()
         at HotChocolate.Execution.Processing.Tasks.ResolverTask.<>c__DisplayClass50_0.<ExecuteResolverPipelineAsync>b__0()
         at System.Threading.Tasks.Task`1.InnerInvoke()
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
      --- End of stack trace from previous location ---
         at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
         at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
      --- End of stack trace from previous location ---
         at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)
         at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)
```

### Additional Context?

HC should try to load data from the IQuerayble asynchronously rather than synchronously

### Version

13.0.5

## Blockers to having a nice repository for searching/paging/filtering for Cosmos and HotChocolate
- [ ] This issue
- [ ] https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3697
- [ ] https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3724
- [ ] https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3725

**Comment by onionhammer** [comment]
It seems like this is the code to blame:

![image](https://user-images.githubusercontent.com/969938/224821329-68e45d05-a800-45e9-a8b5-49553fa297e4.png)

**Comment by onionhammer** [comment]
Workaround:

```C#
using System.Collections;
using Microsoft.Azure.Cosmos.Linq;

namespace C2C.Exchange.GraphQLx;

public class GraphQueryable<T> : IExecutable<T>
{
    public GraphQueryable(IQueryable<T> source)
    {
        SourceQuery = source;
    }

    public IQueryable<T> SourceQuery { get; }
    public object Source => SourceQuery;

    public async ValueTask<object?> FirstOrDefaultAsync(CancellationToken cancellationToken)
    {
        using var iter = SourceQuery.ToFeedIterator();

        if (iter.HasMoreResults)
        {
            var result = await iter.ReadNextAsync(cancellationToken);

            return result.FirstOrDefault();
        }

        return default;
    }

    public string Print()
    {
        return SourceQuery.ToString() ?? string.Empty;
    }

    public async ValueTask<object?> SingleOrDefaultAsync(CancellationToken cancellationToken)
    {
        using var iter = SourceQuery.ToFeedIterator();

        if (iter.HasMoreResults)
        {
            var result = await iter.ReadNextAsync(cancellationToken);

            return result.SingleOrDefault();
        }

        return default;
    }

    public async ValueTask<IList> ToListAsync(CancellationToken cancellationToken)
    {
        using var iter = SourceQuery.ToFeedIterator();

        var list = new List<T>();

        while (iter.HasMoreResults)
        {
            var result = await iter.ReadNextAsync(cancellationToken);

            list.AddRange(result);
        }

        return list;
    }
}
```

```    [UseFiltering]
    [UseSorting]
    [Authorize(Policy = AuthorizationPolicies.SystemReadPartners)]
    public static GraphQueryable<MyModel> GetPartners()
    {
        var query = MyContainer.GetItemLinqQueryable<MyModel>();

        return new (query);
    }
```

**Comment by michaelstaib** [comment]
We check, if the queryable also implements `IAsyncEnumerable` than we will use the async variant. In the case of EFCore, they are implementing `IAsyncEnumerable`.

**Comment by michaelstaib** [comment]
Does Cosmos implement `IAsyncEnumerable`?

**Comment by michaelstaib** [comment]
Just double checked ... in the case of EFCore you can do the following, and that is what we do:

```csharp
            if (source is IAsyncEnumerable<TSource> asyncEnumerable)
            {
                return asyncEnumerable;
            }
```

this is done in a middleware... the resolver task is kind of the last line of defense and there we will execute it in a task if no other way was found in the pipeline.

Looking at the docs the have this weird way with the iterator to fetch it. Strange that they do not implement IAsyncEnumerable.

**Comment by michaelstaib** [comment]
What can be done are several things.... either a middleware specific for cosmos of a paging provider for cosmos.

**Comment by onionhammer** [comment]
Yeah, I think cosmos ought to implement Iasyncenumerable.. but you guys do have a ravendb provider, surely cosmos is more popular than that in 2023… right? 😅

**Comment by michaelstaib** [comment]
> Yeah, I think cosmos ought to implement Iasyncenumerable.. but you guys do have a ravendb provider, surely cosmos is more popular than that in 2023… right?

Not sure about that ... the raven community was very active and lots of people wanted support for that. We had also lots of requests for EfCore and MongoDB ... I would say you are the first to ask for cosmos :D

**Comment by michaelstaib** [comment]
Just checked ... 6 issues including this ... and 5 where asking question for cosmos with EFCore ... so not a lot of demand. Demand as from questions on slack is:

1. Postgres
3. MongoDB
4. RavenDB

**Comment by michaelstaib** [comment]
But if you want to do the work for the driver we will help you with that. The work for the MartenDB diver was also done by one of our community members. Interested to help on cosmos?

**Comment by onionhammer** [comment]
@michaelstaib I am interested in contributing it. I'm still struggling to figure out the best way to accomplish it with minimal use of attributes that have to be tacked on

**Comment by michaelstaib** [comment]
We have a standard template for this. I can post you later a pr that shows how such a driver is implemented.

**Comment by onionhammer** [comment]
@michaelstaib any update on getting me that template?

**Comment by Arcalise08** [comment]
I'm hitting this issue as well. What can i do to work around it?

**Comment by Arcalise08** [comment]
I'm new to this library and also very much invested in CosmosDB. Can anyone tell me if this is a bad approach to fixing the OPs error

```
    [UseFiltering]
    public async Task<IQueryable<CoreDetaineeEntity>?> GetUsers([FromServices] Container<Users> users, IResolverContext resolverContext)
    {
        var query = container
            .GetItemLinqQueryable<Users>()
            .Filter(resolverContext)
            .ToFeedIterator();
        var list = new List<Users>();
        while (query.HasMoreResults)
        { 
            var response = await query.ReadNextAsync();
            foreach (var item in response)
            {
                list.Add(item);
            }
        }
        return list.AsQueryable();
    }
```

It does work without the `allowSynchronousQueryExecution` set to true.

**Comment by Arcalise08** [comment]
@onionhammer I'm also available if you need anything. I'd love to see cosmos officially supported. In the mean-time, is there any issues with my workaround to this? I've been using it for a few days and its worked fairly well.

**Comment by onionhammer** [comment]
> We have a standard template for this. I can post you later a pr that shows how such a driver is implemented.

Any update on this?

**Comment by onionhammer** [comment]
Per nuget:

- RavenDB Client: Per day average 3.3K
- Marten: Per day average 2.1K
- Cosmos: Per day average 40.2K

**Comment by mcquiggd** [comment]
I'm also interested in a Cosmos DB provider - please don't let this get closed by the stale bot.

**Comment by wayne-o** [comment]
Same

**Comment by suneths** [comment]
Hi @onionhammer 

I am also interested in this. did you guys anywhere in the end? I can help out with getting the PR completed - if you need a hand.
tvm

**Comment by onionhammer** [comment]
Unfortunately not, discussed it a few times with @michaelstaib , he seemed to think it was relatively easy but I can't remember any simple samples coming out of it

**Comment by suneths** [comment]
> var list = new List<Users>();
>         while (query.HasMoreResults)
>         { 
>             var response = await query.ReadNextAsync();
>             foreach (var item in response)
>             {
>                 list.Add(item);
>             }
>         }
>         return list;

Thanks for the reply @onionhammer.

The original code you quoted, which part of is it in HC?
Are you still using Cosmos SDK with HC or did you change to use EF Core for example - if i may ask? I do wonder whether it's better to use EF core with HC if one had the choice.

thanks

**Comment by onionhammer** [comment]
@suneths I am still using cosmos SDK with hotchocolate, but I have written a significant amount of ugly glue code in my app to make paging/filtering/sorting work

**Comment by suneths** [comment]
> @suneths I am still using cosmos SDK with hotchocolate, but I have written a significant amount of ugly glue code in my app to make paging/filtering/sorting work

Thanks @onionhammer. 

asking the obvious, but would this code disappear with EF core in place?
I guess there maybe other considerations, but do you have a choice to switch to EF core? - you don't want to because of architectural or other design reasons.

Many thanks.

**Comment by onionhammer** [comment]
> EF core provider is also non-complete so you'll find things not working occasionally.

Sadly so is the Cosmos SDK

**Comment by Arcalise08** [comment]
> > EF core provider is also non-complete so you'll find things not working occasionally.
> 
> Sadly so is the Cosmos SDK

My team hasn't hit any walls with it as of yet. That can change at anytime, however.

**Comment by suneths** [comment]
Thanks @Arcalise08 @onionhammer for the replies. let's see whether @michaelstaib decides to add some love to Cosmos sdk in v14 :)

**Comment by Arcalise08** [comment]
I will say, though, We ultimately decided to use REST instead of GraphQL. Though using my above solution did work, It came with some serious downsides. For one we couldn't control how the query was executed, so again, Cross-partition queries were difficult to stop.

If there is to be any support for the Cosmos.Sdk, Finding ways to avoid cross-partition queries should be a top priority. Partitioning should not just be some abstracted away concept. Its a huge deal to consumers of Cosmos.

**Comment by suneths** [comment]
> I will say, though, We ultimately decided to use REST instead of GraphQL. Though using my above solution did work, It came with some serious downsides. For one we couldn't control how the query was executed, so again, Cross-partition queries were difficult to stop.
> 
> If there is to be any support for the Cosmos.Sdk, Finding ways to avoid cross-partition queries should be a top priority. Partitioning should not just be some abstracted away concept. Its a huge deal to consumers of Cosmos.

interesting. thanks for that. but isn't this down to the partition key and the type of queries though? i guess with REST you can control the type of querying a bit more?

**Comment by Arcalise08** [comment]
Its been almost a year since I did the initial testing, So my memory is a bit fuzzy on what the actual issues were.

We liked graphql because of its ability to query pretty much anything on any field of a class. So our workflow got really easy, No, longer needed to support large filter classes for REST.  In REST we would have a repository which, would have every query we could execute like so

- GetActiveUsers
- GetUsersWhichMiddleNameStartsWithB

These repos enforce the partition rules as well. So if, for instance, If Users were partitioned by a Facility, we would require that facilityId in the repo before running the query.

GraphQL, at least from what I remember, Simply gave us an IQueryable we would give to cosmos directly. Altering it caused problems. Which means clients could execute cross partition queries unchallenged. And again, This problem is only on that special "Query off any field" method of querying.

**Comment by suneths** [comment]
> Its been almost a year since I did the initial testing, So my memory is a bit fuzzy on what the actual issues were.
> 
> We liked graphql because of its ability to query pretty much anything on any field of a class. So our workflow got really easy, No, longer needed to support large filter classes for REST. In REST we would have a repository which, would have every query we could execute like so
> 
> * GetActiveUsers
> * GetUsersWhichMiddleNameStartsWithB
> 
> These repos enforce the partition rules as well. So if, for instance, If Users were partitioned by a Facility, we would require that facilityId as an argument to those methods in the repo before running the query.
> 
> GraphQL, at least from what I remember, Simply gave us an IQueryable we would give to cosmos directly. Altering it caused problems. Which means clients could execute cross partition queries unchallenged. And again, This problem is only on that special "Query off any field" method of querying.

Got it. Thanks very much for the detail reply!

**Comment by Arcalise08** [comment]
Sure thing. I will likely dig back into it within the next week or two and see what changes have been made to address the issues. I'm happy to post my findings in another issue with a more fitting name. Or here if you prefer.

**Comment by suneths** [comment]
> Sure thing. I will likely dig back into it within the next week or two and see what changes have been made to address the issues. I'm happy to post my findings in another issue with a more fitting name. Or here if you prefer.

Thanks. I'd definitely be interested to see your findings.

**Comment by michaelstaib** [comment]
This is fixed with HotChocolate 14 preview 117

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/graphql-platform/pull/7152

**Comment by michaelstaib** [comment]
This one is fixed in 14 ... we will soon publish docs for this.

**Comment by Arcalise08** [comment]
Still seeing the same issue in 14 (Havent came across updated docs)

Also, this seems like it should be dead simple.. But I cant get it to work with the workaround...
```
    [UseFiltering]
    public async Task<IEnumerable<UserDetails>> GetDetainees([Service] UserContainer users, IResolverContext context)
    {

        var result = users.Container.GetItemLinqQueryable<UserEntity>(
                false,
                null,
                null,
                new CosmosLinqSerializerOptions { PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase }
            )
            .Filter(context);
        
        var query =  result.ToFeedIterator();
        var items = await query.ReadNextAsync();
        return items.Resource;
    }
```

My method returns a UserDetails, but my queryable is against UserEntity. So the filtering just is ignored entirely. Surely there's a way around this, as we don't want to expose all the sensitive user information to a client.
