### ISSUE TITLE
Only the default Authentication Scheme is used, disregarding individual policy

### ISSUE THREAD

**Issue by joshuapetryk** [ChilliCream/graphql-platform#5959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

We have an asp.net core 6 application using a mix of GraphQL endpoints and asp.net api controllers. Hot Chocolate version 12.18.

We have an authorization policy consisting of two authentication schemes (MTLS Certificate auth and JWT Bearer auth). We need to run both authentication scheme as part of the authorization policy.

When using the `HotChocolate.AspNetCore.Authorization.AuthorizeAttribute` we notice that the authentication schemes defined in the policy are not being evaluated, only the scheme specified in `.AddAuthentication(defaultScheme)` is used.

Abbreviated sample code:

```c#
services
    .AddAuthentication("Certificate")
// Snipped bearer auth code
// Snipped certificate auth code
    .AddAuthorization(options =>
             {
                 options.AddPolicy("Test", policy =>
                 {
                     policy.AuthenticationSchemes.Add("Bearer");
                     policy.AuthenticationSchemes.Add("Certificate");
                     policy.RequireAuthenticatedUser();
                 });
              })

services.AddGraphQLServer()
                .AddAuthorization()
                .AddProjections()
                .AddFiltering()
                .AddSorting()
                .AddQueryType<CustomQuery>();
```

Is this a known limitation of Hot Chocolate? How can we vary the authentication scheme based on policy?

### Steps to reproduce

1. Create a new asp.net 6 project.
2. Add JWT Bearer authentication, MTLS certificate authentication and authorization.
3. Set the default auth scheme to JWT.
4. Create an authorization policy that uses both JWT and MTLS schemes.
5. Add GraphQL
6. Decorate the graph QL resolver type with `[Authorize(Policy = "Custom Policy"]`
7. Run the server and send a GraphQL request with a valid JWT and valid client certificate.
8. Observe that the User principal does not contain an identity for the **certificate** auth. because the **certificate** auth scheme was not run.
9. Switch the default auth scheme to Certificate.
10. Run step 7 again.
11. Observe that the User principal does not contain an identity for the **JWT** auth. because the **JWT** auth scheme was not run.

### Additional Context?

Note: I ran the repro steps above using the built in asp.net core Authorize attribute on a regular api controller and observed that both authentication schemes were ran and both JWT and Certificate identities are present on the User principal.

### Version

12.18.0

**Comment by michaelstaib** [comment]
you need to sign the user in in the HttpRequestInterceptor. context.AuthenticateAsnc(Scheme) ... you can sign in multiple schemes.

**Comment by ronnyek** [comment]
I've tried to resolve same issue with this... defaulting graphql to a different auth scheme than the default. I created a interceptor an onCreate.. like this
``` cs
internal class BasicAuthRequestInterceptor: DefaultHttpRequestInterceptor
{
    public override async ValueTask OnCreateAsync(HttpContext context, IRequestExecutor requestExecutor, IQueryRequestBuilder requestBuilder,
        CancellationToken cancellationToken)
    {
        await context.AuthenticateAsync("BasicAuthentication");
        base.OnCreateAsync(context, requestExecutor, requestBuilder, cancellationToken);
    }
}
```

I  registered this with 
``` cs
 services.AddGraphQLServer()
     .AddHttpRequestInterceptor<BasicAuthRequestInterceptor>()
```

But I don't even see the interceptor `onCreateAsync` fire, it seems to be attempting to challenge with the default authentication provider (maybe the interceptor is not firing because the default auth scheme is still taking precedence
