### ISSUE TITLE
[Feature] Add support for multiple XML documentation files

### ISSUE THREAD

**Issue by kawazoe** [ChilliCream/graphql-platform#5960]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Most solutions today will include multiple projects. Often, projects will only have a thin API layer on top of a more complex business layer that exposes most of the real types made available in the API.

Currently, there is no easy way to load the generated XmlDocumentation files from both projects into HotChocolate, so if any types in the schema are coming straight from the business layer, they won't get any descriptions.

### The solution you'd like

Out of the box, HotChocolate should look for all xml files that matches the name of a referenced assembly on top of the current assembly. ResolveXmlDocumentationFileName should also be augmented to return a collection. The content of all files should be merged in order that they are listed in the collection.

**Comment by michaelstaib** [comment]
Thats what Hot Chocolate does :) 

https://chillicream.com/docs/hotchocolate/v13/defining-a-schema/documentation#xml-documentation
