### ISSUE TITLE
Possible memory/event leak from RequestExecutorProxy

### ISSUE THREAD

**Issue by octera** [ChilliCream/graphql-platform#5968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

RequestExecutorProxy is subscribing to RequestExecutorEvicted from the _executorResolver
But it never unregister the event, and RequestExecutorResolver seems to not manage the events registered to evict the one that are disposed.

Screen from dotMemory
![image](https://user-images.githubusercontent.com/159349/225879247-93afe85d-b2bf-41c2-bd4d-f2e83df1d863.png)

### Steps to reproduce

1. The simple way to reproduce it, is to have an dedicated endpoint (like an healthCheck) that is creating a RequestExecutorProxy with the injection of IRequestExecutorResolver
2. Even with a manual call on Dispose on the RequestExecutorProxy, the instance is not garbage collected because the reference in RequesetExecutorResolver remains

### Additional Context?

Dispose on the RequestExecutorProxy should unregister the event

### Version

12.0.0+

**Comment by michaelstaib** [comment]
Thank you for reporting this. I have looked at the code and verified the issue. I have put this on out patch milestone.
