### ISSUE TITLE
bin\berry access denied

### ISSUE THREAD

**Issue by dameeks** [ChilliCream/graphql-platform#5975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

Access denied on bin\berry when trying to build

### Steps to reproduce

After following the documentation to get the demo StrawberryShake client created. I run into the following error when I attempt to build the project:
```
$ dotnet build
MSBuild version 17.5.0+6f08c67f3 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
CSC : error SS0006: Access to the path 'C:\Program Files\dotnet\sdk\7.0.202\Roslyn\bincore\obj\berry' is denied. [C:\projects\Demo\Demo\Demo.csproj]

Build FAILED.

CSC : error SS0006: Access to the path 'C:\Program Files\dotnet\sdk\7.0.202\Roslyn\bincore\obj\berry' is denied. [C:\projects\Demo\Demo\Demo.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.42
```

### Version

13.0.5

**Comment by michaelstaib** [comment]
If you properly migrated there should only be a single Strawberry Shake Package.

**Comment by dameeks** [comment]
I removed all packages and added just StrawberryShake.Maui and it is building correctly now. Thanks.
