### ISSUE TITLE
Interfaces without any fields are not supported?

### ISSUE THREAD

**Issue by StefH** [ChilliCream/graphql-platform#5985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

When a graphQL server provides a graphql-interfaces without any fields, no code can be generated by the client.

### Steps to reproduce

This GraphQL:
``` graphql
interface ExecutableInterface {

}
```

Give this error in Strawberry-Shake:
```
CSC : error TS_MISSING_TYPE: Interface `ExecutableInterface` has no fields declared.
```

I see that this is by design (https://github.com/ChilliCream/graphql-platform/blob/main/src/HotChocolate/Core/test/Types.Tests/Types/Validation/InterfaceTypeValidationRuleTests.cs#L9) however I wan to know why this is? And if there is a work-around?

### Relevant log output

```shell
CSC : error TS_MISSING_TYPE: Interface `ExecutableInterface` has no fields declared.
```

### Version

12.16.0

**Comment by PascalSenn** [comment]
@StefH  This is not valid GraphQL:
https://spec.graphql.org/June2018/#sec-Interfaces

``` 
Type Validation

Interface types have the potential to be invalid if incorrectly defined.

1.  An Interface type must define one or more fields
```

**Comment by pawel-baranowski-softserve** [comment]
Hello, I'd also like to ask about possible workarounds. I do understand that [per GraphQL specs](https://spec.graphql.org/September2025/#sel-HAHbnBFBABABxB4a) an interface with no fields is invalid. However, please consider the following.
## The problem
I found myself in a situation that I need to consume an existing GraphQL API, and I'd like to use Strawberry Shake. The API happens to provide a schema with an empty interface that is used as a marker and implemented by several types. Now, the schema is out of my control, I'd like to consume a small part of the API that doesn't use the interface or types that implement it.
## Possible (and failing) workarounds
1. I believe it should be possible to extend the interface using `schema.extensions.graphql`. I tried to add a dummy field but it didn't resolve the issue.
2. There's an option to disable schema validation. I tried different ways of doing so, none of which seems to have worked:
3.1. Adding `"strictSchemaValidation": false` to `.graphqlrc.json`
3.2. Circumventing `dotnet build` and running `dotnet graphql generate --disableSchemaValidation` directly
3.3. Enforcing `GraphQLStrictSchemaValidation` as `disable` in `.csproj` and via MSBuild parameters
## Is there another way?
Is there any other way to work around this and consume a badly designed API? Some sort of fault tolerance would be a great option and could be only enabled on demand.

/cc @PascalSenn @michaelstaib

**Comment by pawel-baranowski-softserve** [comment]
I need to go back to my previous comment. It turns out the GraphQL API I was trying to consume can't be used directly with introspection queries alone. The team responsible is _well aware_ about this, and they maintain and publish a dedicated _consumer schema_ that needs to be downloaded in order to keep the client code in sync. So I removed `url` from `.graphqlrc.json` and downloaded the schema manually. The client build and runs fine this time.

So, in Strawberry Shake's defense - let's enforce standards, I agree.
