### ISSUE TITLE
Does Hot Chocolate graphql-platform have CLI to auto generate resolver code based on Schema.graphql?

### ISSUE THREAD

**Issue by isuhendro** [ChilliCream/graphql-platform#6000]
### Product

Hot Chocolate

### Is your feature request related to a problem?

With an auto-generated resolver as the initial template, the GraphQL server would have a cleaner and more consistent approach, especially on large-scale implementation

### The solution you'd like

a CLI to auto-generate resolvers based on initial and or updated `schema.graphql`

**Comment by michaelstaib** [comment]
No,

I also find that this is a quite difficult problem as there are so many ways you might want to approach this. What are actually your resolvers and what are just entities?

At the moment there are two community projects that try to do that with Hot Chocolate. Microsofts DAB and another community project.
