### ISSUE TITLE
Better errors and/or matching between subscription's and event's message-type

### ISSUE THREAD

**Issue by DanielRose** [ChilliCream/graphql-platform#6007]
### Product

Hot Chocolate

### Is your feature request related to a problem?

In my code, I created mutations with subscriptions, as described in the [documentation](https://chillicream.com/docs/hotchocolate/v13/defining-a-schema/subscriptions/#publishing-events). I found out that the Hot Chocolate code is very strict, specifically `InMemoryPubSub.OnSendAsync`, which calls `DefaultPubSub.TryGetTopic.` In there, the code throws a relatively generic exception without any data, which makes debugging difficult.

In my subscription, the EventMessage has the type `IEnumerable<Item>`. Due to some refactoring, my mutation sends a message via the ITopicEventSender of the type `List<Item>`, which looks similar to this

```cs
public class Mutation
{
    public async Task<IEnumerable<Item>> AddItems(IEnumerable<Item> items, [Service] ITopicEventSender sender)
    {
        var addedItems = items.ToList();

        // do something with the items

        await sender.SendAsync("ItemsAdded", items);
        return addedItems;
    }
}

public class Subscription
{
    [Subscribe]
    [Topic("ItemsAdded")]
    public IEnumerable<Item> ItemsAdded([EventMessage] IEnumerable<Item> items) => items;
}
```

At runtime, this fails when sending the PubSub message, because the types are different. It throws an "empty" `InvalidMessageTypeException`, ie. without any data what the event-message type was and what the topic's type was.

Additionally, this exception is not caught, which means that the mutation also fails with an internal server error.

### The solution you'd like

There are several things which could help here:

In `DefaultPubSub.TryGetTopic`, if the sent message's type does not match the topic's type, there should be more detail in the exception. For example the assembly-qualified-name of the two types could be added as message.

If possible, it would be nice if the types do not need to be exactly the same. However, since the messages are wrapped in an InMemoryTopic, that may not be possible.

Finally, it would be great if there was some way to synchronize the types of the subscription's EventMessage and the ITopicEventSender.SendAsync<TMessage>, so that I would get a build error if the two are different. For example, could it be possible to generate an EventMessageWrapper class from the EventMessageAttribute, which I could then send via the ITopicEventSender?

**Comment by michaelstaib** [comment]
> If possible, it would be nice if the types do not need to be exactly the same. However, since the messages are wrapped in an InMemoryTopic, that may not be possible.

This is difficult. It looks tempting for lists and stuff ... but in general you have message objects. You could get into errors where you suddenly get hundreds of errors where message send and message received to not fit together.

**Comment by michaelstaib** [comment]
> Finally, it would be great if there was some way to synchronize the types of the subscription's EventMessage and the ITopicEventSender.SendAsync, so that I would get a build error if the two are different. For example, could it be possible to generate an EventMessageWrapper class from the EventMessageAttribute, which I could then send via the ITopicEventSender?

We could introduce an analyzer for this that produces an error at build time.

**Comment by michaelstaib** [comment]
> In DefaultPubSub.TryGetTopic, if the sent message's type does not match the topic's type, there should be more detail in the exception. For example the assembly-qualified-name of the two types could be added as message.

We will implement this part for 13.1 to make subscriptions easier to use and fail with more information.

**Comment by DanielRose** [comment]
> > Finally, it would be great if there was some way to synchronize the types of the subscription's EventMessage and the ITopicEventSender.SendAsync, so that I would get a build error if the two are different. For example, could it be possible to generate an EventMessageWrapper class from the EventMessageAttribute, which I could then send via the ITopicEventSender?
> 
> We could introduce an analyzer for this that produces an error at build time.

@michaelstaib I ended up refactoring my code, creating a class for each subscription. It is mostly copy-paste, which means it would be a nice fit for code generation. They all look basically like this:

```cs
[SubscriptionType]
public class ItemsAddedSubscription
{
	[Subscribe(With = nameof(Subscribe))]
	public IEnumerable<IItemGql> ItemsAdded(
		[EventMessage] IEnumerable<Item> addedItems,
		[GraphQLType(typeof(NonNullType<IdType>))] Guid scopeId // advanced feature: subscribe only to items of the given scope
	) => addedItems;

	public ValueTask<ISourceStream<IEnumerable<Item>>> Subscribe(
		[GraphQLType(typeof(NonNullType<IdType>))] Guid scopeId,
		[Service] ITopicEventReceiver receiver,
		CancellationToken ct
	) => receiver.SubscribeAsync<IEnumerable<IItemGql>>(TopicName(scopeId), ct);

	private static string TopicName(Guid scopeId) => $"{nameof(ItemsAdd)}_{scopeId}";

	public static ValueTask Publish(
		ITopicEventSender sender,
		Guid scopeId,
		IEnumerable<Item> addedItems,
		CancellationToken ct = default
	) => sender.SendAsync(TopicName(scopeId), addedItems, ct);
}
```

Then in my mutation I only need to call `await ItemsAddedSubscription.Publish(...)`. This also works even if I call it with a `List<Item>` or similar.
