### ISSUE TITLE
Using both MongoDB pagination and Queryable pagination with default provider not working

### ISSUE THREAD

**Issue by Spaier** [ChilliCream/graphql-platform#6008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Can't use both Queryable and MongoDB providers without specifying ProviderName everywhere

### Steps to reproduce

Given startup
```
            .AddQueryableCursorPagingProvider("Queryable")
            .AddQueryableOffsetPagingProvider("Queryable")
            .AddMongoDbPagingProviders("MongoDb", defaultProvider: true)
            .InitializeOnStartup()
```
And queries
```
    [UseOffsetPaging(IncludeTotalCount = true, MaxPageSize = 200)]
    public IExecutable<MySimpleType1> MySimpleTypes1()
    {
        return dbContext.GetMySimpleTypes1MongoCollection().AsExecutable();
    }
    
    [UseOffsetPaging(IncludeTotalCount = true, MaxPageSize = 200, ProviderName = "Queryable")]
    public IQueryable<MySimpleType2> MySimpleTypes2()
    {
        return dbContext.GetMySimpleTypes2MongoCollection().AsQueryable();
    }
```
When I start the service
I get NotSupportedException from CanHandleAsync of Queryable pagination

Expected result: everything works

### Relevant log output

```shell
public override bool CanHandle(IExtendedType source)
    {
        throw new NotImplementedException(); // THIS thing throws from a loop of resolve pagination provider
    }
```

### Additional Context?

There's a workaround: specify ProviderName everywhere.

### Version

12.18.0

**Comment by Spaier** [comment]
The reason I tried this is because I need IMongoQueryable pagination.

**Comment by michaelstaib** [comment]
Can you create a minimal repro and attach it to this thread?

**Comment by glen-84** [comment]
Closing, for lack of a reproduction.
