### ISSUE TITLE
Unexpected Execution Error with Upload scalars and AddInstrumentation with RequestDetails.Variables

### ISSUE THREAD

**Issue by vbornand** [ChilliCream/graphql-platform#6017]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

If a mutation with a `IFile` is called and the diagnostics is enabled with variables logging:
```
.AddInstrumentation(o =>
{
        o.RequestDetails = HotChocolate.Diagnostics.RequestDetails.Default | HotChocolate.Diagnostics.RequestDetails.Variables;
})
```
The following errors occurs:
`{"errors":[{"message":"Unexpected Execution Error","extensions":{"message":"Unable to cast object of type \u0027HotChocolate.Types.FileValueNode\u0027 to type \u0027HotChocolate.Language.StringValueNode\u0027.","stackTrace":"   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteValue(ISyntaxWriter writer, IValueNode node)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteField(ISyntaxWriter writer, NameNode name, IValueNode value)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteObjectField(ISyntaxWriter writer, ObjectFieldNode node)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.\u003C\u003Ec.\u003CWriteObjectValue\u003Eb__15_0(ObjectFieldNode n, ISyntaxWriter w)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteMany[T](ISyntaxWriter writer, IReadOnlyList\u00601 items, Action\u00602 action, String separator)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteMany[T](ISyntaxWriter writer, IReadOnlyList\u00601 items, Action\u00602 action)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteObjectValue(ISyntaxWriter writer, ObjectValueNode node)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteValue(ISyntaxWriter writer, IValueNode node)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteField(ISyntaxWriter writer, NameNode name, IValueNode value)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteObjectField(ISyntaxWriter writer, ObjectFieldNode node)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.\u003C\u003Ec.\u003CWriteObjectValue\u003Eb__15_0(ObjectFieldNode n, ISyntaxWriter w)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteMany[T](ISyntaxWriter writer, IReadOnlyList\u00601 items, Action\u00602 action, String separator)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteMany[T](ISyntaxWriter writer, IReadOnlyList\u00601 items, Action\u00602 action)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteObjectValue(ISyntaxWriter writer, ObjectValueNode node)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteValue(ISyntaxWriter writer, IValueNode node)\r\n   at HotChocolate.Language.Utilities.SyntaxSerializer.Serialize(ISyntaxNode node, ISyntaxWriter writer)\r\n   at HotChocolate.Language.Utilities.SyntaxPrinter.Print(ISyntaxNode node, Boolean indented)\r\n   at HotChocolate.Diagnostics.ActivityEnricher.EnrichRequestVariables(HttpContext context, GraphQLRequest request, ObjectValueNode variables, Activity activity)\r\n   at HotChocolate.Diagnostics.ActivityEnricher.EnrichSingleRequest(HttpContext context, GraphQLRequest request, Activity activity)\r\n   at HotChocolate.Diagnostics.Listeners.ActivityServerDiagnosticListener.StartSingleRequest(HttpContext context, GraphQLRequest request)\r\n   at HotChocolate.AspNetCore.MiddlewareBase.ExecuteSingleAsync(HttpContext context, IRequestExecutor requestExecutor, IHttpRequestInterceptor requestInterceptor, IServerDiagnosticEvents diagnosticEvents, GraphQLRequest request, GraphQLRequestFlags flags)\r\n   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context)"}}]}`

### Steps to reproduce

1. Add the `UploadType`
2. Create a mutation with a `IFile` parameter
3. Enable the instrumention with RequestDetails.Variables
4. Call the mutation with a file

### Relevant log output

```shell
Unexpected Execution Error","extensions":{"message":"Unable to cast object of type \u0027HotChocolate.Types.FileValueNode\u0027 to type \u0027HotChocolate.Language.StringValueNode\u0027.","stackTrace":"   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteValue(ISyntaxWriter writer, IValueNode node)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteField(ISyntaxWriter writer, NameNode name, IValueNode value)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteObjectField(ISyntaxWriter writer, ObjectFieldNode node)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.\u003C\u003Ec.\u003CWriteObjectValue\u003Eb__15_0(ObjectFieldNode n, ISyntaxWriter w)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteMany[T](ISyntaxWriter writer, IReadOnlyList\u00601 items, Action\u00602 action, String separator)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteMany[T](ISyntaxWriter writer, IReadOnlyList\u00601 items, Action\u00602 action)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteObjectValue(ISyntaxWriter writer, ObjectValueNode node)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteValue(ISyntaxWriter writer, IValueNode node)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteField(ISyntaxWriter writer, NameNode name, IValueNode value)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteObjectField(ISyntaxWriter writer, ObjectFieldNode node)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.\u003C\u003Ec.\u003CWriteObjectValue\u003Eb__15_0(ObjectFieldNode n, ISyntaxWriter w)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteMany[T](ISyntaxWriter writer, IReadOnlyList\u00601 items, Action\u00602 action, String separator)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteMany[T](ISyntaxWriter writer, IReadOnlyList\u00601 items, Action\u00602 action)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteObjectValue(ISyntaxWriter writer, ObjectValueNode node)\r\n   at HotChocolate.Language.Utilities.SyntaxWriterExtensions.WriteValue(ISyntaxWriter writer, IValueNode node)\r\n   at HotChocolate.Language.Utilities.SyntaxSerializer.Serialize(ISyntaxNode node, ISyntaxWriter writer)\r\n   at HotChocolate.Language.Utilities.SyntaxPrinter.Print(ISyntaxNode node, Boolean indented)\r\n   at HotChocolate.Diagnostics.ActivityEnricher.EnrichRequestVariables(HttpContext context, GraphQLRequest request, ObjectValueNode variables, Activity activity)\r\n   at HotChocolate.Diagnostics.ActivityEnricher.EnrichSingleRequest(HttpContext context, GraphQLRequest request, Activity activity)\r\n   at HotChocolate.Diagnostics.Listeners.ActivityServerDiagnosticListener.StartSingleRequest(HttpContext context, GraphQLRequest request)\r\n   at HotChocolate.AspNetCore.MiddlewareBase.ExecuteSingleAsync(HttpContext context, IRequestExecutor requestExecutor, IHttpRequestInterceptor requestInterceptor, IServerDiagnosticEvents diagnosticEvents, GraphQLRequest request, GraphQLRequestFlags flags)\r\n   at HotChocolate.AspNetCore.HttpPostMiddlewareBase.HandleRequestAsync(HttpContext context
```

### Version

13.0.5

**Comment by michaelstaib** [comment]
This one is now fixed #6122
