### ISSUE TITLE
Add helper methods to make it easier to modify the schema

### ISSUE THREAD

**Issue by vlangber** [ChilliCream/graphql-platform#6020]
### Product

Hot Chocolate

### Is your feature request related to a problem?

If you add a base classwith the AddType, Hot Chocolate will automatically add the sub classes as well. 

We have two requirements:
- Possible to have more than one endpoint with different subsets of the whole schema.
- Some of the subclasses of base class should not be included in any of the schemas

From what we have been able to figure out, it is hard to modify the types in a schema as it is now. You can remove fields relatively easily with a TypeInterceptor, but it is not easy to remove a type from the schema. Yes, we can use Dynamic Schemas, but that means quite a bit of work, and it introduces a lot of complexity for something that is almost perfect with a much simpler implementation.

### The solution you'd like

We see two possible solutions that we think will improve Hot Chocolate and they should be relatively easy to make:

1.) Create an overload for AddType where subclasses aren't added automatically, so we can control which types we add to the schema. This would allow us to do something like this to build the schema:

```
var allTypes = StaticContext.GetAllContentTypes().Where(p => p.IsClass && !p.IsAbstract && p.GetTypeInfo().IsSubclassOf(typeToSearch)).ToList();
var filteredTypes = allTypes.Where(t => !excludedTypes.Contains(t)).ToList();
foreach (var type in filteredTypes) {                
    builder.AddType(type);
}
```
            
2.) Create some helper methods to alter the schema after it has been generated. Entity GraphQL have some methods you could use for inspiration that would solve our usecases ([https://entitygraphql.github.io/docs/schema-creation#modifying-the-generated-schema](https://entitygraphql.github.io/docs/schema-creation#modifying-the-generated-schema)):

```
schema.UpdateType<Person>(personType => {
    personType.RemoveField("firstName");
    personType.ReplaceField(
        "lastName",
        p => p.LastName.ToUpper(), // new expression to resolve the lastName field
        "New description"
    );
});
schema.RemoveType<TType>();
schema.RemoveType("TypeName");
// Remove a type and all fields that return that type
schema.RemoveTypeAndAllFields<Type>();
```

**Comment by michaelstaib** [comment]
The HotChocolate schema immutable. Once a schema is composed it cannot be changed.

> Create an overload for AddType where subclasses aren't added automatically, so we can control which types we add to the schema. This would allow us to do something like this to build the schema:

This basically exists, you can use the type objects to  specify which fields shall be added. If you add a field also the return type will be inferred. But only if you do not specify a more precise configuration first.

In the end we guarantee consistency.

 
> Create some helper methods to alter the schema after it has been generated.

As said, Hot Chocolate schemas are immutable and will even use frozen collection for .NET 8. For the execution engine we need the guarantee that a schema cannot change and it must be optimized for execution performance.

Why dont you use type definitions to mutate things? If you remove all usages of a type in a type interceptor we will remove  that type at the end of the process.

For version 14 we have created a project called HotChocolate.Skimmed which is a mutable schema. Its still in early development. It allows to refactor and reshape a schema. We at the moment use it to reshape schemas in a distributed context.

We have plans for redoing the schema builder for version 15 and also use skimmed there to allow for a more powerful schema inference engine. But this is a fairly complex task and at the moment at least 1 1/2 years off.


https://github.com/ChilliCream/graphql-platform/tree/main/src/HotChocolate/Skimmed

**Comment by michaelstaib** [comment]
I am closing this issue since what you want can be achieved already with version 13 although you need some lower level understanding of the type system for that.

**Comment by vlangber** [comment]
@michaelstaib Thank you for replying and explaining. Either I'm not understanding the TypeInterceptors, or I'm not explaining our use case very good. 

We already use the Type Interceptors to remove some properties we have in our C# classes that we don't want as fields in our schema. 

```
public override void OnAfterInitialize(ITypeDiscoveryContext discoveryContext, DefinitionBase definition) {            
            if (definition is ObjectTypeDefinition def) {                
                var fields = (IList<ObjectFieldDefinition>)def.Fields;                
                for (var i = fields.Count - 1; i >= 0; i--) {                    
                    if (fields[i].Name == "dataProvider" || fields[i].Name == "dataProviderCommon") {
                        fields.RemoveAt(i);
                    }
                }
            }            
        }    
```
But I can't find out how to remove types from the schema in a similar fashion. 

> Why dont you use type definitions to mutate things? If you remove all usages of a type in a type interceptor we will remove that type at the end of the process

This is the point I don't understand. 

If we have 3 classes, 

```
public class A{
	public string Name{get;set;}
	public int Id{get;set;}
}

public class B:A{
	public string Email{get;set;}
}

public class C:A{
	public int Calories{get;set;}
}
```
There are no usage of type B or C, but aren't they still added to the schema if I do builder.AddType<A>()? 

How do I remove type C from the schema in the above example?

**Comment by PascalSenn** [comment]
@vlangber  you are probably looking for this:
```csharp
            services
                .AddGraphQLServer()
                .ModifyOptions(x => x.RemoveUnreachableTypes = true

```

**Comment by vlangber** [comment]
@PascalSenn Ok, I wasn't familiar with that option. 

I guess what I'm wondering is what is the definition of an unreachable type?  Is it when there is are no queries or fields that reference the type? I can see what Intellisense is saying, but it's not clear to me what a Root Type is.

**Comment by michaelstaib** [comment]
If it cannot be reached by writing a query, mutation or subscription.
