### ISSUE TITLE
Local stitching nullify the results if an IEnumerable/IQueryable is returned from the stitched API

### ISSUE THREAD

**Issue by Mephistofeles** [ChilliCream/graphql-platform#6024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Stitching in HotChocolate nullify the results if an IEnumerable/IQueryable is returned from the stitched local API.
For example such a simple code returns null when querying stitched graph:
![image](https://user-images.githubusercontent.com/442690/229844472-e4b2d11e-3fb9-49c5-912e-c74dbfe38ea5.png)
![image](https://user-images.githubusercontent.com/442690/229845019-4a07b0b4-47db-42bf-9961-76f9e9caf73b.png)
As this bug breaks local stitching I can't upgrade HotChocolate to 13.
I think it's caused by implementation of IEnumerable in ListResult, which uses capacity instead of elements count to enumerate
![image](https://user-images.githubusercontent.com/442690/229845269-1870c05c-54c4-4fe7-b324-d34bd11b5ba7.png)
and stitching engine copies the ListResult entire array, with unset (null) values as well, which invalidates the query result as the list elements are non-nullable and it's removed from the result and whole list is set to null.

Fix should be simple, just using count instead of capacity in the enumerator of ListResult.

### Steps to reproduce

1. Stitch local schema returning IEnumerable of non-nullable items.
2. Query results are invalidated and null is returned instead.

### Version

13.0.5

**Comment by Mephistofeles** [comment]
Well, I've checked the code once again and see that it's already fixed on the main branch with https://github.com/ChilliCream/graphql-platform/pull/6019/files#diff-7f6b2cfb1fe487d1c83fef1ac3ced8aedcd70f5137ddff6c48a041abe81c1a09
Is this going to be released in 14, or is there a chance of getting the fix done in 13.x?

**Comment by michaelstaib** [comment]
13.1
