### ISSUE TITLE
Paginated output interceptor

### ISSUE THREAD

**Issue by angel-viejobueno** [ChilliCream/graphql-platform#6031]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Is not a bug,  but I'd like to know if exist any interceptor after pagination to avoid the Parallel.ForEach over the "Items" collection that we loaded from the database in the code below, the idea is complete the information of the elements in the "Items" list only for the elements send out to the client (paginated items), and avoid having to do that over all elements in the collection "Items", I'm using Offset Pagination.
 

```csharp
public class AppQueryType : ObjectType
{
    private readonly ILogger _logger;
    private readonly JsonSerializerOptions _serializerOptions;
    private readonly IHttpContextAccessor _httpContextAccessor;
    private readonly ISomeService _someService;
    private readonly ISettings _settings;
    private const string ExceptionMessage = "Bla bla bla";
    private const string SuccessfullyMessage = "Bla bla bla";

    public AppQueryType(
		ILogger logger, 
		IHttpContextAccessor 
		httpContextAccessor, 
		ISomeService someService, 
		ISettings settings)
    {
        _logger = logger.ForContext<AppQueryType>();
        _httpContextAccessor = httpContextAccessor;
        _someService = someService;
        _settings = settings;

        _serializerOptions = new JsonSerializerOptions { WriteIndented = true };
    }

    protected override void Configure(IObjectTypeDescriptor descriptor)
    {
        descriptor.Name(OperationTypeNames.Query);

		const string getEntities = "GetEntities";
        descriptor
           .Field(getEntities)
           .Name(getEntities)
           .UseOffsetPaging<entityType>()
           .UseFiltering<CommonFilterType<EntityModel>>()
           .UseSorting<CommonSortType<EntityModel>>()
           .Resolve(async context =>
			   {
				   _logger.Debug("Start {method}", getEntities);
				   IQueryable<EntityModel> outputList;
				  
				   try
				   {
					   //set culture
					   var culture = HttpHelper.GetCultureInfoFromHttpContext(_httpContextAccessor);
					   Thread.CurrentThread.CurrentCulture = new CultureInfo(culture);                   

					  //get headers
					   var headers = HttpHelper.GetHttpHeaders(_httpContextAccessor);                  

					   //service
					   var service = context.Service<IService<EntityModel, Entities.Entity>>();                  

					   //query
					   var response = await service.GetAll(headers);                   

					   var guidType1 = HttpHelper.GetGuidType1(headers);
					   var guidType2 = HttpHelper.GetGuidType2(headers);                   

					   Parallel.ForEach(response.Items, item =>
					   {
							   item.Name = _someService.DoingSomething(item.SomeKey,
										guidType1, guidType2, _settings.GuidType3);       
					
							   item.Description = _someService.DoingSomething(item.SomeSecondKey,
										guidType1, guidType2, _settings.GuidType3);
					   });                   

					   //output
					   outputList = response.Item1.AsQueryable();                  

					   if (_settings.AllowLoggingOutputs)
						   _logger.Verbose("{method} Result: --> {result}",
							   getEntities, JsonSerializer.Serialize(outputList, _serializerOptions));             
												 _logger.Information(SuccessfullyMessage, getEntities);
				   }
				   catch (Exception ex)
				   {
					   //log the error
					   _logger.Error(ex, ExceptionMessage, getEntities, ex.Message);
					   throw;
				   }               
				   _logger.Debug("End {method}", getEntities);
				   return outputList;
			   }
			);
	}
}
```

### The solution you'd like

This descriptor gets the elements for a particular Entity in a database and retrieves the data paginated, but we need to set a couple of values of this entity with information from another service, my question is:

have we got any way of intercepting the paginated output to assign the information only for the elements paginated not for the whole list of elements (current Parallel.ForEach)?
	
**Has the HotChocolate framework any mechanism for accessing the paginated values that are going to be sent to the client?**	
	
I would like to avoid this Parallel.ForEach for all values retrieved from the database and only change the values paginated that the descriptor is going to send to the client.

**Comment by wambaking** [comment]
After investigating more in-depth,

I've found this solution:



`        const string getEntities = "GetEntities";
        descriptor
           .Field(getEntities)
           .Name(getEntities)
           .Use(next =>
           {
               async ValueTask FieldDelegate(IMiddlewareContext middlewareContext)
               {
                   // before the resolver pipeline
                   await next(middlewareContext);
                   // after the resolver pipeline

                   //get headers
                   var headers = HttpHelper.GetHttpHeaders(_httpContextAccessor);
				   var guidType1 = HttpHelper.GetGuidType1(headers);
				   var guidType2 = HttpHelper.GetGuidType2(headers);

                   if (middlewareContext.Result is CollectionSegment query)
                   {
                       Parallel.ForEach(query.Items, item =>
                       {
                           var entityModel = (entityModel)item;

                           entityModel.Name = _someService.DoingSomething(item.SomeKey,
										guidType1, guidType2, _settings.GuidType3);       

                           entityModel.Description = _someService.DoingSomething(item.SomeSecondKey,
										guidType1, guidType2, _settings.GuidType3);
                       });
                   }
               }

               return FieldDelegate;
           })
           .UseOffsetPaging<entityType>()
           .UseFiltering<CommonFilterType<EntityModel>>()
           .UseSorting<CommonSortType<EntityModel>>()
           .Resolve(async context =>
           {
               _logger.Debug("Start {method}", getEntities);
               IQueryable<EntityModel> outputList;
               try
               {
                   //set culture
                   var culture = HttpHelper.GetCultureInfoFromHttpContext(_httpContextAccessor);
                   Thread.CurrentThread.CurrentCulture = new CultureInfo(culture);

                   //get headers
                   var headers = HttpHelper.GetHttpHeaders(_httpContextAccessor);

                   //service
                   var service = context.Service<IService<EntityModel, Entities.Entity>>();

                   //query
                   var response = await service.GetAll(headers);

                   //output
                   outputList = response.Item1.AsQueryable();

                   if (_settings.AllowLoggingOutputs)
                       _logger.Verbose("{method} Result: --> {result}", 
                           getEntities, JsonSerializer.Serialize(outputList, _serializerOptions));

                   _logger.Information(SuccessfullyMessage, getEntities);
               }
               catch (Exception ex)
               {
                   //log the error
                   _logger.Error(ex, ExceptionMessage, getEntities, ex.Message);
                   throw;
               }

               _logger.Debug("End {method}", getEntities);
               return outputList;
           });`


You can close the ticket, thanks.

**Comment by angel-viejobueno** [comment]
After investigating more in-depth,

I've found this solution:


`       const string getEntities = "GetEntities";
        descriptor
           .Field(getEntities)
           .Name(getEntities)
           .Use(next =>
           {
               async ValueTask FieldDelegate(IMiddlewareContext middlewareContext)
               {
                   // before the resolver pipeline
                   await next(middlewareContext);
                   // after the resolver pipeline

                   //get headers
                   var headers = HttpHelper.GetHttpHeaders(_httpContextAccessor);
				   var guidType1 = HttpHelper.GetGuidType1(headers);
				   var guidType2 = HttpHelper.GetGuidType2(headers);

                   if (middlewareContext.Result is CollectionSegment query)
                   {
                       Parallel.ForEach(query.Items, item =>
                       {
                           var entityModel = (entityModel)item;

                           entityModel.Name = _someService.DoingSomething(item.SomeKey,
										guidType1, guidType2, _settings.GuidType3);       

                           entityModel.Description = _someService.DoingSomething(item.SomeSecondKey,
										guidType1, guidType2, _settings.GuidType3);
                       });
                   }
               }

               return FieldDelegate;
           })
           .UseOffsetPaging<entityType>()
           .UseFiltering<CommonFilterType<EntityModel>>()
           .UseSorting<CommonSortType<EntityModel>>()
           .Resolve(async context =>
           {
               _logger.Debug("Start {method}", getEntities);
               IQueryable<EntityModel> outputList;
               try
               {
                   //set culture
                   var culture = HttpHelper.GetCultureInfoFromHttpContext(_httpContextAccessor);
                   Thread.CurrentThread.CurrentCulture = new CultureInfo(culture);

                   //get headers
                   var headers = HttpHelper.GetHttpHeaders(_httpContextAccessor);

                   //service
                   var service = context.Service<IService<EntityModel, Entities.Entity>>();

                   //query
                   var response = await service.GetAll(headers);

                   //output
                   outputList = response.Item1.AsQueryable();

                   if (_settings.AllowLoggingOutputs)
                       _logger.Verbose("{method} Result: --> {result}", 
                           getEntities, JsonSerializer.Serialize(outputList, _serializerOptions));

                   _logger.Information(SuccessfullyMessage, getEntities);
               }
               catch (Exception ex)
               {
                   //log the error
                   _logger.Error(ex, ExceptionMessage, getEntities, ex.Message);
                   throw;
               }

               _logger.Debug("End {method}", getEntities);
               return outputList;
           });`


You can close the ticket, thanks in advance.
