### ISSUE TITLE
Null values in arrays are not deserialized to "null"

### ISSUE THREAD

**Issue by pixlcrashr** [ChilliCream/graphql-platform#6040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

Consider the following query:

```graphql
query User {
    id: Int!
}

query Query {
    users(ids: [String!]!): [User]!
}

---

query ListUsers($ids: [String!]!) {
    users(ids: $ids) {
        __typename
        id
    }
}
```

Now, if `users` returns the following (valid!) result

```json
{
    "data": {
        "users": [
            { ... },
            null,
            ...
        ]
    }
}
```

Strawberry Shake throws an error that it can not find the `__typename` on the `null` object - which is logically true but does not make any sense.
The following .NET exception is thrown:
```
System.InvalidOperationException: 'The requested operation requires an element of type 'Object', but the target element has type 'Null'.'
```

The following is the generated deserialization method for above query:
```csharp
private global::Test.GraphQl.State.UserData? Deserialize_IListUsers_Users(global::System.Text.Json.JsonElement? obj)
{
	if (!obj.HasValue)
	{
		return null;
	}

	var typename = obj.Value.GetProperty("__typename").GetString();
	if (typename?.Equals("User", global::System.StringComparison.Ordinal) ?? false)
	{
		return new global::Test.GraphQl.State.UserData(typename, id: Deserialize_NonNullableString(global::StrawberryShake.Json.JsonElementExtensions.GetPropertyOrNull(obj, "id")));
	}

	throw new global::System.NotSupportedException();
}
```

The line `var typename = obj.Value.GetProperty("__typename").GetString();` is the one that fails, because the input `obj` is of `JsonElement` value kind `JsonValueKind.Null` and is not generally a nullable type (`JsonElement?`).

Generally, this should be easily solvable by modifying the template that generates above function to:

```csharp
private global::Test.GraphQl.State.UserData? Deserialize_IListUsers_Users(global::System.Text.Json.JsonElement? obj)
{
	if (!obj.HasValue)
	{
		return null;
	}

        if (obj.Value.ValueKind == JsonValueKind.Null) {
                return null;
        }

	var typename = obj.Value.GetProperty("__typename").GetString();
	if (typename?.Equals("User", global::System.StringComparison.Ordinal) ?? false)
	{
		return new global::Test.GraphQl.State.UserData(typename, id: Deserialize_NonNullableString(global::StrawberryShake.Json.JsonElementExtensions.GetPropertyOrNull(obj, "id")));
	}

	throw new global::System.NotSupportedException();
}
```

Of course, above example does not handle non-nullable types.

I would appreciate it if you quickly do a hotfix on that.

### Steps to reproduce

See above.

### Relevant log output

```shell
System.InvalidOperationException: 'The requested operation requires an element of type 'Object', but the target element has type 'Null'.'
```

### Version

13.0.5

### Tasks ❤️ 
* [ ] Fix generating template for deserialization method.

**Comment by pixlcrashr** [comment]
@michaelstaib any news on this?

**Comment by nightroman** [comment]
@michaelstaib Our clients report this issue in the latest official SS 13.7.0 and tell that it seems to be fixed in v14 previews.
If v14 is not expected "soon", is there any chance to backport the fix (if this is the case) to some 13.x?

**Comment by michaelstaib** [comment]
Most of the bug fixes will be back ported. There is already a preview for 13

**Comment by nightroman** [comment]
Thank you @michaelstaib , we look forward for the update.

**Comment by s0bh** [comment]
Hello, Just wanted to check if this fix for deserialization issue when we should expect it to be released because I do have the same situation and upgraded to 13.8.1 and still not fixed on it, so any timeline for it?
