### ISSUE TITLE
Introspection Query travelgatex.com

### ISSUE THREAD

**Issue by michaelstaib** [ChilliCream/graphql-platform#6049]
travelgatex.com does only allow introspection queries if the operation is named `IntrospectionQuery`

- [x] Banana Cake Pop
- [x] Hot Chocolate Introspection Library 
- [x] Strawberry Shake Tooling

**Comment by michaelstaib** [comment]
@davidegolzi you can try out the BCP insider build here:
https://insider.bananacakepop.com/

**Comment by davidegolzi** [comment]
The schema is fetched, and i also try to make a simple query and it works.
If you release this patch in a alpha version of StraberryShake.Server i can try to upgrade my application with that version end try more coplex query.

**Comment by davidegolzi** [comment]
![image](https://user-images.githubusercontent.com/76689954/231748636-efba387b-3bd8-4876-af14-64594109baef.png)

**Comment by davidegolzi** [comment]
the only things are the two red mark in the editor that i can't understand why are there

**Comment by rstaib** [comment]
@davidegolzi the patch for Banana Cake Pop is now released in version 5.0.0

Use the [Web Version](https://eat.bananacakepop.com) or download the [App Version](https://bananacakepop.com).

Enjoy!

**Comment by davidegolzi** [comment]
@michaelstaib hi this fix is available also for the dotnet tool?
