### ISSUE TITLE
AddErrorInterfaceType<IErrorInterface> should have an option to reduce boilerplate

### ISSUE THREAD

**Issue by Arrivegrsmith** [ChilliCream/graphql-platform#6058]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Currently, **exceptions** that implement an **interface** that is registered with AddErrorInterfaceType are treated as unhandled/unexpected unless explicitly registered in an error factory + [Error(typeof(Type))] attribute. The result is an HTTP 500 response and no type 6a error selection pattern. This leads to a lot of boilerplate code. Implementations of the AddErrorInterfaceType's **interface** should be expected to be treated as GQL **errors**, not as unhandled exceptions.

### The solution you'd like

AddErrorInterfaceType<IErrorInterface> should have an option to automatically cast all unhandled **exceptions** that implement the registered **interface** to a base GQL **error** to be surfaced for mutation error selections when no explicit GQL **error** is defined for the **exception.** Additionally, I would like to see base error selection be available on the mutation without requiring an [Error(typeof(Type))] attribute specified.

This should also improve service layer separation of concern.

**Comment by michaelstaib** [comment]
> Currently, exceptions that implement an interface that is registered with AddErrorInterfaceType are treated as unhandled/unexpected unless explicitly registered in an error factory + [Error(typeof(Type))] attribute. The result is an HTTP 500 response and no type 6a error selection pattern. This leads to a lot of boilerplate code. Implementations of the AddErrorInterfaceType's interface should be expected to be treated as GQL errors, not as unhandled exceptions.

There does not need to be an error factory. But you must expose domain errors per mutation as from the client side you want to only deal with the domain errors for that mutation and not with generic errors that are automatically exposed through every mutation.

`[Error<MyDomainException>]` is all what is needed.

**Comment by michaelstaib** [comment]
> AddErrorInterfaceType should have an option to automatically cast all unhandled exceptions that implement the registered interface to a base GQL error to be surfaced for mutation error selections when no explicit GQL error is defined for the exception. Additionally, I would like to see base error selection be available on the mutation without requiring an [Error(typeof(Type))] attribute specified.

`AddErrorInterfaceType` has nothing to do with your exceptions and is barely ever needed.

**Comment by Arrivegrsmith** [comment]
@michaelstaib right now, if I surface an unhandled exception, HC will return an HTTP 500. What I am saying is that if I define an interface in C# that is used for HC's root ErrorInterfaceType, then **all C# exceptions implementing that interface** should be considered an implementation of that GQL SDL interface as well. This intrinsically means that implementations of that interface, even if they inherit the **Exception** class should be converted to expected errors that we can select via the type 6a pattern and return an HTTP 200 instead.

The reason this recommendation is different from your suggestion of using [Error] attributes is verbosity.
If I have a mutation that executes an injected service method which is very complex, it can have N thrown exceptions. Maybe N-1 of those thrown exceptions are considered exceptions to be handled by the UI. Decorating the mutation with N-1 [Error] attributes is not necessary when you consider the Interface implementations. Only once there is a **need** for a concrete GQL Type, should we require the [Error] attr. For rapid iteration, we would benefit from automatically casting those unhandled Exceptions that implement the AddErrorInterfaceType's Interface to a base GQL Type. Maybe that base GQL Type is automatically generated? Mutations would contain the error {} selector regardless of if an [Error] attr was defined and will always contain the base error interface object. This makes the responses predictable as well.

The code structure I would like to use is actually shown in a bug ticket: https://github.com/ChilliCream/graphql-platform/issues/6053. You'll notice a lack of an [Error] definition for **ExpectedExceptionC**. Since **ExpectedExceptionC** implements the GQL ErrorInterfaceType, it should be casted to that base GQL error shape and be returned in the mutation errors {} selection. Instead an HTTP 500 is thrown and the error will be surfaced in a root error array. This convolutes UI error handling and forces verbosity in the mutation conventions. Why are we ignoring inheritance and implied meaning of a GQL error interface in HC?

**Comment by PascalSenn** [comment]
Thank you for your input. I understand your concerns and would like to clarify a few points.

Firstly, it's important to note that the assumption that all Mutations return the ErrorInterfaceType is incorrect. The ErrorInterfaceType is merely a common interface implemented by all the errors in the GraphQL Schema.

Secondly, each mutation should have its own set of errors. It's important to only expose errors in the mutations that the user can influence. For example, a "UsernameAlreadyTaken" error is something the user can address by changing their username, whereas a "DatabaseNotAvailable" error is beyond the user's control.

Checkout this example: 
![image](https://user-images.githubusercontent.com/14233220/232913227-b0183b13-5b14-4dad-8aef-0281b66afca5.png)
![image](https://user-images.githubusercontent.com/14233220/232913254-48af2b94-fb60-40f3-ae4b-eafdbe0238f8.png)
![image](https://user-images.githubusercontent.com/14233220/232913274-a1c5e117-aaf7-4ac7-b605-e3e24d318a39.png)


the AddAssetToWatchlist has a specific error union, which is the correct approach.

Lastly, with the error attribute, you signal what errors can be returned by a specific mutation. If you have common errors, the easiest thing is to create a custom attribute, such as [DefaultErrors], that inherits from ObjectFieldDescriptorAttribute and registers the errors on the field descriptor.

```csharp
// Custom attribute for registering default errors
public class DefaultErrorsAttribute : ObjectFieldDescriptorAttribute
{
    protected override void OnConfigure(IDescriptorContext context, IObjectFieldDescriptor descriptor, MemberInfo member)
    {
        // Register common errors using the Error<TError>() method
        descriptor
            .Error<UnauthorizedOperation>()
            .Error<InvalidTenant>();
    }
}

// Usage of the DefaultErrors attribute on a mutation field
public class Mutation
{
    [DefaultErrors]
    [Error<UserNameAlreadTaken>]
    public async Task<User> UpdateUserName(Guid UserId, string UserName)
    {
        // Implementation of the mutation
    }
}
```

This approach should help you maintain a clean and less verbose code structure while ensuring proper error handling and response predictability.

**Comment by Arrivegrsmith** [comment]
@PascalSenn Thanks for that tip! The confusion is primarily the following:
1) Like you mention, the AddErrorInterface's intent can be confused with general interface behavior
2) Registering an error with a constructor or CreateErrorFrom taking an interface currently does not enable exceptions implementing it to be surfaced with the type 6a pattern, we get HTTP 500 instead. This kind of flies in the face of inheritance expectations.

It would be better if an Error constructor or CreateErrorFrom would be considered for all classes that inherit or implement the class or interface provided in the definition and then prioritized by hierarchy (specificity).
