### ISSUE TITLE
Querying only for total count of paginated items doesn't work with projections enabled when using inheritance in EF Core

### ISSUE THREAD

**Issue by Mephistofeles** [ChilliCream/graphql-platform#6059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I have a simple setup using entity inheritance with an abstract class and two concrete classes and a query returning the base class, with pagination and projection enabled. Running a query for total count with no other properties selected results in "Can't compile a NewExpression with a constructor declared on an abstract class" exception. Querying totalCount with any other property works fine.
I'm using 12.18.0 right now, but on 13.0.5 result is the same.

I think it's related to creating QueryableProjectionScope in QueryableProjectionContext:
```csharp
new QueryableProjectionScope(runtimeType, "_s1")
```
where runtimeType is an abstract class, but is not registered in _abstractType dictionary.

### Steps to reproduce

1. I've created an example https://gist.github.com/Mephistofeles/f6fb684ee45804dee9530f06088c698e
2. Querying for totalCount results in "Can't compile a NewExpression with a constructor declared on an abstract class" error.
 ```graphql
query {
  transactions {
    totalCount
  }
}
```
3.  Querying totalCount with any other property - works fine
```graphql
query {
  transactions {
    totalCount
    nodes {
      id
    }
  }
}
```

### Version

13.0.5

**Comment by Arrivegrsmith** [comment]
Following. FE devs complained about this exact issue when only caring about a count on a WHERE query.

**Comment by michaelmcneilnet** [comment]
We are also having this issue and have had to remove `abstract` from our classes, which is unfortunate as it means our types are less correct.

**Comment by mattkgross** [comment]
We're experiencing this issue with interfaces, too. This is a real inhibitor because now we can't query connection counts nakedly for any connection that returns an interface. This seems like a bug to me.

**Comment by michaelstaib** [comment]
@mattkgross can you open a new issue for your problem. I am going to close this one.

**Comment by madiganz** [comment]
@michaelstaib was there a new issue created for this? If not, what is the solution?
