### ISSUE TITLE
Make `CustomParameterExpressionBuilder<TArg>` non-sealed

### ISSUE THREAD

**Issue by xamir82** [ChilliCream/graphql-platform#6070]
### Product

Hot Chocolate

### Is your feature request related to a problem?

After watching the [Customizing the Resolver Compiler in Hot Chocolate](https://www.youtube.com/watch?v=C2YSeVK6Dck) video and playing with the resolver compiler stuff, it seems to me that it would make sense to make the generic `CustomParameterExpressionBuilder<TArg>` class non-sealed so users can inherit from it to create custom parameter expression builder classes that also implement `IParameterFieldConfiguration` just like what's shown in the video [here](https://youtu.be/C2YSeVK6Dck?t=1028).

Currently, if you want to do that, you need to inherit from the non-generic `CustomParameterExpressionBuilder`, and that requires a fair of amount of boring boilerplate (such as the `Build` and `CanHandle` methods, and the private `Expression<...>` field, shown in the video [here](https://youtu.be/C2YSeVK6Dck?t=1028)), which are all things that the generic `CustomParameterExpressionBuilder<TArg>` class already takes care of.
So why not let people inherit from it instead?

### The solution you'd like

This means you could reduce this:
```csharp
public class AuthenticatedUserParameterExpressionBuilder :
    CustomParameterExpressionBuilder,
    IParameterFieldConfiguration
{
    private static Expression<Func<IResolverContext, AuthenticatedUser?>> _expression =
        ctx => ctx.GetLocalState<AuthenticatedUser?>(nameof(AuthenticatedUser));

    public void ApplyConfiguration(ParameterInfo parameter, ObjectFieldDescriptor descriptor) =>
        descriptor.Use(next => async context =>
        {
            var authRetriever = context.Service<AuthRetriever>();
            context.SetLocalState(nameof(AuthenticatedUser), await authRetriever.User);
            await next(context);
        });

    public override Expression Build(ParameterExpressionBuilderContext context) =>
        Expression.Invoke(_expression, context.ResolverContext);

    public override bool CanHandle(ParameterInfo parameter) =>
        parameter.ParameterType == typeof(AuthenticatedUser);
}
```
To this:
```csharp
public class AuthenticatedUserParameterExpressionBuilder :
    CustomParameterExpressionBuilder<AuthenticatedUser>,
    IParameterFieldConfiguration
{
    public AuthenticatedUserParameterExpressionBuilder() : base(ctx => ctx.GetLocalState<AuthenticatedUser?>(nameof(AuthenticatedUser))) { }

    public void ApplyConfiguration(ParameterInfo parameter, ObjectFieldDescriptor descriptor) =>
        descriptor.Use(next => async context =>
        {
            var authRetriever = context.Service<AuthRetriever>();
            context.SetLocalState(nameof(AuthenticatedUser), await authRetriever.User);
            await next(context);
        });
}
```

**Comment by xamir82** [comment]
@michaelstaib @PascalSenn Sorry to tag you guys but just wanted to ask if you agree with this so I can create a pull request?

**Comment by michaelstaib** [comment]
Yeah ... go ahead.
