### ISSUE TITLE
Better support for Linq's GroupBy in GroupedDataLoader

### ISSUE THREAD

**Issue by EricStG** [ChilliCream/graphql-platform#6073]
### Product

Green Donut

### Is your feature request related to a problem?

In a `GroupedDataLoader`, we have some to use hairy Linq queries to be able to format the data in a shape that allow us to use `ToLookup` (multiple select + select many), when in some cases a single `GroupBy` would work

### The solution you'd like

In `GroupedDataLoader`, replacing `ILookup<TKey, TValue>` by `IEnumerable<IGrouping<TKey, TElement>>` (from which ILookup is derived from) would enable this scenario

**Comment by michaelstaib** [comment]
Its not as easy as that ... as the DataLoader needs to build a map from that ... what you can do is using the batch dataloader and create a `Dictionary<key, value[]>`

**Comment by michaelstaib** [comment]
I leave the issue open for discussion.

**Comment by michaelstaib** [comment]
We will deprecate the `GroupedDataLoader` as it really is just a `BatchDataLoader`. With the `BatchDataLoader` you can just put everything into a map which seem more natural.
