### ISSUE TITLE
wrong ServiceProvider in HC 13.1.0 previews / HC 14.x

### ISSUE THREAD

**Issue by OneCyrus** [ChilliCream/graphql-platform#6076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

HC 13.1.x and HC 14.x seems to have broken the Dependency Injection as registered services are not found in the ServiceProvider used by HC.

### Steps to reproduce

GetRequiredService fails with an exception as it can't find `Person` in the used ServiceProvider

```
            services.AddSingleton<Person>(new Person("test"));
            services
                .AddGraphQLServer()
                .AddQueryType<Query>()
                .AddMutationType<Mutation>()
                .AddType<Person>()
                .ConfigureSchema((s, b) =>
                {
                    var x = s.GetRequiredService<Person>();
                });
```

repro is in this branch here: https://github.com/OneCyrus/hc-inputtype-bug/blob/bug_configureSchemaDI/Startup.cs

### Version

13.1.x / 14.x

**Comment by michaelstaib** [comment]
Its deliberate. We are optimizing for AOT and the combined service provider does not work with AOT as we need to compile generic methods.... So you need to specifically tell us which DI you need.

**Comment by OneCyrus** [comment]
@michaelstaib any input on the recommended way to register services for schema building?
