### ISSUE TITLE
Easier way to get a generic `IOperationExecutor<T>`

### ISSUE THREAD

**Issue by valincius** [ChilliCream/graphql-platform#6089]
### Product

Strawberry Shake

### Is your feature request related to a problem?

I have a use case where I need to resolve an `IOperationExecutor<T>` but this are not registered to the global DI container, so I have to use some hacky way to do it.

Currently, my workaround is resolving the StrawberryShake IServiceProvider by name, with the following:
```c#
var clientServiceProviderType = typeof(DataClientServiceCollectionExtensions).GetNestedType("ClientServiceProvider", BindingFlags.NonPublic)!;
_clientServiceProvider = serviceProvider!.GetRequiredService(clientServiceProviderType)! as IServiceProvider;
```

My actual use case is taking a generic `IOperationRequestFactory` then creating an observable by calling `IOperationExecutor<>` which is all very hard since there's no interfaces on the generated objects. Here's my implementation:
```c#
private static IObservable<IOperationResult> BuildObservable<TAction>(Func<IDataClient, IOperationRequestFactory> subscriptionSelector, TAction action)
    {
        ArgumentNullException.ThrowIfNull(_dataClient); // generated strawberryshake client
        ArgumentNullException.ThrowIfNull(_clientServiceProvider); // the strawberryShake client service provider

        var factory = subscriptionSelector(_dataClient);
        var operation = factory.Create(null);

        var executorType = typeof(IOperationExecutor<>).MakeGenericType(factory.ResultType);
        var executor = _clientServiceProvider.GetRequiredService(executorType);

        var watch = executor.GetType().GetMethod("Watch", BindingFlags.Instance | BindingFlags.Public);
        var observable = watch!.Invoke(executor, new[] { operation, null }) as IObservable<IOperationResult>;

        return observable!;
    }
```

Please let me know if I am overcomplicating this and you've got a better way of doing it!
Thank you guys, you've got an incredible product here.

### The solution you'd like

I am just looking for a simpler way to subscribe to a subscription by it's type, so I can do something like the following:

```c#
public static IDisposable AddFluxorSubscription<TAction>(Func<IDataClient, IOperationRequestFactory> subscriptionSelector, TAction action, bool emitOnAdd = false)
    {
        ArgumentNullException.ThrowIfNull(_dispatcher);

        var observable = BuildObservable(subscriptionSelector, action);

        var subscription = observable.Subscribe(x => _dispatcher!.Dispatch(action));

        if (emitOnAdd)
            _dispatcher.Dispatch(action);

        return subscription;
    }

// usage
AddFluxorSubscription(x => x.OnBookAdded, (IOnBookAddedResult x) => new AddBookAction(x));
```

Ideally something like `_strawberryShakeClient.OnBookAddedSubscription.Subscribe((IOnBookAddedResult x) => ...)` would work for me, but exposing `ClientServiceProvider` would work (I don't like having to find it by it's name & use reflection, feels very hacky), or also putting an interface on the subscriptions which implements `Watch` would also work, I am open to any other ideas.

**Comment by michaelstaib** [comment]
I am not really getting why you do not just inject the operation?

**Comment by valincius** [comment]
> I am not really getting why you do not just inject the operation?

It does not get resolved, just comes back null for me. I can create an example.
