### ISSUE TITLE
Comments (with GraphQLDescription ) on Filter and Sorting InputType not showing 

### ISSUE THREAD

**Issue by sturlath** [ChilliCream/graphql-platform#6090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Comments are only being shown for fields and not the types them self´s.

```csharp
    [GraphQLDescription("This comment does NOT show up in the schema")]
    public class LandingFilterInputType : FilterInputType<Database.Landing>
    {
        protected override void Configure(IFilterInputTypeDescriptor<Database.Landing> descriptor)
        {
            descriptor.Field(f => f.Buyer)
                .Name("Buyer")
                .Description("This is a Buyer filter");
        }
    }
```

Below you can see that the type doesn´t get the comment.
![image](https://user-images.githubusercontent.com/2386572/234579332-5d661f09-2268-4049-a01d-902b495b936a.png)

Or is there some other mechanism that I should be using instead?

### Version

13.0.5

**Comment by michaelstaib** [comment]
If you use a fluent type you got to use descriptors:

```
    public class LandingFilterInputType : FilterInputType<Database.Landing>
    {
        protected override void Configure(IFilterInputTypeDescriptor<Database.Landing> descriptor)
        {
            descriptor.Description("This comment does NOT show up in the schema");
            descriptor.Field(f => f.Buyer)
                .Name("Buyer")
                .Description("This is a Buyer filter");
        }
    }
```

If you want to use the annotations you can do so on the underlying type: Database.Landing

Third alternative is to use xmldocs on Database.Landing
