### ISSUE TITLE
IDirectiveContext doesn't exist HC 13 .Custom Middleware are affected

### ISSUE THREAD

**Issue by Hgaray** [ChilliCream/graphql-platform#6092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

IDirectiveContext doesn't exist HC 13 .Custom Middleware are affected.
How could we get access to directive  with HC , IMiddleWareContext doesn't have Directive property to convert to custom directive

### Steps to reproduce

Old method contains public ValueTask Invoke(IDirectiveContext context) . it worked with HC 12. after upgrade to HC 13.0.5 it doesn't work

/var directive = context.Directive.ToObject<MyDirective>();

### Version

13.0.5

**Comment by michaelstaib** [comment]
This is not a bug. Join the community channel and ask your questions there:
slack.chillicream.com
