### ISSUE TITLE
Issue with latest mongoDB.Driver version

### ISSUE THREAD

**Issue by JuVincent** [ChilliCream/graphql-platform#6108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Hi i got a problem with HC and the latest version of MongoDbDriver

I use HC 13.0.5 to expose a graphql server with a mongoDb database
I use Paging, filtering and sorting attribute on my query.

I want to perform a fulltext search query on my database the latest mongoDB Driver 2.19.1 and i can't downgrade this version because my search engine (MongoDB Atlas) is only compatible with this version

I wrote this search method

```
public IAggregateFluent<Offer> Search(string query)
{ 
        var pathDef = new SearchPathDefinitionBuilder<Offer>().Wildcard("*");
        var q = new SingleSearchQueryDefinition(query);
        var filter = Builders<Offer>.Search.Text(pathDef, q);
        var res = Collection.Aggregate().Search(filter);
        return res;
}
```
    
i got this error when i call the method result
    
`"message": "Method not found: 'MongoDB.Driver.IAggregateFluent`1<System.__Canon> MongoDB.Driver.IAggregateFluent`1.Skip(Int32)'.`
    
I try ton convert my IAggregateFluent object to a List avoid this error
and then i got this message
    
`The provided source HotChocolate.Data.QueryableExecutable is not supported for mongo paging`
    
Have you an idea to fix this maybe i make something bad.

Thanks for your help !

### Steps to reproduce

1. 

### Version

13.0.5

**Comment by tobias-tengler** [comment]
Your problem has the same underlying issue as [this issue](https://github.com/ChilliCream/graphql-platform/issues/6042) and will be fixed by the next Hot Chocolate version, once we update our internal package reference to the MongoDB driver.
Closing this as a duplicate for now.

**Comment by JuVincent** [comment]
thx for your answer ;)
