### ISSUE TITLE
Attribute 'Topic' is not valid on this declaration type. It is valid on 'Method' declarations only.

### ISSUE THREAD

**Issue by LeXaMeN** [ChilliCream/graphql-platform#6111]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Documentation says:

> We can even use the Topic attribute on dynamic arguments of the subscription field.
> https://chillicream.com/docs/hotchocolate/v13/defining-a-schema/subscriptions#dynamic-topics

Visual Studio says:

> Attribute 'Topic' is not valid on this declaration type. It is valid on 'Method' declarations only.

### Steps to reproduce

Example:
```
public class Subscription
{
    [Subscribe]
    public Client ClientUpdated([Topic] int clientId, [EventMessage] Client client) => client;
}
```

### Version

13.0.5

**Comment by tobias-tengler** [comment]
This was a breaking change as part of v13 as detailed here: https://chillicream.com/docs/hotchocolate/v13/migrating/migrate-from-12-to-13/#topicattribute

The documentation needs to be updated.

**Comment by williamdenton** [comment]
when the docs get updated you might want to note that nameof can be used to get the argument name

```cs
public class Subscription
{
    [Subscribe]
    // What's inbetween the curly braces must match an argument name.
    [Topic($"{nameof(author)}")]
    public Book BookPublished(string author, [EventMessage] Book book)
        => book;
}

```

**Comment by aokellermann** [comment]
> when the docs get updated you might want to note that nameof can be used to get the argument name
> 
> ```cs
> public class Subscription
> {
>     [Subscribe]
>     // What's inbetween the curly braces must match an argument name.
>     [Topic($"{nameof(author)}")]
>     public Book BookPublished(string author, [EventMessage] Book book)
>         => book;
> }
> ```

You need extra curly braces here: `[Topic($"{{{nameof(author)}}}")]`
