### ISSUE TITLE
Using BCP Desktop unable to `Create Organization`

### ISSUE THREAD

**Issue by RichardWhitfield** [ChilliCream/graphql-platform#6118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Banana Cake Pop

### Describe the bug

I have a personal account in BCP which I have been using.  I would like to create an Organization for my company (presumably this will facilitate me sharing my queries and mutations). But I am unable to create the Organization.

### Steps to reproduce

1. In BCP desktop if I click my profile icon and then `Manage Organizations` followed by `Add organization`.
![image](https://user-images.githubusercontent.com/17287260/236348379-a8965c2f-3aea-4211-b642-002936a67292.png)

2. I am take to a screen where I can `Create` an organization.
![image](https://user-images.githubusercontent.com/17287260/236348477-2a103737-06de-49a9-9146-e5c70bdfdfa1.png)

3. I input a 'Display Name' and 'Name' (ensuring I follow the regex) but when I click `Create` I get an error 'The IdentityProvider field is required.' This field does not exist so I am unable to proceed.

![image](https://user-images.githubusercontent.com/17287260/236348682-6cceaf58-82de-4405-9ab4-e7d74a123439.png)

### Additional Context?

Version info:
![image](https://user-images.githubusercontent.com/17287260/236348914-c26dc7fa-6e7c-4384-ad90-e285f4099be7.png)

### Version

4.0.1

**Comment by RichardWhitfield** [comment]
One more note, I use GitHub as my identity provider and had previously authenticated against this using MFA.

**Comment by PascalSenn** [comment]
Thanks a lot for reporting this @RichardWhitfield ! 
This is fixed and should work now :)
