### ISSUE TITLE
Code-First field authorization does not work for role only

### ISSUE THREAD

**Issue by lavalleyjr** [ChilliCream/graphql-platform#6126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When attempting to add authorization to a field resolver using only roles and NOT a policy in Code-First, no authorization is performed.
This works in Annotation-based and not Code-First because Code-First does not add the following like the other `Authorize` overloads do
```
descriptor.Extend().Context.ContextData[AuthorizationRequestPolicy] = true;
```

Below is from an example in the v13 documentation

Annotation-Based - Works as expected 
The `AuthorizeAttribute` updates `ContextData[AuthorizationRequestPolicy] = true`
```
public class User
{
    public string Name { get; set; }

    [Authorize(Roles = new[] { "Administrator" })]
    public Address Address { get; set; }
}
```
Code-First - Does not work
The `Authorize` extension method does not update `ContextData[AuthorizationRequestPolicy] = true`
```
public class UserType : ObjectType<User>
{
    protected override Configure(IObjectTypeDescriptor<User> descriptor)
    {
        descriptor.Field(t => t.Address).Authorize(new[] { "Administrator" });
    }
}
```

### Steps to reproduce

1. Setup authentication and authorization in .NET Core and HotChocolate v13.0.5
2. Create a type and query with no authorization required
3.  Secure a single field
```
descriptor.Field("adminOnlyField")
            .Authorize(new[] { "Admin" })
            .Resolve("admin only data")
```
4. Submit a GraphQL query requesting the field `adminOnlyField` with an unauthenticated user
5. The `adminOnlyField` data is returned

### Version

13.0.5

**Comment by tobias-tengler** [comment]
There have been some authorization refinements in 13.1.0.
Could you try the latest preview and let us know if your problem persists?

**Comment by lavalleyjr** [comment]
It appears to be working correctly with the version `13.1.0-preview.9` nuget package. 👍 

It seems like the work-around would be to replace
```
.Authorize(new[] { "Admin" })
```
with
```
.Directive(new AuthorizeDirective(new[] { "Admin" }, ApplyPolicy.BeforeResolver));
```
Can you confirm?
