### ISSUE TITLE
Timeout not throwing exception

### ISSUE THREAD

**Issue by ankit20071991** [ChilliCream/graphql-platform#6132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I have added timeout in my application which is on .Net Core. But it does not throw any exception after timeout. Due to this my application is keep hanging. I need this on urgent. Please help

### Steps to reproduce

1. Added timeout                 .ModifyRequestOptions(o => o.ExecutionTimeout = TimeSpan.FromMilliseconds(30000))
2. Add delay in one of the query.
3. After timeout nothing happend.

### Version

12.15.2

**Comment by michaelstaib** [comment]
Are you honouring CancellationTokens in your resolvers?

**Comment by ankit20071991** [comment]
Could you please provide a snippet for that how to do it. I did not get
anything like that.

**Comment by tobias-tengler** [comment]
https://chillicream.com/docs/hotchocolate/v13/fetching-data/resolvers/#async-resolver

You basically add the CancellationToken to your resolver signature and the forward it to your business layer, where ut can be used to interrupt async work, after the specified timeout was hit.

**Comment by bartdebever** [comment]
Unsure if you already know this but, timeouts don't trigger when debugging. You need to run the project without debugger attached to reproduce timeouts locally (Control + F5 is the default keybind in Visual Studio)
