### ISSUE TITLE
Apollo Federation - Cannot specify `Key` attribute within object type extension.

### ISSUE THREAD

**Issue by RobTF** [ChilliCream/graphql-platform#6153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When creating an object type extension the @key directive is not set and an exception is thrown at startup stating that no types have a key defined.

```csharp
public class Something
{
   public string Id {get;set;}
   // other properties...
}

public class SomethingTypeExtensions : ObjectTypeExtension<Something>
{
    protected override void Configure(IObjectTypeDescriptor<Something> descriptor)
    {
        descriptor.Key("id");
    }
}
```

### Steps to reproduce

1. Create type.
2. Create object type extension.
3. Add Apollo Federation
4. Add  descriptor.Key call into the configure method of the type extension.
5. Boot the web application.
6. Make any GraphQL request (e.g. to request SDL)
7. Observe exception.

### Relevant log output
```
HotChocolate.SchemaException: For more details look at the `Errors` property.

1. The schema has no types with a KeyDirective and therefor no entities. Apollo federation requires at least on entity.
```

### Version

13.0.5

**Comment by michaelstaib** [comment]
Have you registered the type extension?

**Comment by RobTF** [comment]
Yep, that was the first thing I checked, the debugger also hits the line where I call `descriptor.Key()`.

**Comment by michaelstaib** [comment]
Not sure what it is in your setup. Why are you using a extension in this case? Have a look at the demo projects we provide.

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/graphql-platform/tree/main/src/HotChocolate/ApolloFederation/examples

**Comment by michaelstaib** [comment]
Also for questions use slack.chillicream.com please. Try first to resolve your question in the apollo-federation channel on slack and do not create bugs for questions.

**Comment by RobTF** [comment]
Hi,

This is a bug if I'm correct and not a question.

I've already been through your examples and they do not show an example of using a type extension.

The team responsible for our abstractiosj libraries don't want to take a dependency on your federation assembly for the sake of adding an attribute to a POCO object.

Would you like me to prepare an example showing the issue or is there no interest in investigating?

Thanks

**Comment by michaelstaib** [comment]
Sure, you can do so. Do the other teams provide a fluent type configuration that you need to extend?
