### ISSUE TITLE
Apollo Federation - Apollo fails to read schema due to HTTP header expectation which is not met.

### ISSUE THREAD

**Issue by RobTF** [ChilliCream/graphql-platform#6154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I have enabled Apollo federation on a web API and attempted to have the Apollo server read the schema from the API.

```typescript
const gateway = new ApolloGateway({
    supergraphSdl: new IntrospectAndCompose({
        subgraphs: [
            { name: "myapi", url: "https://myhost/graphql" }
        ],
    })
});
``` 

However when I start the Apollo server I get the following error;
```
Error: Couldn't load service definitions for "myapi" at https://myhost/graphql: Expected JSON response body, but received: {"data":{"_service":{...
```

Interesting the data the error message says has been received by the Apollo server *is* JSON. So I dug a bit deeper and found that the issue is with the HTTP headers sent from HotChocolate and expected by Apollo, namely `Content-Type`.

To get the SDL, Apollo uses the following query against the GraphQL endpoint;
```graphql
query __ApolloGetServiceDefinition__ { _service { sdl } }
```

HotChocolate returns the SDL, with a `Content-Type` of `application/graphql-response+json; charset=utf-8`.

![image](https://github.com/ChilliCream/graphql-platform/assets/4292237/b9fa0dd3-0707-4608-8334-d0e84a215b8a)

However, looking at the Apollo source code, the schema loader has the following logic in `RemoteGraphQLDataSource.ts`, line 291.

```typescript
  public parseBody(
    fetchResponse: FetcherResponse,
    _fetchRequest?: NodeFetchRequest,
    _context?: TContext,
  ): Promise<object | string> {
    const contentType = fetchResponse.headers.get('Content-Type');
    if (contentType && contentType.startsWith('application/json')) {
      return fetchResponse.json();
    } else {
      return fetchResponse.text();
    }
  }
```

Note that it is looking for a `Content-Type` starting with `application/json`, not `application/graphql-response+json`. If the test fails it returns `.text()` and fails, hence the error I'm seeing.

I'm not sure what the ideal solution is here? Is it possible/desirable to override the headers sent back from HotChocolate or would this affect other clients? Is the header HotChocolate sends back standard? Is Apollo wrong?

Any advice appreciated!

### Steps to reproduce

1. Create Apollo Federated GraphQL API
2. Attempt to federate with Apollo Server 4.7.1+ and Apollo Gateway 2.4.3+

### Relevant log output

```shell
Error: Couldn't load service definitions for "myapi" at https://myhost/graphql: Expected JSON response body, but received: {"data":{"_service":{...
```

### Version

13.0.5

**Comment by RobTF** [comment]
Ok, I've made further progress on this - so reading the HC docs it looks as thought the header is a standard, but perhaps draft? Apollo doesn't seem to respect it but fortunately as the HC documentation suggests, you can use the `Accept` header to override the response `Content-Type`. By default Apollo sends Accept as `*/*` despite it being quite picky about needing `application/json`.

Apollo can be changed to send an `Accept` header to change the responses from HC.

```typescript
const gateway = new ApolloGateway({
    supergraphSdl: new IntrospectAndCompose({
        subgraphs: [
            { name: "myapi", url: "https://myhost/graphql" }
        ],
        introspectionHeaders: {
            Accept: "application/json",
        },
    }),
    buildService({ name, url }) {
        return new HotChocolateDataSource({ url });
    },
});

class HotChocolateDataSource extends RemoteGraphQLDataSource {
    willSendRequest({ request, context }) {
        request.http.headers.set("Accept", "application/json");
    }
}
```

**Comment by michaelstaib** [comment]
For Apollo tooling switch Hot Chocolate to Legacy support as we already implement the GraphQL over HTTP spec or specify proper accept header as outlined in the GraphQL over HTTP Spec.

**Comment by RobTF** [comment]
OK, any printers to docs?

Your Apollo examples ate out of date. To clarify, the bug for HC is a documentation issue as neither docs nor examples account for or explain this issue.

**Comment by tobias-tengler** [comment]
https://chillicream.com/docs/hotchocolate/v13/server/http-transport/#supporting-legacy-clients

The legacy switch is explained here.
