### ISSUE TITLE
MongoDb paging providers break Entity Framework paging in the same schema.

### ISSUE THREAD

**Issue by CJS2025** [ChilliCream/graphql-platform#6157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

In my query type I have some resolvers that return data from Entity Framework and some that return data from MongoDB. I want to use pagination for both data sources. I am finding that when I am using the MongoDB paging provider it is breaking the entity framework pagination. For example my ER resolver now returns the following error:

"The provided source Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[[AI.ProjectModels.Models.PPS.SQL.Works, AI.ProjectModels, Version=1.0.274.0, Culture=neutral, PublicKeyToken=null]] is not supported for mongo paging"

So it looks like MongDB paging provider is overriding.

I'm sure there must be a solution to this but after many days of searching I have been unable to find it.

### Steps to reproduce

1. my pipeline is set up as follows

```
.AddGraphQLServer()
                .AddProjections()
                .AddSorting()
                .AddFiltering()
                .RegisterDbContext<AIDataContext>() 
                .AddType<WorksiteObjectType>()   
                .AddType<PossessionObjectType>()  
                .AddQueryType<Query>()
                .AddMongoDbFiltering()
                .AddMongoDbSorting()
                .AddMongoDbPagingProviders();
```

My query class includes the following Entity Framework resolver

```
[UsePaging(IncludeTotalCount = true, DefaultPageSize = 10, MaxPageSize = int.MaxValue - 1)]
        [UseProjection]
        [UseFiltering]
        [UseSorting]
        public IEnumerable<Works>? GetWorks(AIDataContext context)
        {
            return context.Workss;
        }
```

and the following MongoDb resolver

[UsePaging]
        [UseProjection]
        [UseSorting]
        [UseFiltering]
        public IExecutable<OracleProjectGraphQL> GetOracleProjects([Service] IMongoCollection<OracleProjectGraphQL> collection)
        {
            return collection.AsExecutable();
        }

### Relevant log output

```shell
When calling GetWorks:

"The provided source Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[[AI.ProjectModels.Models.PPS.SQL.Works, AI.ProjectModels, Version=1.0.274.0, Culture=neutral, PublicKeyToken=null]] is not supported for mongo paging"
```

### Version

13.0.5

**Comment by michaelstaib** [comment]
If you are using multiple paging providers you need to name them and refer to them by key.
