### ISSUE TITLE
Obsolete properties disappear from input object type in schema

### ISSUE THREAD

**Issue by pasanascentic** [ChilliCream/graphql-platform#6164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

After migrate from hot chocolate 12 to 13. Obsolete properties inside the input object type get disappeared.

### Steps to reproduce

Please follow the commits inside this repo https://github.com/pasanascentic/hotchocolate12To13

### Version

13.0.5

**Comment by jhpetersen** [comment]
Hey @michaelstaib i just ran into the same issue after upgrading to HC13 - and i think this has to be mentioned as a breaking change in the docs.
As it seems `inputFields` field on the introspection query has an optional argument `includeDeprecated`, which defaults to false.
I don't know, if this was already the default on HC12, but in HC12 the `@deprecated` directive was not automatically added to input fields, whereas in HC13 those are added automatically from XML documentation.
So in my opinion this is not related to banana cake pop in the first place, but to hot chocolate introspection.

And worse: i have schema snapshot tests, in which the deprecated input fields are included, so i did not notice that apollo generator produces a different schema!

Can we somehow opt-in to change the default to include deprecated fields on inputFields?

**Comment by michaelstaib** [comment]
This is actually a spec change Hot Chocolate now implements but is not yet supported by tooling. We will update probably for version 7.

**Comment by rstaib** [comment]
Fixed in Version 7
