### ISSUE TITLE
DataLoaderBase.LoadAsync is not propagating cancellation token

### ISSUE THREAD

**Issue by ahnseunghae** [ChilliCream/graphql-platform#6194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Green Donut

### Describe the bug

We are getting errors like `Connection id "XXX" application never completed.` from time to time. it happens when a client sends a request which using data loader and cancel the request before it ends. our code is just like workshop code [AttendeeType](https://github.com/ChilliCream/graphql-workshop/blob/ccf79744dca2822ba1f98e54e2a116cb0e1eb9e6/code/session-5/GraphQL/Types/AttendeeType.cs#L21) and [AttendeeByIdDataLoader](https://github.com/ChilliCream/graphql-workshop/blob/ccf79744dca2822ba1f98e54e2a116cb0e1eb9e6/code/complete/GraphQL/DataLoader/AttendeeByIdDataLoader.cs#L12).

I think the reason is cancellation token should be propagated from AttendeeType to AttendeeByIdDataLoader but it isn't. because [DataLoaderBase](https://github.com/ChilliCream/graphql-platform/blob/c1402d5457bfa58c180f1925253d07784bd2c7ee/src/GreenDonut/src/Core/DataLoaderBase.cs#LL87C63-L87C80) is propagating a cancellationToken to nowhere.

### Steps to reproduce

1.

### Version

12.18.0

**Comment by michaelstaib** [comment]
You have to pass it down to the LoadAsync method.

**Comment by ahnseunghae** [comment]
I did, but the cancellation token is not propagated to LoadBatchAsync method.
