### ISSUE TITLE
High cpu load after upgrading to 13.1.0

### ISSUE THREAD

**Issue by xwrs** [ChilliCream/graphql-platform#6208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Once updated from HC 13.0.5 to 13.1.0 application suddenly starts consuming a lot of CPU. Not immediately after start but in 5-15 minutes. Essentially requests are stopped from being processed. Queries start to take up to 1 minute to execute.
**UPD:** Important observation: subscriptions initiate exponential CPU utilisation growth. around 100 subscriptions essentially render the service unresponsive

Grafana dashboard metric illustration of the issue:
<img width="1316" alt="image" src="https://github.com/ChilliCream/graphql-platform/assets/1047069/42c1c01f-7514-420c-b9bf-23bf2b91a232">

CPU profiling attempts were done using perf tool. I didn't observe anything that stands out from default .net classes. All CPU consumption is taken by classes related to the ThreadPool.
Flame graph generated by the profiling report shows even less data:
<img width="1212" alt="image" src="https://github.com/ChilliCream/graphql-platform/assets/1047069/0c683b2a-635c-4421-9ca7-f6eb042d8d9e">

### Steps to reproduce

1. Update to version 13.1.0 or 14 preview
2. Make requests
3. Wait
4. Check metrics

### Relevant log output

```shell
N/A
```

### Additional Context?

net7.0
DB: MongoDB
hosting: Docker, Kubernetes. (base image: mcr.microsoft.com/dotnet/aspnet:7.0)
HC websocket subscriptions with redis adapter
Authorization enabled
Data Loaders are not used - resolvers only if that matters

### Version

13.1.0

**Comment by xwrs** [comment]
Issue seems to exist on Redis subscriptions alone as well

**Comment by MarS0K** [comment]
I experience same issue with InMemorySubscriptions.

**Comment by Driedas** [comment]
Same issue, InMemorySubscriptions as well. Downgrading back to 13.0.5 fixes the issue.

**Comment by xwrs** [comment]
here is the code we have added and which seems to be disposing the sourceStream properly. It is causing internal HC subscription loop in `DefaultSourceStream` class to break
`Task.Factory.StartNew(async () =>
        {
            while (true)
            {
                if (cancellationToken.IsCancellationRequested)
                {
                    await sourceStream.DisposeAsync();
                    break;
                }

                await Task.Delay(1);
            }
        });
        await foreach (var item in sourceStream.ReadEventsAsync().WithCancellation(cancellationToken))`

**Comment by janveldhuis** [comment]
I have the same problem, using .NET 6 with version HC 13.1.0, running with "dotnet run" on my desktop.

In Banana Cake Pop when I start "Run" on a subscription everything is ok

Then when I press "Cancel", to stop the subscription, my app starts to cpu spike in the Task manager,
this is instant with the Subscription Protocol set to Auto, GraphQL WebSocket or Apollo WebSocket,
with GraphQL SSE, there is a wait time of around 6 seconds, before the cpu usage starts to spike.

**Comment by michaelstaib** [comment]
This one is  now fixed with 13.2.0-preview.2
