### ISSUE TITLE
`UseProjection` does not work with filtered include in ef core

### ISSUE THREAD

**Issue by eduardocp** [ChilliCream/graphql-platform#6209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When using `UseProjection` together with a include and and a field expression to filter the inner join ([using this tutorial to filter the inner join](https://learn.microsoft.com/en-us/ef/core/querying/related-data/eager#filtered-include)), the projection removes the filter.

### Steps to reproduce

Example code:

```cs
public class Book {
    public int Id { get; set; }
    public Author Author { get; set; }
}

public class Author {
    public int Id { get; set; }
    public ICollection<Book> Books { get; set; }
}
```

Inside the service:
```cs
...
public IQueryable<Book> GetBooks() {
    return db.Books.Include(x => x.Author.Where(y => y.Id == 1));
}
...
````

The query:
```graphql
query {
  books {
    id
    authors {
      id
    }
  }
}
```

### Version

13.0.5

**Comment by michaelstaib** [comment]
Closing this issue as answered
