### ISSUE TITLE
Button for adding all possible fields during query

### ISSUE THREAD

**Issue by andreamorello93** [ChilliCream/graphql-platform#6213]
### Product

Banana Cake Pop

### Is your feature request related to a problem?

When quering data, using intellisense we can select a field one at a time. for big entities this could be a problem.

### The solution you'd like

I think it would be useful to have a button during intellisense popup that enable the user to automatically add all possible fields for the actual query (TOP 1 level)

**Comment by PascalSenn** [comment]
This is now possible with the operation builder

https://github.com/ChilliCream/graphql-platform/assets/14233220/13e7a743-146e-47c1-8b59-3d628651247e

**Comment by przemyslawszafranski-ttc** [comment]
> This is now possible with the operation builder
> 
>  Screen.Recording.2024-05-09.at.20.32.08.mov

Is it possible to select every nested property without clicking it manually?
