### ISSUE TITLE
Different response status code between HotChocolate 13.0.5 and 13.1.0

### ISSUE THREAD

**Issue by EricStG** [ChilliCream/graphql-platform#6219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

With 13.1.0, when a request is sent without a token, HC returns a status code of 500. In 13.0.5, it was 401.

### Steps to reproduce

1. Have Authorize on a query
2. Upgrade to 13.1
3. Request without a token

### Relevant log output

```shell
N/A
```

### Additional Context?

Full repro available at Full repro: https://github.com/EricStG/HC131AuthRepro

But since the code is simple enough, here's the main bit:
```
using HotChocolate.Authorization;

var builder = WebApplication.CreateBuilder(args);
builder.Services
    .AddAuthorization()
    .AddAuthentication();

builder.Services
    .AddGraphQLServer()
    .AddAuthorization()
    .AddQueryType<Query>();

var app = builder.Build();

app.UseRouting();

app.UseAuthentication();
app.UseAuthorization();

app.MapGraphQL();

app.Run();

public class Book
{
    public string Title { get; set; }
}

[Authorize]
public class Query
{
    public Book GetBook() =>
        new Book
        {
            Title = "C# in depth.",
        };
}
```

### Version

13.1.0

**Comment by psiservices-dbrink** [comment]
Seeing the same behavior after upgrading to 13.1.0.

**Comment by michaelstaib** [comment]
This is correct ... we messed up authorization with 13.0.x. Now the default behaviour is in line with version 12 plus all the improvements we did.

The reason for the 500 in this case is because the root field was non-null and this lead the error propagation to erase the result. Which is correct.

**Comment by cimicdk** [comment]
If this is not being reopened, could you please document how we can configure HotChocolate to return 401? I have multiple versions of mobile app's released. I cannot suddenly return a 500 error and this blocks me from updating HotChocolate

Also, shouldn't a change like this be a major version change? So instead of going from 13.0.5 -> 13.1.0 it should be 14? It's a pretty big change to add to a minor version update

**Comment by michaelstaib** [comment]
This is graphql spec behavior called non-null propagation. The status code itself can be controlled via header.

**Comment by cimicdk** [comment]
Could you please eleborate? I might be looking the wrong places, but how would you control the response of HotChocolate by the header or put it in legacy mode?

**Comment by tobias-tengler** [comment]
https://chillicream.com/docs/hotchocolate/v13/server/http-transport/#supporting-legacy-clients
