### ISSUE TITLE
Set timeout on `HttpClient`

### ISSUE THREAD

**Issue by krispharper** [ChilliCream/graphql-platform#6221]
### Product

Strawberry Shake

### Is your feature request related to a problem?

When making requests using a Strawberry Shake-generated client library, we're hitting the default timeout of 100 seconds for the `HttpClient` class.

### The solution you'd like

We'd like the ability to change the timeout value.

**Comment by michaelstaib** [comment]
This can already be done with the HttpClientFactory.
https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.timeout?view=net-7.0

**Comment by krispharper** [comment]
Maybe I'm being dense, but where is the hook in Strawberry Shake that allows specifying that override? In the generated code I see the `HttpClientFactory` service being used to create a client, but I don't see a way for me to change it or provide my own factory.

**Comment by tobias-tengler** [comment]
```csharp
builder.Services
    .AddMyClient()
    .ConfigureHttpClient(client => 
{
    client.BaseAddress = new Uri("http://my.server.url");
    client.Timeout = TimeSpan.FromSeconds(100);
});
```

**Comment by krispharper** [comment]
Awesome, thank you.
