### ISSUE TITLE
Stitching $fields resolver works only for dictionaries

### ISSUE THREAD

**Issue by EvilVir** [ChilliCream/graphql-platform#6225]
### Product

Hot Chocolate

### Is your feature request related to a problem?

I know Stitching is out of support, but this is small fix that can help people that needs to use it and can't wait for Fusion to replace it.

Anyway problem is that `FieldScopedVariableResolver` works only for `IReadonlyDictionary` types. It might be ok when stiching two remotes on gateway but doesn't cut it when gateway has own schema to which remotes are added.

### The solution you'd like

Ability for `$fields.` variable to resolve property values of POCOs, not only dictionaries.

**Comment by michaelstaib** [comment]
I am closing this issue as we do not want to include reflection code into schema stitching.

**Comment by EvilVir** [comment]
I understand, is there any other way you can advice that I can implement to make this work?
