### ISSUE TITLE
Custom AuthorizationHandlers will only be called if ApplyPolicy.BeforeResolver is set on the queried field.

### ISSUE THREAD

**Issue by DeSebastianSimon** [ChilliCream/graphql-platform#6274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

In HotChocolate 13.1 and 13.2, custom AuthorizationHandlers will only be called if the ApplyPolicy.BeforeResolver is set on the field.

This was not nessesary in v12 and i was told the changes in v13.0 in this area where reverted.

### Steps to reproduce

1. [showcase repo](https://github.com/DeSebastianSimon/HotChocolate-13-PolicyHander-issue)
1. Run Project as is.
1. Query the instance query below.
1. Query will result in 'AUTH_NOT_AUTHORIZED' response, no printout to console
1. Stop the instance.
1. Replace Program.cs line 24 with line 25
1. Start insance and query again
1. Query will return results and Console will have printed 'AuthHandler called.'

```
query {
  book {
    title
    author {
      name
    }
  }
}
```

ok result:

```
{
  "data": {
    "book": {
      "title": "Book Title",
      "author": {
        "name": "Author Name"
      }
    }
  }
}
```

not ok result:

```
{
  "errors": [
    {
      "message": "The current user is not authorized to access this resource.",
      "extensions": {
        "code": "AUTH_NOT_AUTHORIZED"
      }
    }
  ]
}
```

### Relevant log output

```shell
The working version logs 'AuthHandler called.' to console.

Non working version logs nothing, but will return 'AUTH_NOT_AUTHORIZED' to a query.
```

### Additional Context?

[conversation on slack](https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1685012974026499)

### Version

13.2.1

**Comment by michaelstaib** [comment]
Correct, just checked it and we overlooked a couple of overloads that still have the changed default.
