### ISSUE TITLE
GraphQL DateTime scalar should throw when no offset is specified

### ISSUE THREAD

**Issue by glen-84** [ChilliCream/graphql-platform#6276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

A user can currently specify a DateTime without an offset, which should be considered [invalid input](https://www.graphql-scalars.com/date-time/#test-cases).

This leads to confusing behaviour, where the server's offset is used by default.

### Steps to reproduce

Use a DateTime filter like:

```gql
articles(
    where: { publishedAt: { eq: "2022-06-08T16:44:00" } }
)
```

With a type converter like:

```cs
.AddTypeConverter<DateTimeOffset, DateTime>(
    dateTimeOffset => dateTimeOffset.UtcDateTime)
```

Expect the SQL to use `16:44:00`, but it uses `14:44:00`, since the server's offset is `+02:00`.

### Additional Context?

https://github.com/ChilliCream/graphql-platform/issues/2604#issuecomment-730189298

### Version

13.2.1

**Comment by michaelstaib** [comment]
Test Cases are specified here: [graphql-scalars.com/date-time](https://www.graphql-scalars.com/date-time/)
