### ISSUE TITLE
Customize the name generation logic

### ISSUE THREAD

**Issue by dmtrrk** [ChilliCream/graphql-platform#6277]
### Product

Hot Chocolate

### Is your feature request related to a problem?

I have a query:
```
public class TestQuery
{
  public int Run(int value)
  {
    return value * 2;
  }
}
```

Whenever I do
```
internal class TestQueryType : ObjectType<TestQuery> { ... }
```
this would generate a schema for `query { run(value: 10) }`.

I'm looking for a solution to specify a schema generation logic to be able to have such a result by default:
`query { test_run(value: 10) }`.

### The solution you'd like

`GraphQLName` attribute is sealed, so it is not possible to create a custom logic attribute.
I'm looking for a way to set a rule:
1. Attribute for `TestQuery` that can configure the naming rule of its methods
2. Global configuration for all queries
3. Ability to enhance field names e.g. `Field().Name()` with the ability to add a prefix/suffix only to the existing name that was inferred from the method info.

**Comment by michaelstaib** [comment]
For extension purpose we have the `DescriptorAttribute` you can implement this to have a custom naming pattern.

```graphql
public class MyNameAttribute : DescriptorAttribute
{
    protected internal override void TryConfigure(
        IDescriptorContext context,
        IDescriptor descriptor,
        ICustomAttributeProvider element)
    {
        if (descriptor is IObjectTypeDescriptor objectTypeDesc)
        {
            var definition = objectTypeDesc.Extend().Definition;
            definition.Name = "My_" + definition.Name;
        }
    }
}
```

If you need a more general rule to change naming you can extend the  `DefaultNamingConventions`.

```csharp
 public class CustomNamingConvention : DefaultNamingConventions
 {
     public override string GetArgumentName(ParameterInfo parameter)
     {
         var name = base.GetArgumentName(parameter);
         return name + "_Named";
      }
}
```
