### ISSUE TITLE
'IRequestExecutorBuilder' does not contain a definition for 'AddJsonSupport' and no accessible extension method 'AddJsonSupport'

### ISSUE THREAD

**Issue by chinthaka** [ChilliCream/graphql-platform#6316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I was following Fetch From REST documentation and came up with the following issue.

I cannot register Json Support (AddJsonSupport()) in the IServiceCollection. 

Code: 
```
builder.Services
	    .AddGraphQLServer()
	    .AddQueryType<Query>()
	    .AddTypeExtension<AssetSearchExtensions>()
	   .AddJsonSupport()
```

Build error: error CS1061: 'IRequestExecutorBuilder' does not contain a definition for 'AddJsonSupport' and no accessible extension method 'AddJsonSupport' accepting a first argument of type 'IRequestExecutorBuilder' could be found (are you missing a using directive or an assembly reference?)

Version: 13.3.0

I have a question about your namespace too. Why do you use namespace Microsoft.Extensions.DependencyInjection;?

https://github.com/ChilliCream/graphql-platform/blob/main/src/HotChocolate/Core/src/Types.Json/JsonRequestExecutorBuilderExtensions.cs

### Steps to reproduce

1. Trying to add dependency injection configuration to support JSON using AddJsonSupport()

### Additional Context?

![image](https://github.com/ChilliCream/graphql-platform/assets/630314/f3f40d44-e247-4e0d-975a-9114dbec1dbf)

### Version

13.3.0

**Comment by michaelstaib** [comment]
You need to add the package [HotChocolate.Types.Json](https://www.nuget.org/packages/HotChocolate.Types.Json). The method is an extension method.
