### ISSUE TITLE
Missing documentation about required graphql-preflight header for requests dealing with file uploads

### ISSUE THREAD

**Issue by krismale** [ChilliCream/graphql-platform#6317]
### Product

Hot Chocolate

### Is your feature request related to a problem?

We recently migrated our server from HotChocolate v12 to v13.2.1. This caused our mutations dealing with file uploads to break. Even after following the [migration guide](https://chillicream.com/docs/hotchocolate/v13/migrating/migrate-from-12-to-13) and the [files guide](https://chillicream.com/docs/hotchocolate/v13/server/files) we still could not make our mutations work again.

The solution was to add a request header called graphql-preflight to our requests coming from our graphql clients (we use Apollo and urql). This was mentioned as a solution in a thread on your Slack channel but we could not find it anywhere in the docs.

### The solution you'd like

Update the documentation so that others who are facing the same issue can easily find the solution. Since this is related to file handling, I suggest to add it to the [files guide](https://chillicream.com/docs/hotchocolate/v13/server/files)

**Comment by Psypher9** [comment]
This looks like it is already added to the documentation in a note on the [files guide](https://chillicream.com/docs/hotchocolate/v13/server/files) (see below):
![image](https://github.com/ChilliCream/graphql-platform/assets/15854173/c968992c-7a0d-479b-86ed-d5c7f03619de)
