### ISSUE TITLE
Add `IRequestContextAccessor` or equivalent

### ISSUE THREAD

**Issue by glen-84** [ChilliCream/graphql-platform#6318]
### Product

Hot Chocolate

### Is your feature request related to a problem?

I need to access the `ClaimsPrincipal` in a DI context. To do so, I've used:

```cs
builder.Services.AddScoped<IActiveUser>(serviceProvider => new ActiveUser(
    serviceProvider.GetRequiredService<IHttpContextAccessor>().HttpContext!.User));
```

However, this will not work in a testing environment, where there is no `HttpContext`. I need to access the `ClaimsPrincipal` that is set via global state.

From what I understand, this was possible using `IRequestContextAccessor` in previous versions of Hot Chocolate, but this interface is no longer available.

### The solution you'd like

Bring back `IRequestContextAccessor`, or some equivalent means of accessing global state within a DI context.

**Comment by michaelstaib** [comment]
We will not bring back `IRequestContextAccessor`. If you need such a functionality you can implement it on your own by using the `IRequestContextEnricher`.
