### ISSUE TITLE
Runtime REST client 

### ISSUE THREAD

**Issue by vasicvuk** [ChilliCream/graphql-platform#6319]
### Product

Hot Chocolate

### Is your feature request related to a problem?

I was wondering if there can be a possibility to work with REST Clients created in runtime. Currently, guide specifies running nswag to generate the client, instead we would like to load Specifications in runtime and then use the clients without running nswag.

### The solution you'd like

Option to load an swagger specification while in Runtime, and dynamically use the client.

**Comment by michaelstaib** [comment]
Yes ... you can just type things with the HotChocolate.Types.Json package.

https://www.youtube.com/watch?v=l2QsFlKYqhk

**Comment by vasicvuk** [comment]
Hi @michaelstaib, In this video the REST classes are created before build (not in runtime). My question was to have some universal REST client based on OpenAPI spec instead which will work in runtime by just registering specification instead of writing Repositories, Queries and similar.

**Comment by michaelstaib** [comment]
Its basically what it does ... you essentially need to provide the GraphQL typings and done. 

The one thing that is missing is a component that produces the GraphQL typings from an OpenAPI spec document. Is that something you would like to contribute? We can help you with the GraphQL specific things.

**Comment by vasicvuk** [comment]
There is one library from IBM that can maybe be used:

https://github.com/IBM/openapi-to-graphql
