### ISSUE TITLE
Slack links are not working

### ISSUE THREAD

**Issue by rhyder** [ChilliCream/graphql-platform#6320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Unable to join the chillicream slack. Link in the docs appears to have expired.
http://slack.chillicream.com/ 

### Steps to reproduce

1. Go to http://slack.chillicream.com/

### Additional Context?

What is the new slack link so I can get community support?

### Version

13.3.0

**Comment by michaelstaib** [comment]
The slack link is now updated and should work again. Thank you for reaching out.
