### ISSUE TITLE
Documentation Update for Apollo Federation

### ISSUE THREAD

**Issue by gmiklich** [ChilliCream/graphql-platform#6324]
### Product

Hot Chocolate

### Is your feature request related to a problem?

The [current documentation for V13](https://chillicream.com/docs/hotchocolate/v13/api-reference/apollo-federation) in regard to Apollo Federation simply says that support for it "is coming with Hot Chocolate 12.6".

### The solution you'd like

It'd be great to have some sort of examples/documentation around what is supported and what isn't.

**Comment by michaelstaib** [comment]
Closing this issue as it adds nothing,
