### ISSUE TITLE
HotChocolate v13.3.2 is set as a pre-release on github, but not as version number nor as nuget package

### ISSUE THREAD

**Issue by frabe1579** [ChilliCream/graphql-platform#6334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

This is not a bug of code, but maybe a bug in release pipeline.
v13.3.2 is out, but in GitHub is tagget `pre-release`.
The version number is a normal release, and the packages are also available as normal release via NuGet.
This is confusing. Can I install as a normal release, as from NuGet?

### Steps to reproduce

Look at Releases in GitHub, you will see v13.3.1, but via NuGet you will see v13.3.2

### Version

13.3.2

**Comment by michaelstaib** [comment]
https://www.nuget.org/packages/HotChocolate/13.3.2

**Comment by frabe1579** [comment]
Ok, but I don't understand why in GitHub releases this last release is tagged pre-release (from [project main page ](https://github.com/ChilliCream/graphql-platform) the last release is 13.3.1). Am I missig something? Is there any reason?

Thanks.
