### ISSUE TITLE
Possibility to view the error on an invalid graphql schema (Banana Cake Pop)

### ISSUE THREAD

**Issue by tauchmi** [ChilliCream/graphql-platform#6335]
### Product

Banana Cake Pop

### Is your feature request related to a problem?

I have multiple graphql schemas which come from different systems, one seems to be invalid. 
Banana Cake Pop does show a red button in the reload schema button top right but gives no further clues. The "Schema Reference" tab shows "Schema unavailable". No further information on what the problem is.

### The solution you'd like

The system providing a section with information what the problem is (duplicate naming, etc.) or at least a console.log with a bit of information.

**Comment by michaelstaib** [comment]
So Hot Chocolate never composes a schema?

**Comment by tauchmi** [comment]
The backend system that is failing is not using hot chocolate.

**Comment by michaelstaib** [comment]
Then it's not possible as the GraphQL server would need to be able to expose the error to BCP. If the server does that you can have a look at the new operations tab that also shows the introspection queries and their errors.

<img width="1588" alt="image" src="https://github.com/ChilliCream/graphql-platform/assets/9714350/86870238-89e4-4c16-9460-9efb40e125f1">

**Comment by michaelstaib** [comment]
cc @rstaib @artola

**Comment by tauchmi** [comment]
Well, the thing is the introspection queries do not indicate an error. In e.g. Altair I do get a message like "invalid schema" but also without more information.

The endpoint was corrected and Altair is working, but BCP still indicates an error (red dot) and schema unavailable.

**Comment by rstaib** [comment]
@tauchmi which version of BCP?

![image](https://github.com/ChilliCream/graphql-platform/assets/4325318/86db9fbe-8d0e-4d76-b2c8-6c40f483ac9a)

**Comment by rstaib** [comment]
And what do you see in the log panel?

![image](https://github.com/ChilliCream/graphql-platform/assets/4325318/878cbe21-c048-4356-a544-e0f391fafcbf)

**Comment by tauchmi** [comment]
![image](https://github.com/ChilliCream/graphql-platform/assets/1105737/f147d85b-8a70-4e96-aad7-5b01f7f1cdc2)

**Comment by rstaib** [comment]
Ahhh and please check the result of the last log entry `Introspection: http://localhost:5000/graphql`

**Comment by rstaib** [comment]
The request is showing a `200` status code but it could be that the GraphQL response contains errors.

**Comment by rstaib** [comment]
If that is the case we could extract the error and show it in the console as well

**Comment by tauchmi** [comment]
The logs do not indicate or contain any errors on the schema reload, but still bcp ist not able to display the schema.

Is the source code of bcp public?

![image](https://github.com/ChilliCream/graphql-platform/assets/1105737/d89ee85c-50fe-49f6-8245-dc17258740f6)
![image](https://github.com/ChilliCream/graphql-platform/assets/1105737/ba675961-c337-4f29-8dfb-59cd85e5944f)
![image](https://github.com/ChilliCream/graphql-platform/assets/1105737/1ff8d239-671f-4ae7-8939-b1f2146bb249)

**Comment by rstaib** [comment]
No the source code is not public. it's a free to use tool though. There is something strange ongoing. Could you please make sure that you have saved all your documents, then click the sync button in the footer, sign-out from BCP, remove the IndexedDB for BCP and then refresh the browser.

![image](https://github.com/ChilliCream/graphql-platform/assets/4325318/4bc4013f-2259-4977-b24b-db2d75436178)

**Comment by rstaib** [comment]
A few more questions:

1. Would it be also possible to share the Introspection Result with me so I can test if it's valid?
2. What GraphQL server are you using?

**Comment by tauchmi** [comment]
Deleting the database fixed the issue!

I guess when the api had an issue, this persisted in the database and did not refresh after correcting it?

Unfortunately I cannot share the result.
I hope you would not ask ;) The server is graphql.net 2.0.0-alpha something

**Comment by rstaib** [comment]
Okay, so it works now after following my steps I assume? I will check then why the introspection result get stuck in the DB.

**Comment by tauchmi** [comment]
That's correct

**Comment by pkese** [comment]
I'm having the same issue.
If I change the schema, I'm getting 'Schema unavailkable' error.

Deleting Indexed-Db fixes the problem.

I'm using BCP 15.0.4, DB version 19

**Comment by pkese** [comment]
Oh, I noticed, that there was indeed something wrong with my schema.
Some types were apparently using space characters in names:

```
Names must only contain [_a-zA-Z0-9] but "technologymonitoring_ai climate_job market - ai_countries_per_month_Filter" does not.
```
It would be nice if BCP could warn about such things instead of simply failing.

**Comment by michaelstaib** [comment]
@rstaib can this one be closed?

**Comment by rstaib** [comment]
@michaelstaib Yeah, can be closed now.
