### ISSUE TITLE
Result Pooling causes exxessive memory usage

### ISSUE THREAD

**Issue by JanEggers** [ChilliCream/graphql-platform#6343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I have code that returns large resultsets and after running the server for a while the memory usage balloons out of control.

the top allocations are in here:

![image](https://github.com/ChilliCream/graphql-platform/assets/6747376/e88b602f-c744-4056-9f08-b1d3e07be7a9)

please provide a sensible way to limit the result pool size.

the classes seem to support max size options:

https://github.com/ChilliCream/graphql-platform/blob/main/src/HotChocolate/Core/src/Execution/Processing/Result/ObjectResultPool.cs

but it does not seem to work as there are more than 512 items

https://github.com/ChilliCream/graphql-platform/blob/main/src/HotChocolate/Core/src/Execution/Processing/Result/ResultPoolDefaults.cs

### Steps to reproduce

fetch data

### Relevant log output

```shell
x
```

### Additional Context?

x

### Version

13.3.3

**Comment by JanEggers** [comment]
I let it run a bit longer and it seems there is another pool that is also eating up memory

![image](https://github.com/ChilliCream/graphql-platform/assets/6747376/133426fb-f3de-4362-953b-7470d935de9e)

**Comment by JanEggers** [comment]
our app usually uses 1.5 GB and after adding hotchocolate the memory usage ballooned to 13 GB

**Comment by michaelstaib** [comment]
How large are selection sets for your queries? Also are objects collected after some time? Can you provide us with a memory dump off your service?

**Comment by michaelstaib** [comment]
You can also join us on slack .... slack.chillicream.com and give me a ping and we have a look at what is wrong on your system.

**Comment by JanEggers** [comment]
maybe tomorrow im busy with meetings today

**Comment by JanEggers** [comment]
I was able to repro the issue with https://github.com/JanEggers/Playground with 100K Data rows and a query that fetches them all. 

there are a buch of result classes stuck in pools but it seems that is not the main issue. only 30MB of memory. but would like to get rid of them anyway. 

![image](https://github.com/ChilliCream/graphql-platform/assets/6747376/4dca5f63-8407-4eb0-a6ee-a7a7199b22f3)


I had a look at the code. whats the reason behind https://github.com/ChilliCream/graphql-platform/blob/main/src/HotChocolate/Data/src/EntityFramework/EntityFrameworkExecutable.cs ToList ing all the things?

wouldnt it be better to use json streaming?
https://www.tpeczek.com/2021/07/aspnet-core-6-and-iasyncenumerable.html

anyway guess i have to add paging anyways. i was hoping i can avoid it to increase consistency of the data.

**Comment by michaelstaib** [comment]
Closing this issue as it is not an issue in Hot Chocolate.
