### ISSUE TITLE
Add Cmd + K shortcut key to Search the documentation.

### ISSUE THREAD

**Issue by bannarisoftwares** [ChilliCream/graphql-platform#6351]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Add Cmd + K shortcut key to Search the documentation. Globally all documentation pages have this shortcut. See https://mui.com/ pages also

### The solution you'd like

Just enable Cmd + K shortcut to toggle search bar, I assuming your are already using aloglia, Hope the libary also have this feature, Just ON it. Thank you.

**Comment by artola** [comment]
@bannarisoftwares I implemented the shortcut for toggling the search, as you recommended. Thanks for the heads up.

https://github.com/ChilliCream/graphql-platform/assets/11500763/03fe4193-1dcd-4374-b682-d7f3350c1090
