### ISSUE TITLE
Nested mutation execution order is not correct, due to the specs

### ISSUE THREAD

**Issue by dkogithub** [ChilliCream/graphql-platform#6384]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Due to the specs:
https://spec.graphql.org/October2021/#sec-Normal-and-Serial-Execution

let’s assume we have a mutation field changeTheNumber that returns an object containing one field, theNumber. If we execute the following selection set serially:
```
{
  first: changeTheNumber(newNumber: 1) {
    theNumber
  }
  second: changeTheNumber(newNumber: 3) {
    theNumber
  }
  third: changeTheNumber(newNumber: 2) {
    theNumber
  }
}
```
The executor will execute the following serially:

Resolve the changeTheNumber(newNumber: 1) field
Execute the { theNumber } sub-selection set of first normally
Resolve the changeTheNumber(newNumber: 3) field
Execute the { theNumber } sub-selection set of second normally
Resolve the changeTheNumber(newNumber: 2) field
Execute the { theNumber } sub-selection set of third normally

HC executes it in reverse order in case of nested mutation.

### Steps to reproduce

1. Compile and run repro project
[NestedMutationRepro.zip](https://github.com/ChilliCream/graphql-platform/files/12161875/NestedMutationRepro.zip)
2. Go to Banana cake: yourserviceurl/graphql/ui
3. Run the next mutation:
```
mutation {
  modify {
    first: modifyTestData(version: 0) {
      id
    }
    second: anotherModifyTestData(version: 0) {
      id
    }
  }
}
```

Expected result: query result on Banana cake UI

Actual result: Wrong order exception

### Additional Context?

Note that on the root level mutation works as expected.

### Version

13.4.0

**Comment by tobias-tengler** [comment]
A few paragraphs down in the spec section you linked, it reads:
> When executing a mutation, the selections in the top most selection set will be executed in serial order, starting with the first appearing field textually.

Everything below the top-level mutation fields is treated as a query - you are selecting from the  result of the mutation field.

That's why nested mutations, as you've shown them, do not have any execution order guarantees and are therefore highly discouraged.

**Comment by michaelstaib** [comment]
Its not only discouraged but simply leads to non-spec compliant schema.
