### ISSUE TITLE
Limit mutation to only be available in Banana Cake Pop

### ISSUE THREAD

**Issue by gergo-szucs** [ChilliCream/graphql-platform#6386]
### Product

Hot Chocolate

### Is your feature request related to a problem?

I'd like to setup a few mutations that we should only be able to call directly from Banana Cake Pop and not by individual clients. What would be the best way to achieve this please?

### The solution you'd like

An easy way to disallow clients to use specific mutations.

**Comment by michaelstaib** [comment]
This is not possible in this way. 

What you can do... 

1. Have an Admin schema that has a different Authorization ... only people with certain criteria have access to it. This admin schema is everything the public schema is plus these mutations.

Alternatively:
2. Limit the execution of the mutation the authorisation policies.
