### ISSUE TITLE
Stage 6a Error Handling for Queries

### ISSUE THREAD

**Issue by Jonathan-Woo** [ChilliCream/graphql-platform#6391]
### Product

Hot Chocolate

### Is your feature request related to a problem?

I'm a big fan of the stage 6a error handling support for mutations but unfortunately, it appears that this support is not extended to queries. Currently, GraphQL errors thrown by HotChocolate have a 500 status code. Although I'm able to include an error message, this does not follow the stage 6a convention from Marc-Andre Giroux's [guide](https://productionreadygraphql.com/2020-08-01-guide-to-graphql-errors).

### The solution you'd like

I would like to request the same error handling support from mutations for queries.

**Comment by michaelstaib** [comment]
> Although I'm able to include an error message, this does not follow the stage 6a convention from Marc-Andre Giroux's [guide](https://productionreadygraphql.com/2020-08-01-guide-to-graphql-errors).

This depends on you error interface configuration.

We will not extend this to queries as it would lead to bad schema design. There are other patterns better suited for queries.

**Comment by Jonathan-Woo** [comment]
I see. Do you mind sharing what the better patterns are? The one from Marc-Andre Giroux seems really good already.

Additionally, what is the rationale for a convention for mutations but not for queries?
