### ISSUE TITLE
Allow setting Authorization options from code

### ISSUE THREAD

**Issue by gergo-szucs** [ChilliCream/graphql-platform#6393]
### Product

Banana Cake Pop

### Is your feature request related to a problem?

Each user needs to specify the Authorization options individually as I have not found a way to set them from code (e.g. like Swagger allows).

![image](https://github.com/ChilliCream/graphql-platform/assets/68896430/05cebe52-c5df-4e25-95e8-497e5377d3c1)

### The solution you'd like

A way (e.g. using `WithOptions`) to set the Authorization options from code, so the users of BCP only need to click Fetch Token. Is there any other way currently to share these settings please?

**Comment by artola** [comment]
@gergo-szucs Check the version of BCP that you are using (it might be outdated), otherwise you will see a "Fetch token" at the bottom of the auth view.

![image](https://github.com/ChilliCream/graphql-platform/assets/11500763/fb96085c-793f-4aa9-a6b9-c656e8b428a1)

**Comment by gergo-szucs** [comment]
> @gergo-szucs Check the version of BCP that you are using (it might be outdated), otherwise you will see a "Fetch token" at the bottom of the auth view.

Thanks @artola I have this at the bottom, I'm using the latest version in my project. What I'm looking for, is a way to pre-populate these values from code, so that whenever someone opens the BCP UI, they only need to fetch the token (and of course login on our authentication site), instead of requiring everyone to fill these values manually.

**Comment by rstaib** [comment]
@gergo-szucs Sign-in to BCP, then create an Organization, then invite team members, then create an API, then configure the Authorization Settings. Each Document created inside an API will automatically adapt the Authorization Settings. Also we have now a Token Fetch Button right next to the Schema Reload Button.

**Comment by michaelstaib** [comment]
Can this be closed?

**Comment by rstaib** [comment]
I guess so
