### ISSUE TITLE
AspNetCore.CommandLine support FederationSchemaPrinter

### ISSUE THREAD

**Issue by jetersen** [ChilliCream/graphql-platform#6402]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Would you welcome a PR that adds FederationSchemaPrinter support via an option in the HotChocolate.AspNetCore.CommandLine package?

for now, I have created something like this locally as a temporary solution. But perhaps it is better done in HotChocolate.AspNetCore.CommandLine?
```csharp
            if (args.IsGraphQLCommand())
            {
                var outputPath = args.Length > 1 ? args[1] : "schema.graphql";

                var schema = await host.Services.GetRequiredService<IRequestExecutorResolver>().GetRequestExecutorAsync();

                var sdl = FederationSchemaPrinter.Print(schema.Schema);

                await File.WriteAllTextAsync(outputPath, sdl);
            }
            else
            {
                await host.RunAsync();
            }
```

### The solution you'd like

`dotnet run -- schema export --printer FederationSchemaPrinter`

Related #5947

**Comment by jetersen** [comment]
WDYT @PascalSenn @michaelstaib I would be happy to contribute 👏

**Comment by michaelstaib** [comment]
Not really, as this would tie proprietary Apollo logic into the GraphQL core.

**Comment by jetersen** [comment]
Well via dependency injection that could be avoided or am I missing something 🤔
