### ISSUE TITLE
Remove the need to log in to Banana Cake Pop to use history

### ISSUE THREAD

**Issue by rkotenko** [ChilliCream/graphql-platform#6403]
### Product

Banana Cake Pop

### Is your feature request related to a problem?

I can't use history because I an restricted from logging into Banana Cake Pop at my work. I don't even really understand why I would need to be logged into use a graphql IDE

### The solution you'd like

Let me have graph query history in BCP without having to log in.  It makes zero sense from a developer point of view. Just save the history locally like any other UI does.

**Comment by michaelstaib** [comment]
You can use the GraphQL IDE without login. However, there are more things behind that login than just documents. The API nodes and environments are connected to the schema and client registry. We will not change these things. But we soon allow companies to host their own BCP backend.
