### ISSUE TITLE
Add to banana cake input definition [StringLenght()] value for strings 

### ISSUE THREAD

**Issue by andreamorello93** [ChilliCream/graphql-platform#6405]
### Product

Banana Cake Pop

### Is your feature request related to a problem?

When defining input objects it's not possibile knowing max lenght of strings untill firing server validation.

### The solution you'd like

Would be usefull having in input object definition max string length value read from [StringLeght()] attribute. As attribute [Required] for mandatory fields

**Comment by andreamorello93** [comment]
Something like
![Screen](https://github.com/ChilliCream/graphql-platform/assets/56473140/fc518139-58f4-472a-b1e0-aa36bba72a16)

**Comment by michaelstaib** [comment]
This is not as easy as you might think as this needs to work across platforms and there is no standard for this at the moment. Even more problematic is that GraphQL introspection at this point does not allow type system directives to be exposed. Once the introspection allows for such a thing we will explore it. But such thing needs to go through the GraphQL specification working group. There is an issue for enhancing the introspection already open.
