### ISSUE TITLE
Error Class With Nullable String Property incorrectly registering property as NonNullable. 

### ISSUE THREAD

**Issue by AntiTcb** [ChilliCream/graphql-platform#6414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Given this error class definition:
```cs
public class TestError
{
    public string? Message { get; set; } = null;
}
// or as a record
public record TestError(string? Message = null)
```

This is incorrectly registered to the schema as `Message` being nonnullable, when using Mutation Conventions. 
```cs
public class Mutation
{
    public MutationResult<SomeClass, TestError> TestFakeMutation(bool error = false)
    {
        return error ? new TestError() : new SomeClass();
    }

    public MutationResult<TestError> DirectFail()
        => new TestError();
}
public class MutationType : ObjectType<Mutation>{ }
```
Results in:
```graphql
type TestError implements Error {
  message: String!
}
```

I'd have expected this to be nullable as expected, or, a more specific error should be thrown if the expectation that classes like these need at least one non-nullable type. Calling either `TestFakeMutation` or `DirectFail` will cause an error to be thrown because `Message` was null.

### Steps to reproduce

https://github.com/AntiTcb/TestGraphQLNullabilityBug

### Relevant log output

```shell
{
  "errors": [
    {
      "message": "Cannot return null for non-nullable field.",
      "locations": [
        {
          "line": 9,
          "column": 12
        }
      ],
      "path": [
        "testFakeMutation",
        "errors",
        0,
        "message"
      ],
      "extensions": {
        "code": "HC0018"
      }
    }
  ],
  "data": {
    "testFakeMutation": {
      "someClass": null,
      "errors": null
    }
  }
}
```

### Version

13.4.0

**Comment by michaelstaib** [comment]
This is correct, as the default error template for conventions is with message as non-null. You can change that and add a different error interface for the mutation conventions.
