### ISSUE TITLE
Can't generate code

### ISSUE THREAD

**Issue by danny-zegel-zocdoc** [ChilliCream/graphql-platform#6421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

I followed the instructions here https://chillicream.com/docs/strawberryshake/v13/get-started/console but the code is not being generated.

### Steps to reproduce

1. follow the instructions in https://chillicream.com/docs/strawberryshake/v13/get-started/console

### Additional Context?

I'm using .NET 6

### Version

13.4.0

**Comment by danny-zegel-zocdoc** [comment]
i just found that the code is being generated but not in the "Generated" directory as documented

**Comment by raysuelzer** [comment]
@danny-zegel-zocdoc where is it going? i cannot find the generated c# classes anywhere.

**Comment by danny-zegel-zocdoc** [comment]
I see it under `<project-root>/obj/Debug/net6.0/berry/<client-name>.cs` and that file seems to have everything in it including the dependency injection code and the client itself
