### ISSUE TITLE
Replace Moq package

### ISSUE THREAD

**Issue by jarlef** [ChilliCream/graphql-platform#6428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Yesterday it became known that Moq (> 4.20.0) has started to include an obfuscated dll that scans the github history and uploads email addresses to a private server. Hot Chocolate currently uses an older package that is not affected, but its recommended to move away from this package asap since it has been reported to Microsoft.

https://github.com/moq/moq/issues/1372

### Steps to reproduce

N/A

### Version

N/A

**Comment by michaelstaib** [comment]
We are at the moment on Moq 4.18 and will stay on this package for some while. So we are not affected.

**Comment by michaelstaib** [comment]
Also, this is not a bug of our software!
