### ISSUE TITLE
Schema Endpoint is automatically prefixed with https:// even when using environment variable

### ISSUE THREAD

**Issue by kimbirkelund** [ChilliCream/graphql-platform#6432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Banana Cake Pop

### Describe the bug

I have a project where I'm not running https on localhost when developing but am in production, and I'd like to use BCPs Environments to control the Schema Endpoint. However that is not possible as BCP insists on prefix the Schema Endpoint with https:// even when the environment variable I'm referencing contains it.

As a fix I'd suggest just adding the prefix in the background after expanding variables.

### Steps to reproduce

1. Edit Schema Endpoint to not include http(s)://
2. Tab to next field
3. https:// is added as a prefix

### Version

8.0.2

**Comment by rstaib** [comment]
This fix goes today to insider (version: `10.0.0-insider.15`)

**Comment by rstaib** [comment]
It's now on insider https://insider.bananacakepop.com/
