### ISSUE TITLE
Automatic OData stitching

### ISSUE THREAD

**Issue by dtbenson43** [ChilliCream/graphql-platform#6443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

According to #748 automatic OData stitching was closed as completed, but I do not see it in the source code (maybe I'm missing it) and I don't see any references to it anywhere other than that issue. Was this feature actually completed or should the status be changed?

### Version

13.4.0

**Comment by michaelstaib** [comment]
We have abandoned OData stitching in favor of the new Fusion engine. At the moment we are focusing Open API ... the work can be tracked here.

https://github.com/ChilliCream/graphql-platform/pull/6398

**Comment by michaelstaib** [comment]
Just as a note... we will still have an OData Adapter but have refocused on what most community members are using. I expect our work on OData to start later this year (November/December). Until then you could use something like GraphQL Mesh in conjunction with HotChocolate Fusion
