### ISSUE TITLE
Custom Pagination should allow for omitted default argumetns

### ISSUE THREAD

**Issue by icanhasjonas** [ChilliCream/graphql-platform#6459]
### Product

Hot Chocolate

### Is your feature request related to a problem?

The support for custom pagination is great, but the control of arguments are not the best. I propose (I'll follow up with a PR if the appropriate), that we add an option to omit the standard pagination arguments to be emitted to the schema.

Background;
We're trying to move an old graphql code base into new light, and the pagination arguments have been. let's just say. non-standard. But that doesn't mean we don't want to use `Connection<T>`, because it is great. The team has been using an older, hand-rolled, `PageOf<T>` that roughly translates into the same as Connection, but now we're trying to cut all old code, and use the built in support for `Connection<T>`.

Currently we're stuck on controlling the arguments added by `UsePaging`.

### The solution you'd like

Add a parameter to `UsePaging` and `UseOffsetPaging` such as `omitArguments: true` where `first`, `after`, `before`, `last` are not added to the schema. 

For example
```cs
.Field( "someField" )
.UsePaging( omitDefaultPagingArguments: true )
.Resolve( context => ......)
```

... and
```cs
[UsePaging( OmitDefaultPagingArguments = true )]
public Connection<string> SomeField( .... )
```

Or a wild though, introduce a base attribute, that combines the basis for both Offset and Cursor paging that doesn't add arguments that users can extend? (I don't have a good vision of how to implement this alternative though 😂)

**Comment by michaelstaib** [comment]
At the moment I do not see this for the standard library. Paging already is very complex with tons of options. It sounds to me a very project specific issue and nothing that would make sense to a larger community. Technically you already can remove the arguments with type interceptors. But there are middleware and other things to consider. Paging also already has abstractions ... so you could build you very own third provider and use the connection type with it. Connecion for instance is an `IPage` and there is the `IPagingProvider` and `IPagingHandler`. There are all the parts there to build your very own paging that just uses what it needs.

**Comment by icanhasjonas** [comment]
I agree, that would be awesome. 

But, some of the magic to get `Connection<T>` to work is currently internal (All the goodies in `.UsePaging()`.

One solution would be to open up some of the internals/private, so a custom `.UseMyPaging()` would be more feasible. ( The currently private `PagingObjectFieldDescriptorExtensions.CreateConnectionTypeRef()` for example. Rolling my own `CreateConnectionTypeRef` cascades pretty fast into handfuls of other internal/private methods, extensions and helpers.

**Comment by icanhasjonas** [comment]
(PS. I'm happy to close the issue, as you said, a middleware can cleanup the unwanted arguments)
