### ISSUE TITLE
Creating a client side nuget package via StrawberryShake

### ISSUE THREAD

**Issue by gergo-szucs** [ChilliCream/graphql-platform#6466]
### Product

Strawberry Shake

### Is your feature request related to a problem?

We would like to save as much hassle for out clients as possible, so we've decided to look into creating a nuget package to consume our HotChocolate based GraphQL backend.

In short, we'd prefer the clients not having to deal with dotnet tool installations, generating the client code, implementing client side caching etc.

However, as I understand, generating the client side C# client for the clients requires the .graphql file to be present with all the queries, mutations the client would like to execute.

For us it would be important to understand and track what properties the clients are requesting when they send e.g. a Get query, so obviously we don't want to declare a query where all of the fields are being returned.

Is there a way to let the clients declare there own .graphql files and only compile the C# client at that point? The issue with this is even the DI registration is part of this generated file currently.

### The solution you'd like

A way to let us prepare most of the boilerplate code in a small nuget for our clients while still letting them declare their own graphql queries.

**Comment by michaelstaib** [comment]
You mean like the settings file and schema?

**Comment by michaelstaib** [comment]
Closing discussion as there is no feedback

**Comment by gathakursherweb** [comment]
Is it possible to create  nuget feed for local set up, settings file and schema and consume it in my différent applications to avoid this duplicate effort.
