### ISSUE TITLE
[Hot Chocolate]Subscription Topic Encryption as an option.

### ISSUE THREAD

**Issue by DanielxAsolvi** [ChilliCream/graphql-platform#6475]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Hi, we wanted to use subscription with Redis but we spotted that you are doing encryption of topic name which we are specifying. We wanted to communicate with external system which are posting messages on specific channels on Redis. Right now it is not possible to subscribe to existing channel which is not encrypted in the same way as you are doing.

### The solution you'd like

It will be good if you create a flag UseEncryption in subscription options or provide other way to turn off Topic Formatter. 
It will provide consumers of your library possibility to subscribe to existing channels which are not encrypted and communicate with external systems.

**Comment by michaelstaib** [comment]
The topic names are not encrypted. We in general in general prefix them and use the hash of that topic name. As there are restrictions with topic names depending on the system the md5 hash as hex string guarantees that all systems allow the topic name.

If you want to customize this I would opt out of the standard subscription providers and just roll your own. Its quite simple .... 

Have a stream with your subscription like so:

```csharp
public async IAsyncEnumerable<[Your_Event_Payload_Type]> CreateStream() ....
```

Then on your subscription refer to this stream:

```csharp
[Subscribe(With = nameof(CreateStream))]
public async User OnUserChange([EventMessage] Your_Event_Payload_Type message) ....
```

**Comment by DanielxAsolvi** [comment]
I understand that you are trying to solve problems of the topics restrictions and that's great that you are providing solution by hashing topics names. We already found a way to workaround this by inherit from DefaultPubSub class and create out own RedisPubSub implementation which is the same as yours but it is just not hashing topics names. 

We think in that way if you are providing support for redis we should be able to use your implementation and not being forced to use topic formatter, that will be developer responsibility to satisfy topics restrictions. 

The solution that you are proposing (Thank you for that) looks that We need to use our own implementation, We will be creating our own implementation which will be same as yours but just without hashing topic names.

Flag in the settings will be a good feature because it will allow users to use your implementation and connect with existing channels that different part of system are communicating with, it can be true by default but can but changed.

Imagine situation when you are planning to implement new service in your current system, you are choosing GraphQL over the Rest API after research you can see that HotChocolate is the best choice for you because it is providing great implementation of GraphQL and already have Redis Provider so it will be easy to implement service that will be communicating with other services using already existing channels. After Implementation of subscriptions you are finding out that your new service is not subscribing to existing channels but subscribing to different channels so you need to create your own implementation.

To avoid that kind of situation I still encourage you to create that flag in settings, if someone will want to use topic formatter it will be still there turned on by default if We want to turn off We can turn off topic formatter. Or you can implement different way to use your Pub/Sub Providers without topic formatters.

**Comment by danbopes** [comment]
I'm going to one up this by saying that the design is annoying if you want to implement to existing queues that are already created.

The topic formatter should be in a config somewhere, so that it can be overridden on the global level.
