### ISSUE TITLE
Data is lost during testing

### ISSUE THREAD

**Issue by Andras-Csanyi** [ChilliCream/graphql-platform#6483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I'm pretty sure I'm doing something wrong here...

I created test cases both Query and Mutation and the phenomena is the same. Data got lost in the call chain at a certain point.
I also created the same code non-static version and the result is exactly the same.

### Steps to reproduce

1. check out the code from [here](https://github.com/Andras-Csanyi/examples/tree/main/hc-losts-data-during-test/Solution1)
2. run the 2 tests in the `gql.test` project
3. the result will be an empty array in both cases
However!
If you put a breakpoint [here](https://github.com/Andras-Csanyi/examples/blob/b56cfbcccd88ccdd067160485259a94382d72d9d/hc-losts-data-during-test/Solution1/gql.test/TestServices.cs#L47) and observe what is in the instance, you'll see that the expected result is there.
But when the execution arrives [here](https://github.com/Andras-Csanyi/examples/blob/b56cfbcccd88ccdd067160485259a94382d72d9d/hc-losts-data-during-test/Solution1/gql.test/UnitTest1.cs#L25), which is the next step, the debugger shows that there is data in the instance.

I assumed that this might be due to `async` and `static` collision, but the result is the same when I modify the `TestServices` class to be not static.

### Version

13.5.1

**Comment by michaelstaib** [comment]
You are disposing the result before you consume it...

```csharp
        await using var result = await Executor.ExecuteAsync(request, cancellationToken);

        IQueryResult res = result.ExpectQueryResult();

        return res;
```

Result objects are pooled in HotChocolate... disposing them cleans them and removes the data in order to reuse associated memory.

In your tests you actually do not need to dispose them.
