### ISSUE TITLE
Updating/Removing deprecated dependencies in StrawberryShake.Transport.Http

### ISSUE THREAD

**Issue by lentrodev** [ChilliCream/graphql-platform#6486]
### Product

Strawberry Shake

### Is your feature request related to a problem?

Currently, [StrawberryShake.Transport.Http](https://www.nuget.org/packages/StrawberryShake.Transport.Http) references below deprecated packages:
- Microsoft.AspNetCore.WebUtilities - 2.2.0 ([deprecated](https://www.nuget.org/packages/Microsoft.AspNetCore.WebUtilities/2.2.0))
    - Microsoft.Net.Http.Headers - 2.2.0 ([deprecated](https://www.nuget.org/packages/Microsoft.Net.Http.Headers/2.2.0))
- StrawberryShake.Core
    - System.Collections.Immutable - 5.0.0 ([deprecated](https://www.nuget.org/packages/System.Collections.Immutable/5.0.0))

### The solution you'd like

1. Update the references to the deprecated packages to their latest non-deprecated versions.
2. If non-deprecated versions are not available or cannot be used, use replacement or implement missing logic.

**Comment by michaelstaib** [comment]
You can update them in your project ... `Microsoft.AspNetCore.WebUtilities` has a new preview version for .NET 8. We will not upgrade them as we have many people still using legacy with platforms like .NET Framework with StrawberryShake clients.
