### ISSUE TITLE
`Utf8GraphQLReader` doesn't unescape properly

### ISSUE THREAD

**Issue by rickardp** [ChilliCream/graphql-platform#6488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When deserializing a GraphQL request containing emojis, it works when the request was serialized using Newtonsoft but fails when serialized using System.Text.Json. The reason is that they escape the emoji differently.

### Steps to reproduce

This unit test passes

 ```
[Fact]
    public void EmojiSuccess()
    {
        // This test uses Newtonsoft to encode the string, which doesn't escape the emoji.
        var emojiString = Newtonsoft.Json.JsonConvert.SerializeObject("😀");
        var reader = new Utf8GraphQLReader(Encoding.UTF8.GetBytes(emojiString));
        Assert.True(reader.Read());
        Assert.Equal("😀", reader.GetString());
    }
```

while this unit test fails

```
    [Fact]
    public void EmojiFail()
    {
        // This test uses System.Text.Json to encode the string, which does escape the emoji.
        var emojiBytes = System.Text.Json.JsonSerializer.SerializeToUtf8Bytes("😀");
        var reader = new Utf8GraphQLReader(emojiBytes);
        Assert.True(reader.Read());
        Assert.Equal("😀", reader.GetString());
    }
```

### Relevant log output

```shell
The output of the failing test is this

Xunit.Sdk.EqualException
Assert.Equal() Failure
          ↓ (pos 0)
Expected: 😀
Actual:   ������
          ↑ (pos 0)
```

### Version

13.4.0

**Comment by michaelstaib** [comment]
Thanks for the tests ... I did not handle the UTF8 surrogate pairs correctly ... this is now done and I have integrated it into:
https://github.com/ChilliCream/graphql-platform/releases/tag/13.6.0-preview.5

**Comment by benmccallum** [comment]
Thanks for your persistence on this one @rickardp !
