### ISSUE TITLE
Directive Middleware is Singleton but captures FieldDelegate in constructor resulting in the wrong field being resolved on subsequent requests

### ISSUE THREAD

**Issue by williamdenton** [ChilliCream/graphql-platform#6492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I am in the process of upgrading to HC 12->13. I have some validation middleware that is registered by using a fluent directive. The way directives are registered/declared/used has changed  in HC13 and I have updated the directive as described in https://www.youtube.com/watch?v=egyO7rZOoMI
The difference between that example and the code below is the use of `Use<Middleware>` vs an inline lambda.

The issue I encountered is the wrong field mutation being resolved and the payload failing to be cast to the expected type.

### Steps to reproduce

With a schema declared like this

```cs

descriptor.Field("updateThing")
    .Type<NonNullType<ThingGraphType>>()
    .Argument("payload", arg => arg.Type<NonNullType<ThingUpdatePayloadType>>())
    .Resolve(
        async ctx =>
        {
              var input = ctx.ArgumentValue<ThingUpdatePayload>("payload");

              return await ctx.Service<IThingService>().Update(input, ctx.RequestAborted);  
        })
    .Directive<ValidateInputDirective>();
   
descriptor.Field("updateWidget")
    .Type<NonNullType<WidgetGraphType>>()
    .Argument("payload", arg => arg.Type<NonNullType<WidgetUpdatePayloadType>>())
    .Resolve(
        async ctx =>
        {
              var input = ctx.ArgumentValue<WidgetUpdatePayload>("payload");

              return await ctx.Service<IWidgetService>().Update(input, ctx.RequestAborted);  
        })
    .Directive<ValidateInputDirective>();
```

I declare the directive and the middleware like this
```cs
[DirectiveType("validateInput",DirectiveLocation.FieldDefinition)]
[ValidateInputDirectiveMiddleware]
public class ValidateInputDirective { }

public class ValidateInputDirectiveMiddlewareAttribute : DirectiveTypeDescriptorAttribute
{
    protected override void OnConfigure(IDescriptorContext context, IDirectiveTypeDescriptor descriptor, Type type)
         => descriptor.Use<ValidateInputMiddleware>();
}
```

The middleware is declared like this
```cs

public class ValidateInputMiddleware
{
  private readonly FieldDelegate _next;

  public ValidateInputMiddleware(FieldDelegate next)
  {
      _next = next;
  }

  public async ValueTask InvokeAsync(IMiddlewareContext context)
  {
      await _next(context);
  }
}
```

if i call the first mutation `updateThing` then the second mutation `updateWidget` i get this error

```
{
	"errors": [
		{
			"message": "Unable to convert the value of the argument `payload` to `WidgetUpdatePayload`. Check if the requested type is correct or register a custom type converter.",
			"locations": [
				{
					"line": 3,
					"column": 5
				}
			],
			"path": [
				"updateWidget"
			],
			"extensions": {
				"fieldName": "updateWidget",
				"argumentName": "payload",
				"requestedType": "WidgetUpdatePayload"
			}
		}
	]
}
```

This is because the middleware is singleton and has captured the field delegate on the first execution meaning on the second request it is invoking the incorrect mutation and the cast inside the `ctx.ArgumentValue<WidgetUpdatePayload>("payload");` fails.

As a work around I updated the directive middleware from
```cs
protected override void OnConfigure(IDescriptorContext context, IDirectiveTypeDescriptor descriptor, Type type)
     => descriptor.Use<ValidateInputMiddleware>();
```
to this inline lambda which solves the issue.
```cs
protected override void OnConfigure(IDescriptorContext context, IDirectiveTypeDescriptor descriptor, Type type)
    => descriptor.Use((next, _) 
        => async ctx 
            => await new ValidateInputMiddleware(next).InvokeAsync(ctx));
```

Searching the hotchocolate code base for example of other middleware I have found they all follow the pattern of injecting the FieldDelegate in the constructor. This suggests that the problem may be in the way the fluent directive is processed internally as I suspect most use cases for it would be via an attribute in rather than the fluent descriptor.

We are in the process of "modernising" the code base toward using implicit binding and attributes but this is a long road for us. The work around above will do in the short term but I feel this is a reasonable serious footgun that took me a long time to isolate and find the cause. Even describing this issue to my colleagues was difficult until I found the cause. A possible worse case could be that two mutations share an input type and ArgumentValue returns successfully and continues to execute the wrong mutation. Because the middleware is singleton it depends which field is executed first for which will fail which can make this issue appear transient if one of the fields is not commonly used.

### Version

13.5.1

**Comment by williamdenton** [comment]
furthermore if I swap out the directive with a use middleware like this i get a singleton middleware per field, and this does some very weird things to my database access which i haven't diagnosed yet.

```diff
descriptor.Field("updateWidget")
    .Type<NonNullType<WidgetGraphType>>()
    .Argument("payload", arg => arg.Type<NonNullType<WidgetUpdatePayloadType>>())
    .Resolve(
        async ctx =>
        {
              var input = ctx.ArgumentValue<WidgetUpdatePayload>("payload");

              return await ctx.Service<IWidgetService>().Update(input, ctx.RequestAborted);  
        })
+    .Use<ValidateInputMiddleware >();
-    .Directive<ValidateInputDirective>();
```

**Comment by williamdenton** [comment]
i believe the issue might be this:

https://github.com/ChilliCream/graphql-platform/blob/037594643d7b379dd366ee70ef977152858fbb8a/src/HotChocolate/Core/src/Types/Resolvers/DirectiveClassMiddlewareFactory.cs#L114-L118


not caching the instance created by Activate means the constructor is called with the correct FieldDelegate

```diff
         var sync = new object();
         MiddlewareFactory<TMiddleware, IServiceProvider, FieldDelegate>? activate = null;
         ClassQueryDelegate<TMiddleware, IMiddlewareContext>? invoke = null;
-        TMiddleware? instance = null;
 
         return (next, directive) =>
         {
... 
             return context =>
             {
-                instance ??= activate(context.Services, next);
+                var instance = activate(context.Services, next);
                 return invoke(context, instance);
             };
         };

```

As a side note, what happens if the middleware implements IDisposable, would that ever get called?

**Comment by michaelstaib** [comment]
Middleware in HotChocolate is singleton. If you have disposable state it should be used within the middleware. The middleware itself should not hold state. If this were different and you have a middleware on multiple fields it would allocate constantly.

**Comment by williamdenton** [comment]
But the only way of passing the next delegate is via the constructor. 

So the `Use<>` in the directive is a complete trap as there is no way it can work unless you only use a directive on one field. 

For directive middleware you must use the inline lambda notation only. 

Can the Use method be removed?

**Comment by michaelstaib** [comment]
This is a bug ... I focused on your fix and oversaw the issue ... the middleware must be cached in the first delegate ... this is analogue to the field middleware factory.
