### ISSUE TITLE
Exported schema not encoded for UTF

### ISSUE THREAD

**Issue by plhester** [ChilliCream/graphql-platform#6495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Exporting schema via url with **?sdl** querystring results in a Unicode UTF-8 encoded schema.graphql file.

Exporting schema via command line via **dotnet run -- schema export --output schema.graphql** results in a Western European Windows encoded schema.graphql file.  Should also be a Unicode file.

### Steps to reproduce

1. Export schema via browsing to ?sdl
2. Export schema again via dotnet run
3. Do a file diff/compare on the 2 files

### Version

13.5.0

**Comment by michaelstaib** [comment]
Can you retry this with the latest?
