### ISSUE TITLE
Allow DirectiveTypeAttribute to Be Repeatable

### ISSUE THREAD

**Issue by mattkgross** [ChilliCream/graphql-platform#6514]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Directives can be made repeatable using the `Repeatable()` configuration. However, while the DirectiveTypeAttribute has this configuration logic:

```
protected override void OnConfigure(
     IDescriptorContext context,
     IDirectiveTypeDescriptor descriptor,
     Type type)
{
     if (!string.IsNullOrEmpty(Name))
     {
         descriptor.Name(Name);
     }

     descriptor.Location(Location);

     if (IsRepeatable)
     {
         descriptor.Repeatable();
     }

     descriptor.Extend().Definition.Arguments.BindingBehavior = BindingBehavior.Implicit; 
}

```

the `IsRepeatable` property cannot be set when annotating with the attribute, as there is no constructor parameter to set it. Furthermore, the class is sealed, so you cannot inherit from it to create a repeatable subtype.

Current constructors:

```
public DirectiveTypeAttribute(DirectiveLocation location)
{
     Location = location;
}

public DirectiveTypeAttribute(string name, DirectiveLocation location)
{
     Name = name;
     Location = location;
}

```

### The solution you'd like

I propose either that we provide a constructor parameter for `IsRepeatable` to be set from, so that it can be configured during annotation, or that we unseal the class so that others can implement a repeatable subclass.

**Comment by michaelstaib** [comment]
This already works.

```csharp
[DIrectiveType(DirectiveLocation.Field, IsRepeatable = true)]
public class Foo
```
