### ISSUE TITLE
UsePaging returns the same row but with different cursor (duplicate)

### ISSUE THREAD

**Issue by John0x** [ChilliCream/graphql-platform#6518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I have the following API query:

```c#
	[Authorize]
	[UsePaging(MaxPageSize = 100, IncludeTotalCount = true, DefaultPageSize = 20)]
	[UseProjection]
	[UseSorting]
	public IQueryable<TransactionDto> GetTransactions([UserId] string userId, DataContext db, DateTime from, DateTime to)
	{
		return db.Transactions
			.Where(t => t.Account.UserId == userId)
			.Where(t => t.Date >= from && t.Date <= to)
			.ProjectToDto();
	}
``` 

On the initial fetch (without the after parameter), the endCursor is "MTk=". The according edge contains the row with id 25.
After calling fetchMore with `after: "MTk="` the first returned edge has the same row with id 25, but the cursor is "MjA=".

### Steps to reproduce

1. Create an API Endpoint as the one listed above
2. Query first without the "after" param
3. Query again with the "after" param with the endCursor

### Additional Context?

HC Version: 13.4.0
EF Core version: 7.0.9
DB System: Postgres
NpgSql Version: 7.0.4

### Version

13.4.0

**Comment by michaelstaib** [comment]
Can you create a repro that shows your issue?

**Comment by John0x** [comment]
Sure, here it is:
https://github.com/John0x/hc-repro

It seems to be connected to sorting.
My sample queries:
```c#
query initial {
  foos(order: {date: DESC}) {
    pageInfo {
      endCursor
    }
    edges {
      cursor
      node {
        id
      }
    }
  }
}

query after {
  foos(after: "NA==", order: {date: DESC}) {
    pageInfo {
      endCursor
    }
    edges {
      cursor
      node {
        id
      }
    }
  }
}
``` 

the "after" query returns one of the same objects, but with a different cursor.

**Comment by John0x** [comment]
@michaelstaib did you have a chance to look into it yet? :) 
The issue is currently blocking a release of mine
