### ISSUE TITLE
No latest version of HotChocolate.AspNetCore.Subscriptions

### ISSUE THREAD

**Issue by aateeque** [ChilliCream/graphql-platform#6526]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Hi

Not sure what the best category to ask this is, so filing as a bug.

In [HotChocolate documentation](https://chillicream.com/docs/hotchocolate/v13/get-started-with-graphql-in-net-core) it states that all packages should align to the same version. This is called out as a warning.

Though there is no new versions of `HotChocolate.AspNetCore.Subscriptions` since 10.5.5 on nuget. Is this package dead, and if so can we please put a note on its landing page in nuget with pointers to replacement?

### Steps to reproduce

1. Last published package at https://www.nuget.org/packages/HotChocolate.AspNetCore.Subscriptions 

### Version

13.4.0

**Comment by michaelstaib** [comment]
This is now backed into HotChocolate.AspNetCore.
