### ISSUE TITLE
Banana Cake Pop .Net middleware not working anymore

### ISSUE THREAD

**Issue by zulander1** [ChilliCream/graphql-platform#6534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Banana Cake Pop

### Describe the bug

Since the Upgrade to 13.5.1, the .Net middleware of Banana Cake Pop stopped working, in production; when running the application in release/debug it's working; 

### Steps to reproduce

1. Cut off internet ?

### Relevant log output

info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Hot Chocolate GraphQL Pipeline'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://url/graphql/service-worker.js - - - 502 - - 42068.4742ms

### Additional Context?

The server does not have internet; 

### Version

13.5.1

**Comment by michaelstaib** [comment]
BCP by default is hosted on a CDN and we use YARP to refer to these CDN resources. 

This means that you always will get the newest version of BCP served from a CloudFlare CDN. If that is not feasible for your setup you can pin the BCP version to the bundled one in the AspNetCore Package.

```csharp
app.MapGraphQL().WithOptions(
    new GraphQLServerOptions
    {
        Tool = { 
            ServeMode = GraphQLToolServeMode.Embedded 
        }
    });
```
