### ISSUE TITLE
Support for Solace PubSub+ in HotChocolate's PubSub Engine

### ISSUE THREAD

**Issue by TKTheTechie** [ChilliCream/graphql-platform#6540]
### Product

Hot Chocolate

### Is your feature request related to a problem?

I'd like to see support for [Solace PubSub+](https://solace.com) with [HotChocolate's PubSub Engine](https://chillicream.com/docs/hotchocolate/v13/defining-a-schema/subscriptions/#in-memory-provider). 

### The solution you'd like

Ideally there is an interface/API that we could use that will allow us to integrate Solace's .NET API with HotChocolate's PubSub Engine.

**Comment by tobias-tengler** [comment]
The HotChocolate.Subscriptions NuGet package should provide you with all the interfaces and abstract classes you require to build your own provider - in this case for Solace PubSub+.
You can find some examples of PubSub implementations here (directories prefixed with `Subscriptions.`): https://github.com/ChilliCream/graphql-platform/tree/main/src/HotChocolate/Core/src
