### ISSUE TITLE
Excessive memory usage when returning 8.8 MB of JSON

### ISSUE THREAD

**Issue by gerwim** [ChilliCream/graphql-platform#6548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Returning a 8.8MB of JSON string consumes (per call) up to 300 MB. A few calls will result in 2GB+ of memory usage before GC kicks in.

### Steps to reproduce

1. Clone https://github.com/gerwim/hot-chocolate-memory-issue and open the solution
2. Start a profiler to check the memory allocated
3. Run the GraphQL query:
```
{
    image
}
```
4. Check your profiler (each call will result in ~300MB of memory usage):
![Screenshot 2023-09-22 at 10 29 45](https://github.com/ChilliCream/graphql-platform/assets/1841721/674254bc-90c0-47ed-adda-5e9866d25a27)

5. Retrieve this image by using a controller action: http://localhost:5235/image or `curl -s -o /dev/null http://localhost:5235/image` and check the profiler again. Memory usage will be much much lower:
![Screenshot 2023-09-22 at 10 30 28](https://github.com/ChilliCream/graphql-platform/assets/1841721/dc439702-675d-4b2f-9169-08df4c3ed028)

### Version

13.5.2 (issue is also present in 13.3.1)

**Comment by michaelstaib** [comment]
I cannot reproduce this ... I tested on ubuntu and macos and the console you provided stays at 150mb after startup it has this size even when just having only the controller in there. I have no debuggers attached and run the program in release mode with k6 and 10 parallel users and have maybe a fluctuation of 10 mb in both cases which is understandable as this uses base64.

**Comment by arjen1981** [comment]
Hello Michael,

We are still running into this issue. I captured this in the following video: https://www.youtube.com/watch?v=NfyuOeURx88

Also on release mode. I used this K6 script:

`import http from 'k6/http';
import { check } from 'k6';

// https://k6.io/docs/using-k6/options/
export let options = {
    vus: 10, // Virtual Users: Should be set tot the max/expected (not above) concurrent users at a given time (peak)
    duration: '10s',
};

let hcUrl = "http://localhost:5235/graphql/"

export default function () {
    RetrieveImage()
}

export function RetrieveImage() {
    let retrieveImage = HC({
        "operationName": "RetrieveImage",
        "variables": {},
        "query": "query RetrieveImage {\n  image \n}\n"
    })
    check(retrieveImage, { 'returns image': (r) => r })
}

export function HC(operation) {
    let headers = {
        'Content-Type': 'application/json',
    };

    let res = http.post(hcUrl, JSON.stringify(operation), { headers: headers });
    if (res.status === 200) {
        return (JSON.parse(res.body)).data;
    } else {
        console.error('error in http call to HC')
    }
}
`

Which in this video goas up to 13+GB! I am running this locally on .NET 7 in Windows 11 on Release mode.

**Comment by michaelstaib** [comment]
Let's see, will try it out again. This runs against the testserver you provided? I will rerun it on our side.

**Comment by gerwim** [comment]
@michaelstaib Yes. If you clone and run the GitHub project and then run the k6 script, it will execute the GraphQL query `image` which will show the issue.

**Comment by PascalSenn** [comment]
We analyzed this, and discovered two underlying issues
1. The default `JavaScriptEncoder` also escapes HTML sensistive characters such as <,>,&. As a result internally each string is checked for these characters and converted. There is a preset which is more efficent.
 We will in the future (13.6.1) use this [JavaScriptEncoder.UnsafeRelaxedJsonEscaping](https://learn.microsoft.com/en-us/dotnet/api/system.text.encodings.web.javascriptencoder.unsaferelaxedjsonescaping?view=net-7.0#system-text-encodings-web-javascriptencoder-unsaferelaxedjsonescaping)
 
 As a workaround you can at the moment configure this:
 https://github.com/gerwim/hot-chocolate-memory-issue/pull/1/files
 
 This will already safe 3/4 of the allocations.
 
 2. There is another issue we discovered with the internals of `Utf8JsonWriter` that we will also patch with 13.6.1. 
 
 We may have even another idea to improve this in the future further.

**Comment by michaelstaib** [comment]
We have included the fix in 13.6.1 .... have fun

**Comment by michaelstaib** [comment]
@gerwim please provide feedback if this solved your issues?

**Comment by gerwim** [comment]
@michaelstaib I can confirm this issue is fixed in 13.6.1. Thank you very much for your quick responses and the quick fix @PascalSenn!
