### ISSUE TITLE
Using Hotchocolate and Strawberry shake  together.

### ISSUE THREAD

**Issue by tunahan-guler** [ChilliCream/graphql-platform#6556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I am using Strawberry shake and hotchocolate together. I have 2 different APIs, both of which use hotchocolate graphql. But one of them has to send a request to the other API, so I use strawberry shake. But after writing the queries, the interface generated by Strawberry shake corrupts my hotchocolate schema. I added it to the services as AddInterfaceType, but it still didn't work.

### Steps to reproduce

1. Create 2 API.
2. Add Strawberry shake
3. Generate a query
4. Hotchocolate will give error while generating schema

### Version

13.0.0

**Comment by michaelstaib** [comment]
This is not a bug but how you use this thing.

**Comment by michaelstaib** [comment]
Join the slack channel and ask the community:
slack.chillicream.com
