### ISSUE TITLE
Missing Fusion documentation

### ISSUE THREAD

**Issue by anton-kirschhock** [ChilliCream/graphql-platform#6558]
### Product

Hot Chocolate

### Is your feature request related to a problem?

To evaluate Fusion in projects, I need documentation to explore what Fusion has to offer. Currently, there is only one blog post and two YouTube videos available. The lack of documentation makes it difficult to evaluate and support my suggestions to teams for building gateway solutions, especially since Stitching, as I understand it, is being deprecated

### The solution you'd like

I really appreciate the documentation provided by ChilliCream. It would be great to have a dedicated section for Fusion, detailing all its features

**Comment by DatStorm** [comment]
Hey.

How is this coming along? When is the documentation expected to be finished?

**Comment by PascalSenn** [comment]
The docs are now here: https://chillicream.com/docs/fusion/v14
