### ISSUE TITLE
Why is HotChocolate adding its own global usings to my project

### ISSUE THREAD

**Issue by Arcalise08** [ChilliCream/graphql-platform#6560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Whenever I add HotChocolate to my project, I get namespace collisions because it automatically adds the following to my global using file.

``` csharp
global using global::GreenDonut;
global using global::HotChocolate;
global using global::HotChocolate.Types;
global using global::HotChocolate.Types.Relay;
```

I cant seem to find a way to disable this behavior without disabling all of my global usings which would not be good. When those lines, they come back also.

### Steps to reproduce

1. install HotChocolate

### Version

16.6.0-preview.17

**Comment by michaelstaib** [comment]
This is not a bug but a question.

**Comment by michaelstaib** [comment]
You can configure this and disable it by adding this property to your csproj:

```xml
<Project>
  <PropertyGroup>
    <!--HotChocolateImplicitUsings: default|disable|enable-->
    <HotChocolateImplicitUsings>default</HotChocolateImplicitUsings>
  </PropertyGroup>
</Project>
```

**Comment by TsengSR** [comment]
@michaelstaib 
> You can configure this and disable it by adding this property to your csproj:
> 
> <Project>
>   <PropertyGroup>
>     
>     <HotChocolateImplicitUsings>default</HotChocolateImplicitUsings>
>   </PropertyGroup>
> </Project>

This is a really awful default behaviour. This should be disabled by default and opt-in for whoever it wants. It causes dozens of compile errors and hours of serach for a fix because it clashs with AngleSharp
