### ISSUE TITLE
Overfetched sql query

### ISSUE THREAD

**Issue by AsuraKev** [ChilliCream/graphql-platform#6572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I am perform a very simple graphql query and specify only two properties to be return back and it did return back with exactly what I queried for, however when I inspect the SQL query generated by Hot Chocolate it seemed to query all the fields despite my query only requested two fields.

![image](https://github.com/ChilliCream/graphql-platform/assets/52765572/d7eee9dd-1815-4ccf-9a3a-6a4f696d3dda)

![image](https://github.com/ChilliCream/graphql-platform/assets/52765572/20d425be-940b-4c58-92bd-f2adacb8ffa6)

### Steps to reproduce

1. write a simple graphql query definition
2. use a ef core dbcontext to return the entity in the resolver

### Additional Context?

N/A

### Version

13.5.1

**Comment by tobias-tengler** [comment]
Without some additional help, EF Core doesn't know which fields you selected in your query, so it will just evaluate whatever you've written inside your resolver and then only include all the fields that were selected in the server's response.

You can however use projections to only select the requested fields in your query through the DbContext:
https://chillicream.com/docs/hotchocolate/v13/fetching-data/projections
