### ISSUE TITLE
ScopeContextData is discarded in NodeResolvers

### ISSUE THREAD

**Issue by dawust** [ChilliCream/graphql-platform#6574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When data is set in ScopedContextData within a NodeResolver, it appears that the context is simply discarded and becomes unavailable for subsequent operations. This problem does not occur with a regular Resolver.

### Steps to reproduce

Here is a simple Repro

```csharp
public class Query
{
    [NodeResolver]
    public Product GetProductById(int id, IResolverContext resolverContext)
    {
        resolverContext.SetScopedState("foo", id);
        return new Product(id);
    }

    public IEnumerable<Product> GetProducts(IEnumerable<int> ids, IResolverContext resolverContext)
    {
        return ids.Select(id => GetProductById(id, resolverContext));
    }
}

public record Product(int Id)
{
    public int? GetIntId(IResolverContext context) => context.GetScopedStateOrDefault<int?>("foo");
}
```

If we run the following Query it becomes obvious that the context seems to be discarded
Query:

```graphql
query {
  nodes(ids: ["UHJvZHVjdAppMTIz", "UHJvZHVjdAppNDU2"]) {
    ... on Product {
      intId
    }
  }
  products(ids: [123, 456]) {
    ... on Product {
      intId
    }
  }
}
```

Result:
```json
{
  "data": {
    "nodes": [
      {
        "intId": null
      },
      {
        "intId": null
      }
    ],
    "products": [
      {
        "intId": 123
      },
      {
        "intId": 456
      }
    ]
  }
}
```

Thank you!

### Additional Context?

When using "node" instead of "nodes" it works fine, so I guess the cloned Context in ResolveManyNodeAsync has to preserved somehow.

### Version

13.5.1 and 13.6.0-preview.23

**Comment by michaelstaib** [comment]
Thank you for this great repro ... I already created a test from this and we will fix it with 13.6
