### ISSUE TITLE
@resolve produces incorrect query in fusion graph when the field name differs from the query name

### ISSUE THREAD

**Issue by ktrauberman** [ChilliCream/graphql-platform#6579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I have a subgraph "A" that has a query `widgetById(widgetId: ID!): Widget!` and another subgraph "B" that has a type with a widgetId field `type Thing { widgetId: ID! }`.  I want to extend this type with a field `widgetName` that is resolved from the `Widget.name` field.

I added this to schema.extensions.graphql in subgraph "A"
```
extend type Thing
{
    widgetName(widgetId: ID! @require(field: "widgetId")): String @resolve(select: "widgetById(widgetId: $widgetId) { name }")
}
```
which produces this in the fusion graph:
```
  widgetName: String
    @source(subgraph: "SubgraphA")
    @variable(subgraph: "SubgraphB", name: "Thing_widgetId", select: "widgetId")
    @resolver(subgraph: "SubgraphA", select: "{ widgetName(widgetId: $Thing_widgetId) }", arguments: [ { name: "Thing_widgetId", type: "ID!" } ])
```
and when I try to query that field, I get an error:
```
    {
      "message": "The field `widgetName` does not exist on the type `Query`.",
      "locations": [
        {
          "line": 1,
          "column": 46
        }
      ],
      "extensions": {
        "type": "Query",
        "field": "widgetName",
        "responseName": "widgetName",
        "specifiedBy": "http://spec.graphql.org/October2021/#sec-Field-Selections-on-Objects-Interfaces-and-Unions-Types"
      }
    }
```
I would expect the fusion graph to produce the query that I'm passing into the `@resolve` directive.

### Steps to reproduce

1. 

### Version

13.6.0-preview.23

**Comment by michaelstaib** [comment]
resolve is not yet supported..... so no bug here.

**Comment by ktrauberman** [comment]
Alright.  What is the proper way to do what I'm attempting then?  There's no documentation for fusion so I'm fumbling around in the dark here.

**Comment by ktrauberman** [comment]
> resolve is not yet supported..... so no bug here.

Alright. What is the proper way to do what I'm attempting then? There's no documentation for fusion so I'm fumbling around in the dark here.

**Comment by ktrauberman** [comment]
Will [this PR](https://github.com/ChilliCream/graphql-platform/pull/6517) add the proper features to do what I'm trying to do here?
