### ISSUE TITLE
Fusion ignores subgraphs errors and returns only a "Internal Execution Error"

### ISSUE THREAD

**Issue by tessarolli** [ChilliCream/graphql-platform#6588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Whenever a problem occurs on one or more of the subgraphs, Fusion strips away all relevant error messages received and returns only a misleading "Internal Execution Error" with an empty result set.

### Steps to reproduce

1. Run a query which wont process on a subgraph

### Version

13.6.0-preview.23

**Comment by nibblesnbits** [comment]
This is a big holdup for me.  Any progess on this?

**Comment by dsschnau** [comment]
(bump)

**Comment by michaelstaib** [comment]
This is fixed on 14... checkout the preview builds.
