### ISSUE TITLE
BCP - Deleting a Document doesn't take effect

### ISSUE THREAD

**Issue by michaelmcneilnet** [ChilliCream/graphql-platform#6611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Banana Cake Pop

### Describe the bug

When deleting a document from the list, and then dragging it into BCP again, a dialog appears prompting for a rename with a `Name already taken` validation error.

I also noticed that if I delete all of the documents, and then drag a new one into BCP, all the deleted documents appear again.

### Steps to reproduce

1. Drag a document into BCP
2. Delete the document
3. Verify document is no longer in list of documents
4. Drag the same document into BCP again

**Expected**
Document is added to BCP correctly

**Actual**
Dialog prompting `Name already taken` appears.

![image](https://github.com/ChilliCream/graphql-platform/assets/5156449/8e4f7125-b004-4f38-a810-01b2c504b41e)

### Version

5.0.3

**Comment by rstaib** [comment]
Cannot reproduce. Please Update to the latest version `10.0.7`.

**Comment by michaelmcneilnet** [comment]
Thanks, will try and let you know. Due to #6612 I thought I was on the latest version already 😅

**Comment by michaelmcneilnet** [comment]
Can confirm this is working in latest version
