### ISSUE TITLE
Fusion is adding optional parameters with null value in the requests for the subgraphs 

### ISSUE THREAD

**Issue by tessarolli** [ChilliCream/graphql-platform#6614]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Consider you have a Mutation, and this mutation contains one or more optional parameters, and at least one required one.
And you query for that mutation and provides only the required parameters, leaving the optional ones out.
Fusion will add those optional parameters on the fly into the requests being submitted to the subgraphs, and, if the subgraph is not expecting a optional parameter declared with a null value, it breaks the execution of that request.

### Steps to reproduce

1. Consider this type definition for a mutation
passengersSetBatch(
    requests: [Input_PassengerUpdateRequestv2]
    waiveNameChangeFees: Input_Nullable__Boolean
  ): [Passenger]And, consider we are trying to execute this mutation:
mutation mutationName {
  passengersSetBatch(
    requests: [
      {
        valid request data here
      }
    ]
  ) {
    name
  }
}
If you look closely, you will see that there is no waiveNameChangeFees parameter set in the query.Now look at the fusion execution plan:
"extensions": {
    "queryPlan": {
      "document": "mutation mutationName { passengersSetBatch(requests: [ { valid request data } ]) { name { first } } }",
      "operation": "mutationName",
      "rootNode": {
        "type": "Sequence",
        "nodes": [
          {
            "type": "Resolve",
            "subgraph": "subgraphName",
            "document": "mutation mutationName_1 { passengersSetBatch(requests: [ { valid request data } ], waiveNameChangeFees: null) { name { first } } }",
            "selectionSetId": 120
          },
          {
            "type": "Compose",
            "selectionSetIds": [
              120
            ]
          }
        ]
      }
    },
    "queryPlanHash": "5F7C90F2CA95364CC851612A597EC0EF6BD8C1FC"
  }

### Version

13.6.0-preview.31

**Comment by michaelstaib** [comment]
that is kind of intended as we are putting in the gateway defaults. The subgraphs could potentially have diverging default values.

**Comment by tessarolli** [comment]
Understood.
Is there the possibility of adding an optional configuration for disabling
this behavior?
Because this breaks one of our external third party subgraphs that doesnt
expects a null optional parameter to be present in the query.
And we cant modify that subgraph code.

Em seg., 23 de out. de 2023 05:13, Michael Staib ***@***.***>
escreveu:

**Comment by michaelstaib** [comment]
Interesting ... it would be a spec violation of the subgraph. However, we recognise that this answer does not help your in solving this issue. I can put an option into the next release 13.7 that will help you along.

**Comment by tessarolli** [comment]
That would be great, thank you.

Em seg., 23 de out. de 2023 10:47, Michael Staib ***@***.***>
escreveu:

**Comment by michaelstaib** [comment]
This is now fixed with 13.8.0-preview.5
