### ISSUE TITLE
StrawberryShake cannot consume JSON scalar

### ISSUE THREAD

**Issue by grounzero** [ChilliCream/graphql-platform#6617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

When a StrawberryShake query includes a `JSON` type it throws a runtime exception:

```
System.InvalidOperationException: The requested operation requires an element of type 'String', but the target element has type 'Object'.
   at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
   at System.Text.Json.JsonDocument.GetString(Int32 index, JsonTokenType expectedType)
```

![image](https://github.com/ChilliCream/graphql-platform/assets/16921017/04743c89-7d03-47b5-820e-8c9ea85b4b6d)

### Steps to reproduce

1. Create a StrawberryShake client with a query that selects a JSON scalar type.

### Version

13.5.1

**Comment by grounzero** [comment]
I've followed the documentation in https://chillicream.com/docs/strawberryshake/v13/scalars/#any-or-json

and added an extension in `schema.extensions.graphql` and a custom `ScalarSerializer` and swapped around every combination of
serializationType and runtimeType but I can't make the error go away.

This feels like it should be something that should work out of the box so not sure if it is a bug or something that I am doing wrong?

```js
extend scalar Any
  @serializationType(name: "global::System.Text.Json.JsonElement")
  @runtimeType(name: "global::System.String")
```
```cs
public class CustomJsonSerializer : ScalarSerializer<JsonElement, string>
{
    public CustomJsonSerializer(string typeName = BuiltInScalarNames.Any) : base(typeName)
    {
    }

    public override string Parse(JsonElement serializedValue) =>
        serializedValue.GetRawText();

    protected override JsonElement Format(string runtimeValue) =>
        JsonDocument.Parse(runtimeValue).RootElement;
}
```

**Comment by michaelstaib** [comment]
Be careful with that code as `JsonDocument.Parse(runtimeValue).RootElement;` introduces a memory leak... JsonDocument is disposable as it rents memory form the ArrayPool and will only return it on dispose.

**Comment by michaelstaib** [comment]
Alternatively you can parse with the JsonElement and specify that the memory shall not be pooled.

**Comment by michaelstaib** [comment]
Have you registered the serializer with the client

**Comment by david-driscoll** [comment]
It would appear that the `Utf8JsonWriterHelper` does not account for `JsonElement` and instead falls into the default case which calls `.ToString()` on the element itself.

https://github.com/ChilliCream/graphql-platform/blob/99d3adfc9b734cf0e2497f21919cf15a87ef3ff7/src/HotChocolate/AspNetCore/src/Transport.Abstractions/Serialization/Utf8JsonWriterHelper.cs#L175-L177

**Comment by david-driscoll** [comment]
I would assume something similar to the existing implementation in `JsonResultFormatter` would solve this issue.  I tried to see if I could make a failure case but it's pretty deep in the code, would require changing the starwars schema to add a json or other scalar.

https://github.com/ChilliCream/graphql-platform/blob/99d3adfc9b734cf0e2497f21919cf15a87ef3ff7/src/HotChocolate/Core/src/Execution/Serialization/JsonResultFormatter.cs#L660-L667

**Comment by grounzero** [comment]
@michaelstaib @david-driscoll  Eventually my workaround for this was to ditch the CustomJsonSerializer completely and in `schema.extensions.graphql` add:

```js
extend scalar JSON
  @serializationType(name: "global::System.Text.Json.JsonElement")
  @runtimeType(name: "global::System.Text.Json.JsonDocument")
```

Then instead of a custom seriliser, register the built-in [JsonSerilizer](https://github.com/ChilliCream/graphql-platform/blob/main/src/StrawberryShake/Client/src/Core/Serialization/JsonSerializer.cs)

```cs
services..AddSerializer(new JsonSerializer("JSON"))
```
