### ISSUE TITLE
Option to select the content-type used for event stream

### ISSUE THREAD

**Issue by vbornand** [ChilliCream/graphql-platform#6618]
### Product

Hot Chocolate

### Is your feature request related to a problem?

I use HC (13.5.1 or 13.6.0-preview.31) with subscription over SSE.

My HC server is behind an Azure Application Gateway SKU v1 (I know the v1 version is deprectated but I want to keep it as long as possible (April 2026) because the v2 is really more expensive).

The subscriptions don't work because the content-type is "text/event-stream; charset=utf-8". Azure Application Gateway streams the response only if it is "text/event-stream", otherwise it waits the end of the reponse before to send it to the client. So in the case of the subcription, the response never ends.

The subscriptions works well with the v2 SKU with the default content type (text/event-stream; charset=utf-8)

### The solution you'd like

An option to specify a custom content-type when event stream are sent by HC. Maybe in the HttpResponseFormatterOptions struct. (https://github.com/ChilliCream/graphql-platform/blob/main/src/HotChocolate/AspNetCore/src/AspNetCore/Serialization/HttpResponseFormatterOptions.cs)

I can create a PR to add the option.

**Comment by michaelstaib** [comment]
This is the correct `content-type`. I do not want to introduce special logic for hacks. The protocols here are specified protocols.
