### ISSUE TITLE
Exporting and merging ``fgp`` from running webapi(``/graphql?fgp``)

### ISSUE THREAD

**Issue by byme8** [ChilliCream/graphql-platform#6623]
### Product

Hot Chocolate

### Is your feature request related to a problem?

I have a distributed graphql service that is combined via stitching. When the gateway is launched it has a list of urls with corresponding graphql services. The gateway downloads schemas, apply stitching and exposes them as a single schema.

When one of the graphql services have changed. The gateway triggered by CI to download new schemas and the whole process starts again.

I would like to replace stitching with fusion but, at the moment, there is no easy way to replicate workflow described above.

### The solution you'd like

Ideally, it would be nice to have a way on gateway level to fetch multiple graphql schemas and merge them at runtime. It can be raw graphql schemas fetched from ``/graphql?sdl`` or full graphql packages ``/graphql?fgp``.

**Comment by byme8** [comment]
I investigated the CLI for subgrapph composing and managed to replicate my workflow. The `` FusionGraphConfigurationToSchemaRewriter `` was internal class so I copy-pasted it. Everything else looks good as for prototype.

Here is the resulted for gateway:
``` csharp
using System.Reactive.Subjects;
using HotChocolate.Fusion;
using HotChocolate.Fusion.Composition;
using HotChocolate.Language;
using HotChocolate.Language.Visitors;
using HotChocolate.Skimmed.Serialization;

var builder = WebApplication.CreateBuilder(args);
var services = builder.Services;

var gatewaySubject = new ReplaySubject<GatewayConfiguration>();
var systemUri = new Uri("http://localhost:10100/graphql");
var searchUri = new Uri("http://localhost:10200/graphql");

services.AddHttpClient("System",
    o => o.BaseAddress = systemUri);

services.AddHttpClient("Search",
    o => o.BaseAddress = searchUri);

services.AddHttpClient();

services.AddFusionGatewayServer()
    .RegisterGatewayConfiguration((o) => gatewaySubject);

var app = builder.Build();

await Reload();

app.MapGet("/reload", async () =>
{
    var schemaDoc = await Reload();
    return schemaDoc.ToString();
});
app.MapGraphQL();

app.RunWithGraphQLCommands(args);

async Task<DocumentNode> Reload()
{
    var httpClientFactory = app.Services.GetRequiredService<IHttpClientFactory>();
    var systemClient = httpClientFactory.CreateClient("System");
    var searchClient = httpClientFactory.CreateClient("Search");

    var systemSchema = await systemClient.GetStringAsync("?sdl");
    var searchSchema = await searchClient.GetStringAsync("?sdl");

    var systemSubgraph = new SubgraphConfiguration(
        "System",
        systemSchema,
        string.Empty,
        new HttpClientConfiguration(systemUri),
        null);

    var searchSubgraph = new SubgraphConfiguration(
        "Search",
        searchSchema,
        string.Empty,
        new HttpClientConfiguration(searchUri),
        null);

    var fusionGraph = await FusionGraphComposer.ComposeAsync(new[]
    {
        systemSubgraph,
        searchSubgraph
    });

    var fusionGraphDoc = Utf8GraphQLParser.Parse(SchemaFormatter.FormatAsString(fusionGraph));
    var typeNames = FusionTypeNames.From(fusionGraphDoc);
    var rewriter = new SyntaxRewriter<FusionGraphConfigurationToSchemaRewriterContext>();
    var documentNode = (DocumentNode)rewriter.Rewrite(fusionGraphDoc, new(typeNames))!;

    var gatewayConfiguration = new GatewayConfiguration(documentNode);
    gatewaySubject.OnNext(gatewayConfiguration);
    return documentNode;
}

internal sealed class FusionGraphConfigurationToSchemaRewriterContext : ISyntaxVisitorContext
{
    public FusionGraphConfigurationToSchemaRewriterContext(FusionTypeNames typeNames)
    {
        TypeNames = typeNames;
    }

    public FusionTypeNames TypeNames { get; }
}
```

**Comment by michaelstaib** [comment]
The whole idea is that all of this does not happen at runtime. The fusion composition is much more complex and an introduction of one field could lead to the gateway to die. The composition has rich errors for that. But this would lead to downtime of the Gateway.

The idea of Fusion is to make sure at build time that an in isolation developed GraphQL server will work 100% at runtime.

I would not rely on this internal class ... with 13.7 we almost completely rewrote the composition component.

Use BCP as your orchestrator in between the Gateway and your subgraphs and use build pipelines to ensure that everythings.

**Comment by michaelstaib** [comment]
I am closing this issue as for us runtime composition is a thing of the past.

**Comment by byme8** [comment]
I understand your intention that compile-time validation is better than runtime validation. At the same time, taking into account how it works now: 
- pack multiple subgraphs via CLI
- if you have real distributed services, deploy packages somewhere
- if you have real distributed services, getch packages before merge
- merge those packed subgraphs
- if you have real distributed services, deploy the merged package somewhere
- if you have real distributed services, notify the gateway that there is the new package

No one will do it manually in production. It should be a part of the CI/CD pipeline.

Once you have CI/CD you can add an integration test that will make sure that your subgraphs are compatible. As a result, at the runtime, everything would work as expected. In this situation, I think it is debatable to have subgraphs packed and stored somewhere, and so on.

You can just deploy, fetch the current subgraphs, merge them, and that's all.

**Comment by byme8** [comment]
Improved version for those who want to have real-time schema merging:
``` csharp
using System.Reactive.Subjects;
using HotChocolate.Fusion.Composition;
using HotChocolate.Language;
using HotChocolate.Skimmed.Serialization;

var builder = WebApplication.CreateBuilder(args);
var services = builder.Services;

var gatewaySubject = new ReplaySubject<GatewayConfiguration>();
var apis = new[]
{
    (Name: "System", Url: new Uri("http://localhost:10100/graphql")),
    (Name: "Search", Url: new Uri("http://localhost:10200/graphql"))
};

foreach (var api in apis)
{
    services.AddHttpClient(api.Name, o => o.BaseAddress = api.Url);
}

services.AddHttpClient();

services.AddFusionGatewayServer()
    .RegisterGatewayConfiguration(_ => gatewaySubject);

var app = builder.Build();

await Reload();

app.MapGet("/reload", async () =>
{
    var schemaDoc = await Reload();
    return schemaDoc.ToString();
});
app.MapGraphQL();

app.RunWithGraphQLCommands(args);

async Task<DocumentNode> Reload()
{
    var httpClientFactory = app.Services.GetRequiredService<IHttpClientFactory>();
    var subgraphsTask = apis.Select(async o =>
    {
        using var client = httpClientFactory.CreateClient(o.Name);
        var schema = await client.GetStringAsync("?sdl");

        var subgraph = new SubgraphConfiguration(
            o.Name,
            schema,
            string.Empty,
            new HttpClientConfiguration(o.Url),
            null);

        return subgraph;
    });

    var subgraphs = await Task.WhenAll(subgraphsTask);
    var composition = await FusionGraphComposer.ComposeAsync(subgraphs);

    var documentNode = Utf8GraphQLParser.Parse(SchemaFormatter.FormatAsString(composition));

    var gatewayConfiguration = new GatewayConfiguration(documentNode);
    gatewaySubject.OnNext(gatewayConfiguration);
    return documentNode;
}
```

**Comment by michaelstaib** [comment]
Just be aware that this will no longer work with 13.7

**Comment by michaelstaib** [comment]
Are you on our slack channel? Let's discuss fusion there if you are interested. Also, are you interested to get involved in fusion. Give me a ping on slack.chillicream.com
