### ISSUE TITLE
Stitching error: The name `tag` was already registered by another type

### ISSUE THREAD

**Issue by PeterAragon** [ChilliCream/graphql-platform#6634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Upgraded from 13.5.1 to 13.6 in a test project containing two subgraphs and one stitching gateway. 
Snapshot tests for schema's revealed the new @tag directive in both subgraphs:

`directive @tag(name: String!) repeatable on SCHEMA | SCALAR | OBJECT | FIELD_DEFINITION | ARGUMENT_DEFINITION | INTERFACE | UNION | ENUM | ENUM_VALUE | INPUT_OBJECT | INPUT_FIELD_DEFINITION
`

The stitching gateway produces the following exception:
``` Message: 
HotChocolate.SchemaException : For more details look at the `Errors` property.

1. The name `tag` was already registered by another type. (HotChocolate.Types.DirectiveType<HotChocolate.Types.Tag>)


  Stack Trace: 
TypeRegistry.Register(String typeName, RegisteredType registeredType)
TypeInitializer.CompleteTypeName(RegisteredType registeredType)
TypeInitializer.<CompleteNames>b__23_0(RegisteredType type)
TypeInitializer.ProcessTypes(TypeDependencyFulfilled fulfilled, Func`2 action)
TypeInitializer.CompleteNames()
TypeInitializer.Initialize()
Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
SchemaBuilder.Create(IDescriptorContext context)
ISchemaBuilder.Create(IDescriptorContext context)
RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
<<AddRemoteSchema>b__9>d.MoveNext()
--- End of stack trace from previous location ---
RequestExecutorResolver.OnConfigureSchemaBuilderAsync(ConfigurationContext context, IServiceProvider schemaServices, RequestExecutorSetup setup, CancellationToken cancellationToken)
RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
RequestExecutorServiceProviderExtensions.GetSchemaAsync(IServiceProvider services, String schemaName, CancellationToken cancellationToken)
SchemaTests.SchemaChangeTest_Gateway() line 21
--- End of stack trace from previous location ---
```

### Steps to reproduce

1. Define two subgraphs, one having an entity and the other pointing to that entity by the id
2. Define a stitching gateway with an extension similar to: `extend type DefaultEntity {
	secondary: SecondaryEntity
	@delegate (schema: "TestRemoteSchemaSecondary", path: "mySecondaryEntityBatched(id: $fields:secondaryId)")
}`
3. Perform a stitched query through the gateway

### Version

13.6.0

**Comment by Ma1kovich** [comment]
Confirming the same error in my gateway

**Comment by PascalSenn** [comment]
Is the stitching gateway also on 13.6.0?

**Comment by PeterAragon** [comment]
I can confirm the following workaround proposed by @michaelstaib works when applied to the subgraphs ```.AddGraphQLServer().ModifyOptions(o =>
            {
                o.EnableTag = false;
            })```
However, Stitching gateway is a bit weird, not defining EnableTag=false will continue to generate the exception even though the tag is not present anymore downstream, and with EnableTag=false the gateway again works, but the stitched schema will still includes ```directive @tag(name: String!) repeatable on SCHEMA | SCALAR | OBJECT | FIELD_DEFINITION | ARGUMENT_DEFINITION | INTERFACE | UNION | ENUM | ENUM_VALUE | INPUT_OBJECT | INPUT_FIELD_DEFINITION```

**Comment by PeterAragon** [comment]
@PascalSenn yes, all packages are 13.6.0. So from what I can conclude, out of the box a stitched gateway will fail due to a tag directive that is already injected and EnableTag=false will just prevent it from being added twice by stitching ;-)

**Comment by stand-sure** [comment]
quick fix that we did

```c#
private static MergeDirectiveRuleDelegate MergeDirectiveRuleDelegate(MergeDirectiveRuleDelegate next)
    {
        return (context, types) =>
        {
            var newDirectives = new List<IDirectiveTypeInfo>();
            var returnedValue = (List<IDirectiveTypeInfo>)types;

            var directivesToRemove = new List<string>()
            {
                "tag",
            };

            foreach (IDirectiveTypeInfo info in returnedValue)
            {
                ISchemaInfo schemaInfo = info.Schema;

                foreach (string directive in directivesToRemove)
                {
                    ((Dictionary<string, DirectiveDefinitionNode>)schemaInfo.Directives).Remove(directive);
                }

                if (!directivesToRemove.Contains(info.Definition.Name.Value))
                {
                    newDirectives.Add(new DirectiveTypeInfo(info.Definition, schemaInfo));
                }
            }

            next(context, newDirectives);
        };
    }
```

then 
```c#
requestExecutorBuilder.AddDirectiveMergeRule(MergeDirectiveRuleDelegate);
```

**Comment by stand-sure** [comment]
slimmer version

```c#
private static MergeDirectiveRuleDelegate MergeDirectiveRuleDelegate(MergeDirectiveRuleDelegate next)
{
    return (context, types) =>
    {
        var directivesToRemove = new[]
        {
            "tag",
        };

        List<DirectiveTypeInfo> newDirectives =
            (from info in types
                where !directivesToRemove.Contains(info.Definition.Name.Value)
                select new DirectiveTypeInfo(info.Definition, info.Schema)).ToList();

        next(context, newDirectives);
    };
}
```

**Comment by michaelstaib** [comment]
You can also switch tag off ...

```
.AddGraphQLServer().ModifyOptions(t => t.EnableTag = false)
```

**Comment by michaelstaib** [comment]
Stitching is EOL and we will no longer provide anymore fixes. Stay on a version of stitching that worked for you. We will soon provide instructions on how to move to fusion. Stitching will be completly removed with the December release.

**Comment by yurvon-screamo** [comment]
Hi, maybe it will help someone

I caught a bug with utf 8 (https://github.com/ChilliCream/graphql-platform/pull/6503), updated to 13.7 - everything died with a tag error

As a result, I found out that - a change with tags - https://github.com/ChilliCream/graphql-platform/commit/15c01ad7f55f94e0115f5ea21ab5ff1ccbf80a74#diff-96e3c501d54db80565d8ce2e61583dd8ab4a7a57500c59532452385aae7ec4d2

The last release before it is 13.6.0-preview.30, it still works. If nothing else helps, but you need exactly 13.6, use it (or something lower version)
