### ISSUE TITLE
Tag directive added to stitched schema with EnableTag = false, by default (EnableTag = true) it causes an exception

### ISSUE THREAD

**Issue by PeterAragon** [ChilliCream/graphql-platform#6639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

13.6.0 introduced a tag directive which caused an issue described in https://github.com/ChilliCream/graphql-platform/issues/6634.
However, the workaround of EnableTag = false doesn't appear to work as intended on the Stitching gateway.

Without the EnableTag=false on the Stitching gateway it will generate the same exception despite all downstream graphs having EnableTag = false and no tag directive is present there
With EnableTag=false on the Stitching gateway it will work, however the stitched schema will still have a tag directive present even though you specifically asked to disable it.

### Steps to reproduce

1. Define two subgraphs both with EnableTag = false , one having an entity and the other pointing to that entity by the id
2. Define a stitching gateway without EnableTag = false with an extension similar to: extend type DefaultEntity { secondary: SecondaryEntity @delegate (schema: "TestRemoteSchemaSecondary", path: "mySecondaryEntityBatched(id: $fields:secondaryId)") }
3. Perform a stitched query through the gateway, it will cause an exception
4. Change the stitching gateway to have  EnableTag = true
5. Perform a stitched query through the gateway, it will not cause an exception but the tag directive is present

### Additional Context?

Like this it won't be possible to stitch two stitched gateways, and out of the box a stitching gateway won't work despite no tag directives in downstream graphs.

### Version

13.6.0

**Comment by michaelstaib** [comment]
We will be not investing any time anymore into stitching. If you are depending on stitching stay on the latest version that worked for you ... its really EOL and we will remove it from the build by the end of December.
