### ISSUE TITLE
Excessive memory usage - possibly related to caching?

### ISSUE THREAD

**Issue by gilroyneil** [ChilliCream/graphql-platform#6646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

Hi,

I have a service which makes around 15k - 25k calls per day to a GQL server via Strawberry shake v13.2.1. .net 7 webapi service. The responses are quite large - in the 20 - 40KB range typically.

The service memory usage just goes up and up. Im new to diagnosing memory issues, but what seems to be clear is that GC runs, and gen 2 just gets larger and larger. Even when a gen 2 GC is performed (seen via PerfView) the gen 2 survivial rate is 99%, LOH isnt super large.

When I drill into the Heap contents via PerfView, I see a lot of objects that relate to: **StrawberryShake.Core!.StrawberryShake.EntityStoreSnapshot**
These *seem* (still learning...) to be rooted to the **DefaultHttpClientFactory**. Is this related to the built in caching mechanism? If so, im not setting a ExecutionStrategy so it looks like NetworkOnly is the default?

Can I do something about this? Its causing me huge issues, and I am not sure what I can control here?

### Steps to reproduce

1. Default execution strategy
2. Make a client request to a server which returns large responses in the 20 - 40KB range.
3. Use a tool like Postman collection runner to perform many thousands of these requests
4. See process memory usage go up and up, all managed heap.

### Version

13.2.1

**Comment by tobias-tengler** [comment]
Are you using the ["Server" preset](https://chillicream.com/docs/strawberryshake/v13/get-started/console)? 

If your service is just used for querying data from a remote server and you don't need a reactive client-side cache, you should use this preset, which shouldn't come with any client-side caches like the EntityStore.

**Comment by michaelstaib** [comment]
Exactly right ... you need to use the server preset. This will not event generate a cache.

**Comment by gilroyneil** [comment]
Ah - thank you both!!!! I think I was already doing most of this... though I did just re-init and rationalize the .graphqlrc.json file back to the minimum necessary properties to match the sample page.

Looking in the git log someone (around the time of the 12 -> migration we did...) added a bunch of settings into the .graphqlrc.json including:

"noStore": false,

^ could that have been the culprit too?

**Comment by michaelstaib** [comment]
I would reinitialize the client with 13 and the new template and then the settings are actually correctly set. In version 12 it was to complex :D 

Closing this issue as it has been answered

**Comment by michaelstaib** [comment]
Make sure to join us on slack.chillicream.com as its much easier to post a question there.

**Comment by gilroyneil** [comment]
Thank you for all your help - terrific!

**Comment by davidegolzi** [comment]
> Exactly right ... you need to use the server preset. This will not event generate a cache.

Hi @michaelstaib i think i ahve been hit the same behavior. I have e GraphQl Client that do not need cache. My process grow up in memory occupation without any needs. where i can find the "server preset". I mean i chek the linked page but i'm not able to recognize any server preset. How can i disable the cache?
