### ISSUE TITLE
feat: ISchemaBuilder should allow applying multiple schema transformation lambdas

### ISSUE THREAD

**Issue by dariuszkuc** [ChilliCream/graphql-platform#6651]
### Product

Hot Chocolate

### Is your feature request related to a problem?

As a library author, I'd like to be able to create convenient `IRequestExecutorBuilder`/`ISchemaBuilder` extensions that encapsulate lambas to easily set schema directives. Currently it is not possible to apply multiple schema transformations when using lambdas as the last specified transformation overwrites all the previous ones, i.e.

```csharp
var builder = WebApplication.CreateBuilder(args);

builder.Services
    .AddGraphQLServer()
    .ConfigureSchema(b => b.SetSchema(s => s.Directive("foo")))
    .ConfigureSchema(b => b.SetSchema(s => s.Directive("bar")))
// other config
```

This generates

```graphql
schema @bar { ... }
```

While we would expect to have both `@foo` and `@bar` directives applied

```graphql
schema @foo @bar { ... }
```

### The solution you'd like

Applying multiple schema transformation lambdas results in cumulative changes to the underlying schema.

**Comment by michaelstaib** [comment]
As mentioned before, we are removing schema builder at the moment. We slowly hid schema builder behind our schema configuration API and finally towards the end of the year will completely pull it.

**Comment by michaelstaib** [comment]
I am closing this issue as we are heavy at work on the type system at the moment.
