### ISSUE TITLE
Add the ability to specify the name of an Edge when using the UsePaging attribute

### ISSUE THREAD

**Issue by JamesAskew** [ChilliCream/graphql-platform#6696]
### Product

Hot Chocolate

### Is your feature request related to a problem?
Yes.

My company are going through a large migration from GraphQL.Conventions to HotChocolate. One of our requirements is for the HotChocolate schema to match the current one generated by Conventions.

This is required to reduce the amount of changes our customers need to make. The downstream services which call our GraphQL service, use many different clients. Some of these import schemas in various formats and generate objects based on the imported files, others rely heavily on the `__typeName` property.

We are struggling to match objects which use paging. Particularly the edge name, which is blocking us from moving across to HotChocolate. The `UsePaging` attribute allows us to specify the `connectionName`, but we also need the ability to specify the `edgeName`. I’ve included some sections of our schema to demonstrate the mismatch we are facing.

This is our current schema, generated by GraphQL.Conventions
```
type LibraryContentSearchConnection {
  edges: [LibraryContentEdge]
  items: [LibraryContent]
  pageInfo: PageInfo!
  totalCount: Int
}
type LibraryContentEdge {
  cursor: Cursor!
  node: LibraryContent
}
```

This is our new schema, generated by HotChocolate using this attribute `[UsePaging(ConnectionName = "LibraryContentSearch", IncludeTotalCount = true)]`
```
type LibraryContentSearchConnection {
  pageInfo: PageInfo!
  edges: [LibraryContentSearchEdge!]
  nodes: [LibraryContent]
  totalCount: Int!
  items: [LibraryContent!]
}
type LibraryContentSearchEdge {
  cursor: String!
  node: LibraryContent
}
```

### The solution you'd like

Currently in `HotChocolate.Core`, Edge names are generated like this
```
// HotChocolate/Core/src/Types.CursorPagination/NameHelper.cs

public static string CreateEdgeName(string connectionName)
        => connectionName + "Edge";
```

We would like to extend this (via a PR) to include an optional edgeName string and fall back to the current logic if one isn’t provided. Before opening a PR though, we want to check the following:

A) there isn’t a better way to accomplish this
B) the maintainers don’t object

**Comment by michaelstaib** [comment]
The edge name is generated as in the connection spec defined. What is the value of diverting from the spec? I in general feel it would just lead to less well understandable schema.

**Comment by JamesAskew** [comment]
> The edge name is generated as in the connection spec defined. What is the value of diverting from the spec? I in general feel it would just lead to less well understandable schema.

I don’t disagree with you. In an ideal world we want our Edge name to follow along with our Connection name.

Unfortunately for us, we’re stuck trying to get to the ideal world. We want to migrate to HotChocolate, but to do that we need to match the current schemas which we have inherited.  Because we can’t rename the Edge, either with a type extension or the Paging override we are blocked.

Due to the way our Connection types are currently created (in the library we are replacing) we are getting the weird Connection and Edge names shown in the snippet above. Refactoring the Connection code has a big knock on effect due to the way downstream clients are using the typeNames.

We are stuck between a rock and hard place. We can’t refactor the existing code and we can’t use the out of the box edge names. So we are looking for an alternative solution to help us proceed with our migration.

We are proposing this minor change to add the flexibility for our use case. Looking at the HotChocolate code it was the smallest feasible change we could see.
