### ISSUE TITLE
SSE subscription makes HotChocolate not being shutdown gracefully

### ISSUE THREAD

**Issue by sunghwan2789** [ChilliCream/graphql-platform#6698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

If a SSE subscription alives, HotChocolate does not shutdown gracefully.

Sending Ctrl+C (SIGINT), Kestrel requests connections closed, but HotChocolate keeps connections open and `RequestAborted` is false.

![image](https://github.com/ChilliCream/graphql-platform/assets/4927894/2cfeaa3f-c51c-44e8-a164-04d79c29bcd7)

### Steps to reproduce

1. `git clone https://github.com/sunghwan2789/hotchocolate.git --branch repro/sse-hangs --single-branch`
2. `dotnet run --project Server`
3. Wait subscription started, and send `Ctrl+C` (SIGINT) 

### Version

14.0.0-p.9

**Comment by michaelstaib** [comment]
Thank you for reporting this.

**Comment by michaelstaib** [comment]
Can you create a repro?

**Comment by cmeeren** [comment]
Also being hit by this. This means we can't reliably update our API, because shutdown hangs whenever there's an active connection. Hoping this will get fixed soon!

**Comment by sunghwan2789** [comment]
Now, I think this is not a bug, but a user-level mistake: the resolver is responsible for completing the subscription on application stopping.

**Comment by cmeeren** [comment]
> the resolver is responsible for completing the subscription on application stopping

How can this be done? I can't find any information about that in the [HC subscription docs](https://chillicream.com/docs/hotchocolate/v13/defining-a-schema/subscriptions).

**Comment by sunghwan2789** [comment]
Updated the reproduction and found that HC does not send a complete event when `OperationCanceledException` is thrown.

Now, I am sure it is a bug.

**Comment by sunghwan2789** [comment]
fixed in v14

**Comment by Cyberboss** [comment]
I've got a simple repro which seems to cause this. Always hits the shutdown timeout if a subscription is active over SSE.

To work around this, I need to inject an IHostApplicationLifetime and bind together the normal token with the `ApplicationStopping` token.

```cs
public ValueTask<ISourceStream<User>> UserUpdatedStream(
	[ID(nameof(User))] long? userId,
	[Service] ITopicEventReceiver receiver,
	CancellationToken cancellationToken)
{
	ArgumentNullException.ThrowIfNull(receiver);
	var topic = userId.HasValue ? SpecificUserUpdatedTopic(userId.Value) : UserUpdatedTopic;
	return receiver.SubscribeAsync<User>(topic, cancellationToken);
}

[Subscribe(With = nameof(UserUpdatedStream))]
[TgsGraphQLAuthorize(AdministrationRights.ReadUsers)]
public User UserUpdated([EventMessage] User user)
{
	ArgumentNullException.ThrowIfNull(user);
	return user;
}
```

```cs
public ValueTask<ISourceStream<User>> UserUpdatedStream(
	[ID(nameof(User))] long? userId,
	[Service] ITopicEventReceiver receiver,
	[Service] IHostApplicationLifetime applicationLifetime,
	CancellationToken cancellationToken)
{
	ArgumentNullException.ThrowIfNull(receiver);
	var topic = userId.HasValue ? SpecificUserUpdatedTopic(userId.Value) : UserUpdatedTopic;
	var cts = CancellationTokenSource.CreateLinkedTokenSource(applicationLifetime.ApplicationStopping, cancellationToken); // warning because CTS is going out of scope without being disposed
	return receiver.SubscribeAsync<User>(topic, cts.Token);
}

[Subscribe(With = nameof(UserUpdatedStream))]
[TgsGraphQLAuthorize(AdministrationRights.ReadUsers)]
public User UserUpdated([EventMessage] User user)
{
	ArgumentNullException.ThrowIfNull(user);
	return user;
}
```

**Comment by Cyberboss** [comment]
This is HC14 rc2

**Comment by cmeeren** [comment]
@sunghwan2789, could those tokens be automatically linked?

**Comment by Cyberboss** [comment]
Can this issue also be reopened please?

**Comment by Cyberboss** [comment]
Did a bit of code diving, so cancellation token we get is the HotChocolate request token which originates from the `HttpContext.RequestAborted` token. The issue is Kestrel itself doesn't seem to cancel inflight requests when `ApplicationStopping` fires, rather waiting for them all to complete.

Unfortunately, I can't seem to find _any_ discussion about this.

I'm working on a more global workaround. Will reference this issue when I commit it.

**Comment by Cyberboss** [comment]
Argh, no it's worse than I thought. The token passed into `SubscribeAsync` isn't able to shutdown event streams that are open.

**Comment by Cyberboss** [comment]
See my workaround above. A bit heavy handed, but does the trick.

**Comment by cmeeren** [comment]
I think Kestrel's decision to wait for requests to complete before shutting down is sound for normal HTTP requests, but long-lived subscriptions should of course be canceled. Hoping HC could do this.
