### ISSUE TITLE
Regression after 13.5.1 - StrawberryShake sends custom scalar as string instead of object

### ISSUE THREAD

**Issue by nightroman** [ChilliCream/graphql-platform#6701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

StrawberryShake 13.5.1 send custom scalars based on Any as JSON objects.
Starting with 13.6.0 and including latest 13.7.0 StrawberryShake sends such scalars as strings.

Please find attached the HotChocolate service using a custom scalar `Map` based on `AnyType`
and a test project using StrawberryShake 13.7.0 using `Map` with the registered serializer.

[Map-scalar-2.zip](https://github.com/ChilliCream/graphql-platform/files/13363758/Map-scalar-2.zip)

### Steps to reproduce

(1) Start the service `accounts` and run or debug the test method `Test2` in `My.Test`.

The test fails due to the exception on invoking the GQL request:

```
Unable to convert the value of the argument `filter` to `System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.Object, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]`.
Check if the requested type is correct or register a custom type converter.
```

Fiddler shows that the following JSON is sent.
Note that the `filter` type is unexpected `string`:

```json
{
  "id": "b4e69e078977e64770f0bc4dfdfad17a",
  "query": "query Accounts2($filter: Map!) { users(filter: $filter) { __typename id name problemAny } }",
  "operationName": "Accounts2",
  "variables": {
    "filter": "{ \"id\": 2 }"
  }
}
```

(2) Change `StrawberryShake.Server` version to 13.5.1 in `My.Client.csproj` and run the test again.

The test passes.

Fiddler shows that the following JSON is sent.
Note that the `filter` type is expected `object`:

```json
{
  "query": "query Accounts2($filter: Map!) { users(filter: $filter) { __typename id name problemAny } }",
  "operationName": "Accounts2",
  "variables": {
    "filter": {
      "id": 2
    }
  }
}
```

NB I believe this regression happened in 13.6.0.

### Version

13.7.0

**Comment by michaelstaib** [comment]
Its not a regression but a fix. We for any used JsonDocument on in and output types. This can lead to memory leaks so we reworked this and are now using JsonElement instead as we can make sure that we do not use pooled memory this way.

**Comment by michaelstaib** [comment]
```
extend scalar Map 
    @serializationType(name: "System.Text.Json.JsonElement") 
    @runtimeType(name: "System.Text.Json.JsonElement")
```

this is what you need to update.


and this in your test:

```
var filter = JsonDocument.Parse("""{ "id": 2 }""");
        var res = await _client.Accounts2.ExecuteAsync(filter.RootElement);
```

**Comment by nightroman** [comment]
@michaelstaib Thank you but this does not even compile in 13.7.0

**Comment by nightroman** [comment]
> As an info we discussed this on slack and it worked after clean build.

Correct, with a caveat. Worked in the v14 preview, not 13.7.0.

But in the discussion the next patch 13.8 coming "soon in due time" was also mentioned. Looking forward to it. Many thanks!!
