### ISSUE TITLE
Missing license info in BananaCakePop.Middleware NuGet package

### ISSUE THREAD

**Issue by arekgwizdziel** [ChilliCream/graphql-platform#6704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

There is no license information in above NuGet package (which is a dependency of HotChocolate.AspNetCore package). Because of this it's being flagged as a licensing risk in some of the quality gate tools.

https://nuget.info/packages/BananaCakePop.Middleware/10.0.2

Also, I think there might be a slight confusion in this matter. On this project's page, there is an information that Banana Cake Pop is a part of graphql-platform and the project is clearly marked as MIT licensed:

![image](https://github.com/ChilliCream/graphql-platform/assets/150246607/ccfd45c8-1e15-43b4-8171-550064f81a5c)

But [this](https://chillicream.com/licensing/chillicream-license) suggest that Banana Cake Pop is a proprietary software licensed under ChilliCream License 1.0.

Or am I misunderstanding something? 

### Steps to reproduce

N/A

### Version

13.6.1

**Comment by michaelstaib** [comment]
Banana Cake Pop is under the ChilliCream License stated here:
https://chillicream.com/licensing/chillicream-license

The license is very friendly to users of BCP and only forbids to remove sign in functionality to our cloud services.

BCP is a non critical component that is not at the core of Hot Chocolate and can be disabled.

BCP was never part of this repository and was never under the MIT, we state the License clearly and have now fixed the package to also list it in the nuget package.
