### ISSUE TITLE
Fusion not support @defer directive

### ISSUE THREAD

**Issue by huynhlexuan** [ChilliCream/graphql-platform#6721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I'v added
.AddType<DeferDirectiveType>() to fusion but I got error message
![image](https://github.com/ChilliCream/graphql-platform/assets/107555954/bc384967-9a9e-4bea-8626-16982c6b873b)
Does this feature support yet?

### Steps to reproduce

1. Add AddType<DeferDirectiveType>() to Fusion
2. Use it on banana cake pop

### Relevant log output

```shell
{
  "errors": [
    {
      "message": "Incremental delivery is not yet supported."
    }
  ]
}
```

### Additional Context?

NA

### Version

13.7

**Comment by michaelstaib** [comment]
This is not a bug. We will support it with the next fusion release.
