### ISSUE TITLE
Wrong filter operation when annotating with generic IDAttribute

### ISSUE THREAD

**Issue by jonmaylandvitrolife** [ChilliCream/graphql-platform#6722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

When annotating a property with the generic IDAttribute, the filter operation reflects its original type and not the ID type.

Fx, following will use UuidOperationFilterInput:
`
public record([ID<ServiceA>]Guid ForeignKey);
`

And following will use IdOperationFilterInput
`
public record([ID("ServiceA")]Guid ForeignKey);
`

### Steps to reproduce

1. Having a model with a foreign key property, annotated using generic IDAttribute
2. Add query annotated with [UseFiltering]

### Additional Context?

HotChocolate.Data.Filters.FilterTypeInterceptor.OnBeforeRegisterDependencies only checks for the non-generic IDAttribute.
Would it be a solution to let the generic IDAttribute<T> inherit from IDAttribute ?

### Version

13.7.0

**Comment by michaelstaib** [comment]
You are annotating wrongy as you basically annotate the constructor parameter. To annotate the records property do the following:

```csharp
public record([property: ID<ServiceA>]Guid ForeignKey);
```

**Comment by jonmaylandvitrolife** [comment]
Sorry, the provided code was more or less just paeudo-code. I’ve annotated the property using the property-keyword.

**Comment by jonmaylandvitrolife** [comment]
@michaelstaib I think that this needs to be reopened.

From HotChocolate.Data.Filters.FilterTypeInterceptor.OnBeforeRegisterDependencies:
`
foreach (var field in def.Fields)
        {
            if (field is FilterFieldDefinition filterField &&
                filterField.Member?.GetCustomAttribute(typeof(IDAttribute)) != null)
            {
                filterField.Type = discoveryContext.TypeInspector.GetTypeRef(
                    typeof(IdOperationFilterInputType),
                    TypeContext.Input,
                    discoveryContext.Scope);
            }
        }
`

This only checks for the presence of the non-generic IDAttribute
