### ISSUE TITLE
Fusion with only SSE subscriptions fail if message is too large

### ISSUE THREAD

**Issue by molinch** [ChilliCream/graphql-platform#6739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

With version 13.4.0 GraphQL SSE subgraph support was added to fusion. (https://github.com/ChilliCream/graphql-platform/pull/6356)

It seems that when SSE messages are bigger than X bytes, then exceptions occur on the gateway, which results in those messages being dropped.

The issue is with GraphQLHttpEventStreamProcessor, see:
![image](https://github.com/ChilliCream/graphql-platform/assets/5130190/d87328a5-0601-40a5-90ef-729987a0a19c)

The following exception gets thrown:
![image](https://github.com/ChilliCream/graphql-platform/assets/5130190/5e94bf74-7109-45cf-b6cb-8edc0ba924de)

### Steps to reproduce

1. Have a subgraph which offers a subscription via SSE
2. Have a gateway that fusions subgraphs and offers the same subscription via SSE
3. Use BCP of the gateway to subscribe and receive the messages
4. It will throw

If you use BCP directly on the downstream service (subgraph), then it works fine

### Version

13.7.1-preview.2

**Comment by glen-84** [comment]
I don't know if it's related, but there was a fix [here](https://github.com/ChilliCream/graphql-platform/pull/6642) that is in the 14.x previews.

**Comment by glen-84** [comment]
Should be fixed in [13.8.0-preview.3](https://github.com/ChilliCream/graphql-platform/releases/tag/13.8.0-preview.3).
