### ISSUE TITLE
Adding GraphQL causes exception on .net8.0 when using keyed services registration

### ISSUE THREAD

**Issue by psicus78** [ChilliCream/graphql-platform#6750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Hello,
I have a web application (Microsoft.NET.Sdk.Web, net8.0) in which some services are registered as keyed services:
  - services.TryAddKeyedScoped<IService, ActualService>("key");

That feature is only supported in net8.0 I guess. The problem is that when adding HotChocolate (using builder.Services.AddGraphQLServer()...) the application can not start. This exception is raised: System.InvalidOperationException: This service provider doesn't support keyed services

That is the same error I got when my application was running on .net7.0.

Thanks

### Steps to reproduce

1. Create a webapplication targeting .net8.0
2. Register some keyed service: services.TryAddKeyedScoped<IService, ActualService>("key");
3. Add graphQL to the pipeline;
4. Start application

### Relevant log output

```shell
System.InvalidOperationException: This service provider doesn't support keyed services
```

### Version

13.7.0

**Comment by michaelstaib** [comment]
Can you create a repro?

**Comment by anton-tokarchuk-wongapl** [comment]
> Can you create a repro?

Hi, I have created a repo [here](https://github.com/anton-tokarchuk-wongapl/gq_keyed_di)

**Comment by michaelstaib** [comment]
Interesting .... I will have a look.

**Comment by michaelstaib** [comment]
#6782

**Comment by psicus78** [comment]
Thank you!
