### ISSUE TITLE
Code Generation Type Order Differs by File System

### ISSUE THREAD

**Issue by mattkgross** [ChilliCream/graphql-platform#6754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

We just switched to our HC types using [automatic type registration](https://www.youtube.com/watch?v=QPelWd9L9ck).

Once this happened, however, we noticed that the resulting `HotChocolateTypeModule.g.cs` renders its contents in different orders on Unix file systems compared to Windows file systems. This causes the generated schema to be ordered differently depending on the file system it's generated from. This is quite a pain, as it causes schema checks to fail based on which file system it's being run from.

Instead of leaving the ordering of the generated code up to the FS, having the code generator order the generated types (say alphabetically), would resolve this problem across all platforms.

### Steps to reproduce

1. Add HotChocholate.Types.Analyzers to your project.
2. Add `AddMyServiceTypes()` to the setup of the GQL service on startup.
3. Check the `HotChocolateTypeModule.g.cs` file on a Unix-based system.
4. Check the `HotChocolateTypeModule.g.cs` file on a Windows system.

### Additional Context?

We are generating our schema (and validating changes against it) using `BuildSchemaAsync()`. The resulting schema built has an order directly dependent on that of the types registered in `HotChocolateTypeModule.g.cs`. If we manually register the types instead, the order is preserved across different file systems, given the registration order is static.

### Version

13.4.0

**Comment by Spaier** [comment]
@michaelstaib Facing the same issue.

**Comment by astanula** [comment]
@michaelstaib I have the same issue

**Comment by QuyBT-CoverGo** [comment]
Facing with the same issue, different schema on different OS

**Comment by onionhammer** [comment]
Facing same issue on HC 14, disabling schema-consistency test for now.

**Comment by bbrandt** [comment]
Facing same issue.  Local dev is Windows 11.  Ubuntu build agents in Azure Pipelines.
