### ISSUE TITLE
Source generator ambiguous invocation

### ISSUE THREAD

**Issue by ASafdari** [ChilliCream/graphql-platform#6755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

The issue is somewhat similar to [this one](https://github.com/ChilliCream/graphql-platform/issues/5935).
I have installed the HotChocolate templates and created a GraphQL server project. I get a "Ambiguous invocation" error at `services.AddGraphQLServer()
            .AddTypes()`
However, everything is building and running fine.

### Steps to reproduce

1. Install HotChocolate templates 13.7.0 `dotnet new install HotChocolate.Templates::13.7.0`
2. Create a new GraphQL project `dotnet new graphql `
3. Build and run project
4. Application is working and can make requests
5. Ambiguous invocation error in IDE
![image](https://github.com/ChilliCream/graphql-platform/assets/12391848/fc01148e-8b43-4305-9f29-245ec66b3763)

### Additional Context?

IDE is Jetbrain's Rider 2023.2.3

### Version

13.7.0

**Comment by glen-84** [comment]
Does the error persist after restarting Rider?

**Comment by ASafdari** [comment]
@glen-84 Yes after restarting Rider and my computer, the error still persists.

**Comment by glen-84** [comment]
I'm not able to reproduce this error using:

Windows 11
JetBrains Rider 2023.3
Dotnet 8.0.100

Try updating everything and clearing IDE caches, etc.

**Comment by ASafdari** [comment]
Updated my IDE to 2023.3 and the error is gone!
