### ISSUE TITLE
Unable to deserialize string to LocalDateTime

### ISSUE THREAD

**Issue by mjauernig** [ChilliCream/graphql-platform#6759]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I have a class with a `LocalDateTime` field of `nodatime`.

When i send a mutation with an iso date string the error message `Unable to deserialize string to LocalDateTime` appears.
```
{
	"id": "mutationPersistetQuerySample",
	"variables": {
		"to": "2023-12-02T00:00:00.000Z",
		"from": "2023-11-30T23:00:00.000Z"
	}
}
```

I added the package `HotChocolate.Types.NodaTime` and added the types
```
        .AddType<DateTimeZoneType>()
        .AddType<LocalDateTimeType>()
        .AddType<OffsetType>();
```

Is it necessary to write a custom converter or did i forgot something to configure?

### Steps to reproduce

1. Repeat steps from documentation about nodatime [https://chillicream.com/docs/hotchocolate/v13/defining-a-schema/scalars/#nodatime](https://chillicream.com/docs/hotchocolate/v13/defining-a-schema/scalars/#nodatime)

### Version

13.7.0

**Comment by michaelstaib** [comment]
This "2023-12-02T00:00:00.000Z" is not a LocalDateTime format ... it must be "2020-12-25T13:46:78"
