### ISSUE TITLE
Locale issue when deploying to Openshift 

### ISSUE THREAD

**Issue by btranggg** [ChilliCream/graphql-platform#6760]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

error MSB4184: The expression "[MSBuild]::VersionGreaterThanOrEquals(/usr/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8);/usr/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8);

Issue seems similar to [issue](https://github.com/ChilliCream/graphql-platform/issues/6441) which was already closed. 

### Steps to reproduce

1. On a system that does NOT have the "en_US.UTF-8" locale defined, do a build of a Strawberry Shake application.

csproj file 
`<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.21" />
    <PackageReference Include="Microsoft.AspNetCore.JsonPatch" Version="6.0.23" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.21">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Identity.Web" Version="2.13.3" />
    <PackageReference Include="StrawberryShake.Server" Version="13.7.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Persistence\Persistence.csproj" />
  </ItemGroup>
</Project>
`

### Relevant log output

```shell
STEP 3/9: ENV OPENSHIFT_BUILD_NAME="emats-testtttt-23" OPENSHIFT_BUILD_NAMESPACE="emats-test" OPENSHIFT_BUILD_SOURCE="git@ssh.dev.azure.com:v3/AssessorAppSupport/eMATS/eMATS" OPENSHIFT_BUILD_REFERENCE="openshift-test" OPENSHIFT_BUILD_COMMIT="6e271552edeea1bd88f10ddefc731b7c07baaa77" DOTNET_STARTUP_PROJECT="API/API.csproj" LC_ALL="en_US.UTF-8"
STEP 4/9: USER root
STEP 5/9: COPY upload/src /tmp/src
STEP 6/9: RUN chown -R 1001:0 /tmp/src
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
STEP 7/9: USER 1001
STEP 8/9: RUN /usr/libexec/s2i/assemble
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
---> Installing application source...
Using SDK: 6.0.115
---> Restoring application dependencies...
Determining projects to restore...
Restored /opt/app-root/src/Domain/Domain.csproj (in 116 ms).
Restored /opt/app-root/src/Persistence/Persistence.csproj (in 2.76 sec).
Restored /opt/app-root/src/Application/Application.csproj (in 2.76 sec).
Restored /opt/app-root/src/API/API.csproj (in 17.1 sec).
---> Publishing application...
Microsoft (R) Build Engine version 17.0.1+b177f8fa7 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
/usr/bin/sh : warning : setlocale: LC_ALL: cannot change locale (en_US.UTF-8) [/opt/app-root/src/API/API.csproj]
/usr/bin/sh : warning : setlocale: LC_ALL: cannot change locale (en_US.UTF-8) [/opt/app-root/src/API/API.csproj]
/usr/bin/sh : warning : setlocale: LC_ALL: cannot change locale (en_US.UTF-8) [/opt/app-root/src/API/API.csproj]
/opt/app-root/.nuget/packages/strawberryshake.server/13.7.0/build/StrawberryShake.Server.targets(48,20): error MSB4184: The expression "[MSBuild]::VersionGreaterThanOrEquals(/usr/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8);/usr/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8);/usr/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8);6.0.115, 6)" cannot be evaluated. Version string was not in a correct format. [/opt/app-root/src/API/API.csproj]
error: build error: error building at STEP "RUN /usr/libexec/s2i/assemble": error while running runtime: exit status 1
```

### Additional Context?

dotnet sdk - 6.0.115
Strawberryshake.server - 13.7.0

### Version

13.7.0

**Comment by glen-84** [comment]
Did you try a 14.x preview?
