### ISSUE TITLE
Support custom mutation conventions

### ISSUE THREAD

**Issue by igor-shapkin-stenn** [ChilliCream/graphql-platform#6762]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Yes.

The current implementation of mutation conventions follows [the error stage 6a Pattern](https://chillicream.com/docs/hotchocolate/v13/defining-a-schema/mutations#errors). The interface for using it on the server side is perfect: extension methods are expressive and concise, and exception handling does all the work without having to define, catch, and map the errors. But from the client's perspective, it could have been better: 
- Firstly, a response type states that it can have both a payload and a field for errors, assuming only one field can be filled. 
- Secondly, on the frontend side, it has to be initially checked whether the error is null or not, then write a switch for every type of error defined by a mutation. 
- And finally, there is always a collection of errors by this convention. Even though, in reality, API usually throws only one of all possible domain exceptions. For instance, we have a mutation for `tryOnBoots(int size)`, which can return either TooSmall or TooBig errors, but never both.

The current implementation of mutation conventions leverages the TypeIntercpeter hooks. However, some of the essential events are internal, making it impossible to implement our custom approach for error handling (the same way as the current MutationConventionTypeIntercepter implemented) and to build a stricter and more comfortable convention.

### The solution you'd like

To make all events inside the `TypeInterceptor` public so that library users could implement their own custom conventions.

**Comment by michaelstaib** [comment]
> To make all events inside the TypeInterceptor public so that library users could implement their own custom conventions.

TypeInterceptors are our internal API to create HotChocolate features and not intended for the user. TypeInterceptors have side-effect on other TypeInterceptors which leads to a lot of complexities. We will over the next year reinvent HotChocolates type system and introduce ways to easier implement things like that. But do not expect anything before the end of the next year as we building it from the ground up with AOT in mind.

However the intend from us internally is to make building enterprise grade schemas easier with validated patterns.

> Secondly, on the frontend side, it has to be initially checked whether the error is null or not, then write a switch for every type of error defined by a mutation.

Not really right ... on the frontend you can in the simplest of cases just use the error type and and switch on that.

> And finally, there is always a collection of errors by this convention. Even though, in reality, API usually throws only one of all possible domain exceptions. For instance, we have a mutation for tryOnBoots(int size), which can return either TooSmall or TooBig errors, but never both.

Stage 6a is designed for schema evolvability and also to allow validation errors for which you could have many.

**Comment by michaelstaib** [comment]
I am closing this issue as we are working on a new type system core which will enable these features.

**Comment by michaelstaib** [comment]
For reference of what stage 6a is about:
https://xuorig.medium.com/a-guide-to-graphql-errors-bb9ba9f15f85

**Comment by igor-shapkin-stenn** [comment]
@michaelstaib thank you for the quick answer. Ok, I guess we have no other options than waiting. It makes sense if you're going to make a lot of changes.
