### ISSUE TITLE
Cost attribute does not allow for multipliers

### ISSUE THREAD

**Issue by rbaker00** [ChilliCream/graphql-platform#6774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

C# only allows specific types to be used as parameters for attributes. To set the multipliers when using the `Cost` attribute, you need to pass a `MultiplierPathString`. This means the only way to use the `Cost` attribute is with no multipliers (using `Cost` also gets rid of the default multipliers from pagination, so paginated fields are forced to use the default complexity).

https://github.com/dotnet/csharpstandard/blob/standard-v6/standard/attributes.md#2124-attribute-parameter-types

### Steps to reproduce

1. Add the `Cost` attribute to a resolver, ex: `[Cost(1, new MultiplierPathString("test"))]`.

### Version

13.4.0

**Comment by michaelstaib** [comment]
This could be an oversight ... you can however use the fluent API .... we gonna fix it.
