### ISSUE TITLE
Downloaded schema misses deprecated directive of field argument

### ISSUE THREAD

**Issue by nightroman** [ChilliCream/graphql-platform#6785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Strawberry Shake

### Describe the bug

The schema downloaded by `strawberryshake.tools` misses the expected deprecated directive of a field argument.
Please use the attached project and described steps.
[ss-missing-deprecated-directive.zip](https://github.com/ChilliCream/graphql-platform/files/13710905/ss-missing-deprecated-directive.zip)

The original (now changed) issue: <https://github.com/ChilliCream/graphql-platform/issues/6302>

### Steps to reproduce

Start the service:

```
dotnet run
```

Download the schema:

```
dotnet graphql download http://localhost:5000/graphql
```

**Actual result**

The field `book` has the argument `authors` with no `deprecated` directive

```graphql
type Query {
  book(authors: [String!]): Book!
}
```

**Expected result**

The field `book` has the argument `authors` with the `deprecated` directive

```graphql
type Query {
  book(authors: [String!] @deprecated(...)): Book!
}
```

**Workaround(?)**

The expected result maybe obtained using the `?sdl` query parameter

```powershell
Invoke-RestMethod http://localhost:5000/graphql?sdl
```

### Version

13.8.0

**Comment by nightroman** [comment]
@tobias-tengler @michaelstaib This issue might be fixed before (cannot tell) but it is currently present (reappeared?) in the latest v13.9.7.

I cannot reopen this issue. Should I create a new one, basically the same? Please let me know. Thank you.

**Comment by michaelstaib** [comment]
It's not an issue. The tooling uses introspection and introspection does not have the capability for type system directives. You can however use the sdl endpoint which is not specified. It's hotchocolate only.

**Comment by nightroman** [comment]
@michaelstaib 
Maybe there are different deprecated directives? Our same method of getting schema (SS download) gets us some deprecated directives as expected and misses directives like in the story.

**Comment by nightroman** [comment]
Namely here the schema result: it has the expected deprecated on `Book.someDeprecated` but it misses the expected deprecated on `Query.book.authors`:

```graphql
schema {
  query: Query
}

type Query {
  book(authors: [String!]): Book!
}

type Book {
  title: String!
  author: Author!
  someDeprecated: String @deprecated(reason: "This is a test.")
}

type Author {
  name: String!
}
```

**Comment by nightroman** [comment]
> So where is the issue ... not following ... what tool do you think is behaving wrong?

I think it might be StrawberryShake download. I am using the latest "13.9.7"

**Comment by nightroman** [comment]
@michaelstaib  Please find below attached the project (the original updated all pieces with 13.9.7)
[ss-missing-deprecated-directive.zip](https://github.com/user-attachments/files/16235677/ss-missing-deprecated-directive.zip)

**Comment by michaelstaib** [comment]
I have checked it ... its fixed in 14. We do not plan to port this back as we release 14 in August.
