### ISSUE TITLE
Query and mutation type descriptions keep changing when using the source generator

### ISSUE THREAD

**Issue by SapiensAnatis** [ChilliCream/graphql-platform#6787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I am using source generators with the `[QueryType]` and `[MutationType]` attributes, and allowing HC to generate my schema descriptions using XML comments. Because I am using the source generator, I do not have an actual base `Query` class.

I am structuring my project so that I will have a query and mutation type broadly for each entity I have to deal with, so for instance `MovieQueries`, `MovieMutations` and `BookQueries`, `BookMutations`.

I have found that when adding a new mutation or query, often the description of the root query or mutation type in the schema will change to the description of my newest class, so my schema may end up looking like

```gql
"""
Movie queries. <------ Schema picks a seemingly random [QueryType] class for description
"""
type Query {
  """
  Get a book.


  **Returns:**
  A book.
  """
  book: Book!

  """
  Gets a movie.


  **Returns:**
  A movie.
  """
  movie: Movie!
}
```

I understand that HotChocolate has to pick _some_ class for the root query type description, but I was wondering if there is any way to control which class it picks or override it, as currently I don't understand how the class is being picked and it leads to my root type descriptions constantly changing. Am I structuring my project incorrectly?

I would like for my root query type to either have no description or something generic.

### Steps to reproduce

1. `dotnet new graphql`
2. Rename the given `Query` class to `BookQueries` and add an XML summary
3. Add a new `MovieQueries` class and add an XML summary
4. HotChocolcate should pick the MovieQueries class for the schema description.

### Version

13.7.0

**Comment by tobias-tengler** [comment]
This is likely the case, because the source generator is incremental, i.e. the latest class you added will also be the last to be registered. With a full rebuild the result _should_ be consistent.
I would go ahead and override the description of the query type yourself though:

```csharp
services.AddGraphQLServer()
    .AddQueryType(d => d.Description("Your description"))
    .AddSourceGeneratorTypes()
    // ...
```

**Comment by SapiensAnatis** [comment]
Hi Tobias, thanks for your reply. I changed my test project to register HotChocolate as

```cs
builder
    .Services
    .AddGraphQLServer()
    .AddQueryType(d => d.Description("My custom description"))
    .AddTypes();
```

This was partially successful, now my `Query` type in the test project looks like this:

```gql
"""
Query
"""
type Query {
  """
  Get a book.


  **Returns:**
  A book.
  """
  book: Book!

  ...
```

Oddly the custom description I have inputted is not respected, but I would have been happy with """Query""". However, when I came to apply this to my larger project rather than the minimum reproducible example, it doesn't seem to change the description at all from the XML comment, even with a rebuild :(

Do you have any further ideas?
