### ISSUE TITLE
Distributed Tracing of requests

### ISSUE THREAD

**Issue by thompson-tomo** [ChilliCream/graphql-platform#6805]
### Product

Hot Chocolate & Strawberry shake

### Is your feature request related to a problem?

I want to be able trace a request from client to server & see all the logs which have been captured to have a full picture about what is going on.

### The solution you'd like

I want the strawberry shake client to ensure that the tracing headers are set on the requests being made to the server. The server should be setting the current activity based on the data received in the header.

**Comment by thompson-tomo** [comment]
Note I have seen https://chillicream.com/docs/hotchocolate/v13/server/instrumentation which talks about tracing being possible but no mention of the distributed tracing aspect.

**Comment by PascalSenn** [comment]
@thompson-tomo  Distributed tracing is done via OpenTelemetry in .net. Once you have configured open telemetry, the http clients will automatically include the trace headers and your traceId will be consistent throughout your application. We just use the built in `Activity` apis. 

https://github.com/open-telemetry/opentelemetry-dotnet
