### ISSUE TITLE
List of execution events to override is wrong

### ISSUE THREAD

**Issue by gmanvel** [ChilliCream/graphql-platform#6812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

Wiki page of [Execution Events to override](https://chillicream.com/docs/hotchocolate/v12/server/instrumentation#execution-events) lists methods that do not exist in HC v12/v13.

For example `CompileOperation`, `ExecuteOperation` are missing

![image](https://github.com/ChilliCream/graphql-platform/assets/11509911/18e62a83-ee4b-4d49-b780-d8a024259c11)

### Steps to reproduce

Create a class `MyExecutionEventListener` and inherit from `ExecutionDiagnosticEventListener`
Try to override `CompileOperation` or `ExecuteOperation` methods.

### Version

12.3.2

**Comment by glen-84** [comment]
https://github.com/ChilliCream/graphql-platform/blob/12.22.2/src/HotChocolate/Core/src/Execution/Instrumentation/ExecutionDiagnosticEventListener.cs#L77

https://github.com/ChilliCream/graphql-platform/blob/12.22.2/src/HotChocolate/Core/src/Execution/Instrumentation/ExecutionDiagnosticEventListener.cs#L81

You're not on the latest version of v12.

**Comment by michaelstaib** [comment]
Closing issue as this exists on latest version. Thx @glen-84
