### ISSUE TITLE
Add authentication helper function and example for Hot chocolate Subscriptions

### ISSUE THREAD

**Issue by natheeshsunway** [ChilliCream/graphql-platform#6816]
### Product

Hot Chocolate

### Is your feature request related to a problem?

I want to add authentication for my Subscriptions in Graphql. I am not able find easy solution to adopt the authentication for my Subscriptions. And i don't see any full fledged documentations. Seems like anyone able to subscribe the channel.

### The solution you'd like

Please add some helper function to easily authenticate the  Subscriptions. And please add more example to Terminate , Authenticate, How to target user (Like sending message to particular user like Chat)  Subscriptions. Thank you.

Please add example like chat application. Like this https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL.Tests/Subscription/SubscriptionSchema.cs

**Comment by michaelstaib** [comment]
Regarding authentication its important to understand authentication with websockets and also their implications... if you are only using sse its standard HTTP authentication ... although even here you have to think about enduring connection that might need additional validation. You can take control of the stream.

**Comment by michaelstaib** [comment]
This might help:
https://github.com/PascalSenn/SubscriptionChatBotExample

**Comment by michaelstaib** [comment]
In this example pascal takes control of the underlying eventstream. You can also do that with the topic event receiver by using different topics per user.

**Comment by michaelstaib** [comment]
Join us un slack.chillicream.com

**Comment by michaelstaib** [comment]
Closed this as all this is built in. join us in the slack channel and we get you sorted.
