### ISSUE TITLE
HotChocolate.Types.Analyzers doesn't generate anything

### ISSUE THREAD

**Issue by neistow** [ChilliCream/graphql-platform#6849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I've installed `HotChocolate.Types.Analyzers` in my project, but I don't see any generated extension methods.

### Steps to reproduce

1. Create a new project and add the following packages:
```
    <ItemGroup>
        <PackageReference Include="HotChocolate.AspNetCore" Version="13.8.1" />
        <PackageReference Include="HotChocolate.Types.Analyzers" Version="13.8.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>
```
2. Add the following classes:
```cs
[GraphQLName("Book")]
public class BookGql
{
    public Guid Id { get; set; }
    public required string Name { get; set; }
}

[QueryType]
public class GetBooksQuery
{
    public IEnumerable<BookGql> Books()
    {
        return new List<BookGql>
        {
            new()
            {
                Id = Guid.NewGuid(),
                Name = "MyBook"
            }
        };
    }
}
```
3.  Add the following to the `Program.cs`
```cs
var builder = WebApplication.CreateBuilder(args);

builder.Services
    .AddGraphQLServer();

var app = builder.Build();

app.MapGraphQL();

app.Run();
```

4. Add module configuration (just to be sure name is distinct)
```cs
[assembly: Module("BuggyTypes")]
```
5. Observe the result: no generated extension method that registers `BookGql` type and `GetBooksQuery`

### Version

13.8.1

**Comment by tobias-tengler** [comment]
This should be working. What kind of editor are you using? If you write out `.AddBuggyTypes();` by hand and do a `dotnet build`, does it fail?

**Comment by neistow** [comment]
@tobias-tengler I added `.AddBuggyTypes()` and ran `dotnet build` and it worked. I'm using Rider 2023.1. And I had no previous issues with code generation. Packages like `Grpc.Tools` work fine and I'm able use generated files (just checked). Any ideas why this might happen?

**Comment by tobias-tengler** [comment]
Mhmm, I'm not that familiar with Rider. Maybe consult their documentation on incremental source generators. Maybe you have disabled analyzers?

**Comment by neistow** [comment]
Updated to Rider 2023.3.3 and it works. Now I can see generated files. Thanks for the help.

![image](https://github.com/ChilliCream/graphql-platform/assets/55974615/b339ab52-949f-4b47-8499-eef67403730a)
