### ISSUE TITLE
Custom Directive for Argument is not working

### ISSUE THREAD

**Issue by Sangeetha-Murugesan** [ChilliCream/graphql-platform#6858]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Product

Hot Chocolate

### Describe the bug

I have created custom directive for Argument to perform some validations and the created directive is listed as part of schema, But when I am trying to execute the query using the custom argument directive, getting query syntax error as we could'nt use the directive in client graphql.

Also, when I am trying to generate schema file at runtime, custom directive was added as part of query arguments but while viewing the schema definition in banana cake pop, schema is differed from the generated file. 

Attaching the schema and query execution screenshot for your reference, Pls help to resolve this

Schema Definition BCP :  ![schema-argument directive](https://github.com/ChilliCream/graphql-platform/assets/45658961/4dca7679-c4fd-471f-b489-06db012d7b6d)

Schema Definition at generated file : 
![Sdl_01](https://github.com/ChilliCream/graphql-platform/assets/45658961/5fad36a0-c332-42a0-a47e-f34148e87191)

Query execution : 
![query execution](https://github.com/ChilliCream/graphql-platform/assets/45658961/b4c86013-31da-4be2-bda9-7e48dc67f70e)

### Steps to reproduce

Using the sample repo, u could regenerate the same [https://github.com/Sangeetha-Murugesan/CustomDirective](url)

### Version

13.4.0

**Comment by michaelstaib** [comment]
This is not a bug. Directive middleware is only supported for the following locations:
`FIELD` and `FIELD_DEFINITION`.
