### ISSUE TITLE
Faulty documentation on batch sizes

### ISSUE THREAD

**Issue by RobertStigsson** [ChilliCream/graphql-platform#6865]
### Product

Green Donut

### Version

13.8.1

### Link to minimal reproduction

https://github.com/ChilliCream/graphql-platform/blob/e2308ce28c296346bd5443bede04f1b5aec91d8b/src/GreenDonut/src/Core/DataLoaderOptions.cs#L11

### Steps to reproduce

The documentation clearly states 
```
/// default value is set to <c>0</c>.
```

while the actual value clearly is 1024

```
public int MaxBatchSize { get; set; } = 1024;
```

### What is expected?

Documentation should match the code.

### What is actually happening?

Documentation doesn't match the code.

### Additional context

I don't know if you want 1024 to be the default value, or 0, but it should match.

**Comment by PascalSenn** [comment]
@RobertStigsson  Do you want to do a PR?

**Comment by RobertStigsson** [comment]
I could do a PR, but I don't know if I stumbled upon a bug or if it's just documentation being wrong?
