### ISSUE TITLE
Support for [UseFiltering] on `IAsyncEnumerable<>`

### ISSUE THREAD

**Issue by icanhasjonas** [ChilliCream/graphql-platform#6866]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Many of our backends return `IAsyncEnumerable<>` results, as most are just KV-databases and typically partitioned paging is required to get all data. Some times it's just nice to be able to filter the results before returning, specially for database wide mutation such as `mutation { forEachUser( where: { .... etc } ) { addUserToRole(..... ) } }` and such... 

So, we noticed that IAsyncEnumerable just aren't filtered. I propose a simple addition to modify `QueryableFilterProvider. ApplyToResult()` to fix the problem, until the whole flow is async, or `IQueryableAsync` happens, or support for `IObservable` with filters

### The solution you'd like

[QueryableFilterProvider](https://github.com/ChilliCream/graphql-platform/blob/main/src/HotChocolate/Data/src/Data/Filters/Expressions/QueryableFilterProvider.cs#L183-L192)

Could become,

```cs
    protected virtual object? ApplyToResult<TEntityType>(
        object? input,
        Expression<Func<TEntityType, bool>> where)
        => input switch
        {
            IQueryable<TEntityType> q => q.Where(where),
            IEnumerable<TEntityType> q => q.AsQueryable().Where(where),
            /** additional support for IAsyncEnumerable **/
            IAsyncEnumerable<TEntityType> q => q.ToEnumerable().AsQueryable().Where(where),
            QueryableExecutable<TEntityType> q => q.WithSource(q.Source.Where(where)),
            _ => input
        };
```

**Comment by michaelstaib** [comment]
You realize that what you propose there would load everything straight into memory. What we do with `IEnumerable` is for small sets where you pass a small array with filtering. We will not enable this as it would be dangerous to expose such an API.

If you have a proper business layer you should reverse the thinking and grab and rewrite the query graph yourself and then return just the filters stream as an `IAsyncEnumerable`. This works already.

You can get the filter context by injecting `IFilterContext` and signal to the execution engine with `context.Handled()` that you have taken control. In this case the execution engine will just write the stream to the result.
