### ISSUE TITLE
Remove dependencies from Green Donut when provided by framework

### ISSUE THREAD

**Issue by thompson-tomo** [ChilliCream/graphql-platform#6868]
### Product

Green Donut

### Is your feature request related to a problem?

I want to reduce the package size & amount of dependencies to reduce surface area for CVE'S.

### The solution you'd like

I would like that any dependency that can be provided by the framework ie System.Text.Json the framework is leveraged to reduce dependencies.

**Comment by thompson-tomo** [comment]
Happy to submit this as a PR

**Comment by michaelstaib** [comment]
You can have a stab at greendonut ... we have started already grouping the references by framework version ...

```xml
  <ItemGroup>
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0' OR '$(TargetFramework)' == 'netstandard2.1' OR '$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="6.0.0" />
  </ItemGroup>
```
Start with a PR for GreenDonut and then we will work through this.

I am closing the other issues as they are juts clogging the backlog.

**Comment by thompson-tomo** [comment]
PR will be done before Monday

**Comment by thompson-tomo** [comment]
Pr all submitted. as mentioned in #6869 & #6870 happy to do those libraries in a similar manner to reduce the dependency graph.
