### ISSUE TITLE
Remove dependencies from Strawberry Shake when provided by framework

### ISSUE THREAD

**Issue by thompson-tomo** [ChilliCream/graphql-platform#6870]
### Product

Strawberry Shake

### Is your feature request related to a problem?

I want to reduce the package size & amount of dependencies to reduce surface area for CVE'S.

### The solution you'd like

I would like that any dependency that can be provided by the framework ie System.Text.Json the framework is leveraged to reduce dependencies.

**Comment by thompson-tomo** [comment]
Happy to submit this as a PR

**Comment by michaelstaib** [comment]
closing this issue as this is an ongoing effort.

**Comment by thompson-tomo** [comment]
@michaelstaib for the packages I identified as being able to be optimised would you accept PR?
