### ISSUE TITLE
Negative pagination first/last values causes "Unexpected Execution Error"

### ISSUE THREAD

**Issue by cmeeren** [ChilliCream/graphql-platform#6874]
### Product

Hot Chocolate

### Version

13.8.1

### Link to minimal reproduction

See zip below

### Steps to reproduce

Repro solution: [HotChocolateBugRepro.zip](https://github.com/ChilliCream/graphql-platform/files/14221743/HotChocolateBugRepro.zip)

Code for reference:

```c#
public class Query
{
    [UsePaging]
    public IEnumerable<string> GetStrings() => [];
}
```

Query:

```graphql
query {
  foo: strings(first: -1) {
    nodes
  }

  bar: strings(first: 1) {
    nodes
  }
}
```

### What is expected?

A descriptive error message that does not halt the entire execution, just like if the value is too high (e.g. `first: 51` with the repro solution).

Specifically, something like this:

```json
{
  "errors": [
    {
      "message": "The requested number of values per page must be at least 0",
      "path": [
        "foo"
      ],
      "extensions": {
        "code": "HC<something>",
        "field": "Query.strings",
        "requestedItems": -1,
        "minAllowedItems": 0
      }
    }
  ],
  "data": {
    "foo": null,
    "bar": {
      "nodes": []
    }
  }
}
```

### What is actually happening?

Execution halts and a generic "Unexpected Execution Error" is returned.

**Comment by timerplayer** [comment]
I would try to provide a fix for the problem.
