### ISSUE TITLE
[F#] Unexpected "No compatible constructor found for input type" even if type converter is specified

### ISSUE THREAD

**Issue by cmeeren** [ChilliCream/graphql-platform#6886]
### Product

Hot Chocolate

### Version

13.8.1

### Link to minimal reproduction

See zip below

### Steps to reproduce

Repro solution: [HotChocolateRepro.zip](https://github.com/ChilliCream/graphql-platform/files/14237644/HotChocolateRepro.zip)

Not sure if F# is relevant to this issue, but it was the simplest way I could repro it.

Relevant code for reference:

```f#
type Username = Username of string

type Query() =
    member _.GetUsername(username: Username) = username

builder.Services
    .AddGraphQLServer()
    .AddQueryType<Query>()
    .AddTypeConverter<Username, string>(fun (Username x) -> x)
    .AddTypeConverter<string, Username>(Username)
```

### What is expected?

The introspection query works correctly and the following query works: `query { username(username: "foo") }`.

### What is actually happening?

The introspection query fails with:

> System.InvalidOperationException: No compatible constructor found for input type type `HotChocolateRepro.Username`.
> Either you have to provide a public constructor with settable properties or a public constructor that allows to pass in values for read-only properties. There was no way to set the following properties: tag, item.

This is unexpected because in the two `AddTypeConverter` calls I am specifying how to convert between `Username` and `string` both ways, so the constructor HotChocolate complains about will never need to be called.

**Comment by michaelstaib** [comment]
Is username a scalar or an object in GraphQL?

**Comment by cmeeren** [comment]
It's _supposed_ to be a scalar. Given that I specify a conversion to/from `string` I would assume it to be treated as a `String` in GraphQL, but that's not working. However, since the introspection query fails with the exception above, it's impossible for me to know what it _is_.

Please let me know if I misunderstood your question.

**Comment by michaelstaib** [comment]
> member _.GetUsername(username: Username) = username

this needs to be annotated in this case ... with a GraphQLType otherwise it is inferred as a type ... I would guess ... but I have no clue of F#

**Comment by michaelstaib** [comment]
It could also be something different :D

**Comment by cmeeren** [comment]
I have now confirmed this is not related to F#. Please see the attached C# repro solution.

[HotChocolateBugRepro.zip](https://github.com/ChilliCream/graphql-platform/files/14275989/HotChocolateBugRepro.zip)

Relevant code:

```c#
var builder = WebApplication.CreateBuilder(args);
builder
    .Services
    .AddGraphQLServer()
    .AddQueryType<Query>()
    .AddTypeConverter<Username, string>(u => u.Value)
    .AddTypeConverter<string, Username>(u => new Username(u));
var app = builder.Build();
app.MapGraphQL();
app.Run();


public class Query
{
    public Username Username(Username username) => username;
}


public record Username(string Value);
```

Based on my reading of the docs on [Custom converters](https://chillicream.com/docs/hotchocolate/v13/defining-a-schema/scalars#custom-converters), this is my expected SDL:

```graphql
type Query {
  username(username: String!): String!
}
```

Actual SDL:

```graphql
type Query {
  username(username: UsernameInput!): Username!
}

input UsernameInput {
  value: String!
}

type Username {
  value: String!
}
```

**Comment by cmeeren** [comment]
My bad, I see I missed the call to `BindRuntimeType`. If I add `BindRuntimeType<Username, StringType>()`, it works.
