### ISSUE TITLE
Allow eliding GlobalStateAttribute

### ISSUE THREAD

**Issue by cmeeren** [ChilliCream/graphql-platform#6899]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Most of my resolvers require the currently authenticated user, which is a custom `User` type that I add as global state in HTTP/socket interceptors, as recommended in the docs. I have also created a `UserAttribute` inheriting from `GlobalStateAttribute`. However, I still find it noisy to have to apply the attribute everywhere I need a `User`.

### The solution you'd like

I would like something similar to HotChocolate's existing concept of "well-known services" where you don't have to use `[Service]`. I want to be able to register `User` as a well-known global state, and whenever a resolver takes a `User` as an argument, HotChocolate finds the (only) `User` in the global state. (I'm okay with HotChocolate failing if there are multiple `User` values in the global state; that will never happen.)

**Comment by tobias-tengler** [comment]
Something like the following should work:

```csharp
builder.Services
    .AddGraphQLServer()
    .AddParameterExpressionBuilder(ctx => ctx.GetGlobalState<User>("user"))
```

**Comment by cmeeren** [comment]
Great, thanks! This should be documented.
