### ISSUE TITLE
bug(federation): ApolloFederation does not require any entities to be present 

### ISSUE THREAD

**Issue by dariuszkuc** [ChilliCream/graphql-platform#6900]
### Product

Hot Chocolate

### Version

latest

### Link to minimal reproduction

https://github.com/dariuszkuc/hc-no-entities

### Steps to reproduce

Start the server and try to execute a query OR try to generate the schema.

### What is expected?

Valid federated GraphQL schema is generated and server process incoming requests.

### What is actually happening?

Runtime exception is thrown when using `ApolloFederation` package with a GraphQL server that does not specify any entities.

### Relevant log output

```shell
1. The schema has no types with a KeyDirective and therefore no entities. Apollo federation requires at least one entity.
  at HotChocolate.ApolloFederation.FederationTypeInterceptor.OnTypesInitialized()
```

### Additional context

While most federated schemas will contain entities, it is a perfectly valid use case to also federated schemas without any entities (i.e. expose all your queries through a single gateway).

1st attempt with naive fix  -> https://github.com/ChilliCream/graphql-platform/pull/6867

Underlying problem is that `Entity` union is registered before we know whether we have any entities or not. In the PR I was just removing the exception which was thrown when no entities were present but the resulting would generate an invalid schema with empty `Entity` enum.

**Comment by kellyrbourg** [comment]
When testing 13.9.1 and the 14.0.0 preview branch, we are discovering that this error is throwing even though we have type extensions that are defining the `Key` and `ReferenceResolver` for the entities. It's like it is only finding objects that have the key defined via the underlying type and not considering the type extensions at all.

**Comment by michaelstaib** [comment]
Yes ... its on my list ... we will have that fixed in the august release.

**Comment by rohinz** [comment]
@michaelstaib: Will the fix be deployed with the next 13.x release?
