### ISSUE TITLE
Fusion subgraph doesn't send error message when websocket connection is killed

### ISSUE THREAD

**Issue by plhester** [ChilliCream/graphql-platform#6909]
### Product

Hot Chocolate

### Version

14.0.0-p.29

### Link to minimal reproduction

n/a

### Steps to reproduce

1. Have a fusion gateway and a separate subgraph. 
2. Establish a websocket subscription through the gateway to the subgraph. 
3. Kill the subgraph
4. A "complete" message is sent to front-end, so front-end doesn't know to try reconnecting

### What is expected?

I expected an error message to go to front-end so it could try reconnecting.

### What is actually happening?

Receiving a closed message without any error message.

![image](https://github.com/ChilliCream/graphql-platform/assets/5224185/67022ba6-54fd-4d33-8081-dd37a8a0a586)

**Comment by plhester** [comment]
This image is when the gateway is terminated but subgraph is not. Client is able to detect it needs to try reconnecting.
![image](https://github.com/ChilliCream/graphql-platform/assets/5224185/37c360f3-a7f3-438d-b03c-538cb1e03e5f)

This image is when subgraph is terminated but gateway is not. This is bad, as a client does not know to try reconnecting.
![image](https://github.com/ChilliCream/graphql-platform/assets/5224185/b06d18b5-ef2a-4e16-860f-4bfc78802d7c)

**Comment by CormacAtTPICAP** [comment]
Bumping this issue, also affecting us.

**Comment by michaelstaib** [comment]
This is fixed
