### ISSUE TITLE
ApplyPolicy.Validation does not work with Relay node endpoint

### ISSUE THREAD

**Issue by BickelLukas** [ChilliCream/graphql-platform#6945]
### Product

Hot Chocolate

### Version

13.9.0

### Link to minimal reproduction

https://github.com/BickelLukas/HotChocolateAuthorizeRepro

### Steps to reproduce

Getting returns unauthorized when the user does not have access to one possible node, even if a different one is resolved. 

```
# this works
query Books {
  books {
    id
    title
  }
}

# this doesn't work
query Authors {
  authors {
    id
    name
  }
}

# this should work but doesn't
query BookNode {
  node(id: "Qm9vawppMQ==") {
    id
    ... on Book { 
      title
    }
  }
}

# this shouldn't work
query AuthorNode {
  node(id: "QXV0aG9yCmkx") {
    id
    ... on Author { 
      name
    }
  }
}
```

### What is expected?

I should be able to resolve a book via the node endpoint but not an author

### What is actually happening?

Nothing is able to be resolved via the node endpoint

**Comment by michaelstaib** [comment]
This is the correct behaviror for Validation ... as we cannot predict in this case what the entity will be ... you could still fetch each of the items ... try to use BeforeResolver instead as we can in this case use runtime evaluation.

**Comment by BickelLukas** [comment]
@michaelstaib I understand your reasoning for endpoints returning Interfaces and that limitation is alright there.
But the node enpoint can return almost any type in the whole application and not being able to use `ApplyPolicy.Validation` on any type implementing node is a very hard limitation.

The Node enpoint knows which resolver to call based on the type in the `HotChocolate.Types.Relay.IDValue` struct. Couldn't the validation narrow down the possible result types to those returned by the resolver for this id?
