### ISSUE TITLE
Make Banana Cake Pop accessible when .RequireAuthorization() is appeneded to .MapGraphQL() or update Banana Cake Pop to feature a log in dialog

### ISSUE THREAD

**Issue by shaopard** [ChilliCream/graphql-platform#6947]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Yes. I have the same problem as reported in this bug
https://github.com/ChilliCream/graphql-platform/issues/2869

The gist of it is that when appending .RequireAuthorization() to .MapGraphQL(), Banana Cake Pop is no longer accessible - returns a 401 Unauthorized response. This makes it not usable, so Banana Cake Pop cannot be used for testing.

### The solution you'd like

1. Add a setting to allow anonymous users to reach Banana Cake Pop (while still needing authentication for data retrieval calls) or allow anonymous clients to reach Banana Cake Pop by default even when  .RequireAuthorization() to .MapGraphQL()
      or
2. Create a modal to allow putting in the credentials of the user if the response is a 401.

**Comment by michaelstaib** [comment]
Hey .... if you want different auth behaviour between your GraphQL IDE and your GraphQL endpoint you will need to map them on different routes. We at the moment do not plan to change the current behavior.

**Comment by shaopard** [comment]
Hi @michaelstaib,

Thanks for the answer, though could you let me know what do you mean by mapping different routes?
Is it:
1. Instead of using .MapGraphQL(), should I use .MapBananaCakePop() and .MapGraphQLHttp().RequireAuthorization(). If so, I've tried this and it still requires authorization for Banana Cake Pop.
2. Should I use .MapGraphQL().RequireAuthorization() -which uses the default "/graphql" path - and a second .MapGraphQL("/X")/.MapBananaCakePop() without .RequireAuthorization()? If so, I've tried this too and it works - you can reach Banana Cake Pop on the "/X" path and you can test the graphQL queries like this, but this feels counterintuitive for when clients are using the API - or at least that's how I'd feel as a client- to write code to reach some endpoint and test (in the browser) on another.

If I am missing something, let me know.

Again, thanks for the answer.
