### ISSUE TITLE
Allow anonymous schema introspection from federation gateway

### ISSUE THREAD

**Issue by hrshv6** [ChilliCream/graphql-platform#6992]
### Product

Hot Chocolate

### Is your feature request related to a problem?

We have several graphql domain services we are federating through a gateway, via federation with schema polling → [Federation with Polling](https://chillicream.com/docs/hotchocolate/v13/distributed-schema/schema-federations#federation-with-schema-polling)

- Each of our domain services has a fallback authentication policy that enforces authentication on all end points in the service. This is in place so that a developer does not have to remember adding authentication to every end point.

Below screenshot shows a snip of how we add this fallback policy to our domain service:
![2024-03-14_133710](https://github.com/ChilliCream/graphql-platform/assets/5875821/ca084e1d-5658-4884-bb61-8c21e9a59ba2)

- Our problem is that → this fallback authentication policy also enforces authentication on the “`/graphql`”endpoint produced by Hot Chocolate. This is fine, except for the purposes of schema introspection from the gateway. When the gateway starts up and polls for schemas, schema introspection fails with a 401-UnAuthorized response because the domain service is expecting authentication from caller (gateway)

Is there a setting in Hot Chocolate’s authorization middleware that will allow for anonymous introspection of schemas while requiring authentication on other types of queries?

We do have a temporary solution to get around this problem:

1. When calling `MapGraphQL()`, we open up the “`/graphql`” endpoint to be completely anonymous by calling `AllowAnonymous()`
2. Then we decorate our queries and mutations with the `[Authorize]` attribute which adds authentication to the “`/graphql`” endpoint.

![2024-03-14_113320](https://github.com/ChilliCream/graphql-platform/assets/5875821/05c879f1-5da1-4efd-9c36-d7c7d3f8fbbb)

We have already tried the following things in our domain services, to make schema introspection anonymous. But none of these have worked:

![2024-03-14_113532](https://github.com/ChilliCream/graphql-platform/assets/5875821/8cf5df08-f889-4fb0-87f6-c844d9622136)

### The solution you'd like

In [this comment](https://github.com/ChilliCream/graphql-platform/issues/5435#issuecomment-1296211686) and this [one](https://github.com/ChilliCream/graphql-platform/issues/5056#issuecomment-1421054029) in similar issues reported previously, you mentioned that it was now possible in Hot Chocolate.

Can you please provide instructions on how to allow schema introspection without being authenticated, or running into 401-Unauthorized responses? Thanks!

**Comment by michaelstaib** [comment]
There are I think some misconceptions ... The `AllowAnonymous` on `MapGraphQL` is transport authentication ... which has nothing to do with the GraphQL authorization. In most cases I would say this creates most problems.

You can secure your GraphQL types and remove and authentication from the `MapGraphQL` method.

**Comment by michaelstaib** [comment]
Have you considered just dumping the schema at build time ... its far more efficient.

**Comment by hrshv6** [comment]
Hi @michaelstaib No, we have not tried this --> "_Have you considered just dumping the schema at build time ... its far more efficient._"

Can you give us some clues on how we can do this, or where to start? Thanks!

**Comment by sc-cpais** [comment]
Did you end up finding any solution @hrshv6 ? I'm struggling with the same issue.

**Comment by matheusgomesway2** [comment]
I'm facing the same issue, my graphql operations are not being challenged by the authorization middleware except if i add `MapGraphQL()RequireAuthorization()`, thus my federation is not allowed to instrospect the schema.
