### ISSUE TITLE
Allow setting whether to include exception details per request

### ISSUE THREAD

**Issue by cmeeren** [ChilliCream/graphql-platform#7010]
### Product

Hot Chocolate

### Is your feature request related to a problem?

I want to include exception details for requests authenticated as my smoke test user (regardless of the environment).

### The solution you'd like

Add a member to `IQueryRequestBuilder` to set whether to include exception details, so that a rqeuest interceptor can modify it.

Currently configuring the inclusion of exception details is only possible globally using `ModifyRequestOptions(options => options.IncludeExceptionDetails = true)`. I have not found a way to configure this per request.

**Comment by michaelstaib** [comment]
We will not do this one ... this potentially can have a lot of security implications.

**Comment by cmeeren** [comment]
Wait, what? I am of the exact opposite opinion; this could _increase_ security.

If you don't want to prioritize it for other purposes, I get it, and I won't bother you. But if you really want to drop it for security purposes, I humbly request you to elaborate and reconsider.

If you are referring to the general problem of leaking security-sensitive details through exception details, then in this case, I don't see the problem:

Firstly, as mentioned, HotChocolate already allows globally enabling/disabling exception details. I could already shoot myself in the foot by enabling it globally across all environments (which of course I won't). My suggestion is more fine-grained, e.g. enabling only when authenticated as specific users, as in my use-case. (If someone were to steal the credentials to my integration test user, then I have much bigger problems than them having access to exception details.) Security-wise, my proposal is a subset of the current global enable/disable functionality. It does not add additional risk, and in fact can improve security by allowing users to be more fine-grained (e.g. only enable it for superusers or manual/integration test users) whereas the current functionality could push devs to enable it in e.g. semi-open QA environments, which is not safe.

Secondly, the proposed feature would be in the same category as other current authorization-related request-specific functionality such as allowing/disallowing introspection using `IQueryRequestBuilder.AllowIntrospection`.

**Comment by cmeeren** [comment]
Hi, just following up on this. I kindly ask you to either re-open this issue, or provide rebuttals to my arguments.

**Comment by cmeeren** [comment]
Hi, just a friendly reminder that I would like this issue re-opened, or alternatively that my arguments are met with compelling counterarguments.
