### ISSUE TITLE
Middleware Not Invoked for `DirectiveLocation.Object` Directives

### ISSUE THREAD

**Issue by AdamDurkalec** [ChilliCream/graphql-platform#7012]
### Product

Hot Chocolate

### Version

13.9.0

### Link to minimal reproduction

https://github.com/AdamDurkalec/hc-v13-object-directive-bug/blob/main/Program.cs

### Steps to reproduce

1. Define custom 'Object' directive with middleware:
```
public class MyCustomDirectiveObjectDirective { }

public class MyCustomDirectiveObjectDirectiveType : DirectiveType<MyCustomDirectiveObjectDirective>
{
    protected override void Configure(
        IDirectiveTypeDescriptor<MyCustomDirectiveObjectDirective> descriptor)
    {
        descriptor.Name("MyCustomDirectiveObjectDirective");
        descriptor.Location(DirectiveLocation.Object);

        descriptor.Use((next, Directive) => context =>
        {
            context.Result = "Bar";
            return next.Invoke(context);
        });
    }
}
```
2. Add the directive to an `ObjectType`:
```
public class BookType : ObjectType<Book>
{
    protected override void Configure(IObjectTypeDescriptor<Book> descriptor)
    {
        descriptor.Field(b => b.Id).ID();
        descriptor.Directive(new MyCustomDirectiveObjectDirective());
    }
}
```

### What is expected?

The middleware is invoked.

### What is actually happening?

The middleware is not invoked. (in v12 the middleware is invoked)

**Comment by michaelstaib** [comment]
This is correct ... middleware is only invoked on the field but not on the object. We found that in most cases this lead to undesirable behavior. But, you can create such behavior with a descriptor attribute.

**Comment by evansjustind** [comment]
I have a follow-up question about this.  If you were to use a descriptor attribute instead of applying this as an Object level middleware, wouldn't you need to then add this annotation to every part of the ObjectType?
