### ISSUE TITLE
Method `RegisterGeneratedDataLoader()` generated by HotChocolate.Types.Analyzers is missing `this` keyword

### ISSUE THREAD

**Issue by kondelik** [ChilliCream/graphql-platform#7015]
### Product

Hot Chocolate

### Version

13.9.0

### Link to minimal reproduction

https://github.com/kondelik/hc-RegisterGeneratedDataLoader-missing-this-keyword

### Steps to reproduce

1) Add `HotChocolate.Types.Analyzers` package
```
<PackageReference Include="HotChocolate.Types.Analyzers" Version="13.9.0">
  <PrivateAssets>all</PrivateAssets>
  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
</PackageReference>
```

2) Add any `[DataLoader]` to start generating

3) Inspect generated code (`HotChocolateDataLoader.g.cs`), method `RegisterGeneratedDataLoader(IRequestExecutorBuilder builder)` is missing `this` keyword => its not ExtensionMethod.

### What is expected?

Generated code is missing "this" keyword. I am pretty sure the intent here was "this is extension method", but its not.
```
namespace Microsoft.Extensions.DependencyInjection
{
    public static partial class OverviewTypesRequestExecutorBuilderExtensions
    {
// there. Only thing I added is "this" before IRequestExecutorBuilder
        static partial void RegisterGeneratedDataLoader(this IRequestExecutorBuilder builder)
        {
            builder.AddDataLoader<...>();
        }
    }
}
```

### What is actually happening?

`static partial void RegisterGeneratedDataLoader(IRequestExecutorBuilder builder)` is generated without `this` keyword and cannot be used as Extension Method.

**Comment by michaelstaib** [comment]
This is done by design ... why would you need it ... this is not meant for external use.
