### ISSUE TITLE
Generate client in build process from another project/reference

### ISSUE THREAD

**Issue by danbopes** [ChilliCream/graphql-platform#7042]
### Product

Strawberry Shake

### Is your feature request related to a problem?

Currently, I can generate a C# client using gRPC by following this approach:

```
<ItemGroup>
  <Protobuf Include="..\Services.WeatherForecast\Services.WeatherForecast.proto" GrpcServices="Client">
    <Link>Protos\Services.WeatherForecast.proto</Link>
  </Protobuf>
</ItemGroup>
```

This generates a client that I can use in my app. Whenever I update the protobuf reference in my main app, the resulting client is automatically updated.

### The solution you'd like

I’d like to achieve something similar with GraphQL. Imagine if we could do this:

```
<ItemGroup>
  <Graphql Include="..\Services.WeatherForecast\Services.WeatherForecast.graphql" GraphqlServices="Client">
    <Link>Protos\Services.WeatherForecast.graphql</Link>
  </Protobuf>
</ItemGroup>
```

This would generate the GraphQL client, which I could then seamlessly use in my app. Given that .NET is increasingly moving toward cloud support and distributed applications (thanks to .NET Aspire), I believe this addition would be incredibly useful and beneficial.

**Comment by michaelstaib** [comment]
There are key difference here between GraphQL and gRPC ... if you generate a client for the whole schema you are not going for a cloud first API bit something where you need expressions. Strawberry Shake generates from the GraphQL operation as other popular GraphQL clients do.
