### ISSUE TITLE
HotChocolate.Caching 13.9.0 returns empty response

### ISSUE THREAD

**Issue by kiangkuang** [ChilliCream/graphql-platform#7054]
### Product

Hot Chocolate

### Version

13.9.0

### Link to minimal reproduction

https://github.com/kiangkuang/HotChocolateDemo/tree/13.9

### Steps to reproduce

1. Clone project
2. Run project and query with
    ```
    query {
        book {
            title
        }
    }
    ```

### What is expected?

Response with cache control headers and query result, like in version 13.8.1
<img width="1720" alt="image" src="https://github.com/ChilliCream/graphql-platform/assets/7030358/87c3e755-4325-4c35-b054-f780dd39aebc">

### What is actually happening?

Response with cache control headers but response is empty
<img width="1724" alt="image" src="https://github.com/ChilliCream/graphql-platform/assets/7030358/9693dfb7-746a-483b-b038-f1bdde029656">

**Comment by tobias-tengler** [comment]
I'm able to reproduce this. Looking into it.

**Comment by tobias-tengler** [comment]
This seems to have been broken since #6844. The snapshots even shows us that it's broken 😞 
https://github.com/ChilliCream/graphql-platform/pull/6844/files#diff-2803ba1ef05352c4221908b033e53e6563c564873702b5ced27ddd6b495f0f5d

**Comment by miko866** [comment]
Same probleme here.
I use:
.AddCacheControl()
.ModifyCacheControlOptions(o => o.DefaultMaxAge = 60_000)
.UseQueryCachePipeline()

HotChocolate.AspNetCore - 13.9.3
HotChocolate.Caching - 13.9.3

**Comment by tobias-tengler** [comment]
This right here still needs to be addressed: https://github.com/ChilliCream/graphql-platform/pull/7057#discussion_r1564926829
It probably needs some more considerations. Would be great if you could take a look :)

**Comment by keevee1988** [comment]
I am using HotChocolate.AspNetCore - 13.9.12, HotChocolate.Caching - 13.9.12 still facing same issue

Program.cs
 .AddGraphQLServer()
 .AllowIntrospection(false)
 .AddAuthorization()
 .AddFiltering()
 .AddProjections()
 .AddQueryType<Query>()
 .AddTypeExtension<QueryExtended>()
 .AddSorting()
 .AddCacheControl()
 .UseQueryCachePipeline()
 .InitializeOnStartup();

**Comment by kiangkuang** [comment]
@keevee1988 13.9.12 does not include the merged fix yet, you can try waiting for the next release

**Comment by keevee1988** [comment]
> @keevee1988 13.9.12 does not include the merged fix yet, you can try waiting for the next release

Thank you for the update
