### ISSUE TITLE
HotChocolate.AspNetCore package installation issue

### ISSUE THREAD

**Issue by tessierp** [ChilliCream/graphql-platform#7071]
### Product

HotChocolate.AspNetCore

### Version

13.9.0

### Link to minimal reproduction

No reproduction URL

### Steps to reproduce

1. Create ASP.NET Core Empty project
2. Try to add HotChocolate.AspNetCore

### What is expected?

Being able to install the package without any issues

### What is actually happening?

Trying to install the package returns a NU1108 error, Cycle Detected.

### Relevant log output

![image](https://github.com/ChilliCream/graphql-platform/assets/6784384/d62da9b1-bd36-4c51-bead-58521e876fdb)

### Additional context

I tried installing other packages to see if something was wrong with my Visual Studio 2022 installation and I was able to install Automapper, Autofac and a few others without any issues. I have only faced "Cycles Detected" issue with HotChocolate.

**Comment by PascalSenn** [comment]
Can you share your csproj file

**Comment by tessierp** [comment]
> Can you share your csproj file

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>

        <TargetFramework>net8.0</TargetFramework>

        <Nullable>enable</Nullable>

        <ImplicitUsings>enable</ImplicitUsings>

  </PropertyGroup>

        <ItemGroup>

               <PackageReference Include="HotChocolate.AspNetCore" Version="13.9.0" />

        </ItemGroup>

 

</Project>

**Comment by tannerabread** [comment]
@tessierp was your project named HotChocolate?

**Comment by michaelstaib** [comment]
<img width="837" alt="image" src="https://github.com/ChilliCream/graphql-platform/assets/9714350/70db111e-7b52-4b9a-9a91-9fe5e0141113">

**Comment by michaelstaib** [comment]
Closing the issue as the most likely thing here is that the project was simply named HotChocolate.
