### ISSUE TITLE
Connections are always nullable and ignore GraphQLNonNullType

### ISSUE THREAD

**Issue by cmeeren** [ChilliCream/graphql-platform#7073]
### Product

Hot Chocolate

### Version

14.0.0-p.93

### Link to minimal reproduction

See zip below

### Steps to reproduce

Repro solution: [HotChocolateBugRepro.zip](https://github.com/ChilliCream/graphql-platform/files/15129520/HotChocolateBugRepro.zip)

Code for quick reference:

```c#
var builder = WebApplication.CreateBuilder(args);

builder
    .Services
    .AddGraphQLServer()
    .AddQueryType<Query>();

var app = builder.Build();

app.MapGraphQL();
app.Run();

public class Query
{
    [GraphQLNonNullType]
    [UsePaging]
    public List<int> Test() => new List<int>();
}
```

### What is expected?

```graphql
type Query {
  test(...): TestConnection!
}
```

### What is actually happening?

```graphql
type Query {
  test(...): TestConnection
}
```

### Additional context

The order of `UsePaging` and `GraphQLNonNullType` does not matter.

Additionally, I would expect that when

**Comment by michaelstaib** [comment]
This is not a bug but by design ... we will have a look another look at connections for the December release.
