### ISSUE TITLE
Allow [Error] also for queries

### ISSUE THREAD

**Issue by cmeeren** [ChilliCream/graphql-platform#7077]
### Product

Hot Chocolate

### Is your feature request related to a problem?

I know how to use `[Error(...)]` for mutations. It's great! However, I find myself needing this for queries, too.

For example, for a query with a phone number parameter, such an error could be returned for an invalid phone number. Or if a user is not allowed to access a field deep in a graph, a suitable authorization error could be returned from this field.

### The solution you'd like

Support `[Error]` for queries, too.

**Comment by tobias-tengler** [comment]
That's already part of v14: https://youtu.be/yoW2Mt6C0Cg?si=ccXgU2oUX5G-64pv
