### ISSUE TITLE
Allow query conventions for non-object return types

### ISSUE THREAD

**Issue by cmeeren** [ChilliCream/graphql-platform#7085]
### Product

Hot Chocolate

### Is your feature request related to a problem?

I need to use query conventions (e.g., `[Error]`) with fields that return non-object types such as `List` or primitives such as `String`.

### The solution you'd like

I realize that unions do not support lists or primitives as one of their cases. When a field using query conventions returns a non-object type, I would like HotChocolate to automatically wrap the OK result for me, similar (though not identical) to mutation conventions.

For example, the list/primitive could be wrapped in a type called `...ResultValue` which has a single member `Value` that is the returned list/primitive. The `...ResultValue` type will then be the success case of the of the `...Result` union.

**Comment by DatStorm** [comment]
There is a related issue for mutation but would be really nice if it worked for both: #6795

**Comment by michaelstaib** [comment]
We wont support that as unions do not work with scalars. I also do not want to introduce some wrapping here as this would result in a bad schema design. I am closing.

> There is a related issue for mutation but would be really nice if it worked for both: https://github.com/ChilliCream/graphql-platform/issues/6795

For mutations this should work fine. I will have a look at the other issue.

**Comment by cmeeren** [comment]
@michaelstaib Would you mind elaborating on the bad schema design you mention? I'm currently wrapping my types manually. I have fields that return a list of objects, and this field has error conditions I want to return as part of the schema, too.

**Comment by cmeeren** [comment]
Hi, just a friendly reminder that I am interested in the rationale behind this decision, in particular why it's bad schema design.

Again, there are actual domain errors that can occur when attempting to get the field. The error conditions are relevant irrespective of whether a field is an object, a list, or a scalar.

I think it would be best to let users choose. After all, currently `[Error]` does not work at all for non-object fields. If it is allowed (creating a type that wraps the non-object value), then at least users have the option without having to resort to manual boilerplate.

**Comment by cmeeren** [comment]
For the record, @michaelstaib elaborated a bit in this slack thread: https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1724931876935049
