### ISSUE TITLE
Ignoring operation in the FilterInputType does not work

### ISSUE THREAD

**Issue by marekbomber** [ChilliCream/graphql-platform#7096]
### Product

Hot Chocolate

### Version

13.9.1

### Link to minimal reproduction

tbd

### Steps to reproduce

```c#
public class MyTypeFilterType : FilterInputType<MyType>
{
    protected override void Configure(IFilterInputTypeDescriptor<MyType> descriptor)
    {
        descriptor.Ignore(DefaultFilterOperations.Equals); // not working
        descriptor.Operation(DefaultFilterOperations.Equals).Type<StringType>().Ignore(); // not working
        descriptor.Operation(DefaultFilterOperations.Equals).Type<StringOperationFilterInputType>().Ignore(); // not working
    }
}
```

### What is expected?

I would like to be able to ignore operations in the filter definition.

### What is actually happening?

Operations are not ignored.

**Comment by michaelstaib** [comment]
Did you register the filter type?

**Comment by michaelstaib** [comment]
Ah, I see ... what are you trying to do?

**Comment by marekbomber** [comment]
> Ah, I see ... what are you trying to do?

I would like it to be impossible to use Operation Equals for all string properties in my object.

**Comment by glen-84** [comment]
Please add a link to a minimal reproduction of this issue.

**Comment by michaelstaib** [comment]
Closing this issue as there is no repro
