### ISSUE TITLE
Bug: HC 14.0.0-p.98 prevents Relay IDs from working when a custom ID class or record is used

### ISSUE THREAD

**Issue by Jlopez2045** [ChilliCream/graphql-platform#7098]
### Product

Hot Chocolate

### Version

14.0.0-p.98

### Link to minimal reproduction

https://github.com/Jlopez2045/RelayCustomIdIssue

### Steps to reproduce

Run following query:
```gql
query {
    products {
        id
        name
    }
}
```

### What is expected?

```json
{
    "data": {
        "products": [
            {
               "id": "UHJvZHVjdDox"
                "name": "Book"
            }
        ]
    }
}
```

### What is actually happening?

```json
{
    "errors": [
        {
            "message": "Cannot return null for non-nullable field.",
            "locations": [
                {
                    "line": 2,
                    "column": 5
                }
            ],
            "path": [
                "products"
            ],
            "extensions": {
                "code": "HC0018"
            }
        },
        {
            "message": "No serializer registered for type `Product`.",
            "extensions": {
                "typeName": "Product"
            }
        }
    ],
    "data": null
}
```

### Additional context

Upgraded from `14.0.0-p.82`

**Comment by michaelstaib** [comment]
Actually we now support a much better way to support these things ... you can now implement your own optimized value serializers for these. However, in the next couple of builds the source generator will also offer automatic generation of these.

**Comment by michaelstaib** [comment]
This shows the composite ID serializer ....
https://github.com/ChilliCream/graphql-platform/blob/f7dfae1b23a337d90f502c17c4eeca8043be7150/src/HotChocolate/Core/test/Types.Tests/Types/Relay/DefaultNodeIdSerializerTests.cs#L270

these must be registered with AddNodeIdValueSerializer .... 

However ... with the next couple of builds there will be auto generation and auto registration.

**Comment by livwvil** [comment]
`.AddLegacyNodeIdSerializer()` helped me

**Comment by mmccord-processunity** [comment]
This appears to still be present in the latest of the 14.x line, even with `AddLegacyNodeIdSerializer` or with adding a custom `INodeIdValueSerializer`.

**Comment by tobias-tengler** [comment]
I'm 100% confident that it works, because I migrated our custom Ids at work to the new serializers.
Can you share how you configure, register and use one of your custom Ids?

**Comment by tomachristian** [comment]
I am doing this:

![Image](https://github.com/user-attachments/assets/e810b35e-0396-424b-ab36-8016b4db113f)

And still not able to use `WorkflowId` as a global object identifier...

**Comment by tobias-tengler** [comment]
You need to implement an `INodeIdValueSerializer` or you can use `CompositeNodeIdValueSerializer` if you just want to chain some Id "parts" using `:`.

```csharp
internal sealed class ProductIdentifierNodeIdValueSerializer : CompositeNodeIdValueSerializer<ProductIdentifier> {
    protected override NodeIdFormatterResult Format(Span<byte> buffer, ProductIdentifier value, out int written) {
        if (TryFormatIdPart(buffer, value.Part1, out var writtenPart1Length) 
            && TryFormatIdPart(buffer.Slice(writtenPart1Length), value.Part2, out var writtenPart2Length)) {
             written = writtenPart1Length + writtenPart2Length;
             return NodeIdFormatterResult.Success;
        }

        written = 0;
        return NodeIdFormatterResult.BufferTooSmall;
    }

    protected override bool TryParse(ReadOnlySpan<byte> buffer, out ProductIdentifier value) {
        if (/* your parsing logic */) {
          // successfully parsed
          value = parsedValue;
          return true;
       }

      // failed to parse
      return false;
    }
}
```

Then you need to register the serializer.

```csharp
private static IRequestExecutorBuilder AddStronglyTypedIds(
    this IRequestExecutorBuilder builder) {
    builder
        .AddNodeIdValueSerializer<ProductIdentifierNodeIdValueSerializer>()
        .BindRuntimeType<ProductIdentifier, IdType>();
}
```

Hope this helps :)
