### ISSUE TITLE
Is .NET8 Native AOT supported?

### ISSUE THREAD

**Issue by Arktische** [ChilliCream/graphql-platform#7123]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Thanks for your awesome work! I want to use Hotchocolate in serverless production environment but my cloud service provider don't support .NET8 JIT runtime. 

I have searched all issues and docs to find out but seem to get nothing helpful. So Is natvie AOT actually supported now? If not, I would like to request this feature.

Thanks again

### The solution you'd like

Support .NET8. native AOT

**Comment by michaelstaib** [comment]
We are working on AOT but this is a big task which will take two years to fully be implemented. 

At the moment we are focusing on Hot Chocolate Fusion to be AOT compliant by the ned of this year. After fusion we will focus on HotChocolate single server without support of HotChocolate.Data. 

At the moment we have the parser and some core libraries optimized for AOT.

In December 2024, the Gateway and the Transport layer should be AOT ready.

**Comment by michaelstaib** [comment]
If you are interested you can join on this task and help.

**Comment by michaelstaib** [comment]
Closing this issue as we are working on this epic in a multi version effort.
