### ISSUE TITLE
Return 4XX instead of 5XX for client errors

### ISSUE THREAD

**Issue by cmeeren** [ChilliCream/graphql-platform#7128]
### Product

Hot Chocolate

### Version

14.0.0-p.101

### Steps to reproduce

If the client requests more than the maximum number of items during pagination (HC0051), the request responds with status code 500. This is incorrect; it is a client error, so it should return 400.

This issue hits us by triggering the HTTP retry policy for requests that are pointless to retry. (The policy retries 5XX requests, among other things.)

Hopefully this is trivial to repro, or even just find the relevant code. Let me know if you need a repro.

**Comment by michaelstaib** [comment]
This should be solved. Graphql runtime errors are now 200 like the spec defines.

**Comment by cmeeren** [comment]
Great, thanks!
