### ISSUE TITLE
Typo in error code - HC00038 should be HC0038?

### ISSUE THREAD

**Issue by cmeeren** [ChilliCream/graphql-platform#7145]
### Product

Hot Chocolate

### Version

main

### Link to minimal reproduction

See below

### Steps to reproduce

Just came across this:

https://github.com/ChilliCream/graphql-platform/blob/cdbc3e1148d104c3cf78726619423822e5160545/src/HotChocolate/Core/src/Abstractions/ErrorCodes.cs#L138

Based on the surrounding codes, I am guessing there's a `0` too many there.

### What is expected?

See above

### What is actually happening?

See above

**Comment by glen-84** [comment]
Thanks @cmeeren – I've opened a PR.
