### ISSUE TITLE
Unable to use @include or @skip when stitching

### ISSUE THREAD

**Issue by gondera** [ChilliCream/graphql-platform#7149]
### Product

Hot Chocolate

### Version

13.5.1

### Link to minimal reproduction

https://github.com/ChilliCream/graphql-platform/issues/937

### Steps to reproduce

1. Create a stitched schema
2. Attempt to use an @include directive with a boolean field in playground. For example:
```
query TEST($ok:Boolean!) {
  hey {
    hello @include(if:$ok)
  }
}
```

3. The field is executed when `$ok` is `false`

### What is expected?

Same behavior as if the literal `true `or `false `were passed to the `@include` directive. 
Just like if we query the original schema, the field is not queried if `false`.

### What is actually happening?

After some debuging I noticed that the $ok variable didn't reach the original schema and that the query was simplified and doesn't contain the @include directive.

This looks like a issue parsing the query. 

Same situation happened in previous versions like described in issue #937

**Comment by michaelstaib** [comment]
Stitching is deprecated in favor of HotChocolate.Fusion. We are no longer offering any fixes or updates for stitching. With version 14 we have removed the code and packages for stitching.

HotChocolate.Fusion on the other hand supports skip/include and also subscriptions out of the box.
