### ISSUE TITLE
BananaCakePop: Unable to Hide app on MacOS

### ISSUE THREAD

**Issue by icanhasjonas** [ChilliCream/graphql-platform#7156]
### Product

Banana Cake Pop

### Version

16.0.3

### Link to minimal reproduction

N/A

### Steps to reproduce

Hey there

Easy as cake - the BCP app on MacOS is unable to hide. The Hide Action is removed from the menu. Not a show stopper, but it does make the only way to remove the app from the screen, while not quitting the app, is to minimize down to another slot on the app bar (MACOS specific)

### What is expected?

I'd love to be able to have my Hide action back :-)

### What is actually happening?

Nothing, the hide action is disabled or removed.

**Comment by michaelstaib** [comment]
How do you mean ... I just checked and Hide works as expected.

<img width="986" alt="image" src="https://github.com/ChilliCream/graphql-platform/assets/9714350/aec028a3-9e00-4de9-9283-76cd1ef4d324">

**Comment by michaelstaib** [comment]
Closed it as I could not repro this and did not get any feedback
