### ISSUE TITLE
Postgres Subscriptions broken with `System.InvalidOperationException: Missing type info or binding info.`

### ISSUE THREAD

**Issue by williamdenton** [ChilliCream/graphql-platform#7158]
### Product

Hot Chocolate

### Version

13.9.5

### Link to minimal reproduction

sorry - no

### Steps to reproduce

I am unable to reproduce locally, but it reliably happens on every second message processed by the postgres writer when run in my aws environment. Maybe it's a RELEASE mode optimization in Npgsql? Regardless, i dont believe fault lies with this repo as it only occurs when npgsql is updated from v7 to v8 and this code appears to be using the api correctly.

### What is expected?

All messages queued for delivery to postgres should be delivered to the db via pg_notify, regardless of transient errors communicating with the DB

### What is actually happening?

The exception is causing the connection to disconnect (or be broken), which in turn triggers the cancellation token that the writer is using (L129 below). When the writer attempts to re-queue the messages to the channel for retry the channel silently rejects the call as the cancellation token is triggered. This means we lose the message. This message loss is reliably happening on every second invocation of the handler

https://github.com/ChilliCream/graphql-platform/blob/7d21adab765fffad291f22255db1102fed39234e/src/HotChocolate/Core/src/Subscriptions.Postgres/PostgresChannelWriter.cs#L96-L131

### Relevant log output

```shell
Subscription ProviderInfo "The channel writer failed to send messages. Requeueing 1 messages. Error Message: System.InvalidOperationException: Missing type info or binding info.
   at Npgsql.ThrowHelper.ThrowInvalidOperationException(String message)
   at Npgsql.NpgsqlParameter.Write(Boolean async, PgWriter writer, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.WriteBind(List`1 parameters, String portal, Byte[] asciiName, Boolean allResultTypesAreUnknown, Boolean[] unknownResultTypeList, Boolean async, CancellationToken cancellationToken)
```

### Additional context

I have been investigating this for the last week or so and have been detailing my discoveries in a [slack thread](https://hotchocolategraphql.slack.com/archives/CD9TNKT8T/p1716848107783739).

I have tried several ways to identify the problem. there are two issues here
1. When the connection is poisoned, the cancellation token is triggered and messages are not requeued for retry
2. the Npgsql batch suffers errors when using prepared statements

The first issue is easily solved by ignoring the cancellation token.

The second problem I have raised an issue over on the [npgsql repo](https://github.com/npgsql/npgsql/issues/5748), unfortunately as i don't have an isolated reproduction for this i'm not sure if its an easy fix. Its still early days and they may figure it out. As I am not confident that the npgsql issue will be resolved quickly i have refactored how pg_notify is called. By converting the code from a batch statement to using unnest, the problem is solved and also performance is increased.

Please see the related PR for my proposed fix to this issue

**Comment by michaelstaib** [comment]
Is this fixed with the merge of the pr?

**Comment by williamdenton** [comment]
Yes, subscriptions is running nicely again for us @michaelstaib
