### ISSUE TITLE
Support void/Task-returning mutations if using mutation conventions and AddQueryFieldToMutationPayloads

### ISSUE THREAD

**Issue by cmeeren** [ChilliCream/graphql-platform#7159]
### Product

Hot Chocolate

### Is your feature request related to a problem?

In the following, assume mutation conventions and `AddQueryFieldToMutationPayloads` are enabled, i.e., all mutation payloads have at least a `query` field.

Consider this mutation:

```c#
public class Mutation
{
    public void Foo()
    {
    }
}
```

This mutation is not picked up by HotChocolate, presumably because it returns `void`. It's the same if it returns a non-generic `Task`:

```c#
public class Mutation
{
    public Task Foo() => Task.FromResult(1);
}
```

However, I can create an empty `FooPayload` class and return that:

```c#
public class FooPayload;

public class Mutation
{
    public FooPayload Foo() => new();
}
```

This now works, and the `query` field is automatically added to the otherwise empty `FooPayload`.

### The solution you'd like

My desire is that if I use query conventions and `AddQueryFieldToMutationPayloads`, then my mutations can return `void` or a non-generic `Task`, and the effect is the same as if I had defined and returned an empty payload class for that mutation, as demonstrated above.

**Comment by michaelstaib** [comment]
I think that is not a good pattern :) A mutation should return the affected object. If there is no effected object on your graph return success. We will not add support for void as it would lead to bad practices.

I will discuss it in the team however and report back.

**Comment by cmeeren** [comment]
Thanks for your insights! I agree that the affected object should be returned as a general rule. However, say for example that you delete an object, or otherwise that there is no affected object (that still exists, at least). What should be returned then? What do you mean "return success"? Do you mean returning `success: true`? If so, I'd argue that is pointless and just duplicates information (the presence/absence of errors).

**Comment by cmeeren** [comment]
There could also be other operations where normal APIs would return `204 No Content` or `202 Accepted` (instead of, say, `200 OK` or `201 Created`).

**Comment by michaelstaib** [comment]
Closing this issue as we do not plan to implement this

**Comment by cmeeren** [comment]
Thanks for considering it! I accept your decision, though I would be very grateful for a short explanation of why, in light of my questions above.
