### ISSUE TITLE
Support for Zanzibar in Authorization

### ISSUE THREAD

**Issue by RichardWhitfield** [ChilliCream/graphql-platform#7179]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Currently there are 2 options for how to implement authZ in HC, Microsoft's Policy Based AuthZ and OPA.  
Microsoft's PBA requires a commitment to the Microsoft ecosystem which for many organizations is not ideal and the project is not open source which again is not ideal.
OPA is complex to configure (particularly for those new to FGA) and may have issues around scalability.  Many authZ implementations work on the notion of a hierarchy of access which, while this can be supported in OPA is complex to do.  OPA also does not easily support reverse lookups, such as 'who has access to this resource' which is useful in many circumstances.

### The solution you'd like

Technologies built on the back of [Googles 2019 Zanzibar paper](https://storage.googleapis.com/gweb-research2023-media/pubtools/5068.pdf) are starting to gain popularity (paricularly in the golang world).
There are a couple of open-source implementations of Zanzibar:
- Okta have developed an open-source implementation of Zanzibar called [OpenFGA](https://docs.fga.dev/fga) (also see [here](https://zanzibar.academy/) for more info) which can be locally hosted or used in a serverless model.
- [Topaz](https://www.topaz.sh/) supports a Zanzibar based model using OPA Regos?  I have yet to look into this one in detail but this is also open-source.
Zanzibar based FGA seems well suited to securing GraphQL data and is designed for highly scalable ReBAC based authZ.
An additional authZ implementation supporting OpenFGA or similar would be a great benefit for users wanting to use Zanzibar based concepts for securing data using Hot Chocolate.

**Comment by michaelstaib** [comment]
The ASP.NET Core Authorization Policy libs are under MIT so I do not get what you mean there :)
https://github.com/dotnet/aspnetcore/tree/main/src/Security/Authorization/Core/src

If you would like to have this you are welcome to implement this ... the abstraction for the Authorization system are here:
https://github.com/ChilliCream/graphql-platform/tree/main/src/HotChocolate/Core/src/Authorization

**Comment by RichardWhitfield** [comment]
Thanks @michaelstaib we are going to implement using the main data source for authorization initially (using the built in HC authorization and Microsoft policy based auth) and will do some performance testing there.  If we need to implement a Zanzibar based system I will look to contribute this back to add to the MS and OPA implementations though this will need some thought to make generic since Zanzibar also has a data plane unlike OPA.
