### ISSUE TITLE
DbContext access modifiers

### ISSUE THREAD

**Issue by naymore** [ChilliCream/graphql-platform#7199]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Can we please have `internal` access identifiers? Currently I need to make DbContext instances all `public` in order for HotChocolate to work.

### The solution you'd like

Ability to use `internal` DbContexts.

**Comment by michaelstaib** [comment]
Can you provide a code example? I do not really get what you mean here. You can use internal resolvers if that is what you are asking for.

**Comment by glen-84** [comment]
Closing, as no response has been received from the author.
