### ISSUE TITLE
HotChocolate.AspNetCore has MIT license but it has a dependency on BananaCakePop.Middleware which is ChilliCream License 1.0

### ISSUE THREAD

**Issue by jackj-msft** [ChilliCream/graphql-platform#7204]
### Product

Hot Chocolate

### Version

13.9.6

### Link to minimal reproduction

https://www.nuget.org/packages/HotChocolate.AspNetCore/

### Steps to reproduce

See that BananaCakePop.Middleware is a dependency and click on the dependency
Take a look at the license for the dependency.
https://www.nuget.org/packages/BananaCakePop.Middleware/16.0.3/License

### What is expected?

We expect either a way to consume HotChocolate.AspNetCore without BananaCakePop.Middleware
OR
for BananaCakePop.Middleware to have the MIT license

### What is actually happening?

BananaCakePop.Middleware has the ChilliCream License 1.0

**Comment by michaelstaib** [comment]
You can switch it of if you do not want to use it. `MapGraphQL().WithOptions(.... Tool { Enable: false } )`
