### ISSUE TITLE
FilterType<T> has incorrect field definitions

### ISSUE THREAD

**Issue by wietlol** [ChilliCream/graphql-platform#7224]
### Product

Hot Chocolate

### Version

13.9.6

### Link to minimal reproduction

https://github.com/wietlol-org/HotChocolateIssues/tree/main/HotChocolateIssues.InvalidFilterType

### Steps to reproduce

Run the unit tests in the HotChocolateIssues.FilterInputType project.
The test DeleteBooks will fail.
After running the tests, the output is written to the TestFiles folder where the erroneous response is presented.

### What is expected?

When creating a query/mutation with input according to the following snippet.
```csharp
[GraphQLType(typeof(FilterInputType<Book>))]
IDictionary<string, object?> filter
```

The dictionary should only contain the filter as it was specified by the query/mutation input.

### What is actually happening?

Instead of only setting the properties that were provided by the input, the current implementation will incorrectly fill almost all fields with the same data.

Given the following input:
```graphql
mutation {
    deleteBooks(
        filter: {
            title: {eq: "Test"}
        }
    )
}
```
The dictionary should only contain an entry for "title", which should be a dictionary only containing an entry for "eq".

Looking at `HotChocolate.Types.InputParser.cs` line 255, the data seems correct:
![image](https://github.com/ChilliCream/graphql-platform/assets/2802887/9ec4918b-a09a-46f9-8979-d71fe44a83e3)

But the resulting value is definitely not:
![image](https://github.com/ChilliCream/graphql-platform/assets/2802887/fec60a4b-4d34-4222-b1e1-b2edfe8ae2d8)

The reason for this is that the field definitions of the filter type do not have correct index values:
(`HotChocolate.Types.InputObjectType.Initialization.cs` line 126)
![image](https://github.com/ChilliCream/graphql-platform/assets/2802887/0b1c5e09-7b6b-40ae-81bd-10c15ab008cc)

While their values are being loaded by index:
![image](https://github.com/ChilliCream/graphql-platform/assets/2802887/b7223235-2102-4729-998e-d2266a50a844)

This means that the resulting dictionary, instead of the following data:
```json
{
	"title": {
		"eq": "Test"
	}
}
```
will contain the following data:
```json
{
	"and": {
		"and": "Test",
		"or": null,
		"eq": "Test",
		"neq": "Test",
		"contains": "Test",
		"ncontains": "Test",
		"in": "Test",
		"nin": "Test",
		"startsWith": "Test",
		"nstartsWith": "Test",
		"endsWith": "Test",
		"nendsWith": "Test"
	},
	"or": null,
	"title": {
		"and": "Test",
		"or": null,
		"eq": "Test",
		"neq": "Test",
		"contains": "Test",
		"ncontains": "Test",
		"in": "Test",
		"nin": "Test",
		"startsWith": "Test",
		"nstartsWith": "Test",
		"endsWith": "Test",
		"nendsWith": "Test"
	},
	"author": {
		"and": "Test",
		"or": null,
		"eq": "Test",
		"neq": "Test",
		"contains": "Test",
		"ncontains": "Test",
		"in": "Test",
		"nin": "Test",
		"startsWith": "Test",
		"nstartsWith": "Test",
		"endsWith": "Test",
		"nendsWith": "Test"
	}
}

```

### Additional context

The use of `[UseFiltering]` is not a valid alternative as these filter fields need to be used in mutations in different places in the input structure.

A good alternative is if a different type than an `IDictionary<string, object?>` can be used that is deserialized properly that can be used to filter data (IEnumerables/Lists, IQueryable, etc)
But to the best of my knowledge, there isn't.

**Comment by michaelstaib** [comment]
https://github.com/ChilliCream/graphql-platform/pull/7212

**Comment by wietlol** [comment]
With the mentioned fix, the structure of the data is fixed, but unfortunately, there is still an issue with the data.
After upgrading to 14.0.0-p.122, the resulting data is now:
```
{
	"and": null,
	"or": null,
	"title": {
		"and": null,
		"or": null,
		"eq": "Test",
		"neq": null,
		"contains": null,
		"ncontains": null,
		"in": null,
		"nin": null,
		"startsWith": null,
		"nstartsWith": null,
		"endsWith": null,
		"nendsWith": null
	},
	"author": null
}
```
Where the structure is correct, but all fields are added to the dictionary with their default value.
The default value (`null`) however does not have the same meaning as when the entry is missing in the database.
For example, when we would filter for a value where the title is null, we would do something like this:
```
{
	"title": {
		"eq": null
	}
}
```
But if all the fields would be added to the dictionary, it would create a filter that checks if the value is both equal to null and not equal to null and contains null and not contains null and starts with null, etc.

Looking at the `HotChocolate.Types.InputParser.cs` line 307, it only gives an array of the field values, which are always filled with default values too.
Therefor, overriding the type with an OnComplete/_createInstance implementation will not suffice because the input is insufficient to figure out what data to create.

The `CreateInstance` method would require more information, for example the `processed` array, which tells which fields (by index) were processed, or just `resultValue` which contains the input value.

Can we get a prerelease version where the InputParser can be overridden (not sealed) and injected somehow into the services or where the InputParser forwards the `IValueNode resultValue`  to the CreateInstance method allowing the types to use it?
Then I can figure out how the createInstance for the dictionary should work.

**Comment by michaelstaib** [comment]
Have you considered using `IFilterContext` instead of the value ... `IFilterContext` gives you the map exactly like you asked for.

**Comment by wietlol** [comment]
What we need is a patching operation. Something that would allow us to update parts of an object without providing full information of the object (as you would need in a replace operation).
Given that HotChocolate is missing this functionality, we rolled our own.

Given the following models and mutation:
```csharp
public record User(
    string Id
);

public record UserGroup(
    string Id,
    List<User> Users
);

public class Mutations
{
    public async Task<UserGroup> PatchGroupAsync(
        [Service] IUserRepository repository,
        string id,
        UserGroupPatch patch
    )
    {
        return await repository.PatchGroupByIdAsync(id, patch);
    }
}
```

We are able to create a mutation like the following:
```graphql
mutation RemoveUserFromGroup(
    $groupId: String!
    $userId: UserGroupPatchInput!
) {
    patchGroup(
        id: $groupId
        patch: {
            users: {
                removeByFilter: {
                    id: { eq: $userId }
                }
            }
        }
    ) {
        id
        users {
            id
        }
    }
}
```

This would remove a specific user from the group without having to know the other users that are in the group in the input of the mutation.

The `removeByFilter` property is a property of type `[GraphQlType(typeof(AnyType))] Dictionary<string, object?>?` at the  moment, but follows the exact same structure as a hot chocolate filter (as it was designed/based on them).

Given that it is an AnyType, the schema won't provide information of how it should be structured, which is annoying.
We wanted to use the InputFilterType to give it that information, but then it failed to deserialize properly.

If I can get the same information from the `IFilterContext`, that would be great, but keep in mind that the filters should be in specific places in the input structure, because based on where it is used, it has a different meaning, for example under `patch.users.removeByFilter` or `patch.users.patchByFilter.filter` or whatever path they would have in whatever structure our models are.
They cannot be on the root, like how queries with `[UseFiltering]` would be.
And keep in mind that there can be multiple filters in one request, for example if there is both a `removeByFilter` and a 
`patchByFilter` operation in one mutation request, they would have their own separate filters on the same type.

If `IFilterContext` suffices to provide that information, can you elaborate how it should be configured?

**Comment by glen-84** [comment]
The filtering infrastructure is not intended to be used for other purposes such as patching, and we won't be making further changes in this regard.
