### ISSUE TITLE
Type order in introspection response is not deterministic

### ISSUE THREAD

**Issue by tobias-tengler** [ChilliCream/graphql-platform#7254]
### Product

Hot Chocolate

### Version

14.0.0-p.119

### Link to minimal reproduction

I haven't yet been able to craft a reproduction

### Steps to reproduce

I'm not yet entirely sure. I believe it happens when the gateway reloads its configuration.

### What is expected?

The ordering of types in the introspection query stays consistent and matches the schema document that is part of the Fusion configuration package.

### What is actually happening?

One of our types is mixed in between the "internal" schema types and all the other types have random positions in the introspection response that don't correlate to what is defined in the Fusion schema.

![CleanShot 2024-07-10 at 13 29 03@2x](https://github.com/ChilliCream/graphql-platform/assets/45513122/7d90d9f6-b560-4c77-9e5d-a8d6e6830376)

If I download the currently active gateway package, the types have the correct order, both in the `fusion.graphql` and `schema.graphql`.

### Additional context

We use introspection in the Frontend to generate the schema used by Relay and we often have huge diffs, because the ordering of types and fields has changed.

**Comment by tobias-tengler** [comment]
Interestingly, if I use the `?sdl` endpoint the schema types are now ordered alphabetically, which isn't the original order defined by the document, but at least it seems deterministic 😅

**Comment by michaelstaib** [comment]
```
private readonly FrozenDictionary<string, INamedType> _types;
```

**Comment by tobias-tengler** [comment]
Ordering is not prescribed by the spec, so this is not a violation of the spec.
If you need ordering, use the `/graphql?sdl` endpoint or [map a custom endpoint for the schema](https://chillicream.com/docs/hotchocolate/v13/server/endpoints/#mapgraphqlschema).
