### ISSUE TITLE
StrawberryShake download discards deprecated input field

### ISSUE THREAD

**Issue by nightroman** [ChilliCream/graphql-platform#7269]
### Product

Strawberry Shake

### Version

13.9.7

### Link to minimal reproduction

https://github.com/user-attachments/files/16236420/ss-download-discards-deprecated-input-field.zip

### Steps to reproduce

The schema downloaded by `strawberryshake.tools` discards the input field with the deprecated directive.
Please use the attached project and described steps.

[ss-download-discards-deprecated-input-field.zip](https://github.com/user-attachments/files/16236420/ss-download-discards-deprecated-input-field.zip)

Start the service:

```
dotnet run
```

Download the schema:

```
dotnet graphql download http://localhost:5000/graphql
```

### Actual result

`CreateAuthorInput` has `name` and does not have the expected `deprecatedInputField`.

```graphql
input CreateAuthorInput {
  name: String!
}
```

### Expected result

`CreateAuthorInput` has both `name` and `deprecatedInputField`.

```graphql
input CreateAuthorInput {
  name: String!
  deprecatedInputField: String @deprecated(reason: "Deprecated input field.")
}
```

**Comment by HaMster21** [comment]
I think this also applies to deprecated fields in general. I have a query type with a field that returns an object with a deprecated field (among others). Strawberry shake is ignoring the deprecated field on import

**Comment by nightroman** [comment]
> I think this also applies to deprecated fields in general. I have a query type with a field that returns an object with a deprecated field (among others). Strawberry shake is ignoring the deprecated field on import

This is not what we observe. I think deprecated object type fields do not have this issue. One example:
https://github.com/ChilliCream/graphql-platform/issues/6785#issuecomment-2228571979
