### ISSUE TITLE
Add cancellationToken to Subscribe in "Code First"

### ISSUE THREAD

**Issue by AmbroiseCouissin** [ChilliCream/graphql-platform#7289]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Heya!

It seems there is no extension to have a cancellationToken with `.Subscribe' on "code first". Like we do for `.Resolve` for example.

It could look something like that:
```
        descriptor
            .Field("somethingCreated")
            .Subscribe(async (context, ct) =>
            { ...
```

Am i missing something?
Should this be added as well? It would be useful especially to send that cancellationToken to pass it to ISourceStream down the line.

Thanks! 

### The solution you'd like

```
        descriptor
            .Field("somethingCreated")
            .Subscribe(async (context, ct) =>
            { ...
```

**Comment by michaelstaib** [comment]
`context.RequestAborted`
