### ISSUE TITLE
C# Generated code not found in specified directory

### ISSUE THREAD

**Issue by VenkateshSrini** [ChilliCream/graphql-platform#7348]
### Product

Strawberry Shake

### Version

12.0.0

### Link to minimal reproduction

https://github.com/VenkateshSrini/GraphQL

### Steps to reproduce

1. Download the files from Git Repo https://github.com/VenkateshSrini/GraphQL
2. Install the Strawberry Shake tool using the command `dotnet tool install StrawberryShake.Tools --global`
3. Traverse to the directory that has this file
4. Run dotnet graphql generate.
   The below output can be seen 
>     Generate C# Clients started.
>    Generate GenTest started.
>    Generate GenTest completed in 21 ms
>     Generate C# Clients completed in 187 ms

### What is expected?

I expect the generated C# files to be in current directory

### What is actually happening?

No C# file is generated. I could not see them in current directory

### Relevant log output

```shell
Generate C# Clients started.
Generate GenTest started.
Generate GenTest completed in 21 ms
Generate C# Clients completed in 187 ms
```

**Comment by michaelstaib** [comment]
The generated files are transient ... thats by design

**Comment by VenkateshSrini** [comment]
> The generated files are transient ... thats by design

I'm still not getting it. I need those codes to be stored in a .cs file so that I can use them. How do I go about it

**Comment by glen-84** [comment]
@VenkateshSrini Please read the documentation. It's also recommended that you use the latest version.

**Comment by VenkateshSrini** [comment]
Can you please point to the documentation you are referring to? I have seen this documentation https://chillicream.com/docs/strawberryshake/v13. Apart from that I use github copilot also. After all this I'm still not getting the generated files. Attached is the 
[.graphqlrc.json](https://github.com/user-attachments/files/16569600/default.graphqlrc.json)
[OrderManagement - Copy.txt](https://github.com/user-attachments/files/16569604/OrderManagement.-.Copy.txt)

**Comment by glen-84** [comment]
> With the project compiled, you should now see in the directory `./obj/<configuration>/<target-framework>/berry` the generated code that your applications can leverage. For example, if you've run a Debug build for .NET 8, the path would be `./obj/Debug/net8.0/berry`.

Are you looking under these paths?

**Comment by VenkateshSrini** [comment]
No I'm generating it via powershell console. using these files, I generated dotnet graphql Generate
