### ISSUE TITLE
Bring back lazy totalCount for Connection

### ISSUE THREAD

**Issue by cmeeren** [ChilliCream/graphql-platform#7391]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Somewhere between 14.0.0-p.104 and 14.0.0-p.150, the `Connection` constructor overload accepting a `totalCount` with type `CancellationToken -> Task<int>` (or something similar) seems to have been removed.

As far as I can see, this means it is not possible to fetch the total count from the DB only when the GraphQL client actually requests this field. Instead, it is always fetched.

This is a problem for us, because with row-level access checks for rows numbering in the 100.000's, getting the total count slows down the search to an unacceptable level.

### The solution you'd like

Bring back a way of only fetching totalCount if the client requests it. (Or, if this is still supported in a way I'm clearly missing, please let me know how.)

**Comment by michaelstaib** [comment]
Thats actually not whats happening. We are checking what the user selects and only fetch the total count when necessary.

**Comment by michaelstaib** [comment]
What DB driver are you using? EFCore?

**Comment by cmeeren** [comment]
I'm using a `Connection` manually similar to what I described in #6906, and I have to supply `totalCount` as an int in the `Connection` constructor.

**Comment by cmeeren** [comment]
In other words, I am doing what is described [in the HC docs here](https://chillicream.com/docs/hotchocolate/v14/fetching-data/pagination/#custom-pagination-logic) ("Custom pagination logic"). There it also demonstrates the overload I am talking about, that seems to have been removed.

**Comment by cmeeren** [comment]
A workaround is to add a parameter to the query with the attribute `[IsSelected("totalCount")]`. Then I fetch the count from the DB only if this is `true` (and returning `0` if not, which won't be used anyway).

**Comment by michaelstaib** [comment]
Its not a workaround but a better solution... this allows you to inline the data fetch and the count in one SQL query. Did you see our new pagination APIs for layered applications. The EF core team will integrate that functionality into EF itself. 

```csharp
public sealed class BrandService(CatalogContext context)
{
    public async Task<Page<Brand>> GetBrandsAsync(
        PagingArguments args,
        CancellationToken ct = default)
        => await context.Brands
            .AsNoTracking()
            .OrderBy(t => t.Name)
            .ThenBy(t => t.Id)
            .ToPageAsync(args, ct);
}
```

This uses proper keyset pagination and the assemblies are comletly disjunct from HC.

This also allows for the totalCount to be inlined.

**Comment by cmeeren** [comment]
Thanks for the response!

> Did you see our new pagination APIs for layered applications.

I just saw [this video](https://www.youtube.com/watch?v=kOGS7HI3lEA) if that's what you refer to. While it's cool, the video only demoed DB querying with EF. We are not using EF; nor are we otherwise using `IQueryable`. If the video still applies to me, I am unable to see how.

I also don't understand why the removal of a lazily evaluated `totalCount` is a requisite for that functionality. (I'm not saying it shouldn't be, just that I don't understand this.)

In any case, I can live with having to use `[IsSelected("totalCount")]`.

**Comment by michaelstaib** [comment]
With the old way we had total count always as async work in the graph which is overhead that is better consolidated in a single IO operation. While I do not know how you are doing things within your resolvers in most cases you could build a reusable middleware. Anyway, closing this issue.

**Comment by cmeeren** [comment]
> which is overhead that is better consolidated in a single IO operation

If you'd care to illuminate me, I would be very interested in knowing how the overhead of the total count is better consolidated in a single IO operation. I get that, all else being equal, one IO operation is better than two, but in my experience, getting the total count adds unacceptable overhead to a query.

I have tried doing that with SQL Server, by returning a column with the total number of rows (this count is returned for each row in the result set). However, the performance was ultimately worse than simply running two queries in parallel: One to fetch the data without the count, and one to fetch only the count. This has the added benefit that, with the count being expensive to retrieve, it is only retrieved when needed, and the client can also perform two queries in parallel - one to get the items, and one to get the count, meaning that the system as a whole performs better. (Even just running the query to get the items first and then the count after would improve the UX compared to getting both simultaneously in a single, slower request.)
