### ISSUE TITLE
Hook for Field Middleware that trigger when all of the subgraph is evaluated

### ISSUE THREAD

**Issue by icanhasjonas** [ChilliCream/graphql-platform#7416]
### Product

Hot Chocolate

### Is your feature request related to a problem?

So,

I've been experimenting with builder patterns in mutations, not something I've seen before, but it makes sense

```gql
mutation X {
  # not TransactionScope
  withTransaction {
     SomeTask( ... )
     SomeOtherTask( ... )
  }
}
```

... and for `withTransaction` it would be great if I can hook into an event where all of the sub-tree is resolved.

Using normal middleware, I can only observe before the result from `withTransaction` and the actual result from `withTransaction`, but not wait, or know when the subtree is resolved. Maybe there's a way? I've tried `RegisterCleanup()`, or even implementing `IDisposable/IAsyncDisposable` to no avail.

Just a thought. Not a critical issue.

### The solution you'd like

Similar to `RegisterForCleanup()`, but still in the scope of evaluation, so that errors can be properly emitted;

  1. being able to register for a callback when all of the sub graph is started to resolve (i.e, all async fields have at least been called, but not fully awaited)
  2. being able to register for a callback when all of the sub graph is fully resolved and awaited.

**Comment by michaelstaib** [comment]
This is not graphql spec conform an violates the execution principals. Mutations are only toplevel in graphql
