### ISSUE TITLE
Not all errors and exceptions are visible

### ISSUE THREAD

**Issue by taipignas** [ChilliCream/graphql-platform#7432]
### Product

Hot Chocolate

### Version

13.9.11

### Link to minimal reproduction

sorry

### Steps to reproduce

1. create dbcontext with multiple constructors 
2.  use pooled db context AddPooledDbContextFactory like in the documentation from `dataloaders` or `entity framework` 

### What is expected?

Correct error is clearly visible `The DbContext of type 'DbContext' cannot be pooled because it does not have a public constructor accepting a single parameter of type DbContextOptions or has more than one constructor`

### What is actually happening?

Some internal error of Hot Chocolate is displayed `Could not create an instance of the dataloader`

**Comment by michaelstaib** [comment]
can you try with 14?

**Comment by michaelstaib** [comment]
Do you have feedback on this? Also is there a repro?

**Comment by michaelstaib** [comment]
Closing this issue as there is not repro or feedback to this issue.
