### ISSUE TITLE
URL Safe NodeID's

### ISSUE THREAD

**Issue by kwstnr** [ChilliCream/graphql-platform#7451]
### Product

Hot Chocolate

### Is your feature request related to a problem?

When using `GlobalObjectIdentification` in a HotChocolate GraphQL service, the internal ID's of entities get replaced by the ID scalar.
When a web client uses these ID's for routing of let's say detail views of objects or there are other REST services which use these ID's to identify resources, the system breaks, as these base64 strings might contain `/`'s.

Let's say you have a Angular client which has a overview and a detail view for books.
The client fetches a list of books, using a GetBooksAsync NodeResolver where `GlobalObjectIdentification` is enabled. The client receives a list of books which might look like this:
```json
{
  "data": {
    "books": [
      {
        "id": "SW52b2ljZTpoyUj3nFfjSoj7QNnl+/Wi",
        "title": "GraphQL for Dummies"
      },
      {
        "id": "...",
        "title": "..."
      }
    ]
  }
}
```

Now the angular client has a BookComponent which is routed to on the path "/book/$id".
When the user clicks on the book "GraphQL for Dummies", the client tries to call the route "appDomain.com/book/SW52b2ljZTpoyUj3nFfjSoj7QNnl+/Wi" and angular tries to resolve the route to "/book/$param1/$param2" which doesn't exist.

For this to work on a client, either the client needs to decode and later encode the ID scalar or the GraphQL Service needs to append a URL safe Id to the book node.
However it would be easier to add a URL Safe `INodeIdSerializer` to which you can opt in to encode and decode the node ID's in a URL safe manner.

Maybe I'm told that the client side decoding or appending of URL Safe ID's is best practice, but that would already help me a lot and clear things up.

### The solution you'd like

A `UrlSafeNodeIdSerializer` which implements the `INodeIdSerializer` interface and can format and parse ID's in a URL safe manner.

A additional ExtensionMethod in the [RequestExecutorBuilderExtensions](https://github.com/ChilliCream/graphql-platform/blob/14.0.0-rc.0/src/HotChocolate/Core/src/Execution/DependencyInjection/RequestExecutorBuilderExtensions.IdSerializer.cs) `AddUrlSafeNodeIdSerializer` which instead of the `DefaultNodeIdSerializer` registers the `UrlSafeNodeIdSerializer`.

**Comment by michaelstaib** [comment]
This is now implemented

**Comment by kwstnr** [comment]
@michaelstaib thank you for implementing this in such a quick fashion!

I tested this serialization in the [p.164 release](https://github.com/ChilliCream/graphql-platform/blob/14.0.0-p.164) and wasn't able to use the url safe serialization.

I tried to use the url safe serialization as follows:
```csharp
public static IRequestExecutorBuilder AddGraphQLConventions(this IRequestExecutorBuilder builder) =>
        builder
            .AddFiltering()
            .AddSorting()
            .AddDefaultNodeIdSerializer(useUrlSafeBase64: true)
            .AddGlobalObjectIdentification();
``` 

and even ordered differently
```csharp
public static IRequestExecutorBuilder AddGraphQLConventions(this IRequestExecutorBuilder builder) =>
        builder
            .AddFiltering()
            .AddSorting()
            .AddGlobalObjectIdentification()
            .AddDefaultNodeIdSerializer(useUrlSafeBase64: true);
``` 

and still get `/` and `+` in the id's in queries but when I inject the `DefaultNodeIdSerializer` in an integration test and directly try to serialize the id I get the url safe ID.

so it seems to me in the GraphQL Middleware the id isn't serialized in a url safe manner while the serializer itself works fine in a isolated manner.

Maybe I'm registering it wrongly or is something going wrong?

**Comment by robanreuvers** [comment]
I have the same issue running Hot Chocolate 14.1.0. Sticking to the old ID's for now. 👍
