### ISSUE TITLE
Discrepancy between HotChocolate (Status Code 500) and AspNetCore Authorization (Status Code 401)

### ISSUE THREAD

**Issue by erikkipp** [ChilliCream/graphql-platform#7462]
### Product

Hot Chocolate

### Version

13.9.12

### Link to minimal reproduction

https://github.com/erikkipp/minimal-graphql

### Steps to reproduce

Run the app, navigate to /weatherforecast which will return a 401. Then navigate to graphql/ and run query request {
  book {
    title
  }
}

### What is expected?

The API should return a 401 Unauthorized response. This allows third-party services (such as Zapier) to detect unauthorized access, also, returning a 401 is aligned with the principles of proper web architecture.

### What is actually happening?

Currently, the API returns a 500 Internal Server Error.

### Relevant log output

```shell
Request URL: https://localhost:7069/graphql
Request Method: POST
Status Code: 500 Internal Server Error
```

**Comment by michaelstaib** [comment]
Your expectation is wrong. In GraphQL the request never is fully not authorized ... instead there might be non authorized parts to the request. In the GraphQL protocol you need to read the result to interpret which part of the data tree is affected by an error or not. GraphQL explicitly embraces partial results. This is very different to classical REST.

So why the 500? in the case of version 13 we are still implementing an earlier version of the GraphQL over HTTP spec which would assign 500 when all data of a request was erased. GraphQL has no notion about semantics on errors.

With version 14 we are returning a 200 as defined in the GraphQL over HTTP spec

**Comment by erikkipp** [comment]
ok thanks, I also just handled the Zapier issue with some extra js.
