### ISSUE TITLE
Incorrect description for Decimal

### ISSUE THREAD

**Issue by cmeeren** [ChilliCream/graphql-platform#7469]
### Product

Hot Chocolate

### Version

14.0.0-rc.1

### Link to minimal reproduction

none

### Steps to reproduce

Surface a `Decimal` field through HotChocolate.

### What is expected?

This schema:

```graphql
"[some useful description]"
scalar Decimal
```

### What is actually happening?

This schema:

```graphql
"The built-in `Decimal` scalar type."
scalar Decimal
```

The Decimal scalar type is not built-in from a GraphQL perspective, so this message is incorrect.

**Comment by michaelstaib** [comment]
@glen-84 maybe we just put the System.Decimal description in here as this is what the type wrapps.
