### ISSUE TITLE
Send GraphQL request without `id` or `operationName` parameters

### ISSUE THREAD

**Issue by johnrom** [ChilliCream/graphql-platform#7504]
### Product

Strawberry Shake

### Is your feature request related to a problem?

I'm using a third party which responds with a Bad Request. I ran the same query myself, and everything worked, but when I recorded some network requests with Strawberry Shake, I saw the following request:

```json
{
  "id": "{random-hash}",
  "operationName": "QueryName",
  "query": "query QueryName($var: String!) { theQuery($var) { property } }",
  "variables": { "var": "value" }
}
```

It turns out the `id` is causing the third party to return a Bad Request (400). Is there a way to customize the way this JSON is created or mark an operation as not needing these properties?

### The solution you'd like

Rough ideas of where I'd expect to add this option, but whatever makes sense:

- Pass a parameter to `ExecuteAsync`
- Change a parameter in `AddMyService` registration
- Add some kind of attribute in the GraphQL
- Configure it in the `.graphql.json` extension
- Intercept the serialization and unset the ID

**Comment by jarlef** [comment]
You can easily register your own http message handler with Strawberry shake that intercepts the payload and strips the id

```c#
public class StripOperationIdHandler : DelegatingHandler
{
    protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,
        CancellationToken cancellationToken)
    {
         // update request.Content = updatedJSON here

        return await base.SendAsync(request, cancellationToken);
    }
}
```

```#c

serviceCollection.AddSomeClient().ConfigureHttpClient(c =>
{
    c.BaseAddress = new Uri(factory.Server.BaseAddress, "graphql");
}, c =>
{
    c.AddHttpMessageHandler<StripOperationIdHandler>();
});
```

**Comment by tobias-tengler** [comment]
Are you on the latest version? Are persisted wueries enabled?
We switched to persisted queries in our Strawberry Shake codebase a while back and I'm fsirly certain the id was only sent to the server once persisted queries were enabled and the query wouldn't be sent in that case.

**Comment by johnrom** [comment]
> You can easily register your own http message handler with Strawberry shake that intercepts the payload and strips the id
> 
> ```cs
> public class StripOperationIdHandler : DelegatingHandler
> {
>     protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request,
>         CancellationToken cancellationToken)
>     {
>          // update request.Content = updatedJSON here
> 
>         return await base.SendAsync(request, cancellationToken);
>     }
> }
> ```
> 
> ```
> 
> serviceCollection.AddSomeClient().ConfigureHttpClient(httpClient =>
> {
>     httpClient.BaseAddress = new Uri("https://foo.com/graphql");
> }, httpClientBuilder =>
> {
>     httpClientBuilder.AddHttpMessageHandler<StripOperationIdHandler>();
> });
> ```

Thanks, I was trying to avoid deserializing and reserializing the value for performance reasons, as it would probably be more performant to create my own messages as that point with simple queries.

> Are you on the latest version? Are persisted queries enabled? We switched to persisted queries in our Strawberry Shake codebase a while back and I'm fairly certain the id was only sent to the server once persisted queries were enabled and the query wouldn't be sent in that case.

I'll read further on this, thanks!

**Comment by johnrom** [comment]
Actually, it looks like this only happened in 13.9.11 and updating to 13.9.12 removed the ID.
