### ISSUE TITLE
Support async enumerable serialization

### ISSUE THREAD

**Issue by hahn-kev** [ChilliCream/graphql-platform#7511]
### Product

Hot Chocolate

### Is your feature request related to a problem?

When returning a large amount of data from an async enumerable it buffers all the data info memory before beginning serialization

### The solution you'd like

System text json supports streaming serialization, when you return one from a Controller action it uses very little memory because it streams the result to the client. I would like that same support when using GraphQL to reduce memory usage for queries that return a large amount of data.

**Comment by michaelstaib** [comment]
GraphQL does non-null propagation on the data-tree ... this is specified in the GraphQL spec and one of the core pillars of GraphQL. This means that a GraphQL server must keep the result data in memory until it can no longer be erased by propagating non-null errors upwards. Hot Chocolate pools such memory but if data is overly large like 1000 item per collection with nested items this is not recommended.

Further, GraphQL supports defer and stream with directives .... in these cases you can branch of a a list and the data trees are broken down in a continuous stream of results where each result represents a null boundary.

> Section 6.4.4 Handling Field Errors
> https://spec.graphql.org/draft/#sel-FANTNNCAACKhCqoK

**Comment by michaelstaib** [comment]
If you want to read up on defer and stream look here:
https://graphql.org/blog/2020-12-08-defer-stream/

**Comment by hahn-kev** [comment]
Got it, so the server will throw an error if any item in the list is null, which means it needs to load the whole list into memory in order to do that right?

Is there a guide on how to use streaming with Hot Chocolate?
