### ISSUE TITLE
Respect member definition order across methods/properties

### ISSUE THREAD

**Issue by cmeeren** [ChilliCream/graphql-platform#7518]
### Product

Hot Chocolate

### Version

14.0.0-rc.2

### Link to minimal reproduction

See below

### Steps to reproduce

```c#
public class Query
{
    public string D => "";
    
    public string C => "";
    
    public string B() => "";
    
    public string A() => "";
}
```

### What is expected?

```graphql
type Query {
  d: String!
  c: String!
  b: String!
  a: String!
}
```

### What is actually happening?

```graphql
type Query {
  b: String!
  a: String!
  d: String!
  c: String!
}
```

### Additional context

As can be seen, HotChocolate preserves the member order for properties and members individually, but it places the members first.

Member definition order can be important in ensuring a clear API. Member order should not depend on whether or not the field is internally a method or a property.

**Comment by michaelstaib** [comment]
Member order is not guaranteed in .NET 

This is the call we do:

```
        var members = includeStatic
            ? type.GetMembers(Instance | Static | Public)
            : type.GetMembers(Instance | Public);
```

But properties are kind of not real ... so the first members are the internal setter and getter methods ... the actual props that we capture are at the end. Be aware that there are also order differences depending on the compilation.

<img width="457" alt="image" src="https://github.com/user-attachments/assets/beeb09c6-c0e2-43e8-a1da-959f0f544502">

**Comment by cmeeren** [comment]
You are quick to close, but according to my testing, the fix is as trivial as this:

```c#
members = members
  .OrderBy(m => m.DeclaringType?.MetadataToken)
  .ThenBy(m => m switch
  {
      PropertyInfo p => p.GetMethod?.MetadataToken ?? p.SetMethod?.MetadataToken ?? p.MetadataToken,
      _ => m.MetadataToken
  })
  .ToArray();
```

MetadataToken is not guaranteed to correspond to the declaration order, but it is commonly understood to do so and therefore to be a useful proxy for declaration order. I cannot imagine that this is likely to change any time soon, and until it does, this is a value-add for HotChocolate in that member order is more easily controlled (and more as expected in the first place), with no guarantees made on HotChocolate's part and therefore no additional maintenance work.

Would this be acceptable? I believe that being able to better control the schema property order is useful for documentation purposes, and this seems like a very trivial fix.

**Comment by michaelstaib** [comment]
This is to expensive ... we do not do any ordering here ... if you multiply this by 100.000 types that each have their own fields your pretty much done. We already fight schema building time here.

**Comment by michaelstaib** [comment]
I will setup a benchmark to look at the schema building time with this added however.

**Comment by michaelstaib** [comment]
Depending on the compilation the order is not the order in your code file. We had this approach for some time and depending on compilation options you do not get the expected order ... we experimented with this in the past.

- The order of MetadataToken values does not necessarily correspond to the order in which members are declared in the source code.
- MetadataToken values may reflect the order in which the compiler emits metadata but not the exact source code structure.

We have an option to alphabetically order members which is the best option to get a stable order.

**Comment by cmeeren** [comment]
> I will setup a benchmark to look at the schema building time with this added however.

Thank you, I really appreciate that.

**Comment by cmeeren** [comment]
> Depending on the compilation the order is not the order in your code file.

Do you know what it depends on? If it works 90% of the time, I still think it's useful.

> We have an option to alphabetically order members which is the best option to get a stable order.

To be clear: My goal is not to get an arbitrary stable order. My goal is to be able to control the order, at least to some extent, so that semantically related fields can be grouped together.

**Comment by michaelstaib** [comment]
> Do you know what it depends on? If it works 90% of the time, I still think it's useful.

I remember that we had issues between windows and unix ... but I have to look it up again ... it was not stable enough. Also I remember that webassembly for instance also had different ordering. There are also other factors that play into this here. If you for instance use the fluent api for some of the properties it becomes a nightmare. In general I recommend alphabetic order especially as there is also the problem of inheritance and order.

**Comment by cmeeren** [comment]
Thanks, I really appreciate the clarification.
