### ISSUE TITLE
Unhelpful error message when missing `}` in query

### ISSUE THREAD

**Issue by cmeeren** [ChilliCream/graphql-platform#7520]
### Product

Hot Chocolate

### Version

14.0.0-rc.2

### Link to minimal reproduction

See below

### Steps to reproduce

This code:

```c#
public class Query
{
    public string X => "";
}
```

And this query:

```graphql
query { x
```

### What is expected?

An error message that says something about `}` being expected, not a `NameToken`.

### What is actually happening?

```json
{
  "errors": [
    {
      "message": "Expected a `Name`-token, but found a `EndOfFile`-token.",
      "locations": [
        {
          "line": 1,
          "column": 10
        }
      ],
      "extensions": {
        "code": "HC0011"
      }
    }
  ]
}
```

**Comment by michaelstaib** [comment]
Member order is not guaranteed in .NET 

This is the call we do:

```
        var members = includeStatic
            ? type.GetMembers(Instance | Static | Public)
            : type.GetMembers(Instance | Public);
```

But properties are kind of not real ... so the first members are the internal setter and getter methods ... the actual props that we capture are at the end. Be aware that there are also order differences depending on the compilation.

<img width="457" alt="image" src="https://github.com/user-attachments/assets/beeb09c6-c0e2-43e8-a1da-959f0f544502">

**Comment by michaelstaib** [comment]
This one is fixed and will be integrated into rc.3
