### ISSUE TITLE
Decode XML/HTML entities when taking descriptions from doc comments (XML documentation file)

### ISSUE THREAD

**Issue by cmeeren** [ChilliCream/graphql-platform#7521]
### Product

Hot Chocolate

### Version

14.0.0-rc.2

### Link to minimal reproduction

See below

### Steps to reproduce

Repro solution: [HotChocolateBugRepro.zip](https://github.com/user-attachments/files/17161522/HotChocolateBugRepro.zip)

Code for reference:

```c#
public class Query
{
    [GraphQLDescription("Only relevant when foo > bar.")]
    public string X => "";

    /// <summary>
    ///  Only relevant when foo > bar.
    /// </summary>
    public string Y => "";
}
```

### What is expected?

This schema:

```graphql
type Query {
  """
  Only relevant when foo > bar.
  """
  x: String!

  """
  Only relevant when foo > bar.
  """
  y: String!
}
```

### What is actually happening?

This schema:

```graphql
type Query {
  """
  Only relevant when foo > bar.
  """
  x: String!

  """
  Only relevant when foo &gt; bar.
  """
  y: String!
}
```

**Comment by cmeeren** [comment]
It seems this is currently only in 15.0.0 preview, and did not make the final 14.0.0 release. Will it be added to 14.0.0? Asking because [FSharp.HotChocolate](https://github.com/cmeeren/FSharp.HotChocolate) tests get more complicated due to this mismatch.

**Comment by cmeeren** [comment]
Nevermind, I was wrong. It seems this is present in both 14.0.0 and 15.0.0-p.10.

**Comment by cmeeren** [comment]
It seems this was fixed for fields, but not type doc strings, notice the `\"` here (in the code it's just `"` there, so HC adds `\`).

![Image](https://github.com/user-attachments/assets/8c969285-8084-4546-9c90-044ad0d344d3)

**Comment by glen-84** [comment]
You have to escape quotation marks in single-line strings. The second example is a multi-line string where the escaping is not necessary.

It's not specific to XML.

**Comment by cmeeren** [comment]
Ah, of course 🤦 Thanks for the clarification!
