### ISSUE TITLE
HotChocolate.ApolloFederation not outputting key directive

### ISSUE THREAD

**Issue by rquackenbush** [ChilliCream/graphql-platform#7555]
### Product

Hot Chocolate

### Version

13.9.14

### Link to minimal reproduction

https://github.com/rquackenbush/wundergraph-examples/tree/main/Example_001

### Steps to reproduce

Decorate a code first type class with `KeyAttribute`:

```c#
public class Parent
{
  [Key]
  [ID]
  public string Id { get; set; }

  [ReferenceResolver]
  public static Parent? Get(string id)
  {  
     return new Parent { Id = id };
  }
}
```

With the bootstrap code:

```c#
builder.Services
    .AddGraphQLServer()
    .AddApolloFederation();
    .AddQueryType<Query>();
```

### What is expected?

I expect the schema for Parent to be emitted as:

```
type Parent @key(fields: "id") {
  id: ID!
  name: String!
}
```

### What is actually happening?

The schema emitted is:

```
type Parent {
  id: ID!
  name: String!
}
```

Note that the following appears to be emitted instead:

```
"""
Union of all types that key directive applied. This information is needed by the Apollo federation gateway.
"""
union _Entity = Parent
```

### Additional context

I'm attempting to use the `HotChocolate.ApolloFederation` package with WunderGraph Cosmo, and their schema engine appears to require the `key` directive.

**Comment by rquackenbush** [comment]
I am happy to report that there is an out-of-the-box solution.

To output the schema with the @key directive, you can add the [HotChocolate.AspNetCore.CommandLine][1] package to the project per [these instructions][2].

Be sure to replace app.Run():

```c#
//app.Run();

await app.RunWithGraphQLCommandsAsync(args);
```

Then you can execute the application passing in the `schema export` command line options.

For example, when running from code:

```
dotnet run -- schema export
```

And voila, the output contains the @key directive!

```
schema @link(url: "https:\/\/specs.apollo.dev\/federation\/v2.6", import: [ "@key", "@tag", "FieldSet" ]) {
  query: Query
}

type Parent @key(fields: "id") {
  id: ID!
  name: String!
}

type Query {
  allParents: [Parent!]!
  _service: _Service!
  _entities(representations: [_Any!]!): [_Entity]!
}

"This type provides a field named sdl: String! which exposes the SDL of the service's schema. This SDL (schema definition language) is a printed version of the service's schema including the annotations of federation directives. This SDL does not include the additions of the federation spec."
type _Service {
  sdl: String!
}

"Union of all types that key directive applied. This information is needed by the Apollo federation gateway."
union _Entity = Parent

"Used to indicate a combination of fields that can be used to uniquely identify and fetch an object or interface."
directive @key(fields: FieldSet! resolvable: Boolean = true) repeatable on OBJECT | INTERFACE

"Links definitions within the document to external schemas."
directive @link("Gets imported specification url." url: String! "Gets optional list of imported element names." import: [String!]) repeatable on SCHEMA

"Scalar representing a set of fields."
scalar FieldSet

"The _Any scalar is used to pass representations of entities from external services into the root _entities field for execution. Validation of the _Any scalar is done by matching the __typename and @external fields defined in the schema."
scalar _Any
```

  [1]: https://www.nuget.org/packages/HotChocolate.AspNetCore.CommandLine/
  [2]: https://chillicream.com/docs/hotchocolate/v13/server/command-line

**Comment by lghinet** [comment]
hello, is there a reason why the introspection query  is not outputting the correct schema for federation ?
