### ISSUE TITLE
Be able to disable default security when using Azure Functions, like we can with AddGraphQLServer.

### ISSUE THREAD

**Issue by wouth** [ChilliCream/graphql-platform#7599]
### Product

Hot Chocolate

### Is your feature request related to a problem?

`AddGraphQLFunction` misses the `disableDefaultSecurity` argument which `AddGraphQLServer` has.

### The solution you'd like

We would like to be able to disable default security when using Azure Functions, like we can with `AddGraphQLServer`.
Add `disableDefaultSecurity` argument to `AddGraphQLFunction` like `AddGraphQLServer` already has.

**Comment by michaelstaib** [comment]
Can you create a new issue that describes your actual composition issue with the cost directive in fusion ... we will fix that in the first patch release.

**Comment by wouth** [comment]
As requested by @michaelstaib, I created the issue for the Fusion composition issue: https://github.com/ChilliCream/graphql-platform/issues/7618
