### ISSUE TITLE
Update v14 docs on entity framework integration

### ISSUE THREAD

**Issue by juantxorena** [ChilliCream/graphql-platform#7624]
The v14 docs (still marked unstable somehow) show how to register the dbContext with a method RegisterDbContext, so you can make it pooled, resolver, or whatever. That method doesn't exist anymore, now there's only a RegisterDbContextFactory, and the enum DbContextKind doesn't seem to exist anymore (so I have no idea how to register it as pooled).

**Comment by glen-84** [comment]
- https://github.com/ChilliCream/graphql-platform/pull/7622
- https://github.com/ChilliCream/graphql-platform/pull/7604

**Comment by alrz** [comment]
Also please consider elaborating on `Page<T>` support, I could not make that to work in simple setup and it's not clear what is missing (the announcement post does not mention the configuration, only the resolver).

**Comment by glen-84** [comment]
@alrz

When `Page<T>` is documented, it won't be in the Entity Framework Integration section.

With that said, make sure that you call `AddPagingArguments` on the `IRequestExecutorBuilder`, apply the `[UsePaging]` attribute to your resolver, and return a `Connection<T>` from your resolver, not a `Page<T>`.

There's also a [YouTube video](https://www.youtube.com/watch?v=kOGS7HI3lEA).

If you're still stuck, you can ask for assistance on [Slack](http://slack.chillicream.com/).

**Comment by glen-84** [comment]
Closing, as the Entity Framework Integration documentation has been updated.

**Comment by glen-84** [comment]
> I meant the HC 14 `Page<T>` type that was announced a few days earlier. An example in the post mentions this type.

Announced where? If you're referring to the [blog post](https://chillicream.com/blog/2024/08/30/hot-chocolate-14), then the example it shows returns `Page<Brand>` from a _service_, but `Connection<Brand>` from the _resolver_ (later in the post).
