### ISSUE TITLE
Docs Error Builder page not listed in sidebar

### ISSUE THREAD

**Issue by shravan2x** [ChilliCream/graphql-platform#7626]
### Product

Hot Chocolate

### Version

14.0.0

### Link to minimal reproduction

https://chillicream.com/docs/hotchocolate/v14/api-reference/error-filter

### Steps to reproduce

Go to https://chillicream.com/docs/hotchocolate/v14/api-reference/error-filter

### What is expected?

The "Error Filter" option is listed in the contents sidebar.

### What is actually happening?

It isn't.

### Additional context

The same issue affects v13 and possibly other versions.

**Comment by michaelstaib** [comment]
I do not get what you mean. The article describes how to use error filters ... the sub headlines are about aspects of this like the error builder, exceptions and so on.

**Comment by michaelstaib** [comment]
I misunderstood your issue... we are working on fixing the docs.

**Comment by shravan2x** [comment]
Sorry about the skeleton post, I was in a hurry and wanted to track the issue before I forgot it. I'll double check in the future. Glad you were able to resolve the issue!
