### ISSUE TITLE
Include net9.0 tools in StrawberryShake package

### ISSUE THREAD

**Issue by idaMa84** [ChilliCream/graphql-platform#7659]
### Product

Strawberry Shake

### Is your feature request related to a problem?

See PR https://github.com/ChilliCream/graphql-platform/pull/6395 for reference.

### The solution you'd like

Include net9.0 tools in StrawberryShake package

**Comment by TylerSiegrist** [comment]
I'll throw a quick PR together as this is blocking a .NET 9 upgrade on one of my personal projects.

**Comment by dev-in-disguise** [comment]
Is there any rough estimate on when this can be shipped? I'm also blocked at my company by this issue for a .NET 9 upgrade and would love to see that resolved.
