### ISSUE TITLE
`JSON cannot serialize the given value.` when using a remote schema

### ISSUE THREAD

**Issue by ibbyu** [ChilliCream/graphql-platform#7668]
### Product

Hot Chocolate

### Version

13.9.14

### Link to minimal reproduction

https://github.com/ibbyu/gateway-with-remote-schema-cannot-serialize-json

### Steps to reproduce

1. Run both projects in the given solution
2. Run this query in both applications `query { system }`
3. Service returns expected json, Gateway returns `"JSON cannot serialize the given value."` error

### What is expected?

Service & Gateway should both return the expected json value

### What is actually happening?

Service application response:
![Image](https://github.com/user-attachments/assets/ab997d62-61c6-485f-9b1c-d1e702a25ea8)

Gateway application response;
![Image](https://github.com/user-attachments/assets/263098a2-640c-40ab-a5f1-3d74f3373ae6)

**Comment by michaelstaib** [comment]
HotChocolate.Stitching was replaced by HotChocolate.Fusion. Since we released HC 14 HotChocolate.Stitching is EOL.
