### ISSUE TITLE
[SchemaChangeTest] BuildSchemaAsync Fails if a Resolver in Query class has Service as an parameter

### ISSUE THREAD

**Issue by cabillin** [ChilliCream/graphql-platform#7694]
### Product

Hot Chocolate

### Version

13.9.7

### Link to minimal reproduction

https://github.com/cabillin/hot-chocolate-issues/tree/buildSchemaAsync_fails_with_service

### Steps to reproduce

* Open linked branch in the git hub repository.
* Run tests
* Observe test fails with "Unable to infer or resolve a schema type from the type reference `IFakeDataService (Input)`". (which comes from BuildSchemaAsync)
* Comment out GetParents in Query and observe that the test passes (BuildSchemaAsync works as expected)

### What is expected?

Since the IFakeDataService is a registered service, I expect BuildSchemaAsync to be smart enough to ignore it when building the schema (rather than thinking it is an Input and failing).

### What is actually happening?

BuildSchemaAsync fails with error "Unable to infer or resolve a schema type from the type reference `IFakeDataService (Input)`"

### Relevant log output

 GraphQL.Server.Test.BasicTests.SchemaChangeTest
   Source: BasicTests.cs line 22
   Duration: 241 ms

  Message: 
HotChocolate.SchemaException : For more details look at the `Errors` property.

1. Unable to infer or resolve a schema type from the type reference `IFakeDataService (Input)`.

  Stack Trace: 
TypeInitializer.DiscoverTypes()
TypeInitializer.Initialize()
Setup.InitializeTypes(SchemaBuilder builder, IDescriptorContext context, IReadOnlyList`1 types)
Setup.Create(SchemaBuilder builder, LazySchema lazySchema, IDescriptorContext context)
SchemaBuilder.Create(IDescriptorContext context)
ISchemaBuilder.Create(IDescriptorContext context)
RequestExecutorResolver.CreateSchemaAsync(ConfigurationContext context, RequestExecutorSetup setup, RequestExecutorOptions executorOptions, IServiceProvider schemaServices, TypeModuleChangeMonitor typeModuleChangeMonitor, CancellationToken cancellationToken)
RequestExecutorResolver.CreateSchemaServicesAsync(ConfigurationContext context, RequestExecutorSetup setup, CancellationToken cancellationToken)
RequestExecutorResolver.GetRequestExecutorNoLockAsync(String schemaName, CancellationToken cancellationToken)
RequestExecutorResolver.GetRequestExecutorAsync(String schemaName, CancellationToken cancellationToken)
RequestExecutorServiceProviderExtensions.BuildSchemaAsync(IRequestExecutorBuilder builder, String schemaName, CancellationToken cancellationToken)
BasicTests.SchemaChangeTest() line 24
--- End of stack trace from previous location ---

**Comment by cabillin** [comment]
ExecuteRequestAsync fails with the same issue

**Comment by glen-84** [comment]
With Hot Chocolate 13, you need to apply the `[Service]` attribute:

```diff
- public async Task<List<ParentObject>> GetParents(IFakeDataService dataService)
+ public async Task<List<ParentObject>> GetParents([Service] IFakeDataService dataService)
```

With Hot Chocolate 14, this is no longer necessary.

**Comment by cabillin** [comment]
Ah, I must have missed that in the documentation. Thanks for the quick response!
