### ISSUE TITLE
Cost Analyzer Not Using first When Assigned to Variable

### ISSUE THREAD

**Issue by jbenettius** [ChilliCream/graphql-platform#7697]
### Product

Hot Chocolate

### Version

14.1.0

### Link to minimal reproduction

https://github.com/jbenettius/Hotchocolate_Issues/tree/main/CostAnalysisIssue

### Steps to reproduce

With paged queries, the Cost Analyzer uses the MaxPageSize, rather than the _first_ parameter, when the _first_ parameter is assigned to a variable. This results in the fieldCost always being the maximum, for the requested query, regardless of the requested number of elements.

```c#
descriptor.Field(f => f.GetMyThings(""))
            .UsePaging(options: new PagingOptions() { MaxPageSize = 10000 })
``` 

Uses first, calculating for 100:
```
query queryDirect {
  myThings(id: "", first: 100, after: null, last: null, before: null) {
    nodes {
      id
      identifier
    }
  }
}
```

Uses MaxPageSize, calculating for 10000:
```
query queryVariable($count: Int) {
    myThings(id: "", first: $count, after: null, last: null, before: null) {
        nodes {
            id
            identifier
        }
    }
}
```
With variable:
```
{
    "count": 100
}
```

> [!IMPORTANT]  
> The linked project contains a full example

### What is expected?

Cost Analysis should always use the requested _first_ when calculating the _fieldCost_.

### What is actually happening?

Cost Analysis is using the MaxPageSize rather than the _first_ parameter.

**Comment by michaelstaib** [comment]
The spec itself defines 3 types of cost analysis btw ... static, dynamic and response. The static is to check for upper bounds and deny operations that could violate you performance expectations. The second, dynamic has a more accurate estimate and would abort an operation if it violates the estimated upper bounds (for instance if an estimated default bound is actually higher). The third is the result analysis, which traverses the result graph and calculates after the execution what has been produced. The three types have different use cases. The static analysis is the most important as its cheap (can be cached). Its used for rate limiting or threat prevention policies.
The dynamic is for Threat Protection and to fill in the actual used tokens for Rate Limiting. The result cost analysis is use for monetization, basically if you want to bill your consumer based on actual produced data and user resources.

Hot Chocolate 14 only supports static analysis. We will implement result analysis next.
