### ISSUE TITLE
Missing Nitro MIT License

### ISSUE THREAD

**Issue by uwe-schmitz** [ChilliCream/graphql-platform#7701]
### Product

Hot Chocolate

### Version

14.1.0

### Link to minimal reproduction

none

### Steps to reproduce

Use Snyk to analyze a solution using Hot Chocolate.

### What is expected?

Snyk should not report a vulnerability alert, "License in ChilliCream.Nitro.App 20.0.2." Please include an MIT license for Nitro.

### What is actually happening?

Snyk reports a vulnerability alert, "License in ChilliCream.Nitro.App 20.0.2." The MIT license appears to be missing.

**Comment by michaelstaib** [comment]
The ChilliCream license is permissible and allows you to use it. What it does not allow is removal of our sign in functionality.

https://www.chillicream.com/licensing/chillicream-license

Nitro is an optional component that can be switched off if you do not agree with the ChilliCream license. 

If you want to disable Nitro you can do it like the following:

```sharp
app.MapGraphQL().WithOption(new() { Tool = { Enable = false });
```
