### ISSUE TITLE
Old style errors while migrating to QueryConventions

### ISSUE THREAD

**Issue by bjartebore** [ChilliCream/graphql-platform#7730]
### Product

Hot Chocolate

### Is your feature request related to a problem?

There is no practical way to migrate our graph to use QueryConventions while the api is in use by mobile apps. Since we do not control the rollout of mobile applications there will be a lot of broken installations around while migrating.

While we can prepare our applications for upcoming unions with wrapping the affected queries with `... TypeName {}` we cannot prepare it for the upcoming Error types that does not exist until we turn on QueryConventions.

So when we turn on query conventions we can make our application work on a happy path, but when something goes wrong the un-upgraded applications will not get any error messages, just potential missing data.

### The solution you'd like

I would like a way to keep the old error structure along with the new QueryConvententions, this could be done with a new extra parameter to the AddQueryConventions(opt => opt.keepLegacyErrors = true)

**Comment by michaelstaib** [comment]
It's a field by field upgrade. Turning it on will not do anything to your types. Only if you add errors to a field. This will always be a breaking change. You will need to introduce a new field as mobile applications might have a much longer lifetime. This is an opt-in feature. Most applications should not use it in my opinion.
