### ISSUE TITLE
Schema endpoint in v14 returns same etag

### ISSUE THREAD

**Issue by sergiu-enache** [ChilliCream/graphql-platform#7760]
### Product

Hot Chocolate

### Version

14.1.0

### Link to minimal reproduction

repro-uploaded-as-zip

### Steps to reproduce

Since v14 the schema endpoint has cache-control.

Even if the schema changes, the /sdl endpoint returns same etag.

![Image](https://github.com/user-attachments/assets/0c45aa0f-715b-416f-9db2-8d7656bc4443)

After I change the schema (commented out person.shortName)

![Image](https://github.com/user-attachments/assets/2da837bf-30ab-4a58-8dcb-f6a65bb65575)

I get same ETAG and cached schema by browser.

I've uploaded a .zip repro project. [schema-endopoint-etag-issue.zip](https://github.com/user-attachments/files/17893027/schema-endopoint-etag-issue.zip)

### What is expected?

After changing schema and using browser to get /graphql/sdl latest schema should be downloaded.

### What is actually happening?

After changing schema and using browser to get /graphql/sdl latest previous schema with same ETAG is downloaded.

### Relevant log output

```shell

```

**Comment by michaelstaib** [comment]
I have tested this with your repro and I get for each change a new etag...

Original
"1-FulXWMljqt/Ts2ffo0GwgfOgzNl4yGD37d0mRZHWxGo="

After uncommenting `public string? ShortName { get; } `
"1-0rV9c6+YAlBB75JufhVV8z4yLRgFgPJvgoY7g+rJv1k="

**Comment by sergiu-enache** [comment]
I'll try again..

**Comment by sergiu-enache** [comment]
@michaelstaib I tried with Chrome, Edge and Postman

Originals
1-582d8s3vNNey3e2mF6xrFnCR3s63YYKs18c+QUor/tg=
1-582d8s3vNNey3e2mF6xrFnCR3s63YYKs18c+QUor/tg=
1-582d8s3vNNey3e2mF6xrFnCR3s63YYKs18c+QUor/tg=

After uncommemting `public string? ShortName { get; } `
1-582d8s3vNNey3e2mF6xrFnCR3s63YYKs18c+QUor/tg=
1-582d8s3vNNey3e2mF6xrFnCR3s63YYKs18c+QUor/tg=
1-ngiJaIjjSLFgRcTDLS/PBgImr96gPHmI4jIFv85qNeI=

Only with Postman it returns new tag.

Any thoughts?

**Comment by michaelstaib** [comment]
With chrome you get probably the cached result

**Comment by sergiu-enache** [comment]
I think the problem might be with returning 'must-revalidate' 

- no-cache. This actually allows the response to be cached, though it is immediately marked as stale and is always revalidated with the origin server.

- must-revalidate: Only means that a stale cached document must be revalidated with the origin server. Implied by no-cache so has no additional effect here.

- no-store: Don't cache the response.
