### ISSUE TITLE
EF.Constant(keys) usage in BatchDataLoader does not work correctly (MSSQL EF8/9)

### ISSUE THREAD

**Issue by kresimirlesic** [ChilliCream/graphql-platform#7769]
### Product

Hot Chocolate

### Version

14.1.0

### Link to minimal reproduction

https://gist.github.com/kresimirlesic/32e39360f8ec10b6285f58721ec7d69c

### Steps to reproduce

Invoke BatchDataLoader multiple times, passing down different values of keys.

### What is expected?

Results from the database should match accordingly to the passed keys.

### What is actually happening?

Incorrect results are being returned. 
The constructed SQL contains keys in the query from the first BatchDataLoader invocation.

### Relevant log output

```shell

```

### Additional context

I did a bit of investigation on a side and the issue boils down to how HC reuses a list to populate the keys under the hood. 
That causes a weird interaction with EF.

With list reusal:
![Image](https://github.com/user-attachments/assets/2f5472ad-e901-4e3c-a8a6-bbbdd8a02997)

Without list reusal:
![Image](https://github.com/user-attachments/assets/43891966-381c-42f0-9901-6452ce307ff3)

**Comment by michaelstaib** [comment]
This is as designed. We by default rent a list for keys in DataLoader. If you want to use it in combination with `EF.Constant` you need to allocate a list that you can pass on by doing a `ToList` or `ToArray` on the keys.
