### ISSUE TITLE
Options monitor race-condition 

### ISSUE THREAD

**Issue by victor-makovsky-covergo** [ChilliCream/graphql-platform#7778]
### Product

Hot Chocolate

### Version

12.0.0

### Link to minimal reproduction

https://github.com/ChilliCream/graphql-platform/blob/c477e13e161fe6ff682a6849facad19c63d9f83d/src/HotChocolate/Core/src/Execution/Configuration/DefaultRequestExecutorOptionsMonitor.cs#L82C13-L82C34

### Steps to reproduce

May be this is very edge case but sometimes it reproduces on my project and leads to deadlock (graphql requests start but never finish and hanging waiting for sempaphore).
![Image](https://github.com/user-attachments/assets/53cbe7e7-caf2-4b61-8c49-481feeb8201f)

### What is expected?

Semaphore is always released, release statement is put into finalize statement.

### What is actually happening?

Deadlock

### Relevant log output

```shell

```

**Comment by victor-makovsky-covergo** [comment]
It is possible to reproduce exception and deadlock when graphql request is sent and then cancelled (browser cancelled request), this leads to semaphore in the options monitor being always at 0 counter which prevents all graphql requests from processing and requires application restart to fix.
![Image](https://github.com/user-attachments/assets/bc0c8106-0c5f-4f08-b7b7-9a906ef50b65)

**Comment by sunghwan2789** [comment]
I think `InitializeOnStartup` can help the client from hanging for now.
https://chillicream.com/docs/hotchocolate/v14/performance/#startup-performance

**Comment by michaelstaib** [comment]
This will be fixed on 14 ... we no longer backport fixes to 12.
