### ISSUE TITLE
ExportDirective with type argument fails to prepend `@` to directive name

### ISSUE THREAD

**Issue by willgittoes** [ChilliCream/graphql-platform#7799]
### Product

Hot Chocolate

### Version

14.2.0-p.7

### Link to minimal reproduction

https://github.com/ChilliCream/hotchocolate-examples/pull/69/files

### Steps to reproduce

1. Check out branch in MR
2. Run once, service will save schema file when it starts

Bug is:
1. Use ExportDirective with a type parameter (rather than giving a string)
2. The created `composeDirective` does not prefix the directive to compose with `@`

### What is expected?

The created `composeDirective` prefixes the directive to compose with `@`

### What is actually happening?

The created `composeDirective` does not prefix the directive to compose with `@`

### Relevant log output

```shell

```

### Additional context

Workaround is to pass a string rather than use a type param

**Comment by willgittoes** [comment]
Bonus bug/feature request:

`RemoveUnreachableTypes` removes directives that are referenced in `composeDirective` unless they're also used somewhere else, leading to a schema error when you try to compose the schema in Apollo. `RemoveUnreachableTypes` should consider being referenced in `composeDirective` as being reachable.

**Comment by willgittoes** [comment]
Double-bonus bug/feature request:

`DirectiveTypeInterceptor` also discards directives in the same way, marking them as being unused.

**Comment by michaelstaib** [comment]
We have dropped support for `@export` with version 14.

**Comment by michaelstaib** [comment]
Or is you

**Comment by willgittoes** [comment]
Yes, sorry. I don't mean a directive called `@export`, I mean this:

```
        graphQlService
            .AddApolloFederation(FederationVersion.Federation26)
            .AddDirectiveType<MyCoolDirective>()
            .AddLink(
                "https://example.com/customDirectives.graphql/v1.1",
                new[] { "@myCool" }
            )
            // .ExportDirective<MyCoolDirective>() // Doesn't work
            .ExportDirective("@myCool")
```

I made a reproduction in https://github.com/ChilliCream/hotchocolate-examples/pull/69/files
