### ISSUE TITLE
Be able to remove the path and locations from the error object in HotChocolate V14.

### ISSUE THREAD

**Issue by dev-dantong-huang** [ChilliCream/graphql-platform#7824]
### Product

Hot Chocolate

### Is your feature request related to a problem?

Hi team,

I've encountered an issue after upgrading from Hot Chocolate v13 to v14. In the project, I use an ErrorHandlingFilter (implementing **IErrorFilter**) to customize error responses. Previously, I could remove the path and extensions properties from the error object using methods like `error.WithMessage(ex.Message).WithCode(ErrorCodes.BadUserInput).RemovePath().RemoveLocations()`. This worked as expected in v13.
 
However, after upgrading to v14, these `RemovePath() `and `RemoveLocations()` calls no longer have any effect. The path and extensions properties are always present in the final error object.
After investigating, I found a change in MiddlewareContext.Global.cs file in v14
https://github.com/ChilliCream/graphql-platform/blob/410d8977b4a3b68250e7a6aed930df66de527670/src/HotChocolate/Core/src/Execution/Processing/MiddlewareContext.Global.cs#L129
This line seems to be re-adding the path and locations to the error, overriding the removals.

My questions are:
Is this behavior intentional in v14?
Is there a recommended way to remove `path` and `locations` from error objects in v14 if we still need it?

### The solution you'd like

Be able to remove the path and locations from the error object in HotChocolate V14.

**Comment by michaelstaib** [comment]
The GraphQL spec demands that field errors have a path and location. We now will always add a path to an error that is happening in a field execution context.

**Comment by michaelstaib** [comment]
> If an error can be associated to a particular field in the GraphQL result, it must contain an entry with the key path that details the path of the response field which experienced the error. This allows clients to identify whether a null result is intentional or caused by a runtime error.

https://spec.graphql.org/draft/#sel-HAPHRPHEByBB0Bp6Z

**Comment by dev-dantong-huang** [comment]
> > If an error can be associated to a particular field in the GraphQL result, it must contain an entry with the key path that details the path of the response field which experienced the error. This allows clients to identify whether a null result is intentional or caused by a runtime error.
> 
> https://spec.graphql.org/draft/#sel-HAPHRPHEByBB0Bp6Z

Thanks for the response and link. It's good to know that path and location are now mandatory requirements.   @michaelstaib
