### ISSUE TITLE
Possible Memory Leak - Stitching with Data loaders

### ISSUE THREAD

**Issue by JonWillis-Tote** [ChilliCream/graphql-platform#7825]
### Product

Hot Chocolate

### Version

13.9.0

### Link to minimal reproduction

https://hub.production.racing.tote.co.uk/partner/gateway/graphql

### Steps to reproduce

Setup a Gateway with another 2 services. Make a request one server 1, which requires data from service 2. In our case, we have a product on server 1, and sporting event information on server 2. You get 100 products back, so Gateway makes 100 calls to get each event. These are sent in a batch request (built in with Stitching) and uses a DataLoader.

### What is expected?

No hot chocolate objects are left in memory

### What is actually happening?

After making 90 or so calls, for different days worth of information, several garbage collections later, included forced GC from profiling tools like DotMemory or inbuilt Visual Studio profiler. In service 2 (the one getting the batch calls from gateway) There are 400,000+ objects left in memory, about 52MB of objects seem stuck in Generation 2, unable to be cleared.

### Relevant log output

```shell

```

**Comment by JonWillis-Tote** [comment]
Some screenshots from the profiler tools. 

![Image](https://github.com/user-attachments/assets/1723cea3-f558-4ffd-9f7a-87aff37050d8)

![Image](https://github.com/user-attachments/assets/0f22b6b9-8dc1-450f-b894-eb2809b573bf)

![Image](https://github.com/user-attachments/assets/447aa0a4-ab2a-4656-b4a5-973ca0929264)

**Comment by michaelstaib** [comment]
HotChocolate.Stitching is end of life and was replaced by HotChocolate.Fusion.

You can find the documentation for fusion here:
https://chillicream.com/docs/fusion/v14
