### ISSUE TITLE
Nitro CLI does not have a `--configuration` option for `publish start`

### ISSUE THREAD

**Issue by RichardWhitfield** [ChilliCream/graphql-platform#7848]
### Product

Nitro

### Is your feature request related to a problem?

When running `dotnet nitro fusion-configuration publish start --api-key <someKey>` if the command is not executed from the same folder as the *.fgp* file then the command will not complete with the error:
*"Error: The task has already failed. Try restarting the operation."*

Since there is no `--configuration` option available for this command unless you have created your *.fgp* file in the root folder (or navigate to the folder with the *.fgp* file) this command will not complete.

### The solution you'd like

Given that most other commands which require the *.fgp* file have a `--configuration` option it would make sense to make this available for `dotnet nitro fusion-configuration publish start` as well.

**Comment by PascalSenn** [comment]
@RichardWhitfield  

I think your request just timed out. `begin` will reserve a slot for you, once your slot is ready for the deployment, you have 30s to `start` the composition. This is so a cancelled CI pipeline does not block your build pipline. If this timeout is reached, it will automatically fail.

There is no configuration needed for `publish start` you only need the configuration for `publish validate` and `publish commit`
